var searchData=
[
  ['readme_2emd_0',['README.md',['../_r_e_a_d_m_e_8md.html',1,'']]],
  ['rectangular_20matrix_1',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md19',1,'']]],
  ['ref_20la_5fdeterminant_3a_3adet_20det_20determinant_20of_20a_20scalar_20or_20rectangular_20matrix_2',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md19',1,'']]],
  ['ref_20la_5feye_3a_3adiag_20diag_20diagonal_20matrix_3',['@ref la_eye::diag &quot;diag&quot; - Diagonal matrix.',['../index.html#autotoc_md74',1,'']]],
  ['ref_20la_5feye_3a_3aeye_20eye_20identity_20matrix_4',['@ref la_eye::eye &quot;eye&quot; - Identity matrix.',['../index.html#autotoc_md81',1,'']]],
  ['ref_20la_5finverse_3a_3ainv_20inv_20inverse_20of_20a_20square_20matrix_5',['@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.',['../index.html#autotoc_md26',1,'']]],
  ['ref_20la_5finverse_3a_3ainvert_20invert_20in_20place_20matrix_20inversion_6',['@ref la_inverse::invert &quot;invert&quot; - In-place matrix inversion',['../index.html#autotoc_md33',1,'']]],
  ['ref_20la_5finverse_3a_3aoperator_20inv_20operator_20inv_20compute_20the_20inverse_20of_20a_20square_20matrix_7',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md39',1,'']]],
  ['ref_20la_5fleast_5fsquares_3a_3alstsq_20lstsq_20compute_20a_20least_20squares_20solution_20to_20a_20system_20of_20linear_20equations_8',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md12',1,'']]],
  ['ref_20la_5fpseudoinverse_3a_3aoperator_20pinv_20operator_20pinv_20compute_20the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_9',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md53',1,'']]],
  ['ref_20la_5fpseudoinverse_3a_3apinv_20pinv_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_20function_10',['@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).',['../index.html#autotoc_md46',1,'']]],
  ['ref_20la_5fqr_3a_3aqr_20qr_20qr_20factorization_20of_20a_20matrix_11',['@ref la_qr::qr &quot;qr&quot; - QR factorization of a matrix.',['../index.html#autotoc_md92',1,'']]],
  ['ref_20la_5fqr_3a_3aqr_5fspace_20qr_5fspace_20workspace_20size_20for_20qr_20operations_12',['@ref la_qr::qr_space &quot;qr_space&quot; - Workspace size for QR operations.',['../index.html#autotoc_md99',1,'']]],
  ['ref_20la_5fschur_3a_3aschur_20schur_20schur_20decomposition_20of_20a_20matrix_13',['@ref la_schur::schur &quot;schur&quot; - Schur decomposition of a matrix.',['../index.html#autotoc_md106',1,'']]],
  ['ref_20la_5fschur_3a_3aschur_5fspace_20schur_5fspace_20workspace_20size_20for_20schur_20decomposition_14',['@ref la_schur::schur_space &quot;schur_space&quot; - Workspace size for Schur decomposition.',['../index.html#autotoc_md113',1,'']]],
  ['ref_20la_5fsolve_3a_3asolve_20solve_20solve_20a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_15',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md6',1,'']]],
  ['ref_20la_5fsvd_3a_3asvd_20svd_20singular_20value_20decomposition_20svd_20of_20a_20matrix_16',['@ref la_svd::svd &quot;svd&quot; - Singular Value Decomposition (SVD) of a matrix',['../index.html#autotoc_md60',1,'']]],
  ['ref_20la_5fsvd_3a_3asvdvals_20svdvals_20singular_20values_20computation_20function_17',['@ref la_svd::svdvals &quot;svdvals&quot; - Singular Values Computation (function).',['../index.html#autotoc_md67',1,'']]],
  ['return_20value_18',['Return value',['../index.html#autotoc_md10',1,'Return value'],['../index.html#autotoc_md16',1,'Return value'],['../index.html#autotoc_md23',1,'Return value'],['../index.html#autotoc_md30',1,'Return value'],['../index.html#autotoc_md43',1,'Return value'],['../index.html#autotoc_md50',1,'Return value'],['../index.html#autotoc_md57',1,'Return value'],['../index.html#autotoc_md64',1,'Return value'],['../index.html#autotoc_md71',1,'Return value'],['../index.html#autotoc_md78',1,'Return value'],['../index.html#autotoc_md85',1,'Return value'],['../index.html#autotoc_md96',1,'Return value'],['../index.html#autotoc_md103',1,'Return value'],['../index.html#autotoc_md110',1,'Return value'],['../index.html#autotoc_md117',1,'Return value']]],
  ['rot_19',['rot',['../interfacela__blas_1_1rot.html',1,'la_blas::rot'],['../interfacela__lapack_1_1rot.html',1,'la_lapack::rot']]],
  ['rotg_20',['rotg',['../interfacela__blas_1_1rotg.html',1,'la_blas']]],
  ['rotm_21',['rotm',['../interfacela__blas_1_1rotm.html',1,'la_blas']]],
  ['rotmg_22',['rotmg',['../interfacela__blas_1_1rotmg.html',1,'la_blas']]],
  ['rscl_23',['rscl',['../interfacela__lapack_1_1rscl.html',1,'la_lapack']]]
];
