var searchData=
[
  ['pbcon_0',['pbcon',['../interfacela__lapack_1_1pbcon.html',1,'la_lapack']]],
  ['pbequ_1',['pbequ',['../interfacela__lapack_1_1pbequ.html',1,'la_lapack']]],
  ['pbrfs_2',['pbrfs',['../interfacela__lapack_1_1pbrfs.html',1,'la_lapack']]],
  ['pbstf_3',['pbstf',['../interfacela__lapack_1_1pbstf.html',1,'la_lapack']]],
  ['pbsv_4',['pbsv',['../interfacela__lapack_1_1pbsv.html',1,'la_lapack']]],
  ['pbtrf_5',['pbtrf',['../interfacela__lapack_1_1pbtrf.html',1,'la_lapack']]],
  ['pbtrs_6',['pbtrs',['../interfacela__lapack_1_1pbtrs.html',1,'la_lapack']]],
  ['penrose_20pseudo_20inverse_20of_20a_20matrix_7',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md196',1,'']]],
  ['penrose_20pseudo_20inverse_20of_20a_20matrix_20function_8',['@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).',['../index.html#autotoc_md189',1,'']]],
  ['pftrf_9',['pftrf',['../interfacela__lapack_1_1pftrf.html',1,'la_lapack']]],
  ['pftri_10',['pftri',['../interfacela__lapack_1_1pftri.html',1,'la_lapack']]],
  ['pftrs_11',['pftrs',['../interfacela__lapack_1_1pftrs.html',1,'la_lapack']]],
  ['pinv_12',['pinv',['../interfacela__pseudoinverse_1_1pinv.html',1,'la_pseudoinverse']]],
  ['pinv_20compute_20the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_13',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md196',1,'']]],
  ['pinv_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_20function_14',['@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).',['../index.html#autotoc_md189',1,'']]],
  ['pinv_20operator_20pinv_20compute_20the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_15',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md196',1,'']]],
  ['pocon_16',['pocon',['../interfacela__lapack_1_1pocon.html',1,'la_lapack']]],
  ['poequ_17',['poequ',['../interfacela__lapack_1_1poequ.html',1,'la_lapack']]],
  ['poequb_18',['poequb',['../interfacela__lapack_1_1poequb.html',1,'la_lapack']]],
  ['porfs_19',['porfs',['../interfacela__lapack_1_1porfs.html',1,'la_lapack']]],
  ['positive_20definite_20system_20',['@ref la_solve::solve_chol &quot;solve_chol&quot; - Solve a Hermitian positive definite system.',['../index.html#autotoc_md88',1,'']]],
  ['posv_21',['posv',['../interfacela__lapack_1_1posv.html',1,'la_lapack']]],
  ['potrf_22',['potrf',['../interfacela__lapack_1_1potrf.html',1,'la_lapack']]],
  ['potrf2_23',['potrf2',['../interfacela__lapack_1_1potrf2.html',1,'la_lapack']]],
  ['potri_24',['potri',['../interfacela__lapack_1_1potri.html',1,'la_lapack']]],
  ['potrs_25',['potrs',['../interfacela__lapack_1_1potrs.html',1,'la_lapack']]],
  ['ppcon_26',['ppcon',['../interfacela__lapack_1_1ppcon.html',1,'la_lapack']]],
  ['ppequ_27',['ppequ',['../interfacela__lapack_1_1ppequ.html',1,'la_lapack']]],
  ['pprfs_28',['pprfs',['../interfacela__lapack_1_1pprfs.html',1,'la_lapack']]],
  ['ppsv_29',['ppsv',['../interfacela__lapack_1_1ppsv.html',1,'la_lapack']]],
  ['pptrf_30',['pptrf',['../interfacela__lapack_1_1pptrf.html',1,'la_lapack']]],
  ['pptri_31',['pptri',['../interfacela__lapack_1_1pptri.html',1,'la_lapack']]],
  ['pptrs_32',['pptrs',['../interfacela__lapack_1_1pptrs.html',1,'la_lapack']]],
  ['pre_20allocated_20array_33',['pre allocated array',['../index.html#autotoc_md142',1,'@ref la_least_squares::solve_constrained_lstsq &quot;solve_constrained_lstsq&quot; - Equality-constrained least squares solution into a pre-allocated array.'],['../index.html#autotoc_md114',1,'@ref la_least_squares::solve_lstsq &quot;solve_lstsq&quot; - Least squares solution into a pre-allocated array.'],['../index.html#autotoc_md128',1,'@ref la_least_squares::solve_weighted_lstsq &quot;solve_weighted_lstsq&quot; - Weighted least squares solution into a pre-allocated array.'],['../index.html#autotoc_md82',1,'@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.']]],
  ['print_34',['print',['../structla__state__type_1_1la__state.html#a1bf21a3d9fb2c19dfd232528c5b276c8',1,'la_state_type::la_state']]],
  ['print_5fmsg_35',['print_msg',['../structla__state__type_1_1la__state.html#a21d84049d0505e846d324195997e5cbf',1,'la_state_type::la_state']]],
  ['product_20of_20two_203_20dimensional_20vectors_36',['@ref la_eye::cross_product &quot;cross_product&quot; - Cross product of two 3-dimensional vectors.',['../index.html#autotoc_md245',1,'']]],
  ['product_20of_20two_20matrices_37',['@ref la_eye::kronecker_product &quot;kronecker_product&quot; - Kronecker product of two matrices.',['../index.html#autotoc_md252',1,'']]],
  ['product_20of_20two_20vectors_38',['@ref la_eye::outer_product &quot;outer_product&quot; - Outer product of two vectors.',['../index.html#autotoc_md238',1,'']]],
  ['pseudo_20inverse_20of_20a_20matrix_39',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md196',1,'']]],
  ['pseudo_20inverse_20of_20a_20matrix_20function_40',['@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).',['../index.html#autotoc_md189',1,'']]],
  ['pseudoinvert_41',['pseudoinvert',['../interfacela__pseudoinverse_1_1pseudoinvert.html',1,'la_pseudoinverse']]],
  ['pstrf_42',['pstrf',['../interfacela__lapack_1_1pstrf.html',1,'la_lapack']]],
  ['ptcon_43',['ptcon',['../interfacela__lapack_1_1ptcon.html',1,'la_lapack']]],
  ['pteqr_44',['pteqr',['../interfacela__lapack_1_1pteqr.html',1,'la_lapack']]],
  ['ptrfs_45',['ptrfs',['../interfacela__lapack_1_1ptrfs.html',1,'la_lapack']]],
  ['ptsv_46',['ptsv',['../interfacela__lapack_1_1ptsv.html',1,'la_lapack']]],
  ['pttrf_47',['pttrf',['../interfacela__lapack_1_1pttrf.html',1,'la_lapack']]],
  ['pttrs_48',['pttrs',['../interfacela__lapack_1_1pttrs.html',1,'la_lapack']]]
];
