var searchData=
[
  ['tbmv_0',['tbmv',['../interfacela__blas_1_1tbmv.html',1,'la_blas']]],
  ['tbsv_1',['tbsv',['../interfacela__blas_1_1tbsv.html',1,'la_blas']]],
  ['to_20external_20blas_20lapack_20libraries_2',['Extension to external BLAS/LAPACK libraries',['../index.html#autotoc_md32',1,'']]],
  ['tpmv_3',['tpmv',['../interfacela__blas_1_1tpmv.html',1,'la_blas']]],
  ['tpsv_4',['tpsv',['../interfacela__blas_1_1tpsv.html',1,'la_blas']]],
  ['trmm_5',['trmm',['../interfacela__blas_1_1trmm.html',1,'la_blas']]],
  ['trmv_6',['trmv',['../interfacela__blas_1_1trmv.html',1,'la_blas']]],
  ['trsm_7',['trsm',['../interfacela__blas_1_1trsm.html',1,'la_blas']]],
  ['trsv_8',['trsv',['../interfacela__blas_1_1trsv.html',1,'la_blas']]],
  ['tt_9',['tt',['../index.html#autotoc_md17',1,'&lt;tt&gt;.inv.A&lt;/tt&gt;'],['../index.html#autotoc_md18',1,'&lt;tt&gt;.pinv.A&lt;/tt&gt;'],['../index.html#autotoc_md13',1,'&lt;tt&gt;det(A)&lt;/tt&gt;'],['../index.html#autotoc_md26',1,'&lt;tt&gt;diag(n, source)&lt;/tt&gt;'],['../index.html#autotoc_md27',1,'&lt;tt&gt;diag(source)&lt;/tt&gt;'],['../index.html#autotoc_md23',1,'&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md25',1,'&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md22',1,'&lt;tt&gt;eigvals(A)&lt;/tt&gt;'],['../index.html#autotoc_md24',1,'&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;'],['../index.html#autotoc_md21',1,'&lt;tt&gt;eye(m)&lt;/tt&gt;'],['../index.html#autotoc_md14',1,'&lt;tt&gt;inv(A)&lt;/tt&gt;'],['../index.html#autotoc_md16',1,'&lt;tt&gt;invert(A)&lt;/tt&gt;'],['../index.html#autotoc_md12',1,'&lt;tt&gt;lstsq(A, b)&lt;/tt&gt;'],['../index.html#autotoc_md15',1,'&lt;tt&gt;pinv(A)&lt;/tt&gt;'],['../index.html#autotoc_md28',1,'&lt;tt&gt;qr(A, Q, R)&lt;/tt&gt;'],['../index.html#autotoc_md29',1,'&lt;tt&gt;qr_space(A, lwork)&lt;/tt&gt;'],['../index.html#autotoc_md19',1,'&lt;tt&gt;svd(A)&lt;/tt&gt;'],['../index.html#autotoc_md20',1,'&lt;tt&gt;svdvals(A)&lt;/tt&gt;']]],
  ['tt_20det_20a_20tt_10',['&lt;tt&gt;det(A)&lt;/tt&gt;',['../index.html#autotoc_md13',1,'']]],
  ['tt_20diag_20n_20source_20tt_11',['&lt;tt&gt;diag(n, source)&lt;/tt&gt;',['../index.html#autotoc_md26',1,'']]],
  ['tt_20diag_20source_20tt_12',['&lt;tt&gt;diag(source)&lt;/tt&gt;',['../index.html#autotoc_md27',1,'']]],
  ['tt_20eig_20a_20lambda_20tt_13',['&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md23',1,'']]],
  ['tt_20eigh_20a_20lambda_20tt_14',['&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md25',1,'']]],
  ['tt_20eigvals_20a_20tt_15',['&lt;tt&gt;eigvals(A)&lt;/tt&gt;',['../index.html#autotoc_md22',1,'']]],
  ['tt_20eigvalsh_20a_20tt_16',['&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;',['../index.html#autotoc_md24',1,'']]],
  ['tt_20eye_20m_20tt_17',['&lt;tt&gt;eye(m)&lt;/tt&gt;',['../index.html#autotoc_md21',1,'']]],
  ['tt_20inv_20a_20tt_18',['tt inv A tt',['../index.html#autotoc_md17',1,'&lt;tt&gt;.inv.A&lt;/tt&gt;'],['../index.html#autotoc_md14',1,'&lt;tt&gt;inv(A)&lt;/tt&gt;']]],
  ['tt_20invert_20a_20tt_19',['&lt;tt&gt;invert(A)&lt;/tt&gt;',['../index.html#autotoc_md16',1,'']]],
  ['tt_20lstsq_20a_20b_20tt_20',['&lt;tt&gt;lstsq(A, b)&lt;/tt&gt;',['../index.html#autotoc_md12',1,'']]],
  ['tt_20pinv_20a_20tt_21',['tt pinv A tt',['../index.html#autotoc_md18',1,'&lt;tt&gt;.pinv.A&lt;/tt&gt;'],['../index.html#autotoc_md15',1,'&lt;tt&gt;pinv(A)&lt;/tt&gt;']]],
  ['tt_20qr_20a_20q_20r_20tt_22',['&lt;tt&gt;qr(A, Q, R)&lt;/tt&gt;',['../index.html#autotoc_md28',1,'']]],
  ['tt_20qr_5fspace_20a_20lwork_20tt_23',['&lt;tt&gt;qr_space(A, lwork)&lt;/tt&gt;',['../index.html#autotoc_md29',1,'']]],
  ['tt_20solve_20tt_20solves_20a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_24',['@ref la_solve::solve &quot;&lt;tt&gt;solve&lt;/tt&gt;&quot; - Solves a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md6',1,'']]],
  ['tt_20solves_20a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_25',['@ref la_solve::solve &quot;&lt;tt&gt;solve&lt;/tt&gt;&quot; - Solves a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md6',1,'']]],
  ['tt_20svd_20a_20tt_26',['&lt;tt&gt;svd(A)&lt;/tt&gt;',['../index.html#autotoc_md19',1,'']]],
  ['tt_20svdvals_20a_20tt_27',['&lt;tt&gt;svdvals(A)&lt;/tt&gt;',['../index.html#autotoc_md20',1,'']]]
];
