var searchData=
[
  ['a_20least_20squares_20solution_20to_20a_20system_20of_20linear_20equations_0',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md82',1,'']]],
  ['a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_1',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md70',1,'']]],
  ['a_20linear_20system_20into_20a_20pre_20allocated_20array_2',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md76',1,'']]],
  ['a_20linear_20system_20of_20equations_3',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md70',1,'']]],
  ['a_20matrix_4',['a matrix',['../index.html#autotoc_md130',1,'@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.'],['../index.html#autotoc_md165',1,'@ref la_qr::qr &quot;qr&quot; - QR factorization of a matrix.'],['../index.html#autotoc_md179',1,'@ref la_schur::schur &quot;schur&quot; - Schur decomposition of a matrix.'],['../index.html#autotoc_md137',1,'@ref la_svd::svd &quot;svd&quot; - Singular Value Decomposition (SVD) of a matrix']]],
  ['a_20matrix_20function_5',['a matrix function',['../index.html#autotoc_md31',1,'@ref la_cholesky::chol &quot;chol&quot; - Cholesky factorization of a matrix (function).'],['../index.html#autotoc_md123',1,'@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).']]],
  ['a_20matrix_20subroutine_6',['@ref la_cholesky::cholesky &quot;cholesky&quot; - Cholesky factorization of a matrix (subroutine).',['../index.html#autotoc_md38',1,'']]],
  ['a_20pre_20allocated_20array_7',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md76',1,'']]],
  ['a_20real_20symmetric_20or_20complex_20hermitian_20matrix_8',['a real symmetric or complex Hermitian matrix',['../index.html#autotoc_md50',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md63',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['a_20scalar_20or_20rectangular_20matrix_9',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md89',1,'']]],
  ['a_20square_20matrix_10',['a square matrix',['../index.html#autotoc_md96',1,'@ref la_determinant::operator(.det.) &quot;operator(.det.)&quot; - Determinant of a square matrix.'],['../index.html#autotoc_md44',1,'@ref la_eig::eig &quot;eig&quot; - Eigendecomposition of a square matrix.'],['../index.html#autotoc_md103',1,'@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.'],['../index.html#autotoc_md116',1,'@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.']]],
  ['a_20square_20matrix_20interface_11',['@ref la_eig::eigvals &quot;eigvals&quot; - Eigenvalues of a square matrix (interface).',['../index.html#autotoc_md56',1,'']]],
  ['a_20system_20of_20linear_20equations_12',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md82',1,'']]],
  ['acknowledgments_13',['Acknowledgments',['../index.html#autotoc_md198',1,'']]],
  ['allocated_20array_14',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md76',1,'']]],
  ['api_15',['Browse API',['../index.html#autotoc_md30',1,'']]],
  ['arguments_16',['Arguments',['../interfacela__eig_1_1eig.html#autotoc_md6',1,'Arguments'],['../interfacela__eig_1_1eigvals.html#autotoc_md11',1,'Arguments'],['../interfacela__eig_1_1eigh.html#autotoc_md17',1,'Arguments'],['../interfacela__eig_1_1eigvalsh.html#autotoc_md23',1,'Arguments'],['../index.html#autotoc_md34',1,'Arguments'],['../index.html#autotoc_md41',1,'Arguments'],['../index.html#autotoc_md47',1,'Arguments'],['../index.html#autotoc_md53',1,'Arguments'],['../index.html#autotoc_md59',1,'Arguments'],['../index.html#autotoc_md66',1,'Arguments'],['../index.html#autotoc_md73',1,'Arguments'],['../index.html#autotoc_md79',1,'Arguments'],['../index.html#autotoc_md85',1,'Arguments'],['../index.html#autotoc_md92',1,'Arguments'],['../index.html#autotoc_md99',1,'Arguments'],['../index.html#autotoc_md106',1,'Arguments'],['../index.html#autotoc_md113',1,'Arguments'],['../index.html#autotoc_md119',1,'Arguments'],['../index.html#autotoc_md126',1,'Arguments'],['../index.html#autotoc_md133',1,'Arguments'],['../index.html#autotoc_md140',1,'Arguments'],['../index.html#autotoc_md147',1,'Arguments'],['../index.html#autotoc_md154',1,'Arguments'],['../index.html#autotoc_md161',1,'Arguments'],['../index.html#autotoc_md168',1,'Arguments'],['../index.html#autotoc_md175',1,'Arguments'],['../index.html#autotoc_md182',1,'Arguments'],['../index.html#autotoc_md189',1,'Arguments']]],
  ['array_17',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md76',1,'']]],
  ['axpy_18',['axpy',['../interfacela__blas_1_1axpy.html',1,'la_blas']]]
];
