var searchData=
[
  ['of_20a_20matrix_0',['@ref la_qr::qr &quot;&lt;tt&gt;qr&lt;/tt&gt;&quot; - Compute the QR factorization of a matrix.',['../index.html#autotoc_md34',1,'']]],
  ['of_20equations_1',['@ref la_solve::solve &quot;&lt;tt&gt;solve&lt;/tt&gt;&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md6',1,'']]],
  ['of_20linear_20equations_2',['@ref la_least_squares::lstsq &quot;&lt;tt&gt;lstsq&lt;/tt&gt;&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md12',1,'']]],
  ['ok_3',['ok',['../structla__state__type_1_1la__state.html#a7cbd8a858eb21bff269f3f582b1d881e',1,'la_state_type::la_state']]],
  ['operations_4',['@ref la_qr::qr_space &quot;&lt;tt&gt;qr_space&lt;/tt&gt;&quot; - Workspace size for QR operations.',['../index.html#autotoc_md41',1,'']]],
  ['operator_28_2einv_2e_29_5',['operator(.inv.)',['../interfacela__inverse_1_1operator_07_8inv_8_08.html',1,'la_inverse']]],
  ['operator_28_2epinv_2e_29_6',['operator(.pinv.)',['../interfacela__pseudoinverse_1_1operator_07_8pinv_8_08.html',1,'la_pseudoinverse']]],
  ['operator_28_2f_3d_29_7',['operator(/=)',['../interfacela__state__type_1_1operator_07_2_0a_08.html',1,'la_state_type']]],
  ['operator_28_3c_29_8',['operator(&lt;)',['../interfacela__state__type_1_1operator_07_3_08.html',1,'la_state_type']]],
  ['operator_28_3c_3d_29_9',['operator(&lt;=)',['../interfacela__state__type_1_1operator_07_3_0a_08.html',1,'la_state_type']]],
  ['operator_28_3d_3d_29_10',['operator(==)',['../interfacela__state__type_1_1operator_07_0a_0a_08.html',1,'la_state_type']]],
  ['operator_28_3e_29_11',['operator(&gt;)',['../interfacela__state__type_1_1operator_07_4_08.html',1,'la_state_type']]],
  ['operator_28_3e_3d_29_12',['operator(&gt;=)',['../interfacela__state__type_1_1operator_07_4_0a_08.html',1,'la_state_type']]],
  ['opgtr_13',['opgtr',['../interfacela__lapack_1_1opgtr.html',1,'la_lapack']]],
  ['opmtr_14',['opmtr',['../interfacela__lapack_1_1opmtr.html',1,'la_lapack']]],
  ['or_20a_20linear_20system_20of_20equations_15',['@ref la_solve::solve &quot;&lt;tt&gt;solve&lt;/tt&gt;&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md6',1,'']]],
  ['orbdb_16',['orbdb',['../interfacela__lapack_1_1orbdb.html',1,'la_lapack']]],
  ['orbdb1_17',['orbdb1',['../interfacela__lapack_1_1orbdb1.html',1,'la_lapack']]],
  ['orbdb2_18',['orbdb2',['../interfacela__lapack_1_1orbdb2.html',1,'la_lapack']]],
  ['orbdb3_19',['orbdb3',['../interfacela__lapack_1_1orbdb3.html',1,'la_lapack']]],
  ['orbdb4_20',['orbdb4',['../interfacela__lapack_1_1orbdb4.html',1,'la_lapack']]],
  ['orbdb5_21',['orbdb5',['../interfacela__lapack_1_1orbdb5.html',1,'la_lapack']]],
  ['orbdb6_22',['orbdb6',['../interfacela__lapack_1_1orbdb6.html',1,'la_lapack']]],
  ['orcsd_23',['orcsd',['../interfacela__lapack_1_1orcsd.html',1,'la_lapack']]],
  ['orcsd2by1_24',['orcsd2by1',['../interfacela__lapack_1_1orcsd2by1.html',1,'la_lapack']]],
  ['org2l_25',['org2l',['../interfacela__lapack_1_1org2l.html',1,'la_lapack']]],
  ['org2r_26',['org2r',['../interfacela__lapack_1_1org2r.html',1,'la_lapack']]],
  ['orgbr_27',['orgbr',['../interfacela__lapack_1_1orgbr.html',1,'la_lapack']]],
  ['orghr_28',['orghr',['../interfacela__lapack_1_1orghr.html',1,'la_lapack']]],
  ['orglq_29',['orglq',['../interfacela__lapack_1_1orglq.html',1,'la_lapack']]],
  ['orgql_30',['orgql',['../interfacela__lapack_1_1orgql.html',1,'la_lapack']]],
  ['orgqr_31',['orgqr',['../interfacela__lapack_1_1orgqr.html',1,'la_lapack']]],
  ['orgrq_32',['orgrq',['../interfacela__lapack_1_1orgrq.html',1,'la_lapack']]],
  ['orgtr_33',['orgtr',['../interfacela__lapack_1_1orgtr.html',1,'la_lapack']]],
  ['orgtsqr_34',['orgtsqr',['../interfacela__lapack_1_1orgtsqr.html',1,'la_lapack']]],
  ['orgtsqr_5frow_35',['orgtsqr_row',['../interfacela__lapack_1_1orgtsqr__row.html',1,'la_lapack']]],
  ['orhr_5fcol_36',['orhr_col',['../interfacela__lapack_1_1orhr__col.html',1,'la_lapack']]],
  ['orm2l_37',['orm2l',['../interfacela__lapack_1_1orm2l.html',1,'la_lapack']]],
  ['orm2r_38',['orm2r',['../interfacela__lapack_1_1orm2r.html',1,'la_lapack']]],
  ['ormbr_39',['ormbr',['../interfacela__lapack_1_1ormbr.html',1,'la_lapack']]],
  ['ormhr_40',['ormhr',['../interfacela__lapack_1_1ormhr.html',1,'la_lapack']]],
  ['ormlq_41',['ormlq',['../interfacela__lapack_1_1ormlq.html',1,'la_lapack']]],
  ['ormql_42',['ormql',['../interfacela__lapack_1_1ormql.html',1,'la_lapack']]],
  ['ormqr_43',['ormqr',['../interfacela__lapack_1_1ormqr.html',1,'la_lapack']]],
  ['ormrq_44',['ormrq',['../interfacela__lapack_1_1ormrq.html',1,'la_lapack']]],
  ['ormrz_45',['ormrz',['../interfacela__lapack_1_1ormrz.html',1,'la_lapack']]],
  ['ormtr_46',['ormtr',['../interfacela__lapack_1_1ormtr.html',1,'la_lapack']]]
];
