var searchData=
[
  ['tbcon_0',['tbcon',['../interfacela__lapack_1_1tbcon.html',1,'la_lapack']]],
  ['tbig_1',['tbig',['../namespacela__constants__sp.html#a7b7b5c31ad7821fcd6c694f4581924ef',1,'la_constants_sp::tbig'],['../namespacela__constants__dp.html#a0f0be8f50836f5e2d2ec20f7839aebbc',1,'la_constants_dp::tbig'],['../namespacela__constants__qp.html#a6674345bb3dbe6ca92fec7a6301f1f79',1,'la_constants_qp::tbig']]],
  ['tbmv_2',['tbmv',['../interfacela__blas_1_1tbmv.html',1,'la_blas']]],
  ['tbrfs_3',['tbrfs',['../interfacela__lapack_1_1tbrfs.html',1,'la_lapack']]],
  ['tbsv_4',['tbsv',['../interfacela__blas_1_1tbsv.html',1,'la_blas']]],
  ['tbtrs_5',['tbtrs',['../interfacela__lapack_1_1tbtrs.html',1,'la_lapack']]],
  ['ten_6',['ten',['../namespacela__constants__sp.html#a1c82828c49553e38733a8272dc90511b',1,'la_constants_sp::ten'],['../namespacela__constants__dp.html#afe645d862a85db72ed8c0883bb146ec8',1,'la_constants_dp::ten'],['../namespacela__constants__qp.html#a42ae6a8ba1fcdd90ec81a09dc5afc41f',1,'la_constants_qp::ten']]],
  ['tfsm_7',['tfsm',['../interfacela__lapack_1_1tfsm.html',1,'la_lapack']]],
  ['tftri_8',['tftri',['../interfacela__lapack_1_1tftri.html',1,'la_lapack']]],
  ['tfttp_9',['tfttp',['../interfacela__lapack_1_1tfttp.html',1,'la_lapack']]],
  ['tfttr_10',['tfttr',['../interfacela__lapack_1_1tfttr.html',1,'la_lapack']]],
  ['tgevc_11',['tgevc',['../interfacela__lapack_1_1tgevc.html',1,'la_lapack']]],
  ['tgexc_12',['tgexc',['../interfacela__lapack_1_1tgexc.html',1,'la_lapack']]],
  ['tgsen_13',['tgsen',['../interfacela__lapack_1_1tgsen.html',1,'la_lapack']]],
  ['tgsja_14',['tgsja',['../interfacela__lapack_1_1tgsja.html',1,'la_lapack']]],
  ['tgsna_15',['tgsna',['../interfacela__lapack_1_1tgsna.html',1,'la_lapack']]],
  ['tgsyl_16',['tgsyl',['../interfacela__lapack_1_1tgsyl.html',1,'la_lapack']]],
  ['the_20inverse_20of_20a_20square_20matrix_17',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md134',1,'']]],
  ['the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_18',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md148',1,'']]],
  ['three_19',['three',['../namespacela__constants__sp.html#aaa47f7c494fac3a7b8ce70adbd2aceb5',1,'la_constants_sp::three'],['../namespacela__constants__dp.html#ac7384717320ed34160c97e1ef6f0f064',1,'la_constants_dp::three'],['../namespacela__constants__qp.html#a1ef9b9edfcc42ad54e3c24e64678160f',1,'la_constants_qp::three']]],
  ['to_20a_20system_20of_20linear_20equations_20',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md100',1,'']]],
  ['to_20external_20blas_20lapack_20libraries_21',['Extension to external BLAS/LAPACK libraries',['../index.html#autotoc_md297',1,'']]],
  ['tpcon_22',['tpcon',['../interfacela__lapack_1_1tpcon.html',1,'la_lapack']]],
  ['tplqt_23',['tplqt',['../interfacela__lapack_1_1tplqt.html',1,'la_lapack']]],
  ['tplqt2_24',['tplqt2',['../interfacela__lapack_1_1tplqt2.html',1,'la_lapack']]],
  ['tpmlqt_25',['tpmlqt',['../interfacela__lapack_1_1tpmlqt.html',1,'la_lapack']]],
  ['tpmqrt_26',['tpmqrt',['../interfacela__lapack_1_1tpmqrt.html',1,'la_lapack']]],
  ['tpmv_27',['tpmv',['../interfacela__blas_1_1tpmv.html',1,'la_blas']]],
  ['tpqrt_28',['tpqrt',['../interfacela__lapack_1_1tpqrt.html',1,'la_lapack']]],
  ['tpqrt2_29',['tpqrt2',['../interfacela__lapack_1_1tpqrt2.html',1,'la_lapack']]],
  ['tprfb_30',['tprfb',['../interfacela__lapack_1_1tprfb.html',1,'la_lapack']]],
  ['tprfs_31',['tprfs',['../interfacela__lapack_1_1tprfs.html',1,'la_lapack']]],
  ['tpsv_32',['tpsv',['../interfacela__blas_1_1tpsv.html',1,'la_blas']]],
  ['tptri_33',['tptri',['../interfacela__lapack_1_1tptri.html',1,'la_lapack']]],
  ['tptrs_34',['tptrs',['../interfacela__lapack_1_1tptrs.html',1,'la_lapack']]],
  ['tpttf_35',['tpttf',['../interfacela__lapack_1_1tpttf.html',1,'la_lapack']]],
  ['tpttr_36',['tpttr',['../interfacela__lapack_1_1tpttr.html',1,'la_lapack']]],
  ['trace_37',['trace',['../interfacela__eye_1_1trace.html',1,'la_eye']]],
  ['trace_20of_20a_20matrix_38',['@ref la_eye::trace &quot;trace&quot; - Trace of a matrix.',['../index.html#autotoc_md183',1,'']]],
  ['trace_20trace_20of_20a_20matrix_39',['@ref la_eye::trace &quot;trace&quot; - Trace of a matrix.',['../index.html#autotoc_md183',1,'']]],
  ['transpose_20of_20a_20matrix_40',['@ref la_eye::hermitian &quot;hermitian&quot; - Hermitian transpose of a matrix.',['../index.html#autotoc_md211',1,'']]],
  ['trcon_41',['trcon',['../interfacela__lapack_1_1trcon.html',1,'la_lapack']]],
  ['trevc_42',['trevc',['../interfacela__lapack_1_1trevc.html',1,'la_lapack']]],
  ['trevc3_43',['trevc3',['../interfacela__lapack_1_1trevc3.html',1,'la_lapack']]],
  ['trexc_44',['trexc',['../interfacela__lapack_1_1trexc.html',1,'la_lapack']]],
  ['triangular_45',['@ref la_matrix_property_checks::is_triangular &quot;is_triangular&quot; - Check whether a matrix is triangular.',['../index.html#autotoc_md253',1,'']]],
  ['trmm_46',['trmm',['../interfacela__blas_1_1trmm.html',1,'la_blas']]],
  ['trmv_47',['trmv',['../interfacela__blas_1_1trmv.html',1,'la_blas']]],
  ['trrfs_48',['trrfs',['../interfacela__lapack_1_1trrfs.html',1,'la_lapack']]],
  ['trsen_49',['trsen',['../interfacela__lapack_1_1trsen.html',1,'la_lapack']]],
  ['trsm_50',['trsm',['../interfacela__blas_1_1trsm.html',1,'la_blas']]],
  ['trsna_51',['trsna',['../interfacela__lapack_1_1trsna.html',1,'la_lapack']]],
  ['trsv_52',['trsv',['../interfacela__blas_1_1trsv.html',1,'la_blas']]],
  ['trsyl_53',['trsyl',['../interfacela__lapack_1_1trsyl.html',1,'la_lapack']]],
  ['trtri_54',['trtri',['../interfacela__lapack_1_1trtri.html',1,'la_lapack']]],
  ['trtrs_55',['trtrs',['../interfacela__lapack_1_1trtrs.html',1,'la_lapack']]],
  ['trttf_56',['trttf',['../interfacela__lapack_1_1trttf.html',1,'la_lapack']]],
  ['trttp_57',['trttp',['../interfacela__lapack_1_1trttp.html',1,'la_lapack']]],
  ['tsml_58',['tsml',['../namespacela__constants__sp.html#a565282d743b3e42a90a040958e632a7d',1,'la_constants_sp::tsml'],['../namespacela__constants__dp.html#a9be8ac97da1337ac237ef57e419fb22e',1,'la_constants_dp::tsml'],['../namespacela__constants__qp.html#a94a0acc70cece0f67c5123f2184eff90',1,'la_constants_qp::tsml']]],
  ['two_59',['two',['../namespacela__constants__sp.html#a803dd10734830eca99dd490fc6e12799',1,'la_constants_sp::two'],['../namespacela__constants__dp.html#aff1d8ba89977ac41995fb8fe9dac41fe',1,'la_constants_dp::two'],['../namespacela__constants__qp.html#a4bf80b6bdfcac286e01822d49beb7ab2',1,'la_constants_qp::two']]],
  ['two_203_20dimensional_20vectors_60',['@ref la_eye::cross_product &quot;cross_product&quot; - Cross product of two 3-dimensional vectors.',['../index.html#autotoc_md197',1,'']]],
  ['two_20matrices_61',['@ref la_eye::kronecker_product &quot;kronecker_product&quot; - Kronecker product of two matrices.',['../index.html#autotoc_md204',1,'']]],
  ['two_20vectors_62',['@ref la_eye::outer_product &quot;outer_product&quot; - Outer product of two vectors.',['../index.html#autotoc_md190',1,'']]],
  ['tzrzf_63',['tzrzf',['../interfacela__lapack_1_1tzrzf.html',1,'la_lapack']]]
];
