var searchData=
[
  ['tbcon_0',['tbcon',['../interfacela__lapack_1_1tbcon.html',1,'la_lapack']]],
  ['tbmv_1',['tbmv',['../interfacela__blas_1_1tbmv.html',1,'la_blas']]],
  ['tbrfs_2',['tbrfs',['../interfacela__lapack_1_1tbrfs.html',1,'la_lapack']]],
  ['tbsv_3',['tbsv',['../interfacela__blas_1_1tbsv.html',1,'la_blas']]],
  ['tbtrs_4',['tbtrs',['../interfacela__lapack_1_1tbtrs.html',1,'la_lapack']]],
  ['tfsm_5',['tfsm',['../interfacela__lapack_1_1tfsm.html',1,'la_lapack']]],
  ['tftri_6',['tftri',['../interfacela__lapack_1_1tftri.html',1,'la_lapack']]],
  ['tfttp_7',['tfttp',['../interfacela__lapack_1_1tfttp.html',1,'la_lapack']]],
  ['tfttr_8',['tfttr',['../interfacela__lapack_1_1tfttr.html',1,'la_lapack']]],
  ['tgevc_9',['tgevc',['../interfacela__lapack_1_1tgevc.html',1,'la_lapack']]],
  ['tgexc_10',['tgexc',['../interfacela__lapack_1_1tgexc.html',1,'la_lapack']]],
  ['tgsen_11',['tgsen',['../interfacela__lapack_1_1tgsen.html',1,'la_lapack']]],
  ['tgsja_12',['tgsja',['../interfacela__lapack_1_1tgsja.html',1,'la_lapack']]],
  ['tgsna_13',['tgsna',['../interfacela__lapack_1_1tgsna.html',1,'la_lapack']]],
  ['tgsyl_14',['tgsyl',['../interfacela__lapack_1_1tgsyl.html',1,'la_lapack']]],
  ['the_20inverse_20of_20a_20square_20matrix_15',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md39',1,'']]],
  ['the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_16',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md53',1,'']]],
  ['the_20qr_20factorization_20of_20a_20matrix_17',['@ref la_qr::qr &quot;qr&quot; - Compute the QR factorization of a matrix.',['../index.html#autotoc_md69',1,'']]],
  ['to_20a_20system_20of_20linear_20equations_18',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md12',1,'']]],
  ['to_20external_20blas_20lapack_20libraries_19',['Extension to external BLAS/LAPACK libraries',['../index.html#autotoc_md85',1,'']]],
  ['tpcon_20',['tpcon',['../interfacela__lapack_1_1tpcon.html',1,'la_lapack']]],
  ['tplqt_21',['tplqt',['../interfacela__lapack_1_1tplqt.html',1,'la_lapack']]],
  ['tplqt2_22',['tplqt2',['../interfacela__lapack_1_1tplqt2.html',1,'la_lapack']]],
  ['tpmlqt_23',['tpmlqt',['../interfacela__lapack_1_1tpmlqt.html',1,'la_lapack']]],
  ['tpmqrt_24',['tpmqrt',['../interfacela__lapack_1_1tpmqrt.html',1,'la_lapack']]],
  ['tpmv_25',['tpmv',['../interfacela__blas_1_1tpmv.html',1,'la_blas']]],
  ['tpqrt_26',['tpqrt',['../interfacela__lapack_1_1tpqrt.html',1,'la_lapack']]],
  ['tpqrt2_27',['tpqrt2',['../interfacela__lapack_1_1tpqrt2.html',1,'la_lapack']]],
  ['tprfb_28',['tprfb',['../interfacela__lapack_1_1tprfb.html',1,'la_lapack']]],
  ['tprfs_29',['tprfs',['../interfacela__lapack_1_1tprfs.html',1,'la_lapack']]],
  ['tpsv_30',['tpsv',['../interfacela__blas_1_1tpsv.html',1,'la_blas']]],
  ['tptri_31',['tptri',['../interfacela__lapack_1_1tptri.html',1,'la_lapack']]],
  ['tptrs_32',['tptrs',['../interfacela__lapack_1_1tptrs.html',1,'la_lapack']]],
  ['tpttf_33',['tpttf',['../interfacela__lapack_1_1tpttf.html',1,'la_lapack']]],
  ['tpttr_34',['tpttr',['../interfacela__lapack_1_1tpttr.html',1,'la_lapack']]],
  ['trcon_35',['trcon',['../interfacela__lapack_1_1trcon.html',1,'la_lapack']]],
  ['trevc_36',['trevc',['../interfacela__lapack_1_1trevc.html',1,'la_lapack']]],
  ['trevc3_37',['trevc3',['../interfacela__lapack_1_1trevc3.html',1,'la_lapack']]],
  ['trexc_38',['trexc',['../interfacela__lapack_1_1trexc.html',1,'la_lapack']]],
  ['trmm_39',['trmm',['../interfacela__blas_1_1trmm.html',1,'la_blas']]],
  ['trmv_40',['trmv',['../interfacela__blas_1_1trmv.html',1,'la_blas']]],
  ['trrfs_41',['trrfs',['../interfacela__lapack_1_1trrfs.html',1,'la_lapack']]],
  ['trsen_42',['trsen',['../interfacela__lapack_1_1trsen.html',1,'la_lapack']]],
  ['trsm_43',['trsm',['../interfacela__blas_1_1trsm.html',1,'la_blas']]],
  ['trsna_44',['trsna',['../interfacela__lapack_1_1trsna.html',1,'la_lapack']]],
  ['trsv_45',['trsv',['../interfacela__blas_1_1trsv.html',1,'la_blas']]],
  ['trsyl_46',['trsyl',['../interfacela__lapack_1_1trsyl.html',1,'la_lapack']]],
  ['trtri_47',['trtri',['../interfacela__lapack_1_1trtri.html',1,'la_lapack']]],
  ['trtrs_48',['trtrs',['../interfacela__lapack_1_1trtrs.html',1,'la_lapack']]],
  ['trttf_49',['trttf',['../interfacela__lapack_1_1trttf.html',1,'la_lapack']]],
  ['trttp_50',['trttp',['../interfacela__lapack_1_1trttp.html',1,'la_lapack']]],
  ['tt_51',['tt',['../index.html#autotoc_md67',1,'&lt;tt&gt;diag(n, source)&lt;/tt&gt;'],['../index.html#autotoc_md68',1,'&lt;tt&gt;diag(source)&lt;/tt&gt;'],['../index.html#autotoc_md64',1,'&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md66',1,'&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md63',1,'&lt;tt&gt;eigvals(A)&lt;/tt&gt;'],['../index.html#autotoc_md65',1,'&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;'],['../index.html#autotoc_md62',1,'&lt;tt&gt;eye(m)&lt;/tt&gt;'],['../index.html#autotoc_md60',1,'&lt;tt&gt;svd(A)&lt;/tt&gt;'],['../index.html#autotoc_md61',1,'&lt;tt&gt;svdvals(A)&lt;/tt&gt;']]],
  ['tt_20diag_20n_20source_20tt_52',['&lt;tt&gt;diag(n, source)&lt;/tt&gt;',['../index.html#autotoc_md67',1,'']]],
  ['tt_20diag_20source_20tt_53',['&lt;tt&gt;diag(source)&lt;/tt&gt;',['../index.html#autotoc_md68',1,'']]],
  ['tt_20eig_20a_20lambda_20tt_54',['&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md64',1,'']]],
  ['tt_20eigh_20a_20lambda_20tt_55',['&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md66',1,'']]],
  ['tt_20eigvals_20a_20tt_56',['&lt;tt&gt;eigvals(A)&lt;/tt&gt;',['../index.html#autotoc_md63',1,'']]],
  ['tt_20eigvalsh_20a_20tt_57',['&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;',['../index.html#autotoc_md65',1,'']]],
  ['tt_20eye_20m_20tt_58',['&lt;tt&gt;eye(m)&lt;/tt&gt;',['../index.html#autotoc_md62',1,'']]],
  ['tt_20svd_20a_20tt_59',['&lt;tt&gt;svd(A)&lt;/tt&gt;',['../index.html#autotoc_md60',1,'']]],
  ['tt_20svdvals_20a_20tt_60',['&lt;tt&gt;svdvals(A)&lt;/tt&gt;',['../index.html#autotoc_md61',1,'']]],
  ['tzrzf_61',['tzrzf',['../interfacela__lapack_1_1tzrzf.html',1,'la_lapack']]]
];
