var searchData=
[
  ['tbcon_0',['tbcon',['../interfacela__lapack_1_1tbcon.html',1,'la_lapack']]],
  ['tbmv_1',['tbmv',['../interfacela__blas_1_1tbmv.html',1,'la_blas']]],
  ['tbrfs_2',['tbrfs',['../interfacela__lapack_1_1tbrfs.html',1,'la_lapack']]],
  ['tbsv_3',['tbsv',['../interfacela__blas_1_1tbsv.html',1,'la_blas']]],
  ['tbtrs_4',['tbtrs',['../interfacela__lapack_1_1tbtrs.html',1,'la_lapack']]],
  ['tfsm_5',['tfsm',['../interfacela__lapack_1_1tfsm.html',1,'la_lapack']]],
  ['tftri_6',['tftri',['../interfacela__lapack_1_1tftri.html',1,'la_lapack']]],
  ['tfttp_7',['tfttp',['../interfacela__lapack_1_1tfttp.html',1,'la_lapack']]],
  ['tfttr_8',['tfttr',['../interfacela__lapack_1_1tfttr.html',1,'la_lapack']]],
  ['tgevc_9',['tgevc',['../interfacela__lapack_1_1tgevc.html',1,'la_lapack']]],
  ['tgexc_10',['tgexc',['../interfacela__lapack_1_1tgexc.html',1,'la_lapack']]],
  ['tgsen_11',['tgsen',['../interfacela__lapack_1_1tgsen.html',1,'la_lapack']]],
  ['tgsja_12',['tgsja',['../interfacela__lapack_1_1tgsja.html',1,'la_lapack']]],
  ['tgsna_13',['tgsna',['../interfacela__lapack_1_1tgsna.html',1,'la_lapack']]],
  ['tgsyl_14',['tgsyl',['../interfacela__lapack_1_1tgsyl.html',1,'la_lapack']]],
  ['the_20qr_20factorization_20of_20a_20matrix_15',['@ref la_qr::qr &quot;qr&quot; - Compute the QR factorization of a matrix.',['../index.html#autotoc_md34',1,'']]],
  ['to_20a_20system_20of_20linear_20equations_16',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md12',1,'']]],
  ['to_20external_20blas_20lapack_20libraries_17',['Extension to external BLAS/LAPACK libraries',['../index.html#autotoc_md50',1,'']]],
  ['tpcon_18',['tpcon',['../interfacela__lapack_1_1tpcon.html',1,'la_lapack']]],
  ['tplqt_19',['tplqt',['../interfacela__lapack_1_1tplqt.html',1,'la_lapack']]],
  ['tplqt2_20',['tplqt2',['../interfacela__lapack_1_1tplqt2.html',1,'la_lapack']]],
  ['tpmlqt_21',['tpmlqt',['../interfacela__lapack_1_1tpmlqt.html',1,'la_lapack']]],
  ['tpmqrt_22',['tpmqrt',['../interfacela__lapack_1_1tpmqrt.html',1,'la_lapack']]],
  ['tpmv_23',['tpmv',['../interfacela__blas_1_1tpmv.html',1,'la_blas']]],
  ['tpqrt_24',['tpqrt',['../interfacela__lapack_1_1tpqrt.html',1,'la_lapack']]],
  ['tpqrt2_25',['tpqrt2',['../interfacela__lapack_1_1tpqrt2.html',1,'la_lapack']]],
  ['tprfb_26',['tprfb',['../interfacela__lapack_1_1tprfb.html',1,'la_lapack']]],
  ['tprfs_27',['tprfs',['../interfacela__lapack_1_1tprfs.html',1,'la_lapack']]],
  ['tpsv_28',['tpsv',['../interfacela__blas_1_1tpsv.html',1,'la_blas']]],
  ['tptri_29',['tptri',['../interfacela__lapack_1_1tptri.html',1,'la_lapack']]],
  ['tptrs_30',['tptrs',['../interfacela__lapack_1_1tptrs.html',1,'la_lapack']]],
  ['tpttf_31',['tpttf',['../interfacela__lapack_1_1tpttf.html',1,'la_lapack']]],
  ['tpttr_32',['tpttr',['../interfacela__lapack_1_1tpttr.html',1,'la_lapack']]],
  ['trcon_33',['trcon',['../interfacela__lapack_1_1trcon.html',1,'la_lapack']]],
  ['trevc_34',['trevc',['../interfacela__lapack_1_1trevc.html',1,'la_lapack']]],
  ['trevc3_35',['trevc3',['../interfacela__lapack_1_1trevc3.html',1,'la_lapack']]],
  ['trexc_36',['trexc',['../interfacela__lapack_1_1trexc.html',1,'la_lapack']]],
  ['trmm_37',['trmm',['../interfacela__blas_1_1trmm.html',1,'la_blas']]],
  ['trmv_38',['trmv',['../interfacela__blas_1_1trmv.html',1,'la_blas']]],
  ['trrfs_39',['trrfs',['../interfacela__lapack_1_1trrfs.html',1,'la_lapack']]],
  ['trsen_40',['trsen',['../interfacela__lapack_1_1trsen.html',1,'la_lapack']]],
  ['trsm_41',['trsm',['../interfacela__blas_1_1trsm.html',1,'la_blas']]],
  ['trsna_42',['trsna',['../interfacela__lapack_1_1trsna.html',1,'la_lapack']]],
  ['trsv_43',['trsv',['../interfacela__blas_1_1trsv.html',1,'la_blas']]],
  ['trsyl_44',['trsyl',['../interfacela__lapack_1_1trsyl.html',1,'la_lapack']]],
  ['trtri_45',['trtri',['../interfacela__lapack_1_1trtri.html',1,'la_lapack']]],
  ['trtrs_46',['trtrs',['../interfacela__lapack_1_1trtrs.html',1,'la_lapack']]],
  ['trttf_47',['trttf',['../interfacela__lapack_1_1trttf.html',1,'la_lapack']]],
  ['trttp_48',['trttp',['../interfacela__lapack_1_1trttp.html',1,'la_lapack']]],
  ['tt_49',['tt',['../index.html#autotoc_md23',1,'&lt;tt&gt;.inv.A&lt;/tt&gt;'],['../index.html#autotoc_md24',1,'&lt;tt&gt;.pinv.A&lt;/tt&gt;'],['../index.html#autotoc_md19',1,'&lt;tt&gt;det(A)&lt;/tt&gt;'],['../index.html#autotoc_md32',1,'&lt;tt&gt;diag(n, source)&lt;/tt&gt;'],['../index.html#autotoc_md33',1,'&lt;tt&gt;diag(source)&lt;/tt&gt;'],['../index.html#autotoc_md29',1,'&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md31',1,'&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;'],['../index.html#autotoc_md28',1,'&lt;tt&gt;eigvals(A)&lt;/tt&gt;'],['../index.html#autotoc_md30',1,'&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;'],['../index.html#autotoc_md27',1,'&lt;tt&gt;eye(m)&lt;/tt&gt;'],['../index.html#autotoc_md20',1,'&lt;tt&gt;inv(A)&lt;/tt&gt;'],['../index.html#autotoc_md22',1,'&lt;tt&gt;invert(A)&lt;/tt&gt;'],['../index.html#autotoc_md21',1,'&lt;tt&gt;pinv(A)&lt;/tt&gt;'],['../index.html#autotoc_md25',1,'&lt;tt&gt;svd(A)&lt;/tt&gt;'],['../index.html#autotoc_md26',1,'&lt;tt&gt;svdvals(A)&lt;/tt&gt;']]],
  ['tt_20det_20a_20tt_50',['&lt;tt&gt;det(A)&lt;/tt&gt;',['../index.html#autotoc_md19',1,'']]],
  ['tt_20diag_20n_20source_20tt_51',['&lt;tt&gt;diag(n, source)&lt;/tt&gt;',['../index.html#autotoc_md32',1,'']]],
  ['tt_20diag_20source_20tt_52',['&lt;tt&gt;diag(source)&lt;/tt&gt;',['../index.html#autotoc_md33',1,'']]],
  ['tt_20eig_20a_20lambda_20tt_53',['&lt;tt&gt;eig(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md29',1,'']]],
  ['tt_20eigh_20a_20lambda_20tt_54',['&lt;tt&gt;eigh(A, lambda)&lt;/tt&gt;',['../index.html#autotoc_md31',1,'']]],
  ['tt_20eigvals_20a_20tt_55',['&lt;tt&gt;eigvals(A)&lt;/tt&gt;',['../index.html#autotoc_md28',1,'']]],
  ['tt_20eigvalsh_20a_20tt_56',['&lt;tt&gt;eigvalsh(A)&lt;/tt&gt;',['../index.html#autotoc_md30',1,'']]],
  ['tt_20eye_20m_20tt_57',['&lt;tt&gt;eye(m)&lt;/tt&gt;',['../index.html#autotoc_md27',1,'']]],
  ['tt_20inv_20a_20tt_58',['tt inv A tt',['../index.html#autotoc_md23',1,'&lt;tt&gt;.inv.A&lt;/tt&gt;'],['../index.html#autotoc_md20',1,'&lt;tt&gt;inv(A)&lt;/tt&gt;']]],
  ['tt_20invert_20a_20tt_59',['&lt;tt&gt;invert(A)&lt;/tt&gt;',['../index.html#autotoc_md22',1,'']]],
  ['tt_20pinv_20a_20tt_60',['tt pinv A tt',['../index.html#autotoc_md24',1,'&lt;tt&gt;.pinv.A&lt;/tt&gt;'],['../index.html#autotoc_md21',1,'&lt;tt&gt;pinv(A)&lt;/tt&gt;']]],
  ['tt_20svd_20a_20tt_61',['&lt;tt&gt;svd(A)&lt;/tt&gt;',['../index.html#autotoc_md25',1,'']]],
  ['tt_20svdvals_20a_20tt_62',['&lt;tt&gt;svdvals(A)&lt;/tt&gt;',['../index.html#autotoc_md26',1,'']]],
  ['tzrzf_63',['tzrzf',['../interfacela__lapack_1_1tzrzf.html',1,'la_lapack']]]
];
