var searchData=
[
  ['a_20cholesky_20factor_0',['@ref la_solve::solve_lower_chol &quot;solve_lower_chol&quot;, @ref la_solve::solve_upper_chol &quot;solve_upper_chol&quot; - Solve from a Cholesky factor.',['../index.html#autotoc_md94',1,'']]],
  ['a_20hermitian_20positive_20definite_20system_1',['@ref la_solve::solve_chol &quot;solve_chol&quot; - Solve a Hermitian positive definite system.',['../index.html#autotoc_md88',1,'']]],
  ['a_20least_20squares_20solution_20to_20a_20system_20of_20linear_20equations_2',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md100',1,'']]],
  ['a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_3',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md76',1,'']]],
  ['a_20linear_20system_20into_20a_20pre_20allocated_20array_4',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md82',1,'']]],
  ['a_20linear_20system_20of_20equations_5',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md76',1,'']]],
  ['a_20matrix_6',['a matrix',['../index.html#autotoc_md148',1,'@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.'],['../index.html#autotoc_md183',1,'@ref la_qr::qr &quot;qr&quot; - QR factorization of a matrix.'],['../index.html#autotoc_md197',1,'@ref la_schur::schur &quot;schur&quot; - Schur decomposition of a matrix.'],['../index.html#autotoc_md155',1,'@ref la_svd::svd &quot;svd&quot; - Singular Value Decomposition (SVD) of a matrix']]],
  ['a_20matrix_20function_7',['a matrix function',['../index.html#autotoc_md37',1,'@ref la_cholesky::chol &quot;chol&quot; - Cholesky factorization of a matrix (function).'],['../index.html#autotoc_md141',1,'@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).']]],
  ['a_20matrix_20subroutine_8',['@ref la_cholesky::cholesky &quot;cholesky&quot; - Cholesky factorization of a matrix (subroutine).',['../index.html#autotoc_md44',1,'']]],
  ['a_20pre_20allocated_20array_9',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md82',1,'']]],
  ['a_20real_20symmetric_20or_20complex_20hermitian_20matrix_10',['a real symmetric or complex Hermitian matrix',['../index.html#autotoc_md56',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md69',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['a_20scalar_20or_20rectangular_20matrix_11',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md107',1,'']]],
  ['a_20square_20matrix_12',['a square matrix',['../index.html#autotoc_md114',1,'@ref la_determinant::operator(.det.) &quot;operator(.det.)&quot; - Determinant of a square matrix.'],['../index.html#autotoc_md50',1,'@ref la_eig::eig &quot;eig&quot; - Eigendecomposition of a square matrix.'],['../index.html#autotoc_md121',1,'@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.'],['../index.html#autotoc_md134',1,'@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.']]],
  ['a_20square_20matrix_20interface_13',['@ref la_eig::eigvals &quot;eigvals&quot; - Eigenvalues of a square matrix (interface).',['../index.html#autotoc_md62',1,'']]],
  ['a_20system_20of_20linear_20equations_14',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md100',1,'']]],
  ['acknowledgments_15',['Acknowledgments',['../index.html#autotoc_md216',1,'']]],
  ['allocated_20array_16',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md82',1,'']]],
  ['api_17',['Browse API',['../index.html#autotoc_md36',1,'']]],
  ['arguments_18',['Arguments',['../interfacela__eig_1_1eig.html#autotoc_md6',1,'Arguments'],['../interfacela__eig_1_1eigvals.html#autotoc_md11',1,'Arguments'],['../interfacela__eig_1_1eigh.html#autotoc_md17',1,'Arguments'],['../interfacela__eig_1_1eigvalsh.html#autotoc_md23',1,'Arguments'],['../index.html#autotoc_md40',1,'Arguments'],['../index.html#autotoc_md47',1,'Arguments'],['../index.html#autotoc_md53',1,'Arguments'],['../index.html#autotoc_md59',1,'Arguments'],['../index.html#autotoc_md65',1,'Arguments'],['../index.html#autotoc_md72',1,'Arguments'],['../index.html#autotoc_md79',1,'Arguments'],['../index.html#autotoc_md85',1,'Arguments'],['../index.html#autotoc_md91',1,'Arguments'],['../index.html#autotoc_md97',1,'Arguments'],['../index.html#autotoc_md103',1,'Arguments'],['../index.html#autotoc_md110',1,'Arguments'],['../index.html#autotoc_md117',1,'Arguments'],['../index.html#autotoc_md124',1,'Arguments'],['../index.html#autotoc_md131',1,'Arguments'],['../index.html#autotoc_md137',1,'Arguments'],['../index.html#autotoc_md144',1,'Arguments'],['../index.html#autotoc_md151',1,'Arguments'],['../index.html#autotoc_md158',1,'Arguments'],['../index.html#autotoc_md165',1,'Arguments'],['../index.html#autotoc_md172',1,'Arguments'],['../index.html#autotoc_md179',1,'Arguments'],['../index.html#autotoc_md186',1,'Arguments'],['../index.html#autotoc_md193',1,'Arguments'],['../index.html#autotoc_md200',1,'Arguments'],['../index.html#autotoc_md207',1,'Arguments']]],
  ['array_19',['@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.',['../index.html#autotoc_md82',1,'']]],
  ['axpy_20',['axpy',['../interfacela__blas_1_1axpy.html',1,'la_blas']]]
];
