var searchData=
[
  ['a_20least_20squares_20solution_20to_20a_20system_20of_20linear_20equations_0',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md74',1,'']]],
  ['a_20linear_20matrix_20equation_20or_20a_20linear_20system_20of_20equations_1',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md68',1,'']]],
  ['a_20linear_20system_20of_20equations_2',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md68',1,'']]],
  ['a_20matrix_3',['a matrix',['../index.html#autotoc_md115',1,'@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.'],['../index.html#autotoc_md150',1,'@ref la_qr::qr &quot;qr&quot; - QR factorization of a matrix.'],['../index.html#autotoc_md164',1,'@ref la_schur::schur &quot;schur&quot; - Schur decomposition of a matrix.'],['../index.html#autotoc_md122',1,'@ref la_svd::svd &quot;svd&quot; - Singular Value Decomposition (SVD) of a matrix']]],
  ['a_20matrix_20function_4',['a matrix function',['../index.html#autotoc_md29',1,'@ref la_cholesky::chol &quot;chol&quot; - Cholesky factorization of a matrix (function).'],['../index.html#autotoc_md108',1,'@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).']]],
  ['a_20matrix_20subroutine_5',['@ref la_cholesky::cholesky &quot;cholesky&quot; - Cholesky factorization of a matrix (subroutine).',['../index.html#autotoc_md36',1,'']]],
  ['a_20real_20symmetric_20or_20complex_20hermitian_20matrix_6',['a real symmetric or complex Hermitian matrix',['../index.html#autotoc_md48',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md61',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['a_20scalar_20or_20rectangular_20matrix_7',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md81',1,'']]],
  ['a_20square_20matrix_8',['a square matrix',['../index.html#autotoc_md42',1,'@ref la_eig::eig &quot;eig&quot; - Eigendecomposition of a square matrix.'],['../index.html#autotoc_md88',1,'@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.'],['../index.html#autotoc_md101',1,'@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.']]],
  ['a_20square_20matrix_20interface_9',['@ref la_eig::eigvals &quot;eigvals&quot; - Eigenvalues of a square matrix (interface).',['../index.html#autotoc_md54',1,'']]],
  ['a_20system_20of_20linear_20equations_10',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md74',1,'']]],
  ['acknowledgments_11',['Acknowledgments',['../index.html#autotoc_md182',1,'']]],
  ['api_12',['Browse API',['../index.html#autotoc_md28',1,'']]],
  ['arguments_13',['Arguments',['../interfacela__eig_1_1eig.html#autotoc_md6',1,'Arguments'],['../interfacela__eig_1_1eigvals.html#autotoc_md11',1,'Arguments'],['../interfacela__eig_1_1eigh.html#autotoc_md17',1,'Arguments'],['../interfacela__eig_1_1eigvalsh.html#autotoc_md23',1,'Arguments'],['../index.html#autotoc_md32',1,'Arguments'],['../index.html#autotoc_md39',1,'Arguments'],['../index.html#autotoc_md45',1,'Arguments'],['../index.html#autotoc_md51',1,'Arguments'],['../index.html#autotoc_md57',1,'Arguments'],['../index.html#autotoc_md64',1,'Arguments'],['../index.html#autotoc_md71',1,'Arguments'],['../index.html#autotoc_md77',1,'Arguments'],['../index.html#autotoc_md84',1,'Arguments'],['../index.html#autotoc_md91',1,'Arguments'],['../index.html#autotoc_md98',1,'Arguments'],['../index.html#autotoc_md104',1,'Arguments'],['../index.html#autotoc_md111',1,'Arguments'],['../index.html#autotoc_md118',1,'Arguments'],['../index.html#autotoc_md125',1,'Arguments'],['../index.html#autotoc_md132',1,'Arguments'],['../index.html#autotoc_md139',1,'Arguments'],['../index.html#autotoc_md146',1,'Arguments'],['../index.html#autotoc_md153',1,'Arguments'],['../index.html#autotoc_md160',1,'Arguments'],['../index.html#autotoc_md167',1,'Arguments'],['../index.html#autotoc_md174',1,'Arguments']]],
  ['axpy_14',['axpy',['../interfacela__blas_1_1axpy.html',1,'la_blas']]]
];
