var searchData=
[
  ['of_20a_20matrix_0',['of a matrix',['../index.html#autotoc_md115',1,'@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.'],['../index.html#autotoc_md150',1,'@ref la_qr::qr &quot;qr&quot; - QR factorization of a matrix.'],['../index.html#autotoc_md164',1,'@ref la_schur::schur &quot;schur&quot; - Schur decomposition of a matrix.'],['../index.html#autotoc_md122',1,'@ref la_svd::svd &quot;svd&quot; - Singular Value Decomposition (SVD) of a matrix']]],
  ['of_20a_20matrix_20function_1',['of a matrix function',['../index.html#autotoc_md29',1,'@ref la_cholesky::chol &quot;chol&quot; - Cholesky factorization of a matrix (function).'],['../index.html#autotoc_md108',1,'@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).']]],
  ['of_20a_20matrix_20subroutine_2',['@ref la_cholesky::cholesky &quot;cholesky&quot; - Cholesky factorization of a matrix (subroutine).',['../index.html#autotoc_md36',1,'']]],
  ['of_20a_20real_20symmetric_20or_20complex_20hermitian_20matrix_3',['of a real symmetric or complex Hermitian matrix',['../index.html#autotoc_md48',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md61',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['of_20a_20scalar_20or_20rectangular_20matrix_4',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md81',1,'']]],
  ['of_20a_20square_20matrix_5',['of a square matrix',['../index.html#autotoc_md42',1,'@ref la_eig::eig &quot;eig&quot; - Eigendecomposition of a square matrix.'],['../index.html#autotoc_md88',1,'@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.'],['../index.html#autotoc_md101',1,'@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.']]],
  ['of_20a_20square_20matrix_20interface_6',['@ref la_eig::eigvals &quot;eigvals&quot; - Eigenvalues of a square matrix (interface).',['../index.html#autotoc_md54',1,'']]],
  ['of_20equations_7',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md68',1,'']]],
  ['of_20linear_20equations_8',['@ref la_least_squares::lstsq &quot;lstsq&quot; - Compute a least squares solution to a system of linear equations.',['../index.html#autotoc_md74',1,'']]],
  ['ok_9',['ok',['../structla__state__type_1_1la__state.html#a7cbd8a858eb21bff269f3f582b1d881e',1,'la_state_type::la_state']]],
  ['one_10',['one',['../namespacela__constants__sp.html#a8c077b3bc495be8a7a4a8e528a031a0f',1,'la_constants_sp::one'],['../namespacela__constants__dp.html#a0ecad4b71ead9a089301b5d5c4ba0599',1,'la_constants_dp::one'],['../namespacela__constants__qp.html#ae5e3d28a837a488582575317ab58713a',1,'la_constants_qp::one']]],
  ['operations_11',['@ref la_qr::qr_space &quot;qr_space&quot; - Workspace size for QR operations.',['../index.html#autotoc_md157',1,'']]],
  ['operator_20inv_20compute_20the_20inverse_20of_20a_20square_20matrix_12',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md101',1,'']]],
  ['operator_20pinv_20compute_20the_20moore_20penrose_20pseudo_20inverse_20of_20a_20matrix_13',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md115',1,'']]],
  ['operator_28_2einv_2e_29_14',['operator(.inv.)',['../interfacela__inverse_1_1operator_07_8inv_8_08.html',1,'la_inverse']]],
  ['operator_28_2epinv_2e_29_15',['operator(.pinv.)',['../interfacela__pseudoinverse_1_1operator_07_8pinv_8_08.html',1,'la_pseudoinverse']]],
  ['operator_28_2f_3d_29_16',['operator(/=)',['../interfacela__state__type_1_1operator_07_2_0a_08.html',1,'la_state_type']]],
  ['operator_28_3c_29_17',['operator(&lt;)',['../interfacela__state__type_1_1operator_07_3_08.html',1,'la_state_type']]],
  ['operator_28_3c_3d_29_18',['operator(&lt;=)',['../interfacela__state__type_1_1operator_07_3_0a_08.html',1,'la_state_type']]],
  ['operator_28_3d_3d_29_19',['operator(==)',['../interfacela__state__type_1_1operator_07_0a_0a_08.html',1,'la_state_type']]],
  ['operator_28_3e_29_20',['operator(&gt;)',['../interfacela__state__type_1_1operator_07_4_08.html',1,'la_state_type']]],
  ['operator_28_3e_3d_29_21',['operator(&gt;=)',['../interfacela__state__type_1_1operator_07_4_0a_08.html',1,'la_state_type']]],
  ['opgtr_22',['opgtr',['../interfacela__lapack_1_1opgtr.html',1,'la_lapack']]],
  ['opmtr_23',['opmtr',['../interfacela__lapack_1_1opmtr.html',1,'la_lapack']]],
  ['or_20a_20linear_20system_20of_20equations_24',['@ref la_solve::solve &quot;solve&quot; - Solve a linear matrix equation or a linear system of equations.',['../index.html#autotoc_md68',1,'']]],
  ['or_20complex_20hermitian_20matrix_25',['or complex Hermitian matrix',['../index.html#autotoc_md48',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md61',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['or_20rectangular_20matrix_26',['@ref la_determinant::det &quot;det&quot; - Determinant of a scalar or rectangular matrix.',['../index.html#autotoc_md81',1,'']]],
  ['orbdb_27',['orbdb',['../interfacela__lapack_1_1orbdb.html',1,'la_lapack']]],
  ['orbdb1_28',['orbdb1',['../interfacela__lapack_1_1orbdb1.html',1,'la_lapack']]],
  ['orbdb2_29',['orbdb2',['../interfacela__lapack_1_1orbdb2.html',1,'la_lapack']]],
  ['orbdb3_30',['orbdb3',['../interfacela__lapack_1_1orbdb3.html',1,'la_lapack']]],
  ['orbdb4_31',['orbdb4',['../interfacela__lapack_1_1orbdb4.html',1,'la_lapack']]],
  ['orbdb5_32',['orbdb5',['../interfacela__lapack_1_1orbdb5.html',1,'la_lapack']]],
  ['orbdb6_33',['orbdb6',['../interfacela__lapack_1_1orbdb6.html',1,'la_lapack']]],
  ['orcsd_34',['orcsd',['../interfacela__lapack_1_1orcsd.html',1,'la_lapack']]],
  ['orcsd2by1_35',['orcsd2by1',['../interfacela__lapack_1_1orcsd2by1.html',1,'la_lapack']]],
  ['org2l_36',['org2l',['../interfacela__lapack_1_1org2l.html',1,'la_lapack']]],
  ['org2r_37',['org2r',['../interfacela__lapack_1_1org2r.html',1,'la_lapack']]],
  ['orgbr_38',['orgbr',['../interfacela__lapack_1_1orgbr.html',1,'la_lapack']]],
  ['orghr_39',['orghr',['../interfacela__lapack_1_1orghr.html',1,'la_lapack']]],
  ['orglq_40',['orglq',['../interfacela__lapack_1_1orglq.html',1,'la_lapack']]],
  ['orgql_41',['orgql',['../interfacela__lapack_1_1orgql.html',1,'la_lapack']]],
  ['orgqr_42',['orgqr',['../interfacela__lapack_1_1orgqr.html',1,'la_lapack']]],
  ['orgrq_43',['orgrq',['../interfacela__lapack_1_1orgrq.html',1,'la_lapack']]],
  ['orgtr_44',['orgtr',['../interfacela__lapack_1_1orgtr.html',1,'la_lapack']]],
  ['orgtsqr_45',['orgtsqr',['../interfacela__lapack_1_1orgtsqr.html',1,'la_lapack']]],
  ['orgtsqr_5frow_46',['orgtsqr_row',['../interfacela__lapack_1_1orgtsqr__row.html',1,'la_lapack']]],
  ['orhr_5fcol_47',['orhr_col',['../interfacela__lapack_1_1orhr__col.html',1,'la_lapack']]],
  ['orm2l_48',['orm2l',['../interfacela__lapack_1_1orm2l.html',1,'la_lapack']]],
  ['orm2r_49',['orm2r',['../interfacela__lapack_1_1orm2r.html',1,'la_lapack']]],
  ['ormbr_50',['ormbr',['../interfacela__lapack_1_1ormbr.html',1,'la_lapack']]],
  ['ormhr_51',['ormhr',['../interfacela__lapack_1_1ormhr.html',1,'la_lapack']]],
  ['ormlq_52',['ormlq',['../interfacela__lapack_1_1ormlq.html',1,'la_lapack']]],
  ['ormql_53',['ormql',['../interfacela__lapack_1_1ormql.html',1,'la_lapack']]],
  ['ormqr_54',['ormqr',['../interfacela__lapack_1_1ormqr.html',1,'la_lapack']]],
  ['ormrq_55',['ormrq',['../interfacela__lapack_1_1ormrq.html',1,'la_lapack']]],
  ['ormrz_56',['ormrz',['../interfacela__lapack_1_1ormrz.html',1,'la_lapack']]],
  ['ormtr_57',['ormtr',['../interfacela__lapack_1_1ormtr.html',1,'la_lapack']]]
];
