var searchData=
[
  ['half_0',['half',['../namespacela__constants__sp.html#a893211991e990b9bc0bf01ac68909f5a',1,'la_constants_sp::half'],['../namespacela__constants__dp.html#aa4bc43ddb7e56fb022af8598ccebf8ef',1,'la_constants_dp::half'],['../namespacela__constants__qp.html#af006e2f9eeb6cebc06252bbda37b8e2f',1,'la_constants_qp::half']]],
  ['handle_1',['handle',['../structla__state__type_1_1la__state.html#a17369068e74ad52bdd3be236ef1c6530',1,'la_state_type::la_state']]],
  ['hb2st_5fkernels_2',['hb2st_kernels',['../interfacela__lapack_1_1hb2st__kernels.html',1,'la_lapack']]],
  ['hbev_3',['hbev',['../interfacela__lapack_1_1hbev.html',1,'la_lapack']]],
  ['hbevd_4',['hbevd',['../interfacela__lapack_1_1hbevd.html',1,'la_lapack']]],
  ['hbgst_5',['hbgst',['../interfacela__lapack_1_1hbgst.html',1,'la_lapack']]],
  ['hbgv_6',['hbgv',['../interfacela__lapack_1_1hbgv.html',1,'la_lapack']]],
  ['hbgvd_7',['hbgvd',['../interfacela__lapack_1_1hbgvd.html',1,'la_lapack']]],
  ['hbmv_8',['hbmv',['../interfacela__blas_1_1hbmv.html',1,'la_blas']]],
  ['hbtrd_9',['hbtrd',['../interfacela__lapack_1_1hbtrd.html',1,'la_lapack']]],
  ['hecon_10',['hecon',['../interfacela__lapack_1_1hecon.html',1,'la_lapack']]],
  ['hecon_5frook_11',['hecon_rook',['../interfacela__lapack_1_1hecon__rook.html',1,'la_lapack']]],
  ['heequb_12',['heequb',['../interfacela__lapack_1_1heequb.html',1,'la_lapack']]],
  ['heev_13',['heev',['../interfacela__lapack_1_1heev.html',1,'la_lapack']]],
  ['heevd_14',['heevd',['../interfacela__lapack_1_1heevd.html',1,'la_lapack']]],
  ['heevr_15',['heevr',['../interfacela__lapack_1_1heevr.html',1,'la_lapack']]],
  ['hegst_16',['hegst',['../interfacela__lapack_1_1hegst.html',1,'la_lapack']]],
  ['hegv_17',['hegv',['../interfacela__lapack_1_1hegv.html',1,'la_lapack']]],
  ['hegvd_18',['hegvd',['../interfacela__lapack_1_1hegvd.html',1,'la_lapack']]],
  ['hemm_19',['hemm',['../interfacela__blas_1_1hemm.html',1,'la_blas']]],
  ['hemv_20',['hemv',['../interfacela__blas_1_1hemv.html',1,'la_blas']]],
  ['her_21',['her',['../interfacela__blas_1_1her.html',1,'la_blas']]],
  ['her2_22',['her2',['../interfacela__blas_1_1her2.html',1,'la_blas']]],
  ['her2k_23',['her2k',['../interfacela__blas_1_1her2k.html',1,'la_blas']]],
  ['herfs_24',['herfs',['../interfacela__lapack_1_1herfs.html',1,'la_lapack']]],
  ['herk_25',['herk',['../interfacela__blas_1_1herk.html',1,'la_blas']]],
  ['hermitian_26',['@ref la_matrix_property_checks::is_hermitian &quot;is_hermitian&quot; - Check whether a matrix is Hermitian.',['../index.html#autotoc_md246',1,'']]],
  ['hermitian_27',['hermitian',['../interfacela__eye_1_1hermitian.html',1,'la_eye']]],
  ['hermitian_20hermitian_20transpose_20of_20a_20matrix_28',['@ref la_eye::hermitian &quot;hermitian&quot; - Hermitian transpose of a matrix.',['../index.html#autotoc_md211',1,'']]],
  ['hermitian_20matrix_29',['Hermitian matrix',['../index.html#autotoc_md56',1,'@ref la_eig::eigh &quot;eigh&quot; - Eigendecomposition of a real symmetric or complex Hermitian matrix.'],['../index.html#autotoc_md69',1,'@ref la_eig::eigvalsh &quot;eigvalsh&quot; - Eigenvalues of a real symmetric or complex Hermitian matrix.']]],
  ['hermitian_20positive_20definite_20system_30',['@ref la_solve::solve_chol &quot;solve_chol&quot; - Solve a Hermitian positive definite system.',['../index.html#autotoc_md88',1,'']]],
  ['hermitian_20transpose_20of_20a_20matrix_31',['@ref la_eye::hermitian &quot;hermitian&quot; - Hermitian transpose of a matrix.',['../index.html#autotoc_md211',1,'']]],
  ['hessenberg_32',['@ref la_matrix_property_checks::is_hessenberg &quot;is_hessenberg&quot; - Check whether a matrix is Hessenberg.',['../index.html#autotoc_md260',1,'']]],
  ['hesv_33',['hesv',['../interfacela__lapack_1_1hesv.html',1,'la_lapack']]],
  ['hesv_5faa_34',['hesv_aa',['../interfacela__lapack_1_1hesv__aa.html',1,'la_lapack']]],
  ['hesv_5frk_35',['hesv_rk',['../interfacela__lapack_1_1hesv__rk.html',1,'la_lapack']]],
  ['hesv_5frook_36',['hesv_rook',['../interfacela__lapack_1_1hesv__rook.html',1,'la_lapack']]],
  ['heswapr_37',['heswapr',['../interfacela__lapack_1_1heswapr.html',1,'la_lapack']]],
  ['hetf2_5frk_38',['hetf2_rk',['../interfacela__lapack_1_1hetf2__rk.html',1,'la_lapack']]],
  ['hetf2_5frook_39',['hetf2_rook',['../interfacela__lapack_1_1hetf2__rook.html',1,'la_lapack']]],
  ['hetrd_40',['hetrd',['../interfacela__lapack_1_1hetrd.html',1,'la_lapack']]],
  ['hetrd_5fhb2st_41',['hetrd_hb2st',['../interfacela__lapack_1_1hetrd__hb2st.html',1,'la_lapack']]],
  ['hetrd_5fhe2hb_42',['hetrd_he2hb',['../interfacela__lapack_1_1hetrd__he2hb.html',1,'la_lapack']]],
  ['hetrf_43',['hetrf',['../interfacela__lapack_1_1hetrf.html',1,'la_lapack']]],
  ['hetrf_5faa_44',['hetrf_aa',['../interfacela__lapack_1_1hetrf__aa.html',1,'la_lapack']]],
  ['hetrf_5frk_45',['hetrf_rk',['../interfacela__lapack_1_1hetrf__rk.html',1,'la_lapack']]],
  ['hetrf_5frook_46',['hetrf_rook',['../interfacela__lapack_1_1hetrf__rook.html',1,'la_lapack']]],
  ['hetri_47',['hetri',['../interfacela__lapack_1_1hetri.html',1,'la_lapack']]],
  ['hetri_5frook_48',['hetri_rook',['../interfacela__lapack_1_1hetri__rook.html',1,'la_lapack']]],
  ['hetrs_49',['hetrs',['../interfacela__lapack_1_1hetrs.html',1,'la_lapack']]],
  ['hetrs2_50',['hetrs2',['../interfacela__lapack_1_1hetrs2.html',1,'la_lapack']]],
  ['hetrs_5f3_51',['hetrs_3',['../interfacela__lapack_1_1hetrs__3.html',1,'la_lapack']]],
  ['hetrs_5faa_52',['hetrs_aa',['../interfacela__lapack_1_1hetrs__aa.html',1,'la_lapack']]],
  ['hetrs_5frook_53',['hetrs_rook',['../interfacela__lapack_1_1hetrs__rook.html',1,'la_lapack']]],
  ['hfrk_54',['hfrk',['../interfacela__lapack_1_1hfrk.html',1,'la_lapack']]],
  ['hgeqz_55',['hgeqz',['../interfacela__lapack_1_1hgeqz.html',1,'la_lapack']]],
  ['hpcon_56',['hpcon',['../interfacela__lapack_1_1hpcon.html',1,'la_lapack']]],
  ['hpev_57',['hpev',['../interfacela__lapack_1_1hpev.html',1,'la_lapack']]],
  ['hpevd_58',['hpevd',['../interfacela__lapack_1_1hpevd.html',1,'la_lapack']]],
  ['hpgst_59',['hpgst',['../interfacela__lapack_1_1hpgst.html',1,'la_lapack']]],
  ['hpgv_60',['hpgv',['../interfacela__lapack_1_1hpgv.html',1,'la_lapack']]],
  ['hpgvd_61',['hpgvd',['../interfacela__lapack_1_1hpgvd.html',1,'la_lapack']]],
  ['hpmv_62',['hpmv',['../interfacela__blas_1_1hpmv.html',1,'la_blas']]],
  ['hpr_63',['hpr',['../interfacela__blas_1_1hpr.html',1,'la_blas']]],
  ['hpr2_64',['hpr2',['../interfacela__blas_1_1hpr2.html',1,'la_blas']]],
  ['hprfs_65',['hprfs',['../interfacela__lapack_1_1hprfs.html',1,'la_lapack']]],
  ['hpsv_66',['hpsv',['../interfacela__lapack_1_1hpsv.html',1,'la_lapack']]],
  ['hptrd_67',['hptrd',['../interfacela__lapack_1_1hptrd.html',1,'la_lapack']]],
  ['hptrf_68',['hptrf',['../interfacela__lapack_1_1hptrf.html',1,'la_lapack']]],
  ['hptri_69',['hptri',['../interfacela__lapack_1_1hptri.html',1,'la_lapack']]],
  ['hptrs_70',['hptrs',['../interfacela__lapack_1_1hptrs.html',1,'la_lapack']]],
  ['hsein_71',['hsein',['../interfacela__lapack_1_1hsein.html',1,'la_lapack']]],
  ['hseqr_72',['hseqr',['../interfacela__lapack_1_1hseqr.html',1,'la_lapack']]]
];
