var searchData=
[
  ['identity_20matrix_0',['@ref la_eye::eye &quot;eye&quot; - Identity matrix.',['../index.html#autotoc_md224',1,'']]],
  ['ilp_1',['ilp',['../namespacela__constants.html#a855ee4571ad1f4065aca0717ce55fd0f',1,'la_constants']]],
  ['interface_2',['@ref la_eig::eigvals &quot;eigvals&quot; - Eigenvalues of a square matrix (interface).',['../index.html#autotoc_md62',1,'']]],
  ['into_20a_20pre_20allocated_20array_3',['into a pre allocated array',['../index.html#autotoc_md142',1,'@ref la_least_squares::solve_constrained_lstsq &quot;solve_constrained_lstsq&quot; - Equality-constrained least squares solution into a pre-allocated array.'],['../index.html#autotoc_md114',1,'@ref la_least_squares::solve_lstsq &quot;solve_lstsq&quot; - Least squares solution into a pre-allocated array.'],['../index.html#autotoc_md128',1,'@ref la_least_squares::solve_weighted_lstsq &quot;solve_weighted_lstsq&quot; - Weighted least squares solution into a pre-allocated array.'],['../index.html#autotoc_md82',1,'@ref la_solve::solve_lu &quot;solve_lu&quot; - Solve a linear system into a pre-allocated array.']]],
  ['inv_4',['inv',['../interfacela__inverse_1_1inv.html',1,'la_inverse']]],
  ['inv_20compute_20the_20inverse_20of_20a_20square_20matrix_5',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md182',1,'']]],
  ['inv_20inverse_20of_20a_20square_20matrix_6',['@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.',['../index.html#autotoc_md169',1,'']]],
  ['inv_20operator_20inv_20compute_20the_20inverse_20of_20a_20square_20matrix_7',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md182',1,'']]],
  ['inverse_20of_20a_20matrix_8',['@ref la_pseudoinverse::operator(.pinv.) &quot;operator(.pinv.)&quot; - Compute the Moore-Penrose pseudo-inverse of a matrix.',['../index.html#autotoc_md196',1,'']]],
  ['inverse_20of_20a_20matrix_20function_9',['@ref la_pseudoinverse::pinv &quot;pinv&quot; - Moore-Penrose pseudo-inverse of a matrix (function).',['../index.html#autotoc_md189',1,'']]],
  ['inverse_20of_20a_20square_20matrix_10',['@ref la_inverse::inv &quot;inv&quot; - Inverse of a square matrix.',['../index.html#autotoc_md169',1,'']]],
  ['inverse_20of_20a_20square_20matrix_11',['@ref la_inverse::operator(.inv.) &quot;operator(.inv.)&quot; - Compute the inverse of a square matrix.',['../index.html#autotoc_md182',1,'']]],
  ['inversion_20subroutine_12',['@ref la_inverse::invert &quot;invert&quot; - Matrix inversion (subroutine).',['../index.html#autotoc_md176',1,'']]],
  ['invert_13',['invert',['../interfacela__inverse_1_1invert.html',1,'la_inverse']]],
  ['invert_20matrix_20inversion_20subroutine_14',['@ref la_inverse::invert &quot;invert&quot; - Matrix inversion (subroutine).',['../index.html#autotoc_md176',1,'']]],
  ['is_20diagonal_15',['@ref la_matrix_property_checks::is_diagonal &quot;is_diagonal&quot; - Check whether a matrix is diagonal.',['../index.html#autotoc_md273',1,'']]],
  ['is_20hermitian_16',['@ref la_matrix_property_checks::is_hermitian &quot;is_hermitian&quot; - Check whether a matrix is Hermitian.',['../index.html#autotoc_md294',1,'']]],
  ['is_20hessenberg_17',['@ref la_matrix_property_checks::is_hessenberg &quot;is_hessenberg&quot; - Check whether a matrix is Hessenberg.',['../index.html#autotoc_md308',1,'']]],
  ['is_20skew_20symmetric_18',['@ref la_matrix_property_checks::is_skew_symmetric &quot;is_skew_symmetric&quot; - Check whether a matrix is skew-symmetric.',['../index.html#autotoc_md287',1,'']]],
  ['is_20square_19',['@ref la_matrix_property_checks::is_square &quot;is_square&quot; - Check whether a matrix is square.',['../index.html#autotoc_md266',1,'']]],
  ['is_20symmetric_20',['@ref la_matrix_property_checks::is_symmetric &quot;is_symmetric&quot; - Check whether a matrix is symmetric.',['../index.html#autotoc_md280',1,'']]],
  ['is_20triangular_21',['@ref la_matrix_property_checks::is_triangular &quot;is_triangular&quot; - Check whether a matrix is triangular.',['../index.html#autotoc_md301',1,'']]],
  ['is_5fdiagonal_22',['is_diagonal',['../interfacela__matrix__property__checks_1_1is__diagonal.html',1,'la_matrix_property_checks']]],
  ['is_5fdiagonal_20check_20whether_20a_20matrix_20is_20diagonal_23',['@ref la_matrix_property_checks::is_diagonal &quot;is_diagonal&quot; - Check whether a matrix is diagonal.',['../index.html#autotoc_md273',1,'']]],
  ['is_5fhermitian_24',['is_hermitian',['../interfacela__matrix__property__checks_1_1is__hermitian.html',1,'la_matrix_property_checks']]],
  ['is_5fhermitian_20check_20whether_20a_20matrix_20is_20hermitian_25',['@ref la_matrix_property_checks::is_hermitian &quot;is_hermitian&quot; - Check whether a matrix is Hermitian.',['../index.html#autotoc_md294',1,'']]],
  ['is_5fhessenberg_26',['is_hessenberg',['../interfacela__matrix__property__checks_1_1is__hessenberg.html',1,'la_matrix_property_checks']]],
  ['is_5fhessenberg_20check_20whether_20a_20matrix_20is_20hessenberg_27',['@ref la_matrix_property_checks::is_hessenberg &quot;is_hessenberg&quot; - Check whether a matrix is Hessenberg.',['../index.html#autotoc_md308',1,'']]],
  ['is_5fskew_5fsymmetric_28',['is_skew_symmetric',['../interfacela__matrix__property__checks_1_1is__skew__symmetric.html',1,'la_matrix_property_checks']]],
  ['is_5fskew_5fsymmetric_20check_20whether_20a_20matrix_20is_20skew_20symmetric_29',['@ref la_matrix_property_checks::is_skew_symmetric &quot;is_skew_symmetric&quot; - Check whether a matrix is skew-symmetric.',['../index.html#autotoc_md287',1,'']]],
  ['is_5fsquare_30',['is_square',['../interfacela__matrix__property__checks_1_1is__square.html',1,'la_matrix_property_checks']]],
  ['is_5fsquare_20check_20whether_20a_20matrix_20is_20square_31',['@ref la_matrix_property_checks::is_square &quot;is_square&quot; - Check whether a matrix is square.',['../index.html#autotoc_md266',1,'']]],
  ['is_5fsymmetric_32',['is_symmetric',['../interfacela__matrix__property__checks_1_1is__symmetric.html',1,'la_matrix_property_checks']]],
  ['is_5fsymmetric_20check_20whether_20a_20matrix_20is_20symmetric_33',['@ref la_matrix_property_checks::is_symmetric &quot;is_symmetric&quot; - Check whether a matrix is symmetric.',['../index.html#autotoc_md280',1,'']]],
  ['is_5ftriangular_34',['is_triangular',['../interfacela__matrix__property__checks_1_1is__triangular.html',1,'la_matrix_property_checks']]],
  ['is_5ftriangular_20check_20whether_20a_20matrix_20is_20triangular_35',['@ref la_matrix_property_checks::is_triangular &quot;is_triangular&quot; - Check whether a matrix is triangular.',['../index.html#autotoc_md301',1,'']]],
  ['isnan_36',['isnan',['../interfacela__lapack_1_1isnan.html',1,'la_lapack']]]
];
