#:include "common.fypp"
#:include "la_blas_interfaces.fypp"
!> Precision-agnostic BLAS interface
module la_blas
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level2_ban
     use la_blas_level2_gen
     use la_blas_level2_pac
     use la_blas_level2_sym
     use la_blas_level2_tri
     use la_blas_level3_gen
     use la_blas_level3_sym
     use la_blas_level3_tri
     implicit none(type,external)
     public

#:for generic, doc, entries, stubs in LA_BLAS_INTERFACES
#:for line in doc
          !> ${line}$
#:endfor
          interface ${generic}$
#:for specific, internal, stub in entries
#:if LA_GUARD[specific[0]]
#ifdef ${LA_GUARD[specific[0]]}$
#:endif
#:if stub
#ifdef LA_EXTERNAL_BLAS
$:stubs[stub].format(**LA_BY_INITIAL[specific[0]])
#else
               module procedure la_${internal}$
#endif
#:else
               module procedure la_${internal}$
#:endif
#:if LA_GUARD[specific[0]]
#endif
#:endif
#:endfor
          end interface ${generic}$

#:endfor
end module la_blas
