#:include "common.fypp"
!> BLAS helpers: character comparison, error reporting, index of maximum
module la_blas_aux
     use la_constants
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     public :: la_${ri}$cabs1
     public :: la_i${ri}$amax
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     public :: la_i${ri}$amax
#:endfor
     public :: la_lsame
     public :: la_xerbla
     public :: la_xerbla_array

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if rk == "sp"
     !> ${ri.upper()}$CABS1: computes |Re(.)| + |Im(.)| of a complex number
#:else
     !> ${ri.upper()}$CABS1: computes |Re(.)| + |Im(.)| of a double complex number
#:endif

     pure real(${rk}$) function la_${ri}$cabs1(z)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           complex(${rk}$),intent(in) :: z
        ! =====================================================================
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,real
#:else
           intrinsic :: abs,real,aimag
#:endif
           la_${ri}$cabs1 = abs(real(z,KIND=${rk}$)) + abs(aimag(z))
           return
     end function la_${ri}$cabs1
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> I${ri.upper()}$AMAX: finds the index of the first element having maximum absolute value.

     pure integer(ilp) function la_i${ri}$amax(n,${ri}$x,incx)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incx,n
           ! Array Arguments
           real(${rk}$),intent(in) :: ${ri}$x(*)
        ! =====================================================================
           ! Local Scalars
           real(${rk}$) :: ${ri}$max
           integer(ilp) :: i,ix
           ! Intrinsic Functions
           intrinsic :: abs
           la_i${ri}$amax = 0
           if (n < 1 .or. incx <= 0) return
           la_i${ri}$amax = 1
           if (n == 1) return
           if (incx == 1) then
              ! code for increment equal to 1
              ${ri}$max = abs(${ri}$x(1))
              do i = 2,n
                 if (abs(${ri}$x(i)) > ${ri}$max) then
                    la_i${ri}$amax = i
                    ${ri}$max = abs(${ri}$x(i))
                 end if
              end do
           else
              ! code for increment not equal to 1
              ix = 1
              ${ri}$max = abs(${ri}$x(1))
              ix = ix + incx
              do i = 2,n
                 if (abs(${ri}$x(ix)) > ${ri}$max) then
                    la_i${ri}$amax = i
                    ${ri}$max = abs(${ri}$x(ix))
                 end if
                 ix = ix + incx
              end do
           end if
           return
     end function la_i${ri}$amax
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> I${ri.upper()}$AMAX: finds the index of the first element having maximum |Re(.)| + |Im(.)|

     pure integer(ilp) function la_i${ri}$amax(n,${ri}$x,incx)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incx,n
           ! Array Arguments
           complex(${rk}$),intent(in) :: ${ri}$x(*)
        ! =====================================================================
           ! Local Scalars
           real(${rk}$) :: ${ci}$max
           integer(ilp) :: i,ix
           la_i${ri}$amax = 0
           if (n < 1 .or. incx <= 0) return
           la_i${ri}$amax = 1
           if (n == 1) return
           if (incx == 1) then
              ! code for increment equal to 1
              ${ci}$max = la_${ci}$cabs1(${ri}$x(1))
              do i = 2,n
                 if (la_${ci}$cabs1(${ri}$x(i)) > ${ci}$max) then
                    la_i${ri}$amax = i
                    ${ci}$max = la_${ci}$cabs1(${ri}$x(i))
                 end if
              end do
           else
              ! code for increment not equal to 1
              ix = 1
              ${ci}$max = la_${ci}$cabs1(${ri}$x(1))
              ix = ix + incx
              do i = 2,n
                 if (la_${ci}$cabs1(${ri}$x(ix)) > ${ci}$max) then
                    la_i${ri}$amax = i
                    ${ci}$max = la_${ci}$cabs1(${ri}$x(ix))
                 end if
                 ix = ix + incx
              end do
           end if
           return
     end function la_i${ri}$amax
#:endfor

     !> LSAME: returns .TRUE. if CA is the same letter as CB regardless of
     !> case.

     pure logical(lk) function la_lsame(ca,cb)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: ca,cb
       ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: ichar
           ! Local Scalars
           integer(ilp) :: inta,intb,zcode
           ! test if the characters are equal
           la_lsame = ca == cb
           if (la_lsame) return
           ! now test for equivalence if both characters are alphabetic.
           zcode = ichar('Z')
           ! use 'z' rather than 'a' so that ascii can be detected on prime
           ! machines, on which ichar returns a value with bit 8 set.
           ! ichar('a') on prime machines returns 193 which is the same as
           ! ichar('a') on an ebcdic machine.
           inta = ichar(ca)
           intb = ichar(cb)
           if (zcode == 90 .or. zcode == 122) then
              ! ascii is assumed - zcode is the ascii code of either lower or
              ! upper case 'z'.
               if (inta >= 97 .and. inta <= 122) inta = inta - 32
               if (intb >= 97 .and. intb <= 122) intb = intb - 32
           else if (zcode == 233 .or. zcode == 169) then
              ! ebcdic is assumed - zcode is the ebcdic code of either lower or
              ! upper case 'z'.
               if (inta >= 129 .and. inta <= 137 .or. inta >= 145 .and. inta <= 153 .or. inta >= 162 .and. &
                         inta <= 169) inta = inta + 64
               if (intb >= 129 .and. intb <= 137 .or. intb >= 145 .and. intb <= 153 .or. intb >= 162 .and. &
                         intb <= 169) intb = intb + 64
           else if (zcode == 218 .or. zcode == 250) then
              ! ascii is assumed, on prime machines - zcode is the ascii code
              ! plus 128 of either lower or upper case 'z'.
               if (inta >= 225 .and. inta <= 250) inta = inta - 32
               if (intb >= 225 .and. intb <= 250) intb = intb - 32
           end if
           la_lsame = inta == intb
           ! return
     end function la_lsame

     !> XERBLA:  is an error handler for the LAPACK routines.
     !> It is called by an LAPACK routine if an input parameter has an
     !> invalid value.  A message is printed and execution stops.
     !> Installers may consider modifying the STOP statement in order to
     !> call system-specific exception-handling facilities.

     pure subroutine la_xerbla(srname,info)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character(len=*),intent(in) :: srname
           integer(ilp),intent(in) :: info
       ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: len_trim
           ! Executable Statements
9999  format(' ** ON ENTRY TO ',a,' PARAMETER NUMBER ',i2,' HAD ','AN ILLEGAL VALUE')
                
     end subroutine la_xerbla

     !> XERBLA_ARRAY: assists other languages in calling XERBLA, the LAPACK
     !> and BLAS error handler.  Rather than taking a Fortran string argument
     !> as the function's name, XERBLA_ARRAY takes an array of single
     !> characters along with the array's length.  XERBLA_ARRAY then copies
     !> up to 32 characters of that array into a Fortran string and passes
     !> that to XERBLA.  If called with a non-positive SRNAME_LEN,
     !> XERBLA_ARRAY will call XERBLA with a string of all blank characters.
     !> Say some macro or other device makes XERBLA_ARRAY available to C99
     !> by a name lapack_xerbla and with a common Fortran calling convention.
     !> Then a C99 program could invoke XERBLA via:
     !> {
     !> int flen = strlen(__func__);
     !> lapack_xerbla(__func__,
     !> }
     !> Providing XERBLA_ARRAY is not necessary for intercepting LAPACK
     !> errors.  XERBLA_ARRAY calls XERBLA.

     pure subroutine la_xerbla_array(srname_array,srname_len,info)
        ! -- reference blas level1 routine --
        ! -- reference blas is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: srname_len,info
           ! Array Arguments
           character(1),intent(in) :: srname_array(srname_len)
       ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i
           ! Local Arrays
           character*32 srname
           ! Intrinsic Functions
           intrinsic :: min,len
           ! Executable Statements
           srname = ''
           do i = 1,min(srname_len,len(srname))
              srname(i:i) = srname_array(i)
           end do
           call la_xerbla(srname,info)
           return
     end subroutine la_xerbla_array

end module la_blas_aux
