#:include "common.fypp"
!> Least-squares helpers: incremental condition estimation and divide-and-conquer back-substitution
module la_lapack_lsq_aux
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level2_gen
     use la_blas_level3_gen
     use la_lapack_auxiliary
     use la_lapack_blas_like_base
     use la_lapack_blas_like_l1
     use la_lapack_blas_like_l2
     use la_lapack_blas_like_mnorm
     use la_lapack_eigv_svd_bidiag_dc
     use la_lapack_givens_jacobi_rot
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     public :: la_${ri}$laic1
     public :: la_${ri}$lals0
     public :: la_${ri}$lalsa
     public :: la_${ri}$lalsd
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     public :: la_${ri}$laic1
     public :: la_${ri}$lals0
     public :: la_${ri}$lalsa
     public :: la_${ri}$lalsd
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LAIC1: applies one step of incremental condition estimation in
     !> its simplest version:
     !> Let x, twonorm(x) = 1, be an approximate singular vector of an j-by-j
     !> lower triangular matrix L, such that
     !> twonorm(L*x) = sest
     !> Then ${ri.upper()}$LAIC1 computes sestpr, s, c such that
     !> the vector
     !> [ s*x ]
     !> xhat = [  c  ]
     !> is an approximate singular vector of
     !> [ L       0  ]
     !> Lhat = [ w**T gamma ]
     !> in the sense that
     !> twonorm(Lhat*xhat) = sestpr.
     !> Depending on JOB, an estimate for the largest or smallest singular
     !> value is computed.
     !> Note that [s c]**T and sestpr**2 is an eigenpair of the system
     !> diag(sest*sest, 0) + [alpha  gamma] * [ alpha ]
     !> [ gamma ]
     !> where  alpha =  x**T*w.

     pure subroutine la_${ri}$laic1(job,j,x,sest,w,gamma,sestpr,s,c)
        use la_constants_${rk}$,only:zero,half,one,two,four
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: j,job
           real(${rk}$),intent(out) :: c,s,sestpr
           real(${rk}$),intent(in) :: gamma,sest
           ! Array Arguments
           real(${rk}$),intent(in) :: w(j),x(j)
        ! =====================================================================

           ! Local Scalars
           real(${rk}$) :: absalp,absest,absgam,alpha,b,cosine,eps,norma,s1,s2,sine,t, &
                     test,tmp,zeta1,zeta2
           ! Intrinsic Functions
           intrinsic :: abs,max,sign,sqrt
           ! Executable Statements
           eps = la_${ri}$lamch('EPSILON')
           alpha = la_${ri}$dot(j,x,1,w,1)
           absalp = abs(alpha)
           absgam = abs(gamma)
           absest = abs(sest)
           if (job == 1) then
              ! estimating largest singular value
              ! special cases
              if (sest == zero) then
                 s1 = max(absgam,absalp)
                 if (s1 == zero) then
                    s = zero
                    c = one
                    sestpr = zero
                 else
                    s = alpha/s1
                    c = gamma/s1
                    tmp = sqrt(s*s + c*c)
                    s = s/tmp
                    c = c/tmp
                    sestpr = s1*tmp
                 end if
                 return
              else if (absgam <= eps*absest) then
                 s = one
                 c = zero
                 tmp = max(absest,absalp)
                 s1 = absest/tmp
                 s2 = absalp/tmp
                 sestpr = tmp*sqrt(s1*s1 + s2*s2)
                 return
              else if (absalp <= eps*absest) then
                 s1 = absgam
                 s2 = absest
                 if (s1 <= s2) then
                    s = one
                    c = zero
                    sestpr = s2
                 else
                    s = zero
                    c = one
                    sestpr = s1
                 end if
                 return
              else if (absest <= eps*absalp .or. absest <= eps*absgam) then
                 s1 = absgam
                 s2 = absalp
                 if (s1 <= s2) then
                    tmp = s1/s2
                    s = sqrt(one + tmp*tmp)
                    sestpr = s2*s
                    c = (gamma/s2)/s
                    s = sign(one,alpha)/s
                 else
                    tmp = s2/s1
                    c = sqrt(one + tmp*tmp)
                    sestpr = s1*c
                    s = (alpha/s1)/c
                    c = sign(one,gamma)/c
                 end if
                 return
              else
                 ! normal case
                 zeta1 = alpha/absest
                 zeta2 = gamma/absest
                 b = (one - zeta1*zeta1 - zeta2*zeta2)*half
                 c = zeta1*zeta1
                 if (b > zero) then
                    t = c/(b + sqrt(b*b + c))
                 else
                    t = sqrt(b*b + c) - b
                 end if
                 sine = -zeta1/t
                 cosine = -zeta2/(one + t)
                 tmp = sqrt(sine*sine + cosine*cosine)
                 s = sine/tmp
                 c = cosine/tmp
                 sestpr = sqrt(t + one)*absest
                 return
              end if
           else if (job == 2) then
              ! estimating smallest singular value
              ! special cases
              if (sest == zero) then
                 sestpr = zero
                 if (max(absgam,absalp) == zero) then
                    sine = one
                    cosine = zero
                 else
                    sine = -gamma
                    cosine = alpha
                 end if
                 s1 = max(abs(sine),abs(cosine))
                 s = sine/s1
                 c = cosine/s1
                 tmp = sqrt(s*s + c*c)
                 s = s/tmp
                 c = c/tmp
                 return
              else if (absgam <= eps*absest) then
                 s = zero
                 c = one
                 sestpr = absgam
                 return
              else if (absalp <= eps*absest) then
                 s1 = absgam
                 s2 = absest
                 if (s1 <= s2) then
                    s = zero
                    c = one
                    sestpr = s1
                 else
                    s = one
                    c = zero
                    sestpr = s2
                 end if
                 return
              else if (absest <= eps*absalp .or. absest <= eps*absgam) then
                 s1 = absgam
                 s2 = absalp
                 if (s1 <= s2) then
                    tmp = s1/s2
                    c = sqrt(one + tmp*tmp)
                    sestpr = absest*(tmp/c)
                    s = -(gamma/s2)/c
                    c = sign(one,alpha)/c
                 else
                    tmp = s2/s1
                    s = sqrt(one + tmp*tmp)
                    sestpr = absest/s
                    c = (alpha/s1)/s
                    s = -sign(one,gamma)/s
                 end if
                 return
              else
                 ! normal case
                 zeta1 = alpha/absest
                 zeta2 = gamma/absest
                 norma = max(one + zeta1*zeta1 + abs(zeta1*zeta2),abs(zeta1*zeta2) + zeta2*zeta2)

                 ! see if root is closer to zero or to one
                 test = one + two*(zeta1 - zeta2)*(zeta1 + zeta2)
                 if (test >= zero) then
                    ! root is close to zero, compute directly
                    b = (zeta1*zeta1 + zeta2*zeta2 + one)*half
                    c = zeta2*zeta2
                    t = c/(b + sqrt(abs(b*b - c)))
                    sine = zeta1/(one - t)
                    cosine = -zeta2/t
                    sestpr = sqrt(t + four*eps*eps*norma)*absest
                 else
                    ! root is closer to one, shift by that amount
                    b = (zeta2*zeta2 + zeta1*zeta1 - one)*half
                    c = zeta1*zeta1
                    if (b >= zero) then
                       t = -c/(b + sqrt(b*b + c))
                    else
                       t = b - sqrt(b*b + c)
                    end if
                    sine = -zeta1/t
                    cosine = -zeta2/(one + t)
                    sestpr = sqrt(one + t + four*eps*eps*norma)*absest
                 end if
                 tmp = sqrt(sine*sine + cosine*cosine)
                 s = sine/tmp
                 c = cosine/tmp
                 return
              end if
           end if
           return
     end subroutine la_${ri}$laic1
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LALS0: applies back the multiplying factors of either the left or the
     !> right singular vector matrix of a diagonal matrix appended by a row
     !> to the right hand side matrix B in solving the least squares problem
     !> using the divide-and-conquer SVD approach.
     !> For the left singular vector matrix, three types of orthogonal
     !> matrices are involved:
     !> (1L) Givens rotations: the number of such rotations is GIVPTR; the
     !> pairs of columns/rows they were applied to are stored in GIVCOL;
     !> and the C- and S-values of these rotations are stored in GIVNUM.
     !> (2L) Permutation. The (NL+1)-st row of B is to be moved to the first
     !> row, and for J=2:N, PERM(J)-th row of B is to be moved to the
     !> J-th row.
     !> (3L) The left singular vector matrix of the remaining matrix.
     !> For the right singular vector matrix, four types of orthogonal
     !> matrices are involved:
     !> (1R) The right singular vector matrix of the remaining matrix.
     !> (2R) If SQRE = 1, one extra Givens rotation to generate the right
     !> null space.
     !> (3R) The inverse transformation of (2L).
     !> (4R) The inverse transformation of (1L).

     pure subroutine la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,b,ldb,bx,ldbx,perm,givptr, &
               givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: givptr,icompq,k,ldb,ldbx,ldgcol,ldgnum,nl,nr,nrhs, &
                      sqre
           integer(ilp),intent(out) :: info
           real(${rk}$),intent(in) :: c,s
           ! Array Arguments
           integer(ilp),intent(in) :: givcol(ldgcol,*),perm(*)
           real(${rk}$),intent(inout) :: b(ldb,*)
           real(${rk}$),intent(out) :: bx(ldbx,*),work(*)
           real(${rk}$),intent(in) :: difl(*),difr(ldgnum,*),givnum(ldgnum,*),poles(ldgnum,*),z( &
                     *)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,m,n,nlp1
           real(${rk}$) :: diflj,difrj,dj,dsigj,dsigjp,temp
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           n = nl + nr + 1
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (nl < 1) then
              info = -2
           else if (nr < 1) then
              info = -3
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -4
           else if (nrhs < 1) then
              info = -5
           else if (ldb < n) then
              info = -7
           else if (ldbx < n) then
              info = -9
           else if (givptr < 0) then
              info = -11
           else if (ldgcol < n) then
              info = -13
           else if (ldgnum < n) then
              info = -15
           else if (k < 1) then
              info = -20
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALS0',-info)
              return
           end if
           m = n + sqre
           nlp1 = nl + 1
           if (icompq == 0) then
              ! apply back orthogonal transformations from the left.
              ! step (1l): apply back the givens rotations performed.
              do i = 1,givptr
                 call la_${ri}$rot(nrhs,b(givcol(i,2),1),ldb,b(givcol(i,1),1),ldb, &
                           givnum(i,2),givnum(i,1))
              end do
              ! step (2l): permute rows of b.
              call la_${ri}$copy(nrhs,b(nlp1,1),ldb,bx(1,1),ldbx)
              do i = 2,n
                 call la_${ri}$copy(nrhs,b(perm(i),1),ldb,bx(i,1),ldbx)
              end do
              ! step (3l): apply the inverse of the left singular vector
              ! matrix to bx.
              if (k == 1) then
                 call la_${ri}$copy(nrhs,bx,ldbx,b,ldb)
                 if (z(1) < zero) then
                    call la_${ri}$scal(nrhs,negone,b,ldb)
                 end if
              else
                 loop_50: do j = 1,k
                    diflj = difl(j)
                    dj = poles(j,1)
                    dsigj = -poles(j,2)
                    if (j < k) then
                       difrj = -difr(j,1)
                       dsigjp = -poles(j + 1,2)
                    end if
                    if ((z(j) == zero) .or. (poles(j,2) == zero)) then
                       work(j) = zero
                    else
                       work(j) = -poles(j,2)*z(j)/diflj/(poles(j,2) + dj)
                    end if
                    do i = 1,j - 1
                       if ((z(i) == zero) .or. (poles(i,2) == zero)) then
                          work(i) = zero
                       else
                          work(i) = poles(i,2)*z(i)/(la_${ri}$lamc3(poles(i,2),dsigj &
                                    ) - diflj)/(poles(i,2) + dj)
                       end if
                    end do
                    do i = j + 1,k
                       if ((z(i) == zero) .or. (poles(i,2) == zero)) then
                          work(i) = zero
                       else
                          work(i) = poles(i,2)*z(i)/(la_${ri}$lamc3(poles(i,2), &
                                    dsigjp) + difrj)/(poles(i,2) + dj)
                       end if
                    end do
                    work(1) = negone
                    temp = la_${ri}$nrm2(k,work,1)
                    call la_${ri}$gemv('T',k,nrhs,one,bx,ldbx,work,1,zero,b(j,1),ldb)

                    call la_${ri}$lascl('G',0,0,temp,one,1,nrhs,b(j,1),ldb,info)

                 end do loop_50
              end if
              ! move the deflated rows of bx to b also.
              if (k < max(m,n)) call la_${ri}$lacpy('A',n - k,nrhs,bx(k + 1,1),ldbx,b(k + 1,1 &
                        ),ldb)
           else
              ! apply back the right orthogonal transformations.
              ! step (1r): apply back the new right singular vector matrix
              ! to b.
              if (k == 1) then
                 call la_${ri}$copy(nrhs,b,ldb,bx,ldbx)
              else
                 do j = 1,k
                    dsigj = poles(j,2)
                    if (z(j) == zero) then
                       work(j) = zero
                    else
                       work(j) = -z(j)/difl(j)/(dsigj + poles(j,1))/difr(j,2)

                    end if
                    do i = 1,j - 1
                       if (z(j) == zero) then
                          work(i) = zero
                       else
                          work(i) = z(j)/(la_${ri}$lamc3(dsigj,-poles(i + 1,2)) - difr(i, &
                                    1))/(dsigj + poles(i,1))/difr(i,2)
                       end if
                    end do
                    do i = j + 1,k
                       if (z(j) == zero) then
                          work(i) = zero
                       else
                          work(i) = z(j)/(la_${ri}$lamc3(dsigj,-poles(i,2)) - difl(i)) &
                                     /(dsigj + poles(i,1))/difr(i,2)
                       end if
                    end do
                    call la_${ri}$gemv('T',k,nrhs,one,b,ldb,work,1,zero,bx(j,1),ldbx)

                 end do
              end if
              ! step (2r): if sqre = 1, apply back the rotation that is
              ! related to the right null space of the subproblem.
              if (sqre == 1) then
                 call la_${ri}$copy(nrhs,b(m,1),ldb,bx(m,1),ldbx)
                 call la_${ri}$rot(nrhs,bx(1,1),ldbx,bx(m,1),ldbx,c,s)
              end if
              if (k < max(m,n)) call la_${ri}$lacpy('A',n - k,nrhs,b(k + 1,1),ldb,bx(k + 1,1 &
                        ),ldbx)
              ! step (3r): permute rows of b.
              call la_${ri}$copy(nrhs,bx(1,1),ldbx,b(nlp1,1),ldb)
              if (sqre == 1) then
                 call la_${ri}$copy(nrhs,bx(m,1),ldbx,b(m,1),ldb)
              end if
              do i = 2,n
                 call la_${ri}$copy(nrhs,bx(i,1),ldbx,b(perm(i),1),ldb)
              end do
              ! step (4r): apply back the givens rotations performed.
              do i = givptr,1,-1
                 call la_${ri}$rot(nrhs,b(givcol(i,2),1),ldb,b(givcol(i,1),1),ldb, &
                           givnum(i,2),-givnum(i,1))
              end do
           end if
           return
     end subroutine la_${ri}$lals0
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LALSA: is an itermediate step in solving the least squares problem
     !> by computing the SVD of the coefficient matrix in compact form (The
     !> singular vectors are computed as products of simple orthorgonal
     !> matrices.).
     !> If ICOMPQ = 0, ${ri.upper()}$LALSA applies the inverse of the left singular vector
     !> matrix of an upper bidiagonal matrix to the right hand side; and if
     !> ICOMPQ = 1, ${ri.upper()}$LALSA applies the right singular vector matrix to the
     !> right hand side. The singular vector matrices were generated in
     !> compact form by ${ri.upper()}$LALSA.

     pure subroutine la_${ri}$lalsa(icompq,smlsiz,n,nrhs,b,ldb,bx,ldbx,u,ldu,vt,k,difl, &
                difr,z,poles,givptr,givcol,ldgcol,perm,givnum,c,s,work,iwork,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: icompq,ldb,ldbx,ldgcol,ldu,n,nrhs,smlsiz
           integer(ilp),intent(out) :: info
           ! Array Arguments
           integer(ilp),intent(in) :: givcol(ldgcol,*),givptr(*),k(*),perm(ldgcol,*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: b(ldb,*)
           real(${rk}$),intent(out) :: bx(ldbx,*),work(*)
           real(${rk}$),intent(in) :: c(*),difl(ldu,*),difr(ldu,*),givnum(ldu,*),poles(ldu,*),s( &
                     *),u(ldu,*),vt(ldu,*),z(ldu,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,i1,ic,im1,inode,j,lf,ll,lvl,lvl2,nd,ndb1,ndiml,ndimr, &
                     nl,nlf,nlp1,nlvl,nr,nrf,nrp1,sqre
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (smlsiz < 3) then
              info = -2
           else if (n < smlsiz) then
              info = -3
           else if (nrhs < 1) then
              info = -4
           else if (ldb < n) then
              info = -6
           else if (ldbx < n) then
              info = -8
           else if (ldu < n) then
              info = -10
           else if (ldgcol < n) then
              info = -19
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALSA',-info)
              return
           end if
           ! book-keeping and  setting up the computation tree.
           inode = 1
           ndiml = inode + n
           ndimr = ndiml + n
           call la_${ri}$lasdt(n,nlvl,nd,iwork(inode),iwork(ndiml),iwork(ndimr),smlsiz &
                     )
           ! the following code applies back the left singular vector factors.
           ! for applying back the right singular vector factors, go to 50.
           if (icompq == 1) then
              go to 50
           end if
           ! the nodes on the bottom level of the tree were solved
           ! by la_${ri}$lasdq. the corresponding left and right singular vector
           ! matrices are in explicit form. first apply back the left
           ! singular vector matrices.
           ndb1 = (nd + 1)/2
           do i = ndb1,nd
              ! ic : center row of each node
              ! nl : number of rows of left  subproblem
              ! nr : number of rows of right subproblem
              ! nlf: starting row of the left   subproblem
              ! nrf: starting row of the right  subproblem
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nr = iwork(ndimr + i1)
              nlf = ic - nl
              nrf = ic + 1
              call la_${ri}$gemm('T','N',nl,nrhs,nl,one,u(nlf,1),ldu,b(nlf,1),ldb, &
                        zero,bx(nlf,1),ldbx)
              call la_${ri}$gemm('T','N',nr,nrhs,nr,one,u(nrf,1),ldu,b(nrf,1),ldb, &
                        zero,bx(nrf,1),ldbx)
           end do
           ! next copy the rows of b that correspond to unchanged rows
           ! in the bidiagonal matrix to bx.
           do i = 1,nd
              ic = iwork(inode + i - 1)
              call la_${ri}$copy(nrhs,b(ic,1),ldb,bx(ic,1),ldbx)
           end do
           ! finally go through the left singular vector matrices of all
           ! the other subproblems bottom-up on the tree.
           j = 2**nlvl
           sqre = 0
           do lvl = nlvl,1,-1
              lvl2 = 2*lvl - 1
              ! find the first node lf and last node ll on
              ! the current level lvl
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              do i = lf,ll
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 nrf = ic + 1
                 j = j - 1
                 call la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,bx(nlf,1),ldbx,b(nlf,1), &
                 ldb,perm(nlf,lvl),givptr(j),givcol(nlf,lvl2),ldgcol,givnum(nlf,lvl2 &
                 ),ldu,poles(nlf,lvl2),difl(nlf,lvl),difr(nlf,lvl2),z(nlf,lvl),k( &
                           j),c(j),s(j),work,info)
              end do
           end do
           go to 90
           ! icompq = 1: applying back the right singular vector factors.
           50 continue
           ! first now go through the right singular vector matrices of all
           ! the tree nodes top-down.
           j = 0
           loop_70: do lvl = 1,nlvl
              lvl2 = 2*lvl - 1
              ! find the first node lf and last node ll on
              ! the current level lvl.
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              do i = ll,lf,-1
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 nrf = ic + 1
                 if (i == ll) then
                    sqre = 0
                 else
                    sqre = 1
                 end if
                 j = j + 1
                 call la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,b(nlf,1),ldb,bx(nlf,1), &
                 ldbx,perm(nlf,lvl),givptr(j),givcol(nlf,lvl2),ldgcol,givnum(nlf, &
                 lvl2),ldu,poles(nlf,lvl2),difl(nlf,lvl),difr(nlf,lvl2),z(nlf,lvl) &
                           ,k(j),c(j),s(j),work,info)
              end do
           end do loop_70
           ! the nodes on the bottom level of the tree were solved
           ! by la_${ri}$lasdq. the corresponding right singular vector
           ! matrices are in explicit form. apply them back.
           ndb1 = (nd + 1)/2
           do i = ndb1,nd
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nr = iwork(ndimr + i1)
              nlp1 = nl + 1
              if (i == nd) then
                 nrp1 = nr
              else
                 nrp1 = nr + 1
              end if
              nlf = ic - nl
              nrf = ic + 1
              call la_${ri}$gemm('T','N',nlp1,nrhs,nlp1,one,vt(nlf,1),ldu,b(nlf,1), &
                        ldb,zero,bx(nlf,1),ldbx)
              call la_${ri}$gemm('T','N',nrp1,nrhs,nrp1,one,vt(nrf,1),ldu,b(nrf,1), &
                        ldb,zero,bx(nrf,1),ldbx)
           end do
           90 continue
           return
     end subroutine la_${ri}$lalsa
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LALSD: uses the singular value decomposition of A to solve the least
     !> squares problem of finding X to minimize the Euclidean norm of each
     !> column of A*X-B, where A is N-by-N upper bidiagonal, and X and B
     !> are N-by-NRHS. The solution X overwrites B.
     !> The singular values of A smaller than RCOND times the largest
     !> singular value are treated as zero in solving the least squares
     !> problem; in this case a minimum norm solution is returned.
     !> The actual singular values are returned in D in ascending order.
     !> This code makes very mild assumptions about floating point
     !> arithmetic. It will work on machines with a guard digit in
     !> add/subtract, or on those binary machines without guard digits
     !> which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2.
     !> It could conceivably fail on hexadecimal or decimal machines
     !> without guard digits, but we know of none.

     pure subroutine la_${ri}$lalsd(uplo,smlsiz,n,nrhs,d,e,b,ldb,rcond,rank,work,iwork, &
               info)
        use la_constants_${rk}$,only:zero,one,two
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info,rank
           integer(ilp),intent(in) :: ldb,n,nrhs,smlsiz
           real(${rk}$),intent(in) :: rcond
           ! Array Arguments
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: b(ldb,*),d(*),e(*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: bx,bxst,c,difl,difr,givcol,givnum,givptr,i,icmpq1,icmpq2, &
           iwk,j,k,nlvl,nm1,nsize,nsub,nwork,perm,poles,s,sizei,smlszp,sqre,st,st1, &
                      u,vt,z
           real(${rk}$) :: cs,eps,orgnrm,r,rcnd,sn,tol
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,int,log,real,sign
#:else
           intrinsic :: abs,real,int,log,sign
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -3
           else if (nrhs < 1) then
              info = -4
           else if ((ldb < 1) .or. (ldb < n)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALSD',-info)
              return
           end if
           eps = la_${ri}$lamch('EPSILON')
           ! set up the tolerance.
           if ((rcond <= zero) .or. (rcond >= one)) then
              rcnd = eps
           else
              rcnd = rcond
           end if
           rank = 0
           ! quick return if possible.
           if (n == 0) then
              return
           else if (n == 1) then
              if (d(1) == zero) then
                 call la_${ri}$laset('A',1,nrhs,zero,zero,b,ldb)
              else
                 rank = 1
                 call la_${ri}$lascl('G',0,0,d(1),one,1,nrhs,b,ldb,info)
                 d(1) = abs(d(1))
              end if
              return
           end if
           ! rotate the matrix if it is lower bidiagonal.
           if (uplo == 'L') then
              do i = 1,n - 1
                 call la_${ri}$lartg(d(i),e(i),cs,sn,r)
                 d(i) = r
                 e(i) = sn*d(i + 1)
                 d(i + 1) = cs*d(i + 1)
                 if (nrhs == 1) then
                    call la_${ri}$rot(1,b(i,1),1,b(i + 1,1),1,cs,sn)
                 else
                    work(i*2 - 1) = cs
                    work(i*2) = sn
                 end if
              end do
              if (nrhs > 1) then
                 do i = 1,nrhs
                    do j = 1,n - 1
                       cs = work(j*2 - 1)
                       sn = work(j*2)
                       call la_${ri}$rot(1,b(j,i),1,b(j + 1,i),1,cs,sn)
                    end do
                 end do
              end if
           end if
           ! scale.
           nm1 = n - 1
           orgnrm = la_${ri}$lanst('M',n,d,e)
           if (orgnrm == zero) then
              call la_${ri}$laset('A',n,nrhs,zero,zero,b,ldb)
              return
           end if
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,1,d,n,info)
           call la_${ri}$lascl('G',0,0,orgnrm,one,nm1,1,e,nm1,info)
           ! if n is smaller than the minimum divide size smlsiz, then solve
           ! the problem with another solver.
           if (n <= smlsiz) then
              nwork = 1 + n*n
              call la_${ri}$laset('A',n,n,zero,one,work,n)
              call la_${ri}$lasdq('U',0,n,n,0,nrhs,d,e,work,n,work,n,b,ldb,work( &
                        nwork),info)
              if (info /= 0) then
                 return
              end if
              tol = rcnd*abs(d(la_i${ri}$amax(n,d,1)))
              do i = 1,n
                 if (d(i) <= tol) then
                    call la_${ri}$laset('A',1,nrhs,zero,zero,b(i,1),ldb)
                 else
                    call la_${ri}$lascl('G',0,0,d(i),one,1,nrhs,b(i,1),ldb,info)

                    rank = rank + 1
                 end if
              end do
              call la_${ri}$gemm('T','N',n,nrhs,n,one,work,n,b,ldb,zero,work(nwork), &
                        n)
              call la_${ri}$lacpy('A',n,nrhs,work(nwork),n,b,ldb)
              ! unscale.
              call la_${ri}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
              call la_${ri}$lasrt('D',n,d,info)
              call la_${ri}$lascl('G',0,0,orgnrm,one,n,nrhs,b,ldb,info)
              return
           end if
           ! book-keeping and setting up some constants.
           nlvl = int(log(real(n,KIND=${rk}$)/real(smlsiz + 1,KIND=${rk}$))/log(two),KIND=ilp) + &
                     1
           smlszp = smlsiz + 1
           u = 1
           vt = 1 + smlsiz*n
           difl = vt + smlszp*n
           difr = difl + nlvl*n
           z = difr + nlvl*n*2
           c = z + nlvl*n
           s = c + n
           poles = s + n
           givnum = poles + 2*nlvl*n
           bx = givnum + 2*nlvl*n
           nwork = bx + n*nrhs
           sizei = 1 + n
           k = sizei + n
           givptr = k + n
           perm = givptr + n
           givcol = perm + nlvl*n
           iwk = givcol + nlvl*n*2
           st = 1
           sqre = 0
           icmpq1 = 1
           icmpq2 = 0
           nsub = 0
           do i = 1,n
              if (abs(d(i)) < eps) then
                 d(i) = sign(eps,d(i))
              end if
           end do
           loop_60: do i = 1,nm1
              if ((abs(e(i)) < eps) .or. (i == nm1)) then
                 nsub = nsub + 1
                 iwork(nsub) = st
                 ! subproblem found. first determine its size and then
                 ! apply divide and conquer on it.
                 if (i < nm1) then
                    ! a subproblem with e(i) small for i < nm1.
                    nsize = i - st + 1
                    iwork(sizei + nsub - 1) = nsize
                 else if (abs(e(i)) >= eps) then
                    ! a subproblem with e(nm1) not too small but i = nm1.
                    nsize = n - st + 1
                    iwork(sizei + nsub - 1) = nsize
                 else
                    ! a subproblem with e(nm1) small. this implies an
                    ! 1-by-1 subproblem at d(n), which is not solved
                    ! explicitly.
                    nsize = i - st + 1
                    iwork(sizei + nsub - 1) = nsize
                    nsub = nsub + 1
                    iwork(nsub) = n
                    iwork(sizei + nsub - 1) = 1
                    call la_${ri}$copy(nrhs,b(n,1),ldb,work(bx + nm1),n)
                 end if
                 st1 = st - 1
                 if (nsize == 1) then
                    ! this is a 1-by-1 subproblem and is not solved
                    ! explicitly.
                    call la_${ri}$copy(nrhs,b(st,1),ldb,work(bx + st1),n)
                 else if (nsize <= smlsiz) then
                    ! this is a small subproblem and is solved by la_${ri}$lasdq.
                    call la_${ri}$laset('A',nsize,nsize,zero,one,work(vt + st1),n)
                    call la_${ri}$lasdq('U',0,nsize,nsize,0,nrhs,d(st),e(st),work(vt + &
                              st1),n,work(nwork),n,b(st,1),ldb,work(nwork),info)
                    if (info /= 0) then
                       return
                    end if
                    call la_${ri}$lacpy('A',nsize,nrhs,b(st,1),ldb,work(bx + st1),n)

                 else
                    ! a large problem. solve it using divide and conquer.
                    call la_${ri}$lasda(icmpq1,smlsiz,nsize,sqre,d(st),e(st),work(u + st1 &
                    ),n,work(vt + st1),iwork(k + st1),work(difl + st1),work(difr + st1),work( &
                    z + st1),work(poles + st1),iwork(givptr + st1),iwork(givcol + st1),n,iwork( &
                    perm + st1),work(givnum + st1),work(c + st1),work(s + st1),work(nwork), &
                              iwork(iwk),info)
                    if (info /= 0) then
                       return
                    end if
                    bxst = bx + st1
                    call la_${ri}$lalsa(icmpq2,smlsiz,nsize,nrhs,b(st,1),ldb,work(bxst), &
                     n,work(u + st1),n,work(vt + st1),iwork(k + st1),work(difl + st1),work( &
                     difr + st1),work(z + st1),work(poles + st1),iwork(givptr + st1),iwork( &
                     givcol + st1),n,iwork(perm + st1),work(givnum + st1),work(c + st1),work(s + &
                               st1),work(nwork),iwork(iwk),info)
                    if (info /= 0) then
                       return
                    end if
                 end if
                 st = i + 1
              end if
           end do loop_60
           ! apply the singular values and treat the tiny ones as zero.
           tol = rcnd*abs(d(la_i${ri}$amax(n,d,1)))
           do i = 1,n
              ! some of the elements in d can be negative because 1-by-1
              ! subproblems were not solved explicitly.
              if (abs(d(i)) <= tol) then
                 call la_${ri}$laset('A',1,nrhs,zero,zero,work(bx + i - 1),n)
              else
                 rank = rank + 1
                 call la_${ri}$lascl('G',0,0,d(i),one,1,nrhs,work(bx + i - 1),n,info)

              end if
              d(i) = abs(d(i))
           end do
           ! now apply back the right singular vectors.
           icmpq2 = 1
           do i = 1,nsub
              st = iwork(i)
              st1 = st - 1
              nsize = iwork(sizei + i - 1)
              bxst = bx + st1
              if (nsize == 1) then
                 call la_${ri}$copy(nrhs,work(bxst),n,b(st,1),ldb)
              else if (nsize <= smlsiz) then
                 call la_${ri}$gemm('T','N',nsize,nrhs,nsize,one,work(vt + st1),n,work( &
                           bxst),n,zero,b(st,1),ldb)
              else
                 call la_${ri}$lalsa(icmpq2,smlsiz,nsize,nrhs,work(bxst),n,b(st,1),ldb, &
                  work(u + st1),n,work(vt + st1),iwork(k + st1),work(difl + st1),work(difr + &
                  st1),work(z + st1),work(poles + st1),iwork(givptr + st1),iwork(givcol + st1), &
                   n,iwork(perm + st1),work(givnum + st1),work(c + st1),work(s + st1),work( &
                             nwork),iwork(iwk),info)
                 if (info /= 0) then
                    return
                 end if
              end if
           end do
           ! unscale and sort the singular values.
           call la_${ri}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
           call la_${ri}$lasrt('D',n,d,info)
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,nrhs,b,ldb,info)
           return
     end subroutine la_${ri}$lalsd
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LAIC1: applies one step of incremental condition estimation in
     !> its simplest version:
     !> Let x, twonorm(x) = 1, be an approximate singular vector of an j-by-j
     !> lower triangular matrix L, such that
     !> twonorm(L*x) = sest
     !> Then ${ri.upper()}$LAIC1 computes sestpr, s, c such that
     !> the vector
     !> [ s*x ]
     !> xhat = [  c  ]
     !> is an approximate singular vector of
#:if rk == "sp"
     !> [ L      0  ]
#:else
     !> [ L       0  ]
#:endif
     !> Lhat = [ w**H gamma ]
     !> in the sense that
     !> twonorm(Lhat*xhat) = sestpr.
     !> Depending on JOB, an estimate for the largest or smallest singular
     !> value is computed.
     !> Note that [s c]**H and sestpr**2 is an eigenpair of the system
     !> diag(sest*sest, 0) + [alpha  gamma] * [ conjg(alpha) ]
     !> [ conjg(gamma) ]
#:if rk == "sp"
     !> where  alpha =  x**H*w.
#:else
     !> where  alpha =  x**H * w.
#:endif

     pure subroutine la_${ri}$laic1(job,j,x,sest,w,gamma,sestpr,s,c)
        use la_constants_${rk}$,only:zero,half,one,two,four
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: j,job
           real(${rk}$),intent(in) :: sest
           real(${rk}$),intent(out) :: sestpr
           complex(${rk}$),intent(out) :: c,s
           complex(${rk}$),intent(in) :: gamma
           ! Array Arguments
           complex(${rk}$),intent(in) :: w(j),x(j)
        ! =====================================================================

           ! Local Scalars
           real(${rk}$) :: absalp,absest,absgam,b,eps,norma,s1,s2,scl,t,test,tmp,zeta1, &
                     zeta2
           complex(${rk}$) :: alpha,cosine,sine
           ! Intrinsic Functions
           intrinsic :: abs,conjg,max,sqrt
           ! Executable Statements
           eps = la_${ci}$lamch('EPSILON')
           alpha = la_${ri}$dotc(j,x,1,w,1)
           absalp = abs(alpha)
           absgam = abs(gamma)
           absest = abs(sest)
           if (job == 1) then
              ! estimating largest singular value
              ! special cases
              if (sest == zero) then
                 s1 = max(absgam,absalp)
                 if (s1 == zero) then
                    s = zero
                    c = one
                    sestpr = zero
                 else
                    s = alpha/s1
                    c = gamma/s1
                    tmp = real(sqrt(s*conjg(s) + c*conjg(c)),KIND=${rk}$)
                    s = s/tmp
                    c = c/tmp
                    sestpr = s1*tmp
                 end if
                 return
              else if (absgam <= eps*absest) then
                 s = one
                 c = zero
                 tmp = max(absest,absalp)
                 s1 = absest/tmp
                 s2 = absalp/tmp
                 sestpr = tmp*sqrt(s1*s1 + s2*s2)
                 return
              else if (absalp <= eps*absest) then
                 s1 = absgam
                 s2 = absest
                 if (s1 <= s2) then
                    s = one
                    c = zero
                    sestpr = s2
                 else
                    s = zero
                    c = one
                    sestpr = s1
                 end if
                 return
              else if (absest <= eps*absalp .or. absest <= eps*absgam) then
                 s1 = absgam
                 s2 = absalp
                 if (s1 <= s2) then
                    tmp = s1/s2
                    scl = sqrt(one + tmp*tmp)
                    sestpr = s2*scl
                    s = (alpha/s2)/scl
                    c = (gamma/s2)/scl
                 else
                    tmp = s2/s1
                    scl = sqrt(one + tmp*tmp)
                    sestpr = s1*scl
                    s = (alpha/s1)/scl
                    c = (gamma/s1)/scl
                 end if
                 return
              else
                 ! normal case
                 zeta1 = absalp/absest
                 zeta2 = absgam/absest
                 b = (one - zeta1*zeta1 - zeta2*zeta2)*half
                 c = zeta1*zeta1
                 if (b > zero) then
                    t = real(c/(b + sqrt(b*b + c)),KIND=${rk}$)
                 else
                    t = real(sqrt(b*b + c) - b,KIND=${rk}$)
                 end if
                 sine = -(alpha/absest)/t
                 cosine = -(gamma/absest)/(one + t)
                 tmp = real(sqrt(sine*conjg(sine) + cosine*conjg(cosine)),KIND=${rk}$)

                 s = sine/tmp
                 c = cosine/tmp
                 sestpr = sqrt(t + one)*absest
                 return
              end if
           else if (job == 2) then
              ! estimating smallest singular value
              ! special cases
              if (sest == zero) then
                 sestpr = zero
                 if (max(absgam,absalp) == zero) then
                    sine = one
                    cosine = zero
                 else
                    sine = -conjg(gamma)
                    cosine = conjg(alpha)
                 end if
                 s1 = max(abs(sine),abs(cosine))
                 s = sine/s1
                 c = cosine/s1
                 tmp = real(sqrt(s*conjg(s) + c*conjg(c)),KIND=${rk}$)
                 s = s/tmp
                 c = c/tmp
                 return
              else if (absgam <= eps*absest) then
                 s = zero
                 c = one
                 sestpr = absgam
                 return
              else if (absalp <= eps*absest) then
                 s1 = absgam
                 s2 = absest
                 if (s1 <= s2) then
                    s = zero
                    c = one
                    sestpr = s1
                 else
                    s = one
                    c = zero
                    sestpr = s2
                 end if
                 return
              else if (absest <= eps*absalp .or. absest <= eps*absgam) then
                 s1 = absgam
                 s2 = absalp
                 if (s1 <= s2) then
                    tmp = s1/s2
                    scl = sqrt(one + tmp*tmp)
                    sestpr = absest*(tmp/scl)
                    s = -(conjg(gamma)/s2)/scl
                    c = (conjg(alpha)/s2)/scl
                 else
                    tmp = s2/s1
                    scl = sqrt(one + tmp*tmp)
                    sestpr = absest/scl
                    s = -(conjg(gamma)/s1)/scl
                    c = (conjg(alpha)/s1)/scl
                 end if
                 return
              else
                 ! normal case
                 zeta1 = absalp/absest
                 zeta2 = absgam/absest
                 norma = max(one + zeta1*zeta1 + zeta1*zeta2,zeta1*zeta2 + zeta2*zeta2)
                 ! see if root is closer to zero or to one
                 test = one + two*(zeta1 - zeta2)*(zeta1 + zeta2)
                 if (test >= zero) then
                    ! root is close to zero, compute directly
                    b = (zeta1*zeta1 + zeta2*zeta2 + one)*half
                    c = zeta2*zeta2
                    t = real(c/(b + sqrt(abs(b*b - c))),KIND=${rk}$)
                    sine = (alpha/absest)/(one - t)
                    cosine = -(gamma/absest)/t
                    sestpr = sqrt(t + four*eps*eps*norma)*absest
                 else
                    ! root is closer to one, shift by that amount
                    b = (zeta2*zeta2 + zeta1*zeta1 - one)*half
                    c = zeta1*zeta1
                    if (b >= zero) then
#:if rk == "sp"
                       t = real(-c/(b + sqrt(b*b + c)),KIND=${rk}$)
#:else
                       t = -c/(b + sqrt(b*b + c))
#:endif
                    else
#:if rk == "sp"
                       t = real(b - sqrt(b*b + c),KIND=${rk}$)
#:else
                       t = b - sqrt(b*b + c)
#:endif
                    end if
                    sine = -(alpha/absest)/t
                    cosine = -(gamma/absest)/(one + t)
                    sestpr = sqrt(one + t + four*eps*eps*norma)*absest
                 end if
                 tmp = real(sqrt(sine*conjg(sine) + cosine*conjg(cosine)),KIND=${rk}$)

                 s = sine/tmp
                 c = cosine/tmp
                 return
              end if
           end if
           return
     end subroutine la_${ri}$laic1
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LALS0: applies back the multiplying factors of either the left or the
     !> right singular vector matrix of a diagonal matrix appended by a row
     !> to the right hand side matrix B in solving the least squares problem
     !> using the divide-and-conquer SVD approach.
     !> For the left singular vector matrix, three types of orthogonal
     !> matrices are involved:
     !> (1L) Givens rotations: the number of such rotations is GIVPTR; the
     !> pairs of columns/rows they were applied to are stored in GIVCOL;
     !> and the C- and S-values of these rotations are stored in GIVNUM.
     !> (2L) Permutation. The (NL+1)-st row of B is to be moved to the first
     !> row, and for J=2:N, PERM(J)-th row of B is to be moved to the
     !> J-th row.
     !> (3L) The left singular vector matrix of the remaining matrix.
     !> For the right singular vector matrix, four types of orthogonal
     !> matrices are involved:
     !> (1R) The right singular vector matrix of the remaining matrix.
     !> (2R) If SQRE = 1, one extra Givens rotation to generate the right
     !> null space.
     !> (3R) The inverse transformation of (2L).
     !> (4R) The inverse transformation of (1L).

     pure subroutine la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,b,ldb,bx,ldbx,perm,givptr, &
               givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,rwork,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: givptr,icompq,k,ldb,ldbx,ldgcol,ldgnum,nl,nr,nrhs, &
                      sqre
           integer(ilp),intent(out) :: info
           real(${rk}$),intent(in) :: c,s
           ! Array Arguments
           integer(ilp),intent(in) :: givcol(ldgcol,*),perm(*)
           real(${rk}$),intent(in) :: difl(*),difr(ldgnum,*),givnum(ldgnum,*),poles(ldgnum,*),z( &
                     *)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
           complex(${rk}$),intent(out) :: bx(ldbx,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,jcol,jrow,m,n,nlp1
           real(${rk}$) :: diflj,difrj,dj,dsigj,dsigjp,temp
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: aimag,cmplx,max,real
#:else
           intrinsic :: real,cmplx,aimag,max
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           n = nl + nr + 1
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (nl < 1) then
              info = -2
           else if (nr < 1) then
              info = -3
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -4
           else if (nrhs < 1) then
              info = -5
           else if (ldb < n) then
              info = -7
           else if (ldbx < n) then
              info = -9
           else if (givptr < 0) then
              info = -11
           else if (ldgcol < n) then
              info = -13
           else if (ldgnum < n) then
              info = -15
           else if (k < 1) then
              info = -20
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALS0',-info)
              return
           end if
           m = n + sqre
           nlp1 = nl + 1
           if (icompq == 0) then
              ! apply back orthogonal transformations from the left.
              ! step (1l): apply back the givens rotations performed.
              do i = 1,givptr
                 call la_${ri}$${ci}$rot(nrhs,b(givcol(i,2),1),ldb,b(givcol(i,1),1),ldb, &
                            givnum(i,2),givnum(i,1))
              end do
              ! step (2l): permute rows of b.
              call la_${ri}$copy(nrhs,b(nlp1,1),ldb,bx(1,1),ldbx)
              do i = 2,n
                 call la_${ri}$copy(nrhs,b(perm(i),1),ldb,bx(i,1),ldbx)
              end do
              ! step (3l): apply the inverse of the left singular vector
              ! matrix to bx.
              if (k == 1) then
                 call la_${ri}$copy(nrhs,bx,ldbx,b,ldb)
                 if (z(1) < zero) then
                    call la_${ri}$${ci}$scal(nrhs,negone,b,ldb)
                 end if
              else
                 loop_100: do j = 1,k
                    diflj = difl(j)
                    dj = poles(j,1)
                    dsigj = -poles(j,2)
                    if (j < k) then
                       difrj = -difr(j,1)
                       dsigjp = -poles(j + 1,2)
                    end if
                    if ((z(j) == zero) .or. (poles(j,2) == zero)) then
                       rwork(j) = zero
                    else
                       rwork(j) = -poles(j,2)*z(j)/diflj/(poles(j,2) + dj)
                    end if
                    do i = 1,j - 1
                       if ((z(i) == zero) .or. (poles(i,2) == zero)) then
                          rwork(i) = zero
                       else
                          rwork(i) = poles(i,2)*z(i)/(la_${ci}$lamc3(poles(i,2), &
                                    dsigj) - diflj)/(poles(i,2) + dj)
                       end if
                    end do
                    do i = j + 1,k
                       if ((z(i) == zero) .or. (poles(i,2) == zero)) then
                          rwork(i) = zero
                       else
                          rwork(i) = poles(i,2)*z(i)/(la_${ci}$lamc3(poles(i,2), &
                                    dsigjp) + difrj)/(poles(i,2) + dj)
                       end if
                    end do
                    rwork(1) = negone
                    temp = la_${ci}$nrm2(k,rwork,1)
                    ! since b and bx are complex, the following call to la_${ci}$gemv
                    ! is performed in two steps (real and imaginary parts).
                    ! call la_${ci}$gemv( 't', k, nrhs, one, bx, ldbx, work, 1, zero,
          ! $                     b( j, 1 ), ldb )
                    i = k + nrhs*2
                    do jcol = 1,nrhs
                       do jrow = 1,k
                          i = i + 1
                          rwork(i) = real(bx(jrow,jcol),KIND=${rk}$)
                       end do
                    end do
                    call la_${ci}$gemv('T',k,nrhs,one,rwork(1 + k + nrhs*2),k,rwork(1),1, &
                              zero,rwork(1 + k),1)
                    i = k + nrhs*2
                    do jcol = 1,nrhs
                       do jrow = 1,k
                          i = i + 1
                          rwork(i) = aimag(bx(jrow,jcol))
                       end do
                    end do
                    call la_${ci}$gemv('T',k,nrhs,one,rwork(1 + k + nrhs*2),k,rwork(1),1, &
                              zero,rwork(1 + k + nrhs),1)
                    do jcol = 1,nrhs
                       b(j,jcol) = cmplx(rwork(jcol + k),rwork(jcol + k + nrhs),KIND=${rk}$)
                    end do
                    call la_${ri}$lascl('G',0,0,temp,one,1,nrhs,b(j,1),ldb,info)

                 end do loop_100
              end if
              ! move the deflated rows of bx to b also.
              if (k < max(m,n)) call la_${ri}$lacpy('A',n - k,nrhs,bx(k + 1,1),ldbx,b(k + 1,1 &
                        ),ldb)
           else
              ! apply back the right orthogonal transformations.
              ! step (1r): apply back the new right singular vector matrix
              ! to b.
              if (k == 1) then
                 call la_${ri}$copy(nrhs,b,ldb,bx,ldbx)
              else
                 loop_180: do j = 1,k
                    dsigj = poles(j,2)
                    if (z(j) == zero) then
                       rwork(j) = zero
                    else
                       rwork(j) = -z(j)/difl(j)/(dsigj + poles(j,1))/difr(j,2)

                    end if
                    do i = 1,j - 1
                       if (z(j) == zero) then
                          rwork(i) = zero
                       else
                          rwork(i) = z(j)/(la_${ci}$lamc3(dsigj,-poles(i + 1,2)) - difr(i, &
                                     1))/(dsigj + poles(i,1))/difr(i,2)
                       end if
                    end do
                    do i = j + 1,k
                       if (z(j) == zero) then
                          rwork(i) = zero
                       else
                          rwork(i) = z(j)/(la_${ci}$lamc3(dsigj,-poles(i,2)) - difl(i) &
                                    )/(dsigj + poles(i,1))/difr(i,2)
                       end if
                    end do
                    ! since b and bx are complex, the following call to la_${ci}$gemv
                    ! is performed in two steps (real and imaginary parts).
                    ! call la_${ci}$gemv( 't', k, nrhs, one, b, ldb, work, 1, zero,
          ! $                     bx( j, 1 ), ldbx )
                    i = k + nrhs*2
                    do jcol = 1,nrhs
                       do jrow = 1,k
                          i = i + 1
                          rwork(i) = real(b(jrow,jcol),KIND=${rk}$)
                       end do
                    end do
                    call la_${ci}$gemv('T',k,nrhs,one,rwork(1 + k + nrhs*2),k,rwork(1),1, &
                              zero,rwork(1 + k),1)
                    i = k + nrhs*2
                    do jcol = 1,nrhs
                       do jrow = 1,k
                          i = i + 1
                          rwork(i) = aimag(b(jrow,jcol))
                       end do
                    end do
                    call la_${ci}$gemv('T',k,nrhs,one,rwork(1 + k + nrhs*2),k,rwork(1),1, &
                              zero,rwork(1 + k + nrhs),1)
                    do jcol = 1,nrhs
                       bx(j,jcol) = cmplx(rwork(jcol + k),rwork(jcol + k + nrhs),KIND=${rk}$)

                    end do
                 end do loop_180
              end if
              ! step (2r): if sqre = 1, apply back the rotation that is
              ! related to the right null space of the subproblem.
              if (sqre == 1) then
                 call la_${ri}$copy(nrhs,b(m,1),ldb,bx(m,1),ldbx)
                 call la_${ri}$${ci}$rot(nrhs,bx(1,1),ldbx,bx(m,1),ldbx,c,s)
              end if
#:if rk == "sp"
              if (k < max(m,n)) call la_${ri}$lacpy('A',n - k,nrhs,b(k + 1,1),ldb,bx(k + 1,1) &
                        ,ldbx)
#:else
              if (k < max(m,n)) call la_${ri}$lacpy('A',n - k,nrhs,b(k + 1,1),ldb,bx(k + 1,1 &
                        ),ldbx)
#:endif
              ! step (3r): permute rows of b.
              call la_${ri}$copy(nrhs,bx(1,1),ldbx,b(nlp1,1),ldb)
              if (sqre == 1) then
                 call la_${ri}$copy(nrhs,bx(m,1),ldbx,b(m,1),ldb)
              end if
              do i = 2,n
                 call la_${ri}$copy(nrhs,bx(i,1),ldbx,b(perm(i),1),ldb)
              end do
              ! step (4r): apply back the givens rotations performed.
              do i = givptr,1,-1
                 call la_${ri}$${ci}$rot(nrhs,b(givcol(i,2),1),ldb,b(givcol(i,1),1),ldb, &
                            givnum(i,2),-givnum(i,1))
              end do
           end if
           return
     end subroutine la_${ri}$lals0
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LALSA: is an itermediate step in solving the least squares problem
     !> by computing the SVD of the coefficient matrix in compact form (The
     !> singular vectors are computed as products of simple orthorgonal
     !> matrices.).
     !> If ICOMPQ = 0, ${ri.upper()}$LALSA applies the inverse of the left singular vector
     !> matrix of an upper bidiagonal matrix to the right hand side; and if
     !> ICOMPQ = 1, ${ri.upper()}$LALSA applies the right singular vector matrix to the
     !> right hand side. The singular vector matrices were generated in
     !> compact form by ${ri.upper()}$LALSA.

     pure subroutine la_${ri}$lalsa(icompq,smlsiz,n,nrhs,b,ldb,bx,ldbx,u,ldu,vt,k,difl, &
                difr,z,poles,givptr,givcol,ldgcol,perm,givnum,c,s,rwork,iwork,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: icompq,ldb,ldbx,ldgcol,ldu,n,nrhs,smlsiz
           integer(ilp),intent(out) :: info
           ! Array Arguments
           integer(ilp),intent(in) :: givcol(ldgcol,*),givptr(*),k(*),perm(ldgcol,*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(in) :: c(*),difl(ldu,*),difr(ldu,*),givnum(ldu,*),poles(ldu,*),s( &
                     *),u(ldu,*),vt(ldu,*),z(ldu,*)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
           complex(${rk}$),intent(out) :: bx(ldbx,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,i1,ic,im1,inode,j,jcol,jimag,jreal,jrow,lf,ll,lvl,lvl2, &
                     nd,ndb1,ndiml,ndimr,nl,nlf,nlp1,nlvl,nr,nrf,nrp1,sqre
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: aimag,cmplx,real
#:else
           intrinsic :: real,cmplx,aimag
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (smlsiz < 3) then
              info = -2
           else if (n < smlsiz) then
              info = -3
           else if (nrhs < 1) then
              info = -4
           else if (ldb < n) then
              info = -6
           else if (ldbx < n) then
              info = -8
           else if (ldu < n) then
              info = -10
           else if (ldgcol < n) then
              info = -19
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALSA',-info)
              return
           end if
           ! book-keeping and  setting up the computation tree.
           inode = 1
           ndiml = inode + n
           ndimr = ndiml + n
           call la_${ci}$lasdt(n,nlvl,nd,iwork(inode),iwork(ndiml),iwork(ndimr),smlsiz &
                     )
           ! the following code applies back the left singular vector factors.
           ! for applying back the right singular vector factors, go to 170.
           if (icompq == 1) then
              go to 170
           end if
           ! the nodes on the bottom level of the tree were solved
           ! by la_${ci}$lasdq. the corresponding left and right singular vector
           ! matrices are in explicit form. first apply back the left
           ! singular vector matrices.
           ndb1 = (nd + 1)/2
           loop_130: do i = ndb1,nd
              ! ic : center row of each node
              ! nl : number of rows of left  subproblem
              ! nr : number of rows of right subproblem
              ! nlf: starting row of the left   subproblem
              ! nrf: starting row of the right  subproblem
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nr = iwork(ndimr + i1)
              nlf = ic - nl
              nrf = ic + 1
              ! since b and bx are complex, the following call to la_${ci}$gemm
              ! is performed in two steps (real and imaginary parts).
              ! call la_${ci}$gemm( 't', 'n', nl, nrhs, nl, one, u( nlf, 1 ), ldu,
           ! $               b( nlf, 1 ), ldb, zero, bx( nlf, 1 ), ldbx )
              j = nl*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nl - 1
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',nl,nrhs,nl,one,u(nlf,1),ldu,rwork(1 + nl*nrhs*2 &
                        ),nl,zero,rwork(1),nl)
              j = nl*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nl - 1
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',nl,nrhs,nl,one,u(nlf,1),ldu,rwork(1 + nl*nrhs*2 &
                        ),nl,zero,rwork(1 + nl*nrhs),nl)
              jreal = 0
              jimag = nl*nrhs
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nl - 1
                    jreal = jreal + 1
                    jimag = jimag + 1
                    bx(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
              ! since b and bx are complex, the following call to la_${ci}$gemm
              ! is performed in two steps (real and imaginary parts).
              ! call la_${ci}$gemm( 't', 'n', nr, nrhs, nr, one, u( nrf, 1 ), ldu,
          ! $               b( nrf, 1 ), ldb, zero, bx( nrf, 1 ), ldbx )
              j = nr*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nr - 1
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',nr,nrhs,nr,one,u(nrf,1),ldu,rwork(1 + nr*nrhs*2 &
                        ),nr,zero,rwork(1),nr)
              j = nr*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nr - 1
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',nr,nrhs,nr,one,u(nrf,1),ldu,rwork(1 + nr*nrhs*2 &
                        ),nr,zero,rwork(1 + nr*nrhs),nr)
              jreal = 0
              jimag = nr*nrhs
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nr - 1
                    jreal = jreal + 1
                    jimag = jimag + 1
                    bx(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
           end do loop_130
           ! next copy the rows of b that correspond to unchanged rows
           ! in the bidiagonal matrix to bx.
           do i = 1,nd
              ic = iwork(inode + i - 1)
              call la_${ri}$copy(nrhs,b(ic,1),ldb,bx(ic,1),ldbx)
           end do
           ! finally go through the left singular vector matrices of all
           ! the other subproblems bottom-up on the tree.
           j = 2**nlvl
           sqre = 0
           do lvl = nlvl,1,-1
              lvl2 = 2*lvl - 1
              ! find the first node lf and last node ll on
              ! the current level lvl
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              do i = lf,ll
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 nrf = ic + 1
                 j = j - 1
                 call la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,bx(nlf,1),ldbx,b(nlf,1), &
                 ldb,perm(nlf,lvl),givptr(j),givcol(nlf,lvl2),ldgcol,givnum(nlf,lvl2 &
                 ),ldu,poles(nlf,lvl2),difl(nlf,lvl),difr(nlf,lvl2),z(nlf,lvl),k( &
                           j),c(j),s(j),rwork,info)
              end do
           end do
           go to 330
           ! icompq = 1: applying back the right singular vector factors.
           170 continue
           ! first now go through the right singular vector matrices of all
           ! the tree nodes top-down.
           j = 0
           loop_190: do lvl = 1,nlvl
              lvl2 = 2*lvl - 1
              ! find the first node lf and last node ll on
              ! the current level lvl.
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              do i = ll,lf,-1
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 nrf = ic + 1
                 if (i == ll) then
                    sqre = 0
                 else
                    sqre = 1
                 end if
                 j = j + 1
                 call la_${ri}$lals0(icompq,nl,nr,sqre,nrhs,b(nlf,1),ldb,bx(nlf,1), &
                 ldbx,perm(nlf,lvl),givptr(j),givcol(nlf,lvl2),ldgcol,givnum(nlf, &
                 lvl2),ldu,poles(nlf,lvl2),difl(nlf,lvl),difr(nlf,lvl2),z(nlf,lvl) &
                           ,k(j),c(j),s(j),rwork,info)
              end do
           end do loop_190
           ! the nodes on the bottom level of the tree were solved
           ! by la_${ci}$lasdq. the corresponding right singular vector
           ! matrices are in explicit form. apply them back.
           ndb1 = (nd + 1)/2
           loop_320: do i = ndb1,nd
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nr = iwork(ndimr + i1)
              nlp1 = nl + 1
              if (i == nd) then
                 nrp1 = nr
              else
                 nrp1 = nr + 1
              end if
              nlf = ic - nl
              nrf = ic + 1
              ! since b and bx are complex, the following call to la_${ci}$gemm is
              ! performed in two steps (real and imaginary parts).
              ! call la_${ci}$gemm( 't', 'n', nlp1, nrhs, nlp1, one, vt( nlf, 1 ), ldu,
          ! $               b( nlf, 1 ), ldb, zero, bx( nlf, 1 ), ldbx )
              j = nlp1*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nlp1 - 1
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',nlp1,nrhs,nlp1,one,vt(nlf,1),ldu,rwork(1 + &
                        nlp1*nrhs*2),nlp1,zero,rwork(1),nlp1)
              j = nlp1*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nlp1 - 1
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',nlp1,nrhs,nlp1,one,vt(nlf,1),ldu,rwork(1 + &
                        nlp1*nrhs*2),nlp1,zero,rwork(1 + nlp1*nrhs),nlp1)
              jreal = 0
              jimag = nlp1*nrhs
              do jcol = 1,nrhs
                 do jrow = nlf,nlf + nlp1 - 1
                    jreal = jreal + 1
                    jimag = jimag + 1
                    bx(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
              ! since b and bx are complex, the following call to la_${ci}$gemm is
              ! performed in two steps (real and imaginary parts).
              ! call la_${ci}$gemm( 't', 'n', nrp1, nrhs, nrp1, one, vt( nrf, 1 ), ldu,
          ! $               b( nrf, 1 ), ldb, zero, bx( nrf, 1 ), ldbx )
              j = nrp1*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nrp1 - 1
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',nrp1,nrhs,nrp1,one,vt(nrf,1),ldu,rwork(1 + &
                        nrp1*nrhs*2),nrp1,zero,rwork(1),nrp1)
              j = nrp1*nrhs*2
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nrp1 - 1
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',nrp1,nrhs,nrp1,one,vt(nrf,1),ldu,rwork(1 + &
                        nrp1*nrhs*2),nrp1,zero,rwork(1 + nrp1*nrhs),nrp1)
              jreal = 0
              jimag = nrp1*nrhs
              do jcol = 1,nrhs
                 do jrow = nrf,nrf + nrp1 - 1
                    jreal = jreal + 1
                    jimag = jimag + 1
                    bx(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
           end do loop_320
           330 continue
           return
     end subroutine la_${ri}$lalsa
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LALSD: uses the singular value decomposition of A to solve the least
     !> squares problem of finding X to minimize the Euclidean norm of each
     !> column of A*X-B, where A is N-by-N upper bidiagonal, and X and B
     !> are N-by-NRHS. The solution X overwrites B.
     !> The singular values of A smaller than RCOND times the largest
     !> singular value are treated as zero in solving the least squares
     !> problem; in this case a minimum norm solution is returned.
     !> The actual singular values are returned in D in ascending order.
     !> This code makes very mild assumptions about floating point
     !> arithmetic. It will work on machines with a guard digit in
     !> add/subtract, or on those binary machines without guard digits
     !> which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2.
     !> It could conceivably fail on hexadecimal or decimal machines
     !> without guard digits, but we know of none.

     pure subroutine la_${ri}$lalsd(uplo,smlsiz,n,nrhs,d,e,b,ldb,rcond,rank,work,rwork, &
               iwork,info)
        use la_constants_${rk}$,only:zero,one,two,czero
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info,rank
           integer(ilp),intent(in) :: ldb,n,nrhs,smlsiz
           real(${rk}$),intent(in) :: rcond
           ! Array Arguments
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: d(*),e(*)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: bx,bxst,c,difl,difr,givcol,givnum,givptr,i,icmpq1,icmpq2, &
           irwb,irwib,irwrb,irwu,irwvt,irwwrk,iwk,j,jcol,jimag,jreal,jrow,k,nlvl, &
           nm1,nrwork,nsize,nsub,perm,poles,s,sizei,smlszp,sqre,st,st1,u,vt, &
                     z
#:if rk == "sp"
           real(${rk}$) :: cs,eps,orgnrm,r,rcnd,sn,tol
#:else
           real(${rk}$) :: cs,eps,orgnrm,rcnd,r,sn,tol
#:endif
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,cmplx,int,log,real,sign
#:else
           intrinsic :: abs,real,cmplx,aimag,int,log,sign
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -3
           else if (nrhs < 1) then
              info = -4
           else if ((ldb < 1) .or. (ldb < n)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LALSD',-info)
              return
           end if
           eps = la_${ci}$lamch('EPSILON')
           ! set up the tolerance.
           if ((rcond <= zero) .or. (rcond >= one)) then
              rcnd = eps
           else
              rcnd = rcond
           end if
           rank = 0
           ! quick return if possible.
           if (n == 0) then
              return
           else if (n == 1) then
              if (d(1) == zero) then
                 call la_${ri}$laset('A',1,nrhs,czero,czero,b,ldb)
              else
                 rank = 1
                 call la_${ri}$lascl('G',0,0,d(1),one,1,nrhs,b,ldb,info)
                 d(1) = abs(d(1))
              end if
              return
           end if
           ! rotate the matrix if it is lower bidiagonal.
           if (uplo == 'L') then
              do i = 1,n - 1
                 call la_${ci}$lartg(d(i),e(i),cs,sn,r)
                 d(i) = r
                 e(i) = sn*d(i + 1)
                 d(i + 1) = cs*d(i + 1)
                 if (nrhs == 1) then
                    call la_${ri}$${ci}$rot(1,b(i,1),1,b(i + 1,1),1,cs,sn)
                 else
                    rwork(i*2 - 1) = cs
                    rwork(i*2) = sn
                 end if
              end do
              if (nrhs > 1) then
                 do i = 1,nrhs
                    do j = 1,n - 1
                       cs = rwork(j*2 - 1)
                       sn = rwork(j*2)
                       call la_${ri}$${ci}$rot(1,b(j,i),1,b(j + 1,i),1,cs,sn)
                    end do
                 end do
              end if
           end if
           ! scale.
           nm1 = n - 1
           orgnrm = la_${ci}$lanst('M',n,d,e)
           if (orgnrm == zero) then
              call la_${ri}$laset('A',n,nrhs,czero,czero,b,ldb)
              return
           end if
           call la_${ci}$lascl('G',0,0,orgnrm,one,n,1,d,n,info)
           call la_${ci}$lascl('G',0,0,orgnrm,one,nm1,1,e,nm1,info)
           ! if n is smaller than the minimum divide size smlsiz, then solve
           ! the problem with another solver.
           if (n <= smlsiz) then
              irwu = 1
              irwvt = irwu + n*n
              irwwrk = irwvt + n*n
              irwrb = irwwrk
              irwib = irwrb + n*nrhs
              irwb = irwib + n*nrhs
              call la_${ci}$laset('A',n,n,zero,one,rwork(irwu),n)
              call la_${ci}$laset('A',n,n,zero,one,rwork(irwvt),n)
              call la_${ci}$lasdq('U',0,n,n,n,0,d,e,rwork(irwvt),n,rwork(irwu),n, &
                        rwork(irwwrk),1,rwork(irwwrk),info)
              if (info /= 0) then
                 return
              end if
              ! in the real version, b is passed to la_${ci}$lasdq and multiplied
              ! internally by q**h. here b is complex and that product is
              ! computed below in two steps (real and imaginary parts).
              j = irwb - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',n,nrhs,n,one,rwork(irwu),n,rwork(irwb),n, &
                        zero,rwork(irwrb),n)
              j = irwb - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',n,nrhs,n,one,rwork(irwu),n,rwork(irwb),n, &
                        zero,rwork(irwib),n)
              jreal = irwrb - 1
              jimag = irwib - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    jreal = jreal + 1
                    jimag = jimag + 1
                    b(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
              tol = rcnd*abs(d(la_i${ci}$amax(n,d,1)))
              do i = 1,n
                 if (d(i) <= tol) then
                    call la_${ri}$laset('A',1,nrhs,czero,czero,b(i,1),ldb)
                 else
                    call la_${ri}$lascl('G',0,0,d(i),one,1,nrhs,b(i,1),ldb,info)

                    rank = rank + 1
                 end if
              end do
              ! since b is complex, the following call to la_${ci}$gemm is performed
              ! in two steps (real and imaginary parts). that is for v * b
              ! (in the real version of the code v**h is stored in work).
              ! call la_${ci}$gemm( 't', 'n', n, nrhs, n, one, work, n, b, ldb, zero,
          ! $               work( nwork ), n )
              j = irwb - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    j = j + 1
                    rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                 end do
              end do
              call la_${ci}$gemm('T','N',n,nrhs,n,one,rwork(irwvt),n,rwork(irwb),n, &
                        zero,rwork(irwrb),n)
              j = irwb - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    j = j + 1
                    rwork(j) = aimag(b(jrow,jcol))
                 end do
              end do
              call la_${ci}$gemm('T','N',n,nrhs,n,one,rwork(irwvt),n,rwork(irwb),n, &
                        zero,rwork(irwib),n)
              jreal = irwrb - 1
              jimag = irwib - 1
              do jcol = 1,nrhs
                 do jrow = 1,n
                    jreal = jreal + 1
                    jimag = jimag + 1
                    b(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                 end do
              end do
              ! unscale.
              call la_${ci}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
              call la_${ci}$lasrt('D',n,d,info)
              call la_${ri}$lascl('G',0,0,orgnrm,one,n,nrhs,b,ldb,info)
              return
           end if
           ! book-keeping and setting up some constants.
           nlvl = int(log(real(n,KIND=${rk}$)/real(smlsiz + 1,KIND=${rk}$))/log(two),KIND=ilp) + &
                     1
           smlszp = smlsiz + 1
           u = 1
           vt = 1 + smlsiz*n
           difl = vt + smlszp*n
           difr = difl + nlvl*n
           z = difr + nlvl*n*2
           c = z + nlvl*n
           s = c + n
           poles = s + n
           givnum = poles + 2*nlvl*n
           nrwork = givnum + 2*nlvl*n
           bx = 1
           irwrb = nrwork
           irwib = irwrb + smlsiz*nrhs
           irwb = irwib + smlsiz*nrhs
           sizei = 1 + n
           k = sizei + n
           givptr = k + n
           perm = givptr + n
           givcol = perm + nlvl*n
           iwk = givcol + nlvl*n*2
           st = 1
           sqre = 0
           icmpq1 = 1
           icmpq2 = 0
           nsub = 0
           do i = 1,n
              if (abs(d(i)) < eps) then
                 d(i) = sign(eps,d(i))
              end if
           end do
           loop_240: do i = 1,nm1
              if ((abs(e(i)) < eps) .or. (i == nm1)) then
                 nsub = nsub + 1
                 iwork(nsub) = st
                 ! subproblem found. first determine its size and then
                 ! apply divide and conquer on it.
                 if (i < nm1) then
                    ! a subproblem with e(i) small for i < nm1.
                    nsize = i - st + 1
                    iwork(sizei + nsub - 1) = nsize
                 else if (abs(e(i)) >= eps) then
                    ! a subproblem with e(nm1) not too small but i = nm1.
                    nsize = n - st + 1
                    iwork(sizei + nsub - 1) = nsize
                 else
                    ! a subproblem with e(nm1) small. this implies an
                    ! 1-by-1 subproblem at d(n), which is not solved
                    ! explicitly.
                    nsize = i - st + 1
                    iwork(sizei + nsub - 1) = nsize
                    nsub = nsub + 1
                    iwork(nsub) = n
                    iwork(sizei + nsub - 1) = 1
                    call la_${ri}$copy(nrhs,b(n,1),ldb,work(bx + nm1),n)
                 end if
                 st1 = st - 1
                 if (nsize == 1) then
                    ! this is a 1-by-1 subproblem and is not solved
                    ! explicitly.
                    call la_${ri}$copy(nrhs,b(st,1),ldb,work(bx + st1),n)
                 else if (nsize <= smlsiz) then
                    ! this is a small subproblem and is solved by la_${ci}$lasdq.
                    call la_${ci}$laset('A',nsize,nsize,zero,one,rwork(vt + st1),n)
                    call la_${ci}$laset('A',nsize,nsize,zero,one,rwork(u + st1),n)
                    call la_${ci}$lasdq('U',0,nsize,nsize,nsize,0,d(st),e(st),rwork( &
                    vt + st1),n,rwork(u + st1),n,rwork(nrwork),1,rwork(nrwork),info)

                    if (info /= 0) then
                       return
                    end if
                    ! in the real version, b is passed to la_${ci}$lasdq and multiplied
                    ! internally by q**h. here b is complex and that product is
                    ! computed below in two steps (real and imaginary parts).
                    j = irwb - 1
                    do jcol = 1,nrhs
                       do jrow = st,st + nsize - 1
                          j = j + 1
                          rwork(j) = real(b(jrow,jcol),KIND=${rk}$)
                       end do
                    end do
                    call la_${ci}$gemm('T','N',nsize,nrhs,nsize,one,rwork(u + st1),n,rwork( &
                               irwb),nsize,zero,rwork(irwrb),nsize)
                    j = irwb - 1
                    do jcol = 1,nrhs
                       do jrow = st,st + nsize - 1
                          j = j + 1
                          rwork(j) = aimag(b(jrow,jcol))
                       end do
                    end do
                    call la_${ci}$gemm('T','N',nsize,nrhs,nsize,one,rwork(u + st1),n,rwork( &
                               irwb),nsize,zero,rwork(irwib),nsize)
                    jreal = irwrb - 1
                    jimag = irwib - 1
                    do jcol = 1,nrhs
                       do jrow = st,st + nsize - 1
                          jreal = jreal + 1
                          jimag = jimag + 1
                          b(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                       end do
                    end do
                    call la_${ri}$lacpy('A',nsize,nrhs,b(st,1),ldb,work(bx + st1),n)

                 else
                    ! a large problem. solve it using divide and conquer.
                    call la_${ci}$lasda(icmpq1,smlsiz,nsize,sqre,d(st),e(st),rwork(u + &
                    st1),n,rwork(vt + st1),iwork(k + st1),rwork(difl + st1),rwork(difr + st1), &
                     rwork(z + st1),rwork(poles + st1),iwork(givptr + st1),iwork(givcol + st1), &
                     n,iwork(perm + st1),rwork(givnum + st1),rwork(c + st1),rwork(s + st1), &
                               rwork(nrwork),iwork(iwk),info)
                    if (info /= 0) then
                       return
                    end if
                    bxst = bx + st1
                    call la_${ri}$lalsa(icmpq2,smlsiz,nsize,nrhs,b(st,1),ldb,work(bxst), &
                     n,rwork(u + st1),n,rwork(vt + st1),iwork(k + st1),rwork(difl + st1), &
                     rwork(difr + st1),rwork(z + st1),rwork(poles + st1),iwork(givptr + st1), &
                     iwork(givcol + st1),n,iwork(perm + st1),rwork(givnum + st1),rwork(c + st1), &
                                rwork(s + st1),rwork(nrwork),iwork(iwk),info)
                    if (info /= 0) then
                       return
                    end if
                 end if
                 st = i + 1
              end if
           end do loop_240
           ! apply the singular values and treat the tiny ones as zero.
           tol = rcnd*abs(d(la_i${ci}$amax(n,d,1)))
           do i = 1,n
              ! some of the elements in d can be negative because 1-by-1
              ! subproblems were not solved explicitly.
              if (abs(d(i)) <= tol) then
                 call la_${ri}$laset('A',1,nrhs,czero,czero,work(bx + i - 1),n)
              else
                 rank = rank + 1
                 call la_${ri}$lascl('G',0,0,d(i),one,1,nrhs,work(bx + i - 1),n,info)

              end if
              d(i) = abs(d(i))
           end do
           ! now apply back the right singular vectors.
           icmpq2 = 1
           loop_320: do i = 1,nsub
              st = iwork(i)
              st1 = st - 1
              nsize = iwork(sizei + i - 1)
              bxst = bx + st1
              if (nsize == 1) then
                 call la_${ri}$copy(nrhs,work(bxst),n,b(st,1),ldb)
              else if (nsize <= smlsiz) then
                 ! since b and bx are complex, the following call to la_${ci}$gemm
                 ! is performed in two steps (real and imaginary parts).
                 ! call la_${ci}$gemm( 't', 'n', nsize, nrhs, nsize, one,
          ! $                  rwork( vt+st1 ), n, rwork( bxst ), n, zero,
          ! $                  b( st, 1 ), ldb )
                 j = bxst - n - 1
                 jreal = irwb - 1
                 do jcol = 1,nrhs
                    j = j + n
                    do jrow = 1,nsize
                       jreal = jreal + 1
                       rwork(jreal) = real(work(j + jrow),KIND=${rk}$)
                    end do
                 end do
                 call la_${ci}$gemm('T','N',nsize,nrhs,nsize,one,rwork(vt + st1),n,rwork( &
                           irwb),nsize,zero,rwork(irwrb),nsize)
                 j = bxst - n - 1
                 jimag = irwb - 1
                 do jcol = 1,nrhs
                    j = j + n
                    do jrow = 1,nsize
                       jimag = jimag + 1
                       rwork(jimag) = aimag(work(j + jrow))
                    end do
                 end do
                 call la_${ci}$gemm('T','N',nsize,nrhs,nsize,one,rwork(vt + st1),n,rwork( &
                           irwb),nsize,zero,rwork(irwib),nsize)
                 jreal = irwrb - 1
                 jimag = irwib - 1
                 do jcol = 1,nrhs
                    do jrow = st,st + nsize - 1
                       jreal = jreal + 1
                       jimag = jimag + 1
                       b(jrow,jcol) = cmplx(rwork(jreal),rwork(jimag),KIND=${rk}$)
                    end do
                 end do
              else
                 call la_${ri}$lalsa(icmpq2,smlsiz,nsize,nrhs,work(bxst),n,b(st,1),ldb, &
                  rwork(u + st1),n,rwork(vt + st1),iwork(k + st1),rwork(difl + st1),rwork( &
                  difr + st1),rwork(z + st1),rwork(poles + st1),iwork(givptr + st1),iwork( &
                  givcol + st1),n,iwork(perm + st1),rwork(givnum + st1),rwork(c + st1),rwork(s + &
                            st1),rwork(nrwork),iwork(iwk),info)
                 if (info /= 0) then
                    return
                 end if
              end if
           end do loop_320
           ! unscale and sort the singular values.
           call la_${ci}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
           call la_${ci}$lasrt('D',n,d,info)
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,nrhs,b,ldb,info)
           return
     end subroutine la_${ri}$lalsd
#:endfor

end module la_lapack_lsq_aux
