#:include "common.fypp"
!> Constrained least squares: equality constraints and the general Gauss-Markov model
module la_lapack_lsq_constrained
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level2_gen
     use la_blas_level2_tri
     use la_lapack_aux
     use la_lapack_orthogonal_factors_qr
     use la_lapack_solve_tri_comp
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     public :: la_${ri}$ggglm
     public :: la_${ri}$gglse
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     public :: la_${ri}$ggglm
     public :: la_${ri}$gglse
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$GGGLM: solves a general Gauss-Markov linear model (GLM) problem:
     !> minimize || y ||_2   subject to   d = A*x + B*y
     !> x
     !> where A is an N-by-M matrix, B is an N-by-P matrix, and d is a
     !> given N-vector. It is assumed that M <= N <= M+P, and
     !> rank(A) = M    and    rank( A B ) = N.
     !> Under these assumptions, the constrained equation is always
     !> consistent, and there is a unique solution x and a minimal 2-norm
     !> solution y, which is obtained using a generalized QR factorization
     !> of the matrices (A, B) given by
     !> A = Q*(R),   B = Q*T*Z.
     !> (0)
     !> In particular, if matrix B is square nonsingular, then the problem
     !> GLM is equivalent to the following weighted linear least squares
     !> problem
     !> minimize || inv(B)*(d-A*x) ||_2
     !> x
     !> where inv(B) denotes the inverse of B.

     pure subroutine la_${ri}$ggglm(n,m,p,a,lda,b,ldb,d,x,y,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,lwork,m,n,p
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*),b(ldb,*),d(*)
           real(${rk}$),intent(out) :: work(*),x(*),y(*)
        ! ===================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: i,lopt,lwkmin,lwkopt,nb,nb1,nb2,nb3,nb4,np
           ! Intrinsic Functions
           intrinsic :: int,max,min
           ! Executable Statements
           ! test the input parameters
           info = 0
           np = min(n,p)
           lquery = (lwork == -1)
           if (n < 0) then
              info = -1
           else if (m < 0 .or. m > n) then
              info = -2
           else if (p < 0 .or. p < n - m) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldb < max(1,n)) then
              info = -7
           end if
           ! calculate workspace
           if (info == 0) then
              if (n == 0) then
                 lwkmin = 1
                 lwkopt = 1
              else
                 nb1 = la_ilaenv(1,'${ri.upper()}$GEQRF',' ',n,m,-1,-1)
                 nb2 = la_ilaenv(1,'${ri.upper()}$GERQF',' ',n,m,-1,-1)
                 nb3 = la_ilaenv(1,'${ri.upper()}$ORMQR',' ',n,m,p,-1)
                 nb4 = la_ilaenv(1,'${ri.upper()}$ORMRQ',' ',n,m,p,-1)
                 nb = max(nb1,nb2,nb3,nb4)
                 lwkmin = m + n + p
                 lwkopt = m + np + max(n,p)*nb
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -12
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GGGLM',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (n == 0) then
              do i = 1,m
                 x(i) = zero
              end do
              do i = 1,p
                 y(i) = zero
              end do
              return
           end if
           ! compute the gqr factorization of matrices a and b:
                ! q**t*a = ( r11 ) m,    q**t*b*z**t = ( t11   t12 ) m
                         ! (  0  ) n-m                 (  0    t22 ) n-m
                            ! m                         m+p-n  n-m
           ! where r11 and t22 are upper triangular, and q and z are
           ! orthogonal.
           call la_${ri}$ggqrf(n,m,p,a,lda,work,b,ldb,work(m + 1),work(m + np + 1),lwork - m - &
                     np,info)
           lopt = work(m + np + 1)
           ! update left-hand-side vector d = q**t*d = ( d1 ) m
                                                     ! ( d2 ) n-m
           call la_${ri}$ormqr('LEFT','TRANSPOSE',n,1,m,a,lda,work,d,max(1,n),work(m + &
                     np + 1),lwork - m - np,info)
           lopt = max(lopt,int(work(m + np + 1),KIND=ilp))
           ! solve t22*y2 = d2 for y2
           if (n > m) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON UNIT',n - m,1,b(m + 1,m + p - n + 1), &
                        ldb,d(m + 1),n - m,info)
              if (info > 0) then
                 info = 1
                 return
              end if
              call la_${ri}$copy(n - m,d(m + 1),1,y(m + p - n + 1),1)
           end if
           ! set y1 = 0
           do i = 1,m + p - n
              y(i) = zero
           end do
           ! update d1 = d1 - t12*y2
           call la_${ri}$gemv('NO TRANSPOSE',m,n - m,-one,b(1,m + p - n + 1),ldb,y(m + p - n + 1),1, &
                     one,d,1)
           ! solve triangular system: r11*x = d1
           if (m > 0) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON UNIT',m,1,a,lda,d,m,info)

              if (info > 0) then
                 info = 2
                 return
              end if
              ! copy d to x
              call la_${ri}$copy(m,d,1,x,1)
           end if
           ! backward transformation y = z**t *y
           call la_${ri}$ormrq('LEFT','TRANSPOSE',p,1,np,b(max(1,n - p + 1),1),ldb,work( &
                     m + 1),y,max(1,p),work(m + np + 1),lwork - m - np,info)
           work(1) = m + np + max(lopt,int(work(m + np + 1),KIND=ilp))
           return
     end subroutine la_${ri}$ggglm
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$GGLSE: solves the linear equality-constrained least squares (LSE)
     !> problem:
     !> minimize || c - A*x ||_2   subject to   B*x = d
     !> where A is an M-by-N matrix, B is a P-by-N matrix, c is a given
     !> M-vector, and d is a given P-vector. It is assumed that
     !> P <= N <= M+P, and
     !> rank(B) = P and  rank( (A) ) = N.
     !> ( (B) )
     !> These conditions ensure that the LSE problem has a unique solution,
     !> which is obtained using a generalized RQ factorization of the
     !> matrices (B, A) given by
     !> B = (0 R)*Q,   A = Z*T*Q.

     pure subroutine la_${ri}$gglse(m,n,p,a,lda,b,ldb,c,d,x,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,lwork,m,n,p
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*),b(ldb,*),c(*),d(*)
           real(${rk}$),intent(out) :: work(*),x(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: lopt,lwkmin,lwkopt,mn,nb,nb1,nb2,nb3,nb4,nr
           ! Intrinsic Functions
           intrinsic :: int,max,min
           ! Executable Statements
           ! test the input parameters
           info = 0
           mn = min(m,n)
           lquery = (lwork == -1)
           if (m < 0) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (p < 0 .or. p > n .or. p < n - m) then
              info = -3
           else if (lda < max(1,m)) then
              info = -5
           else if (ldb < max(1,p)) then
              info = -7
           end if
           ! calculate workspace
           if (info == 0) then
              if (n == 0) then
                 lwkmin = 1
                 lwkopt = 1
              else
                 nb1 = la_ilaenv(1,'${ri.upper()}$GEQRF',' ',m,n,-1,-1)
                 nb2 = la_ilaenv(1,'${ri.upper()}$GERQF',' ',m,n,-1,-1)
                 nb3 = la_ilaenv(1,'${ri.upper()}$ORMQR',' ',m,n,p,-1)
                 nb4 = la_ilaenv(1,'${ri.upper()}$ORMRQ',' ',m,n,p,-1)
                 nb = max(nb1,nb2,nb3,nb4)
                 lwkmin = m + n + p
                 lwkopt = p + mn + max(m,n)*nb
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -12
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GGLSE',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (n == 0) return
           ! compute the grq factorization of matrices b and a:
                  ! b*q**t = (  0  t12 ) p   z**t*a*q**t = ( r11 r12 ) n-p
                              ! n-p  p                     (  0  r22 ) m+p-n
                                                            ! n-p  p
           ! where t12 and r11 are upper triangular, and q and z are
           ! orthogonal.
           call la_${ri}$ggrqf(p,m,n,b,ldb,work,a,lda,work(p + 1),work(p + mn + 1),lwork - p - &
                     mn,info)
           lopt = work(p + mn + 1)
           ! update c = z**t *c = ( c1 ) n-p
                                ! ( c2 ) m+p-n
           call la_${ri}$ormqr('LEFT','TRANSPOSE',m,1,mn,a,lda,work(p + 1),c,max(1,m), &
                     work(p + mn + 1),lwork - p - mn,info)
           lopt = max(lopt,int(work(p + mn + 1),KIND=ilp))
           ! solve t12*x2 = d for x2
           if (p > 0) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON-UNIT',p,1,b(1,n - p + 1),ldb,d, &
                         p,info)
              if (info > 0) then
                 info = 1
                 return
              end if
              ! put the solution in x
              call la_${ri}$copy(p,d,1,x(n - p + 1),1)
              ! update c1
              call la_${ri}$gemv('NO TRANSPOSE',n - p,p,-one,a(1,n - p + 1),lda,d,1,one,c,1 &
                        )
           end if
           ! solve r11*x1 = c1 for x1
           if (n > p) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON-UNIT',n - p,1,a,lda,c,n - p, &
                        info)
              if (info > 0) then
                 info = 2
                 return
              end if
              ! put the solutions in x
              call la_${ri}$copy(n - p,c,1,x,1)
           end if
           ! compute the residual vector:
           if (m < n) then
              nr = m + p - n
              if (nr > 0) call la_${ri}$gemv('NO TRANSPOSE',nr,n - m,-one,a(n - p + 1,m + 1),lda,d( &
                        nr + 1),1,one,c(n - p + 1),1)
           else
              nr = p
           end if
           if (nr > 0) then
              call la_${ri}$trmv('UPPER','NO TRANSPOSE','NON UNIT',nr,a(n - p + 1,n - p + 1),lda, &
                        d,1)
              call la_${ri}$axpy(nr,-one,d,1,c(n - p + 1),1)
           end if
           ! backward transformation x = q**t*x
           call la_${ri}$ormrq('LEFT','TRANSPOSE',n,1,p,b,ldb,work(1),x,n,work(p + mn + 1 &
                     ),lwork - p - mn,info)
           work(1) = p + mn + max(lopt,int(work(p + mn + 1),KIND=ilp))
           return
     end subroutine la_${ri}$gglse
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$GGGLM: solves a general Gauss-Markov linear model (GLM) problem:
     !> minimize || y ||_2   subject to   d = A*x + B*y
     !> x
     !> where A is an N-by-M matrix, B is an N-by-P matrix, and d is a
     !> given N-vector. It is assumed that M <= N <= M+P, and
     !> rank(A) = M    and    rank( A B ) = N.
     !> Under these assumptions, the constrained equation is always
     !> consistent, and there is a unique solution x and a minimal 2-norm
     !> solution y, which is obtained using a generalized QR factorization
     !> of the matrices (A, B) given by
     !> A = Q*(R),   B = Q*T*Z.
     !> (0)
     !> In particular, if matrix B is square nonsingular, then the problem
     !> GLM is equivalent to the following weighted linear least squares
     !> problem
     !> minimize || inv(B)*(d-A*x) ||_2
     !> x
     !> where inv(B) denotes the inverse of B.

     pure subroutine la_${ri}$ggglm(n,m,p,a,lda,b,ldb,d,x,y,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,lwork,m,n,p
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,*),b(ldb,*),d(*)
           complex(${rk}$),intent(out) :: work(*),x(*),y(*)
        ! ===================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: i,lopt,lwkmin,lwkopt,nb,nb1,nb2,nb3,nb4,np
           ! Intrinsic Functions
           intrinsic :: int,max,min
           ! Executable Statements
           ! test the input parameters
           info = 0
           np = min(n,p)
           lquery = (lwork == -1)
           if (n < 0) then
              info = -1
           else if (m < 0 .or. m > n) then
              info = -2
           else if (p < 0 .or. p < n - m) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldb < max(1,n)) then
              info = -7
           end if
           ! calculate workspace
           if (info == 0) then
              if (n == 0) then
                 lwkmin = 1
                 lwkopt = 1
              else
                 nb1 = la_ilaenv(1,'${ri.upper()}$GEQRF',' ',n,m,-1,-1)
                 nb2 = la_ilaenv(1,'${ri.upper()}$GERQF',' ',n,m,-1,-1)
                 nb3 = la_ilaenv(1,'${ri.upper()}$UNMQR',' ',n,m,p,-1)
                 nb4 = la_ilaenv(1,'${ri.upper()}$UNMRQ',' ',n,m,p,-1)
                 nb = max(nb1,nb2,nb3,nb4)
                 lwkmin = m + n + p
                 lwkopt = m + np + max(n,p)*nb
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -12
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GGGLM',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (n == 0) then
              do i = 1,m
                 x(i) = czero
              end do
              do i = 1,p
                 y(i) = czero
              end do
              return
           end if
           ! compute the gqr factorization of matrices a and b:
                ! q**h*a = ( r11 ) m,    q**h*b*z**h = ( t11   t12 ) m
                         ! (  0  ) n-m                 (  0    t22 ) n-m
                            ! m                         m+p-n  n-m
           ! where r11 and t22 are upper triangular, and q and z are
           ! unitary.
           call la_${ri}$ggqrf(n,m,p,a,lda,work,b,ldb,work(m + 1),work(m + np + 1),lwork - m - &
                     np,info)
           lopt = real(work(m + np + 1),KIND=${rk}$)
           ! update left-hand-side vector d = q**h*d = ( d1 ) m
                                                     ! ( d2 ) n-m
           call la_${ri}$unmqr('LEFT','CONJUGATE TRANSPOSE',n,1,m,a,lda,work,d,max(1,n) &
                     ,work(m + np + 1),lwork - m - np,info)
           lopt = max(lopt,int(work(m + np + 1),KIND=ilp))
           ! solve t22*y2 = d2 for y2
           if (n > m) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON UNIT',n - m,1,b(m + 1,m + p - n + 1), &
                        ldb,d(m + 1),n - m,info)
              if (info > 0) then
                 info = 1
                 return
              end if
              call la_${ri}$copy(n - m,d(m + 1),1,y(m + p - n + 1),1)
           end if
           ! set y1 = 0
           do i = 1,m + p - n
              y(i) = czero
           end do
           ! update d1 = d1 - t12*y2
           call la_${ri}$gemv('NO TRANSPOSE',m,n - m,-cone,b(1,m + p - n + 1),ldb,y(m + p - n + 1),1, &
                      cone,d,1)
           ! solve triangular system: r11*x = d1
           if (m > 0) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON UNIT',m,1,a,lda,d,m,info)

              if (info > 0) then
                 info = 2
                 return
              end if
              ! copy d to x
              call la_${ri}$copy(m,d,1,x,1)
           end if
           ! backward transformation y = z**h *y
           call la_${ri}$unmrq('LEFT','CONJUGATE TRANSPOSE',p,1,np,b(max(1,n - p + 1),1), &
                     ldb,work(m + 1),y,max(1,p),work(m + np + 1),lwork - m - np,info)
           work(1) = m + np + max(lopt,int(work(m + np + 1),KIND=ilp))
           return
     end subroutine la_${ri}$ggglm
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$GGLSE: solves the linear equality-constrained least squares (LSE)
     !> problem:
     !> minimize || c - A*x ||_2   subject to   B*x = d
     !> where A is an M-by-N matrix, B is a P-by-N matrix, c is a given
     !> M-vector, and d is a given P-vector. It is assumed that
     !> P <= N <= M+P, and
     !> rank(B) = P and  rank( (A) ) = N.
     !> ( (B) )
     !> These conditions ensure that the LSE problem has a unique solution,
     !> which is obtained using a generalized RQ factorization of the
     !> matrices (B, A) given by
     !> B = (0 R)*Q,   A = Z*T*Q.

     pure subroutine la_${ri}$gglse(m,n,p,a,lda,b,ldb,c,d,x,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,lwork,m,n,p
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,*),b(ldb,*),c(*),d(*)
           complex(${rk}$),intent(out) :: work(*),x(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: lopt,lwkmin,lwkopt,mn,nb,nb1,nb2,nb3,nb4,nr
           ! Intrinsic Functions
           intrinsic :: int,max,min
           ! Executable Statements
           ! test the input parameters
           info = 0
           mn = min(m,n)
           lquery = (lwork == -1)
           if (m < 0) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (p < 0 .or. p > n .or. p < n - m) then
              info = -3
           else if (lda < max(1,m)) then
              info = -5
           else if (ldb < max(1,p)) then
              info = -7
           end if
           ! calculate workspace
           if (info == 0) then
              if (n == 0) then
                 lwkmin = 1
                 lwkopt = 1
              else
                 nb1 = la_ilaenv(1,'${ri.upper()}$GEQRF',' ',m,n,-1,-1)
                 nb2 = la_ilaenv(1,'${ri.upper()}$GERQF',' ',m,n,-1,-1)
                 nb3 = la_ilaenv(1,'${ri.upper()}$UNMQR',' ',m,n,p,-1)
                 nb4 = la_ilaenv(1,'${ri.upper()}$UNMRQ',' ',m,n,p,-1)
                 nb = max(nb1,nb2,nb3,nb4)
                 lwkmin = m + n + p
                 lwkopt = p + mn + max(m,n)*nb
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -12
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GGLSE',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (n == 0) return
           ! compute the grq factorization of matrices b and a:
                  ! b*q**h = (  0  t12 ) p   z**h*a*q**h = ( r11 r12 ) n-p
                              ! n-p  p                     (  0  r22 ) m+p-n
                                                            ! n-p  p
           ! where t12 and r11 are upper triangular, and q and z are
           ! unitary.
           call la_${ri}$ggrqf(p,m,n,b,ldb,work,a,lda,work(p + 1),work(p + mn + 1),lwork - p - &
                     mn,info)
           lopt = real(work(p + mn + 1),KIND=${rk}$)
           ! update c = z**h *c = ( c1 ) n-p
                             ! ( c2 ) m+p-n
           call la_${ri}$unmqr('LEFT','CONJUGATE TRANSPOSE',m,1,mn,a,lda,work(p + 1),c, &
                     max(1,m),work(p + mn + 1),lwork - p - mn,info)
           lopt = max(lopt,int(work(p + mn + 1),KIND=ilp))
           ! solve t12*x2 = d for x2
           if (p > 0) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON-UNIT',p,1,b(1,n - p + 1),ldb,d, &
                         p,info)
              if (info > 0) then
                 info = 1
                 return
              end if
              ! put the solution in x
              call la_${ri}$copy(p,d,1,x(n - p + 1),1)
              ! update c1
              call la_${ri}$gemv('NO TRANSPOSE',n - p,p,-cone,a(1,n - p + 1),lda,d,1,cone,c, &
                        1)
           end if
           ! solve r11*x1 = c1 for x1
           if (n > p) then
              call la_${ri}$trtrs('UPPER','NO TRANSPOSE','NON-UNIT',n - p,1,a,lda,c,n - p, &
                        info)
              if (info > 0) then
                 info = 2
                 return
              end if
              ! put the solutions in x
              call la_${ri}$copy(n - p,c,1,x,1)
           end if
           ! compute the residual vector:
           if (m < n) then
              nr = m + p - n
              if (nr > 0) call la_${ri}$gemv('NO TRANSPOSE',nr,n - m,-cone,a(n - p + 1,m + 1),lda,d( &
                         nr + 1),1,cone,c(n - p + 1),1)
           else
              nr = p
           end if
           if (nr > 0) then
              call la_${ri}$trmv('UPPER','NO TRANSPOSE','NON UNIT',nr,a(n - p + 1,n - p + 1),lda, &
                        d,1)
              call la_${ri}$axpy(nr,-cone,d,1,c(n - p + 1),1)
           end if
           ! backward transformation x = q**h*x
           call la_${ri}$unmrq('LEFT','CONJUGATE TRANSPOSE',n,1,p,b,ldb,work(1),x,n, &
                     work(p + mn + 1),lwork - p - mn,info)
           work(1) = p + mn + max(lopt,int(work(p + mn + 1),KIND=ilp))
           return
     end subroutine la_${ri}$gglse
#:endfor

end module la_lapack_lsq_constrained
