#:include "common.fypp"
!> Bidiagonal singular values by divide and conquer, with its secular-equation and merge kernels
module la_lapack_eigv_svd_bidiag_dc
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level3_gen
     use la_lapack_aux
     use la_lapack_auxiliary
     use la_lapack_blas_like_base
     use la_lapack_blas_like_l2
     use la_lapack_blas_like_mnorm
     use la_lapack_blas_like_scalar
     use la_lapack_eigv_tridiag
     use la_lapack_eigv_tridiag2
     use la_lapack_givens_jacobi_rot
     use la_lapack_svd_bidiag_qr
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     public :: la_${ri}$lasd5
     public :: la_${ri}$lasdt
     public :: la_${ri}$lasd4
     public :: la_${ri}$lasd7
     public :: la_${ri}$lasd8
     public :: la_${ri}$lasd3
     public :: la_${ri}$lasd6
     public :: la_${ri}$lasd2
     public :: la_${ri}$lasd1
     public :: la_${ri}$bdsdc
     public :: la_${ri}$lasd0
     public :: la_${ri}$lasda
     public :: la_${ri}$lasdq
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> This subroutine computes the square root of the I-th eigenvalue
     !> of a positive symmetric rank-one modification of a 2-by-2 diagonal
     !> matrix
     !> diag( D ) * diag( D ) +  RHO * Z * transpose(Z) .
     !> The diagonal entries in the array D are assumed to satisfy
     !> 0 <= D(i) < D(j)  for  i < j .
     !> We also assume RHO > 0 and that the Euclidean norm of the vector
     !> Z is one.

     pure subroutine la_${ri}$lasd5(i,d,z,delta,rho,dsigma,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: i
           real(${rk}$),intent(out) :: dsigma
           real(${rk}$),intent(in) :: rho
           ! Array Arguments
           real(${rk}$),intent(in) :: d(2),z(2)
           real(${rk}$),intent(out) :: delta(2),work(2)
        ! =====================================================================

           ! Local Scalars
           real(${rk}$) :: b,c,del,delsq,tau,w
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           del = d(2) - d(1)
           delsq = del*(d(2) + d(1))
           if (i == 1) then
              w = one + four*rho*(z(2)*z(2)/(d(1) + three*d(2)) - z(1)*z(1)/( &
                        three*d(1) + d(2)))/del
              if (w > zero) then
                 b = delsq + rho*(z(1)*z(1) + z(2)*z(2))
                 c = rho*z(1)*z(1)*delsq
                 ! b > zero, always
                 ! the following tau is dsigma * dsigma - d( 1 ) * d( 1 )
                 tau = two*c/(b + sqrt(abs(b*b - four*c)))
                 ! the following tau is dsigma - d( 1 )
                 tau = tau/(d(1) + sqrt(d(1)*d(1) + tau))
                 dsigma = d(1) + tau
                 delta(1) = -tau
                 delta(2) = del - tau
                 work(1) = two*d(1) + tau
                 work(2) = (d(1) + tau) + d(2)
                 ! delta( 1 ) = -z( 1 ) / tau
                 ! delta( 2 ) = z( 2 ) / ( del-tau )
              else
                 b = -delsq + rho*(z(1)*z(1) + z(2)*z(2))
                 c = rho*z(2)*z(2)*delsq
                 ! the following tau is dsigma * dsigma - d( 2 ) * d( 2 )
                 if (b > zero) then
                    tau = -two*c/(b + sqrt(b*b + four*c))
                 else
                    tau = (b - sqrt(b*b + four*c))/two
                 end if
                 ! the following tau is dsigma - d( 2 )
                 tau = tau/(d(2) + sqrt(abs(d(2)*d(2) + tau)))
                 dsigma = d(2) + tau
                 delta(1) = -(del + tau)
                 delta(2) = -tau
                 work(1) = d(1) + tau + d(2)
                 work(2) = two*d(2) + tau
                 ! delta( 1 ) = -z( 1 ) / ( del+tau )
                 ! delta( 2 ) = -z( 2 ) / tau
              end if
              ! temp = sqrt( delta( 1 )*delta( 1 )+delta( 2 )*delta( 2 ) )
              ! delta( 1 ) = delta( 1 ) / temp
              ! delta( 2 ) = delta( 2 ) / temp
           else
              ! now i=2
              b = -delsq + rho*(z(1)*z(1) + z(2)*z(2))
              c = rho*z(2)*z(2)*delsq
              ! the following tau is dsigma * dsigma - d( 2 ) * d( 2 )
              if (b > zero) then
                 tau = (b + sqrt(b*b + four*c))/two
              else
                 tau = two*c/(-b + sqrt(b*b + four*c))
              end if
              ! the following tau is dsigma - d( 2 )
              tau = tau/(d(2) + sqrt(d(2)*d(2) + tau))
              dsigma = d(2) + tau
              delta(1) = -(del + tau)
              delta(2) = -tau
              work(1) = d(1) + tau + d(2)
              work(2) = two*d(2) + tau
              ! delta( 1 ) = -z( 1 ) / ( del+tau )
              ! delta( 2 ) = -z( 2 ) / tau
              ! temp = sqrt( delta( 1 )*delta( 1 )+delta( 2 )*delta( 2 ) )
              ! delta( 1 ) = delta( 1 ) / temp
              ! delta( 2 ) = delta( 2 ) / temp
           end if
           return
     end subroutine la_${ri}$lasd5
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASDT: creates a tree of subproblems for bidiagonal divide and
     !> conquer.

     pure subroutine la_${ri}$lasdt(n,lvl,nd,inode,ndiml,ndimr,msub)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: lvl,nd
           integer(ilp),intent(in) :: msub,n
           ! Array Arguments
           integer(ilp),intent(out) :: inode(*),ndiml(*),ndimr(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,il,ir,llst,maxn,ncrnt,nlvl
           real(${rk}$) :: temp
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: int,log,max,real
#:else
           intrinsic :: real,int,log,max
#:endif
           ! Executable Statements
           ! find the number of levels on the tree.
           maxn = max(1,n)
           temp = log(real(maxn,KIND=${rk}$)/real(msub + 1,KIND=${rk}$))/log(two)
           lvl = int(temp,KIND=ilp) + 1
           i = n/2
           inode(1) = i + 1
           ndiml(1) = i
           ndimr(1) = n - i - 1
           il = 0
           ir = 1
           llst = 1
           do nlvl = 1,lvl - 1
              ! constructing the tree at (nlvl+1)-st level. the number of
              ! nodes created on this level is llst * 2.
              do i = 0,llst - 1
                 il = il + 2
                 ir = ir + 2
                 ncrnt = llst + i
                 ndiml(il) = ndiml(ncrnt)/2
                 ndimr(il) = ndiml(ncrnt) - ndiml(il) - 1
                 inode(il) = inode(ncrnt) - ndimr(il) - 1
                 ndiml(ir) = ndimr(ncrnt)/2
                 ndimr(ir) = ndimr(ncrnt) - ndiml(ir) - 1
                 inode(ir) = inode(ncrnt) + ndiml(ir) + 1
              end do
              llst = llst*2
           end do
           nd = llst*2 - 1
           return
     end subroutine la_${ri}$lasdt
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> This subroutine computes the square root of the I-th updated
     !> eigenvalue of a positive symmetric rank-one modification to
     !> a positive diagonal matrix whose entries are given as the squares
     !> of the corresponding entries in the array d, and that
     !> 0 <= D(i) < D(j)  for  i < j
     !> and that RHO > 0. This is arranged by the calling routine, and is
     !> no loss in generality.  The rank-one modified system is thus
     !> diag( D ) * diag( D ) +  RHO * Z * Z_transpose.
     !> where we assume the Euclidean norm of Z is 1.
     !> The method consists of approximating the rational functions in the
     !> secular equation by simpler interpolating rational functions.

     pure subroutine la_${ri}$lasd4(n,i,d,z,delta,rho,sigma,work,info)
        use la_constants_${rk}$,only:zero,one,two,three,four,eight,ten
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: i,n
           integer(ilp),intent(out) :: info
           real(${rk}$),intent(in) :: rho
           real(${rk}$),intent(out) :: sigma
           ! Array Arguments
           real(${rk}$),intent(in) :: d(*),z(*)
           real(${rk}$),intent(out) :: delta(*),work(*)
        ! =====================================================================
           ! Parameters
           integer(ilp),parameter :: maxit = 400

           ! Local Scalars
           logical(lk) :: orgati,swtch,swtch3,geomavg
           integer(ilp) :: ii,iim1,iip1,ip1,iter,j,niter
           real(${rk}$) :: a,b,c,delsq,delsq2,sq2,dphi,dpsi,dtiim,dtiip,dtipsq,dtisq, &
           dtnsq,dtnsq1,dw,eps,erretm,eta,phi,prew,psi,rhoinv,sglb,sgub,tau,tau2, &
                     temp,temp1,temp2,w
           ! Local Arrays
           real(${rk}$) :: dd(3),zz(3)
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           ! since this routine is called in an inner loop, we do no argument
           ! checking.
           ! quick return for n=1 and 2.
           info = 0
           if (n == 1) then
              ! presumably, i=1 upon entry
              sigma = sqrt(d(1)*d(1) + rho*z(1)*z(1))
              delta(1) = one
              work(1) = one
              return
           end if
           if (n == 2) then
              call la_${ri}$lasd5(i,d,z,delta,rho,sigma,work)
              return
           end if
           ! compute machine epsilon
           eps = la_${ri}$lamch('EPSILON')
           rhoinv = one/rho
           tau2 = zero
           ! the case i = n
           if (i == n) then
              ! initialize some basic variables
              ii = n - 1
              niter = 1
              ! calculate initial guess
              temp = rho/two
              ! if ||z||_2 is not one, then temp should be set to
              ! rho * ||z||_2^2 / two
              temp1 = temp/(d(n) + sqrt(d(n)*d(n) + temp))
              do j = 1,n
                 work(j) = d(j) + d(n) + temp1
                 delta(j) = (d(j) - d(n)) - temp1
              end do
              psi = zero
              do j = 1,n - 2
                 psi = psi + z(j)*z(j)/(delta(j)*work(j))
              end do
              c = rhoinv + psi
              w = c + z(ii)*z(ii)/(delta(ii)*work(ii)) + z(n)*z(n)/(delta(n) &
                        *work(n))
              if (w <= zero) then
                 temp1 = sqrt(d(n)*d(n) + rho)
                 temp = z(n - 1)*z(n - 1)/((d(n - 1) + temp1)*(d(n) - d(n - 1) + rho/(d(n) + &
                           temp1))) + z(n)*z(n)/rho
                 ! the following tau2 is to approximate
                 ! sigma_n^2 - d( n )*d( n )
                 if (c <= temp) then
                    tau = rho
                 else
                    delsq = (d(n) - d(n - 1))*(d(n) + d(n - 1))
                    a = -c*delsq + z(n - 1)*z(n - 1) + z(n)*z(n)
                    b = z(n)*z(n)*delsq
                    if (a < zero) then
                       tau2 = two*b/(sqrt(a*a + four*b*c) - a)
                    else
                       tau2 = (a + sqrt(a*a + four*b*c))/(two*c)
                    end if
                    tau = tau2/(d(n) + sqrt(d(n)*d(n) + tau2))
                 end if
                 ! it can be proved that
                     ! d(n)^2+rho/2 <= sigma_n^2 < d(n)^2+tau2 <= d(n)^2+rho
              else
                 delsq = (d(n) - d(n - 1))*(d(n) + d(n - 1))
                 a = -c*delsq + z(n - 1)*z(n - 1) + z(n)*z(n)
                 b = z(n)*z(n)*delsq
                 ! the following tau2 is to approximate
                 ! sigma_n^2 - d( n )*d( n )
                 if (a < zero) then
                    tau2 = two*b/(sqrt(a*a + four*b*c) - a)
                 else
                    tau2 = (a + sqrt(a*a + four*b*c))/(two*c)
                 end if
                 tau = tau2/(d(n) + sqrt(d(n)*d(n) + tau2))
                 ! it can be proved that
                 ! d(n)^2 < d(n)^2+tau2 < sigma(n)^2 < d(n)^2+rho/2
              end if
              ! the following tau is to approximate sigma_n - d( n )
               ! tau = tau2 / ( d( n )+sqrt( d( n )*d( n )+tau2 ) )
              sigma = d(n) + tau
              do j = 1,n
                 delta(j) = (d(j) - d(n)) - tau
                 work(j) = d(j) + d(n) + tau
              end do
              ! evaluate psi and the derivative dpsi
              dpsi = zero
              psi = zero
              erretm = zero
              do j = 1,ii
                 temp = z(j)/(delta(j)*work(j))
                 psi = psi + z(j)*temp
                 dpsi = dpsi + temp*temp
                 erretm = erretm + psi
              end do
              erretm = abs(erretm)
              ! evaluate phi and the derivative dphi
              temp = z(n)/(delta(n)*work(n))
              phi = z(n)*temp
              dphi = temp*temp
              erretm = eight*(-phi - psi) + erretm - phi + rhoinv
          ! $          + abs( tau2 )*( dpsi+dphi )
              w = rhoinv + phi + psi
              ! test for convergence
              if (abs(w) <= eps*erretm) then
                 go to 240
              end if
              ! calculate the new step
              niter = niter + 1
              dtnsq1 = work(n - 1)*delta(n - 1)
              dtnsq = work(n)*delta(n)
              c = w - dtnsq1*dpsi - dtnsq*dphi
              a = (dtnsq + dtnsq1)*w - dtnsq*dtnsq1*(dpsi + dphi)
              b = dtnsq*dtnsq1*w
              if (c < zero) c = abs(c)
              if (c == zero) then
                 eta = rho - sigma*sigma
              else if (a >= zero) then
                 eta = (a + sqrt(abs(a*a - four*b*c)))/(two*c)
              else
                 eta = two*b/(a - sqrt(abs(a*a - four*b*c)))
              end if
              ! note, eta should be positive if w is negative, and
              ! eta should be negative otherwise. however,
              ! if for some reason caused by roundoff, eta*w > 0,
              ! we simply use one newton step instead. this way
              ! will guarantee eta*w < 0.
              if (w*eta > zero) eta = -w/(dpsi + dphi)
              temp = eta - dtnsq
              if (temp > rho) eta = rho + dtnsq
              eta = eta/(sigma + sqrt(eta + sigma*sigma))
              tau = tau + eta
              sigma = sigma + eta
              do j = 1,n
                 delta(j) = delta(j) - eta
                 work(j) = work(j) + eta
              end do
              ! evaluate psi and the derivative dpsi
              dpsi = zero
              psi = zero
              erretm = zero
              do j = 1,ii
                 temp = z(j)/(work(j)*delta(j))
                 psi = psi + z(j)*temp
                 dpsi = dpsi + temp*temp
                 erretm = erretm + psi
              end do
              erretm = abs(erretm)
              ! evaluate phi and the derivative dphi
              tau2 = work(n)*delta(n)
              temp = z(n)/tau2
              phi = z(n)*temp
              dphi = temp*temp
              erretm = eight*(-phi - psi) + erretm - phi + rhoinv
          ! $          + abs( tau2 )*( dpsi+dphi )
              w = rhoinv + phi + psi
              ! main loop to update the values of the array   delta
              iter = niter + 1
              loop_90: do niter = iter,maxit
                 ! test for convergence
                 if (abs(w) <= eps*erretm) then
                    go to 240
                 end if
                 ! calculate the new step
                 dtnsq1 = work(n - 1)*delta(n - 1)
                 dtnsq = work(n)*delta(n)
                 c = w - dtnsq1*dpsi - dtnsq*dphi
                 a = (dtnsq + dtnsq1)*w - dtnsq1*dtnsq*(dpsi + dphi)
                 b = dtnsq1*dtnsq*w
                 if (a >= zero) then
                    eta = (a + sqrt(abs(a*a - four*b*c)))/(two*c)
                 else
                    eta = two*b/(a - sqrt(abs(a*a - four*b*c)))
                 end if
                 ! note, eta should be positive if w is negative, and
                 ! eta should be negative otherwise. however,
                 ! if for some reason caused by roundoff, eta*w > 0,
                 ! we simply use one newton step instead. this way
                 ! will guarantee eta*w < 0.
                 if (w*eta > zero) eta = -w/(dpsi + dphi)
                 temp = eta - dtnsq
                 if (temp <= zero) eta = eta/two
                 eta = eta/(sigma + sqrt(eta + sigma*sigma))
                 tau = tau + eta
                 sigma = sigma + eta
                 do j = 1,n
                    delta(j) = delta(j) - eta
                    work(j) = work(j) + eta
                 end do
                 ! evaluate psi and the derivative dpsi
                 dpsi = zero
                 psi = zero
                 erretm = zero
                 do j = 1,ii
                    temp = z(j)/(work(j)*delta(j))
                    psi = psi + z(j)*temp
                    dpsi = dpsi + temp*temp
                    erretm = erretm + psi
                 end do
                 erretm = abs(erretm)
                 ! evaluate phi and the derivative dphi
                 tau2 = work(n)*delta(n)
                 temp = z(n)/tau2
                 phi = z(n)*temp
                 dphi = temp*temp
                 erretm = eight*(-phi - psi) + erretm - phi + rhoinv
          ! $             + abs( tau2 )*( dpsi+dphi )
                 w = rhoinv + phi + psi
              end do loop_90
              ! return with info = 1, niter = maxit and not converged
              info = 1
              go to 240
              ! end for the case i = n
           else
              ! the case for i < n
              niter = 1
              ip1 = i + 1
              ! calculate initial guess
              delsq = (d(ip1) - d(i))*(d(ip1) + d(i))
              delsq2 = delsq/two
              sq2 = sqrt((d(i)*d(i) + d(ip1)*d(ip1))/two)
              temp = delsq2/(d(i) + sq2)
              do j = 1,n
                 work(j) = d(j) + d(i) + temp
                 delta(j) = (d(j) - d(i)) - temp
              end do
              psi = zero
              do j = 1,i - 1
                 psi = psi + z(j)*z(j)/(work(j)*delta(j))
              end do
              phi = zero
              do j = n,i + 2,-1
                 phi = phi + z(j)*z(j)/(work(j)*delta(j))
              end do
              c = rhoinv + psi + phi
              w = c + z(i)*z(i)/(work(i)*delta(i)) + z(ip1)*z(ip1)/(work(ip1) &
                        *delta(ip1))
              geomavg = .false.
              if (w > zero) then
                 ! d(i)^2 < the ith sigma^2 < (d(i)^2+d(i+1)^2)/2
                 ! we choose d(i) as origin.
                 orgati = .true.
                 ii = i
                 sglb = zero
                 sgub = delsq2/(d(i) + sq2)
                 a = c*delsq + z(i)*z(i) + z(ip1)*z(ip1)
                 b = z(i)*z(i)*delsq
                 if (a > zero) then
                    tau2 = two*b/(a + sqrt(abs(a*a - four*b*c)))
                 else
                    tau2 = (a - sqrt(abs(a*a - four*b*c)))/(two*c)
                 end if
                 ! tau2 now is an estimation of sigma^2 - d( i )^2. the
                 ! following, however, is the corresponding estimation of
                 ! sigma - d( i ).
                 tau = tau2/(d(i) + sqrt(d(i)*d(i) + tau2))
                 temp = sqrt(eps)
                 if ((d(i) <= temp*d(ip1)) .and. (abs(z(i)) <= temp) .and. (d(i) > zero)) then
                    tau = min(ten*d(i),sgub)
                    geomavg = .true.
                 end if
              else
                 ! (d(i)^2+d(i+1)^2)/2 <= the ith sigma^2 < d(i+1)^2/2
                 ! we choose d(i+1) as origin.
                 orgati = .false.
                 ii = ip1
                 sglb = -delsq2/(d(ii) + sq2)
                 sgub = zero
                 a = c*delsq - z(i)*z(i) - z(ip1)*z(ip1)
                 b = z(ip1)*z(ip1)*delsq
                 if (a < zero) then
                    tau2 = two*b/(a - sqrt(abs(a*a + four*b*c)))
                 else
                    tau2 = -(a + sqrt(abs(a*a + four*b*c)))/(two*c)
                 end if
                 ! tau2 now is an estimation of sigma^2 - d( ip1 )^2. the
                 ! following, however, is the corresponding estimation of
                 ! sigma - d( ip1 ).
                 tau = tau2/(d(ip1) + sqrt(abs(d(ip1)*d(ip1) + tau2)))
              end if
              sigma = d(ii) + tau
              do j = 1,n
                 work(j) = d(j) + d(ii) + tau
                 delta(j) = (d(j) - d(ii)) - tau
              end do
              iim1 = ii - 1
              iip1 = ii + 1
              ! evaluate psi and the derivative dpsi
              dpsi = zero
              psi = zero
              erretm = zero
              do j = 1,iim1
                 temp = z(j)/(work(j)*delta(j))
                 psi = psi + z(j)*temp
                 dpsi = dpsi + temp*temp
                 erretm = erretm + psi
              end do
              erretm = abs(erretm)
              ! evaluate phi and the derivative dphi
              dphi = zero
              phi = zero
              do j = n,iip1,-1
                 temp = z(j)/(work(j)*delta(j))
                 phi = phi + z(j)*temp
                 dphi = dphi + temp*temp
                 erretm = erretm + phi
              end do
              w = rhoinv + phi + psi
              ! w is the value of the secular function with
              ! its ii-th element removed.
              swtch3 = .false.
              if (orgati) then
                 if (w < zero) swtch3 = .true.
              else
                 if (w > zero) swtch3 = .true.
              end if
              if (ii == 1 .or. ii == n) swtch3 = .false.
              temp = z(ii)/(work(ii)*delta(ii))
              dw = dpsi + dphi + temp*temp
              temp = z(ii)*temp
              w = w + temp
              erretm = eight*(phi - psi) + erretm + two*rhoinv + three*abs(temp)
          ! $          + abs( tau2 )*dw
              ! test for convergence
              if (abs(w) <= eps*erretm) then
                 go to 240
              end if
              if (w <= zero) then
                 sglb = max(sglb,tau)
              else
                 sgub = min(sgub,tau)
              end if
              ! calculate the new step
              niter = niter + 1
              if (.not. swtch3) then
                 dtipsq = work(ip1)*delta(ip1)
                 dtisq = work(i)*delta(i)
                 if (orgati) then
                    c = w - dtipsq*dw + delsq*(z(i)/dtisq)**2
                 else
                    c = w - dtisq*dw - delsq*(z(ip1)/dtipsq)**2
                 end if
                 a = (dtipsq + dtisq)*w - dtipsq*dtisq*dw
                 b = dtipsq*dtisq*w
                 if (c == zero) then
                    if (a == zero) then
                       if (orgati) then
                          a = z(i)*z(i) + dtipsq*dtipsq*(dpsi + dphi)
                       else
                          a = z(ip1)*z(ip1) + dtisq*dtisq*(dpsi + dphi)
                       end if
                    end if
                    eta = b/a
                 else if (a <= zero) then
                    eta = (a - sqrt(abs(a*a - four*b*c)))/(two*c)
                 else
                    eta = two*b/(a + sqrt(abs(a*a - four*b*c)))
                 end if
              else
                 ! interpolation using three most relevant poles
                 dtiim = work(iim1)*delta(iim1)
                 dtiip = work(iip1)*delta(iip1)
                 temp = rhoinv + psi + phi
                 if (orgati) then
                    temp1 = z(iim1)/dtiim
                    temp1 = temp1*temp1
                    c = (temp - dtiip*(dpsi + dphi)) - (d(iim1) - d(iip1))*(d(iim1) + d( &
                              iip1))*temp1
                    zz(1) = z(iim1)*z(iim1)
                    if (dpsi < temp1) then
                       zz(3) = dtiip*dtiip*dphi
                    else
                       zz(3) = dtiip*dtiip*((dpsi - temp1) + dphi)
                    end if
                 else
                    temp1 = z(iip1)/dtiip
                    temp1 = temp1*temp1
                    c = (temp - dtiim*(dpsi + dphi)) - (d(iip1) - d(iim1))*(d(iim1) + d( &
                              iip1))*temp1
                    if (dphi < temp1) then
                       zz(1) = dtiim*dtiim*dpsi
                    else
                       zz(1) = dtiim*dtiim*(dpsi + (dphi - temp1))
                    end if
                    zz(3) = z(iip1)*z(iip1)
                 end if
                 zz(2) = z(ii)*z(ii)
                 dd(1) = dtiim
                 dd(2) = delta(ii)*work(ii)
                 dd(3) = dtiip
                 call la_${ri}$laed6(niter,orgati,c,dd,zz,w,eta,info)
                 if (info /= 0) then
                    ! if info is not 0, i.e., la_${ri}$laed6 failed, switch back
                    ! to 2 pole interpolation.
                    swtch3 = .false.
                    info = 0
                    dtipsq = work(ip1)*delta(ip1)
                    dtisq = work(i)*delta(i)
                    if (orgati) then
                       c = w - dtipsq*dw + delsq*(z(i)/dtisq)**2
                    else
                       c = w - dtisq*dw - delsq*(z(ip1)/dtipsq)**2
                    end if
                    a = (dtipsq + dtisq)*w - dtipsq*dtisq*dw
                    b = dtipsq*dtisq*w
                    if (c == zero) then
                       if (a == zero) then
                          if (orgati) then
                             a = z(i)*z(i) + dtipsq*dtipsq*(dpsi + dphi)
                          else
                             a = z(ip1)*z(ip1) + dtisq*dtisq*(dpsi + dphi)
                          end if
                       end if
                       eta = b/a
                    else if (a <= zero) then
                       eta = (a - sqrt(abs(a*a - four*b*c)))/(two*c)
                    else
                       eta = two*b/(a + sqrt(abs(a*a - four*b*c)))
                    end if
                 end if
              end if
              ! note, eta should be positive if w is negative, and
              ! eta should be negative otherwise. however,
              ! if for some reason caused by roundoff, eta*w > 0,
              ! we simply use one newton step instead. this way
              ! will guarantee eta*w < 0.
              if (w*eta >= zero) eta = -w/dw
              eta = eta/(sigma + sqrt(sigma*sigma + eta))
              temp = tau + eta
              if (temp > sgub .or. temp < sglb) then
                 if (w < zero) then
                    eta = (sgub - tau)/two
                 else
                    eta = (sglb - tau)/two
                 end if
                 if (geomavg) then
                    if (w < zero) then
                       if (tau > zero) then
                          eta = sqrt(sgub*tau) - tau
                       end if
                    else
                       if (sglb > zero) then
                          eta = sqrt(sglb*tau) - tau
                       end if
                    end if
                 end if
              end if
              prew = w
              tau = tau + eta
              sigma = sigma + eta
              do j = 1,n
                 work(j) = work(j) + eta
                 delta(j) = delta(j) - eta
              end do
              ! evaluate psi and the derivative dpsi
              dpsi = zero
              psi = zero
              erretm = zero
              do j = 1,iim1
                 temp = z(j)/(work(j)*delta(j))
                 psi = psi + z(j)*temp
                 dpsi = dpsi + temp*temp
                 erretm = erretm + psi
              end do
              erretm = abs(erretm)
              ! evaluate phi and the derivative dphi
              dphi = zero
              phi = zero
              do j = n,iip1,-1
                 temp = z(j)/(work(j)*delta(j))
                 phi = phi + z(j)*temp
                 dphi = dphi + temp*temp
                 erretm = erretm + phi
              end do
              tau2 = work(ii)*delta(ii)
              temp = z(ii)/tau2
              dw = dpsi + dphi + temp*temp
              temp = z(ii)*temp
              w = rhoinv + phi + psi + temp
              erretm = eight*(phi - psi) + erretm + two*rhoinv + three*abs(temp)
          ! $          + abs( tau2 )*dw
              swtch = .false.
              if (orgati) then
                 if (-w > abs(prew)/ten) swtch = .true.
              else
                 if (w > abs(prew)/ten) swtch = .true.
              end if
              ! main loop to update the values of the array   delta and work
              iter = niter + 1
              loop_230: do niter = iter,maxit
                 ! test for convergence
                 if (abs(w) <= eps*erretm) then
           ! $          .or. (sgub-sglb)<=eight*abs(sgub+sglb) ) then
                    go to 240
                 end if
                 if (w <= zero) then
                    sglb = max(sglb,tau)
                 else
                    sgub = min(sgub,tau)
                 end if
                 ! calculate the new step
                 if (.not. swtch3) then
                    dtipsq = work(ip1)*delta(ip1)
                    dtisq = work(i)*delta(i)
                    if (.not. swtch) then
                       if (orgati) then
                          c = w - dtipsq*dw + delsq*(z(i)/dtisq)**2
                       else
                          c = w - dtisq*dw - delsq*(z(ip1)/dtipsq)**2
                       end if
                    else
                       temp = z(ii)/(work(ii)*delta(ii))
                       if (orgati) then
                          dpsi = dpsi + temp*temp
                       else
                          dphi = dphi + temp*temp
                       end if
                       c = w - dtisq*dpsi - dtipsq*dphi
                    end if
                    a = (dtipsq + dtisq)*w - dtipsq*dtisq*dw
                    b = dtipsq*dtisq*w
                    if (c == zero) then
                       if (a == zero) then
                          if (.not. swtch) then
                             if (orgati) then
                                a = z(i)*z(i) + dtipsq*dtipsq*(dpsi + dphi)
                             else
                                a = z(ip1)*z(ip1) + dtisq*dtisq*(dpsi + dphi)
                             end if
                          else
                             a = dtisq*dtisq*dpsi + dtipsq*dtipsq*dphi
                          end if
                       end if
                       eta = b/a
                    else if (a <= zero) then
                       eta = (a - sqrt(abs(a*a - four*b*c)))/(two*c)
                    else
                       eta = two*b/(a + sqrt(abs(a*a - four*b*c)))
                    end if
                 else
                    ! interpolation using three most relevant poles
                    dtiim = work(iim1)*delta(iim1)
                    dtiip = work(iip1)*delta(iip1)
                    temp = rhoinv + psi + phi
                    if (swtch) then
                       c = temp - dtiim*dpsi - dtiip*dphi
                       zz(1) = dtiim*dtiim*dpsi
                       zz(3) = dtiip*dtiip*dphi
                    else
                       if (orgati) then
                          temp1 = z(iim1)/dtiim
                          temp1 = temp1*temp1
                          temp2 = (d(iim1) - d(iip1))*(d(iim1) + d(iip1))*temp1
                          c = temp - dtiip*(dpsi + dphi) - temp2
                          zz(1) = z(iim1)*z(iim1)
                          if (dpsi < temp1) then
                             zz(3) = dtiip*dtiip*dphi
                          else
                             zz(3) = dtiip*dtiip*((dpsi - temp1) + dphi)
                          end if
                       else
                          temp1 = z(iip1)/dtiip
                          temp1 = temp1*temp1
                          temp2 = (d(iip1) - d(iim1))*(d(iim1) + d(iip1))*temp1
                          c = temp - dtiim*(dpsi + dphi) - temp2
                          if (dphi < temp1) then
                             zz(1) = dtiim*dtiim*dpsi
                          else
                             zz(1) = dtiim*dtiim*(dpsi + (dphi - temp1))
                          end if
                          zz(3) = z(iip1)*z(iip1)
                       end if
                    end if
                    dd(1) = dtiim
                    dd(2) = delta(ii)*work(ii)
                    dd(3) = dtiip
                    call la_${ri}$laed6(niter,orgati,c,dd,zz,w,eta,info)
                    if (info /= 0) then
                       ! if info is not 0, i.e., la_${ri}$laed6 failed, switch
                       ! back to two pole interpolation
                       swtch3 = .false.
                       info = 0
                       dtipsq = work(ip1)*delta(ip1)
                       dtisq = work(i)*delta(i)
                       if (.not. swtch) then
                          if (orgati) then
                             c = w - dtipsq*dw + delsq*(z(i)/dtisq)**2
                          else
                             c = w - dtisq*dw - delsq*(z(ip1)/dtipsq)**2
                          end if
                       else
                          temp = z(ii)/(work(ii)*delta(ii))
                          if (orgati) then
                             dpsi = dpsi + temp*temp
                          else
                             dphi = dphi + temp*temp
                          end if
                          c = w - dtisq*dpsi - dtipsq*dphi
                       end if
                       a = (dtipsq + dtisq)*w - dtipsq*dtisq*dw
                       b = dtipsq*dtisq*w
                       if (c == zero) then
                          if (a == zero) then
                             if (.not. swtch) then
                                if (orgati) then
                                   a = z(i)*z(i) + dtipsq*dtipsq*(dpsi + dphi)
                                else
                                   a = z(ip1)*z(ip1) + dtisq*dtisq*(dpsi + dphi)
                                end if
                             else
                                a = dtisq*dtisq*dpsi + dtipsq*dtipsq*dphi
                             end if
                          end if
                          eta = b/a
                       else if (a <= zero) then
                          eta = (a - sqrt(abs(a*a - four*b*c)))/(two*c)
                       else
                          eta = two*b/(a + sqrt(abs(a*a - four*b*c)))
                       end if
                    end if
                 end if
                 ! note, eta should be positive if w is negative, and
                 ! eta should be negative otherwise. however,
                 ! if for some reason caused by roundoff, eta*w > 0,
                 ! we simply use one newton step instead. this way
                 ! will guarantee eta*w < 0.
                 if (w*eta >= zero) eta = -w/dw
                 eta = eta/(sigma + sqrt(sigma*sigma + eta))
                 temp = tau + eta
                 if (temp > sgub .or. temp < sglb) then
                    if (w < zero) then
                       eta = (sgub - tau)/two
                    else
                       eta = (sglb - tau)/two
                    end if
                    if (geomavg) then
                       if (w < zero) then
                          if (tau > zero) then
                             eta = sqrt(sgub*tau) - tau
                          end if
                       else
                          if (sglb > zero) then
                             eta = sqrt(sglb*tau) - tau
                          end if
                       end if
                    end if
                 end if
                 prew = w
                 tau = tau + eta
                 sigma = sigma + eta
                 do j = 1,n
                    work(j) = work(j) + eta
                    delta(j) = delta(j) - eta
                 end do
                 ! evaluate psi and the derivative dpsi
                 dpsi = zero
                 psi = zero
                 erretm = zero
                 do j = 1,iim1
                    temp = z(j)/(work(j)*delta(j))
                    psi = psi + z(j)*temp
                    dpsi = dpsi + temp*temp
                    erretm = erretm + psi
                 end do
                 erretm = abs(erretm)
                 ! evaluate phi and the derivative dphi
                 dphi = zero
                 phi = zero
                 do j = n,iip1,-1
                    temp = z(j)/(work(j)*delta(j))
                    phi = phi + z(j)*temp
                    dphi = dphi + temp*temp
                    erretm = erretm + phi
                 end do
                 tau2 = work(ii)*delta(ii)
                 temp = z(ii)/tau2
                 dw = dpsi + dphi + temp*temp
                 temp = z(ii)*temp
                 w = rhoinv + phi + psi + temp
                 erretm = eight*(phi - psi) + erretm + two*rhoinv + three*abs(temp)
          ! $             + abs( tau2 )*dw
                 if (w*prew > zero .and. abs(w) > abs(prew)/ten) swtch = .not. swtch
              end do loop_230
              ! return with info = 1, niter = maxit and not converged
              info = 1
           end if
           240 continue
           return
     end subroutine la_${ri}$lasd4
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD7: merges the two sets of singular values together into a single
     !> sorted set. Then it tries to deflate the size of the problem. There
     !> are two ways in which deflation can occur:  when two or more singular
     !> values are close together or if there is a tiny entry in the Z
     !> vector. For each such occurrence the order of the related
     !> secular equation problem is reduced by one.
     !> ${ri.upper()}$LASD7 is called from ${ri.upper()}$LASD6.

     pure subroutine la_${ri}$lasd7(icompq,nl,nr,sqre,k,d,z,zw,vf,vfw,vl,vlw,alpha, &
     beta,dsigma,idx,idxp,idxq,perm,givptr,givcol,ldgcol,givnum,ldgnum,c,s,info)
        use la_constants_${rk}$,only:zero,one,two,eight

        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: givptr,info,k
           integer(ilp),intent(in) :: icompq,ldgcol,ldgnum,nl,nr,sqre
           real(${rk}$),intent(in) :: alpha,beta
           real(${rk}$),intent(out) :: c,s
           ! Array Arguments
           integer(ilp),intent(out) :: givcol(ldgcol,*),idx(*),idxp(*),perm(*)
           integer(ilp),intent(inout) :: idxq(*)
           real(${rk}$),intent(inout) :: d(*),vf(*),vl(*)
           real(${rk}$),intent(out) :: dsigma(*),givnum(ldgnum,*),vfw(*),vlw(*),z(*),zw(*)

        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,idxi,idxj,idxjp,j,jp,jprev,k2,m,n,nlp1,nlp2
           real(${rk}$) :: eps,hlftol,tau,tol,z1
           ! Intrinsic Functions
           intrinsic :: abs,max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           n = nl + nr + 1
           m = n + sqre
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (nl < 1) then
              info = -2
           else if (nr < 1) then
              info = -3
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -4
           else if (ldgcol < n) then
              info = -22
           else if (ldgnum < n) then
              info = -24
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD7',-info)
              return
           end if
           nlp1 = nl + 1
           nlp2 = nl + 2
           if (icompq == 1) then
              givptr = 0
           end if
           ! generate the first part of the vector z and move the singular
           ! values in the first part of d one position backward.
           z1 = alpha*vl(nlp1)
           vl(nlp1) = zero
           tau = vf(nlp1)
           do i = nl,1,-1
              z(i + 1) = alpha*vl(i)
              vl(i) = zero
              vf(i + 1) = vf(i)
              d(i + 1) = d(i)
              idxq(i + 1) = idxq(i) + 1
           end do
           vf(1) = tau
           ! generate the second part of the vector z.
           do i = nlp2,m
              z(i) = beta*vf(i)
              vf(i) = zero
           end do
           ! sort the singular values into increasing order
           do i = nlp2,n
              idxq(i) = idxq(i) + nlp1
           end do
           ! dsigma, idxc, idxc, and zw are used as storage space.
           do i = 2,n
              dsigma(i) = d(idxq(i))
              zw(i) = z(idxq(i))
              vfw(i) = vf(idxq(i))
              vlw(i) = vl(idxq(i))
           end do
           call la_${ri}$lamrg(nl,nr,dsigma(2),1,1,idx(2))
           do i = 2,n
              idxi = 1 + idx(i)
              d(i) = dsigma(idxi)
              z(i) = zw(idxi)
              vf(i) = vfw(idxi)
              vl(i) = vlw(idxi)
           end do
           ! calculate the allowable deflation tolerance
           eps = la_${ri}$lamch('EPSILON')
           tol = max(abs(alpha),abs(beta))
           tol = eight*eight*eps*max(abs(d(n)),tol)
           ! there are 2 kinds of deflation -- first a value in the z-vector
           ! is small, second two (or more) singular values are very close
           ! together (their difference is small).
           ! if the value in the z-vector is small, we simply permute the
           ! array so that the corresponding singular value is moved to the
           ! end.
           ! if two values in the d-vector are close, we perform a two-sided
           ! rotation designed to make one of the corresponding z-vector
           ! entries zero, and then permute the array so that the deflated
           ! singular value is moved to the end.
           ! if there are multiple singular values then the problem deflates.
           ! here the number of equal singular values are found.  as each equal
           ! singular value is found, an elementary reflector is computed to
           ! rotate the corresponding singular subspace so that the
           ! corresponding components of z are zero in this new basis.
           k = 1
           k2 = n + 1
           do j = 2,n
              if (abs(z(j)) <= tol) then
                 ! deflate due to small z component.
                 k2 = k2 - 1
                 idxp(k2) = j
                 if (j == n) go to 100
              else
                 jprev = j
                 go to 70
              end if
           end do
           70 continue
           j = jprev
           80 continue
           j = j + 1
           if (j > n) go to 90
           if (abs(z(j)) <= tol) then
              ! deflate due to small z component.
              k2 = k2 - 1
              idxp(k2) = j
           else
              ! check if singular values are close enough to allow deflation.
              if (abs(d(j) - d(jprev)) <= tol) then
                 ! deflation is possible.
                 s = z(jprev)
                 c = z(j)
                 ! find sqrt(a**2+b**2) without overflow or
                 ! destructive underflow.
                 tau = la_${ri}$lapy2(c,s)
                 z(j) = tau
                 z(jprev) = zero
                 c = c/tau
                 s = -s/tau
                 ! record the appropriate givens rotation
                 if (icompq == 1) then
                    givptr = givptr + 1
                    idxjp = idxq(idx(jprev) + 1)
                    idxj = idxq(idx(j) + 1)
                    if (idxjp <= nlp1) then
                       idxjp = idxjp - 1
                    end if
                    if (idxj <= nlp1) then
                       idxj = idxj - 1
                    end if
                    givcol(givptr,2) = idxjp
                    givcol(givptr,1) = idxj
                    givnum(givptr,2) = c
                    givnum(givptr,1) = s
                 end if
                 call la_${ri}$rot(1,vf(jprev),1,vf(j),1,c,s)
                 call la_${ri}$rot(1,vl(jprev),1,vl(j),1,c,s)
                 k2 = k2 - 1
                 idxp(k2) = jprev
                 jprev = j
              else
                 k = k + 1
                 zw(k) = z(jprev)
                 dsigma(k) = d(jprev)
                 idxp(k) = jprev
                 jprev = j
              end if
           end if
           go to 80
           90 continue
           ! record the last singular value.
           k = k + 1
           zw(k) = z(jprev)
           dsigma(k) = d(jprev)
           idxp(k) = jprev
           100 continue
           ! sort the singular values into dsigma. the singular values which
           ! were not deflated go into the first k slots of dsigma, except
           ! that dsigma(1) is treated separately.
           do j = 2,n
              jp = idxp(j)
              dsigma(j) = d(jp)
              vfw(j) = vf(jp)
              vlw(j) = vl(jp)
           end do
           if (icompq == 1) then
              do j = 2,n
                 jp = idxp(j)
                 perm(j) = idxq(idx(jp) + 1)
                 if (perm(j) <= nlp1) then
                    perm(j) = perm(j) - 1
                 end if
              end do
           end if
           ! the deflated singular values go back into the last n - k slots of
           ! d.
           call la_${ri}$copy(n - k,dsigma(k + 1),1,d(k + 1),1)
           ! determine dsigma(1), dsigma(2), z(1), vf(1), vl(1), vf(m), and
           ! vl(m).
           dsigma(1) = zero
           hlftol = tol/two
           if (abs(dsigma(2)) <= hlftol) dsigma(2) = hlftol
           if (m > n) then
              z(1) = la_${ri}$lapy2(z1,z(m))
              if (z(1) <= tol) then
                 c = one
                 s = zero
                 z(1) = tol
              else
                 c = z1/z(1)
                 s = -z(m)/z(1)
              end if
              call la_${ri}$rot(1,vf(m),1,vf(1),1,c,s)
              call la_${ri}$rot(1,vl(m),1,vl(1),1,c,s)
           else
              if (abs(z1) <= tol) then
                 z(1) = tol
              else
                 z(1) = z1
              end if
           end if
           ! restore z, vf, and vl.
           call la_${ri}$copy(k - 1,zw(2),1,z(2),1)
           call la_${ri}$copy(n - 1,vfw(2),1,vf(2),1)
           call la_${ri}$copy(n - 1,vlw(2),1,vl(2),1)
           return
     end subroutine la_${ri}$lasd7
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD8: finds the square roots of the roots of the secular equation,
     !> as defined by the values in DSIGMA and Z. It makes the appropriate
     !> calls to ${ri.upper()}$LASD4, and stores, for each  element in D, the distance
     !> to its two nearest poles (elements in DSIGMA). It also updates
     !> the arrays VF and VL, the first and last components of all the
     !> right singular vectors of the original bidiagonal matrix.
     !> ${ri.upper()}$LASD8 is called from ${ri.upper()}$LASD6.

     pure subroutine la_${ri}$lasd8(icompq,k,d,z,vf,vl,difl,difr,lddifr,dsigma,work, &
               info)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: icompq,k,lddifr
           integer(ilp),intent(out) :: info
           ! Array Arguments
           real(${rk}$),intent(out) :: d(*),difl(*),difr(lddifr,*),work(*)
           real(${rk}$),intent(inout) :: dsigma(*),vf(*),vl(*),z(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,iwk1,iwk2,iwk2i,iwk3,iwk3i,j
           real(${rk}$) :: diflj,difrj,dj,dsigj,dsigjp,rho,temp
           ! Intrinsic Functions
           intrinsic :: abs,sign,sqrt
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (k < 1) then
              info = -2
           else if (lddifr < k) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD8',-info)
              return
           end if
           ! quick return if possible
           if (k == 1) then
              d(1) = abs(z(1))
              difl(1) = d(1)
              if (icompq == 1) then
                 difl(2) = one
                 difr(1,2) = one
              end if
              return
           end if
           ! modify values dsigma(i) to make sure all dsigma(i)-dsigma(j) can
           ! be computed with high relative accuracy (barring over/underflow).
           ! this is a problem on machines without a guard digit in
           ! add/subtract (cray xmp, cray ymp, cray c 90 and cray 2).
           ! the following code replaces dsigma(i) by 2*dsigma(i)-dsigma(i),
           ! which on any of these machines zeros out the bottommost
           ! bit of dsigma(i) if it is 1; this makes the subsequent
           ! subtractions dsigma(i)-dsigma(j) unproblematic when cancellation
           ! occurs. on binary machines with a guard digit (almost all
           ! machines) it does not change dsigma(i) at all. on hexadecimal
           ! and decimal machines with a guard digit, it slightly
           ! changes the bottommost bits of dsigma(i). it does not account
           ! for hexadecimal or decimal machines without guard digits
           ! (we know of none). we use a subroutine call to compute
           ! 2*dlambda(i) to prevent optimizing compilers from eliminating
           ! this code.
           do i = 1,k
              dsigma(i) = la_${ri}$lamc3(dsigma(i),dsigma(i)) - dsigma(i)
           end do
           ! book keeping.
           iwk1 = 1
           iwk2 = iwk1 + k
           iwk3 = iwk2 + k
           iwk2i = iwk2 - 1
           iwk3i = iwk3 - 1
           ! normalize z.
           rho = la_${ri}$nrm2(k,z,1)
           call la_${ri}$lascl('G',0,0,rho,one,k,1,z,k,info)
           rho = rho*rho
           ! initialize work(iwk3).
           call la_${ri}$laset('A',k,1,one,one,work(iwk3),k)
           ! compute the updated singular values, the arrays difl, difr,
           ! and the updated z.
           do j = 1,k
              call la_${ri}$lasd4(k,j,dsigma,z,work(iwk1),rho,d(j),work(iwk2),info)

              ! if the root finder fails, report the convergence failure.
              if (info /= 0) then
                 return
              end if
              work(iwk3i + j) = work(iwk3i + j)*work(j)*work(iwk2i + j)
              difl(j) = -work(j)
              difr(j,1) = -work(j + 1)
              do i = 1,j - 1
                 work(iwk3i + i) = work(iwk3i + i)*work(i)*work(iwk2i + i)/(dsigma(i) - &
                           dsigma(j))/(dsigma(i) + dsigma(j))
              end do
              do i = j + 1,k
                 work(iwk3i + i) = work(iwk3i + i)*work(i)*work(iwk2i + i)/(dsigma(i) - &
                           dsigma(j))/(dsigma(i) + dsigma(j))
              end do
           end do
           ! compute updated z.
           do i = 1,k
              z(i) = sign(sqrt(abs(work(iwk3i + i))),z(i))
           end do
           ! update vf and vl.
           do j = 1,k
              diflj = difl(j)
              dj = d(j)
              dsigj = -dsigma(j)
              if (j < k) then
                 difrj = -difr(j,1)
                 dsigjp = -dsigma(j + 1)
              end if
              work(j) = -z(j)/diflj/(dsigma(j) + dj)
              do i = 1,j - 1
                 work(i) = z(i)/(la_${ri}$lamc3(dsigma(i),dsigj) - diflj)/(dsigma(i) &
                           + dj)
              end do
              do i = j + 1,k
                 work(i) = z(i)/(la_${ri}$lamc3(dsigma(i),dsigjp) + difrj)/(dsigma(i &
                           ) + dj)
              end do
              temp = la_${ri}$nrm2(k,work,1)
              work(iwk2i + j) = la_${ri}$dot(k,work,1,vf,1)/temp
              work(iwk3i + j) = la_${ri}$dot(k,work,1,vl,1)/temp
              if (icompq == 1) then
                 difr(j,2) = temp
              end if
           end do
           call la_${ri}$copy(k,work(iwk2),1,vf,1)
           call la_${ri}$copy(k,work(iwk3),1,vl,1)
           return
     end subroutine la_${ri}$lasd8
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD3: finds all the square roots of the roots of the secular
     !> equation, as defined by the values in D and Z.  It makes the
     !> appropriate calls to ${ri.upper()}$LASD4 and then updates the singular
     !> vectors by matrix multiplication.
     !> This code makes very mild assumptions about floating point
     !> arithmetic. It will work on machines with a guard digit in
     !> add/subtract, or on those binary machines without guard digits
     !> which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2.
     !> It could conceivably fail on hexadecimal or decimal machines
     !> without guard digits, but we know of none.
     !> ${ri.upper()}$LASD3 is called from ${ri.upper()}$LASD1.

     pure subroutine la_${ri}$lasd3(nl,nr,sqre,k,d,q,ldq,dsigma,u,ldu,u2,ldu2,vt,ldvt, &
                vt2,ldvt2,idxc,ctot,z,info)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: k,ldq,ldu,ldu2,ldvt,ldvt2,nl,nr,sqre
           ! Array Arguments
           integer(ilp),intent(in) :: ctot(*),idxc(*)
           real(${rk}$),intent(out) :: d(*),q(ldq,*),u(ldu,*),vt(ldvt,*)
           real(${rk}$),intent(inout) :: dsigma(*),vt2(ldvt2,*),z(*)
           real(${rk}$),intent(in) :: u2(ldu2,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: ctemp,i,j,jc,ktemp,m,n,nlp1,nlp2,nrp1
           real(${rk}$) :: rho,temp
           ! Intrinsic Functions
           intrinsic :: abs,sign,sqrt
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (nl < 1) then
              info = -1
           else if (nr < 1) then
              info = -2
           else if ((sqre /= 1) .and. (sqre /= 0)) then
              info = -3
           end if
           n = nl + nr + 1
           m = n + sqre
           nlp1 = nl + 1
           nlp2 = nl + 2
           if ((k < 1) .or. (k > n)) then
              info = -4
           else if (ldq < k) then
              info = -7
           else if (ldu < n) then
              info = -10
           else if (ldu2 < n) then
              info = -12
           else if (ldvt < m) then
              info = -14
           else if (ldvt2 < m) then
              info = -16
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD3',-info)
              return
           end if
           ! quick return if possible
           if (k == 1) then
              d(1) = abs(z(1))
              call la_${ri}$copy(m,vt2(1,1),ldvt2,vt(1,1),ldvt)
              if (z(1) > zero) then
                 call la_${ri}$copy(n,u2(1,1),1,u(1,1),1)
              else
                 do i = 1,n
                    u(i,1) = -u2(i,1)
                 end do
              end if
              return
           end if
           ! modify values dsigma(i) to make sure all dsigma(i)-dsigma(j) can
           ! be computed with high relative accuracy (barring over/underflow).
           ! this is a problem on machines without a guard digit in
           ! add/subtract (cray xmp, cray ymp, cray c 90 and cray 2).
           ! the following code replaces dsigma(i) by 2*dsigma(i)-dsigma(i),
           ! which on any of these machines zeros out the bottommost
           ! bit of dsigma(i) if it is 1; this makes the subsequent
           ! subtractions dsigma(i)-dsigma(j) unproblematic when cancellation
           ! occurs. on binary machines with a guard digit (almost all
           ! machines) it does not change dsigma(i) at all. on hexadecimal
           ! and decimal machines with a guard digit, it slightly
           ! changes the bottommost bits of dsigma(i). it does not account
           ! for hexadecimal or decimal machines without guard digits
           ! (we know of none). we use a subroutine call to compute
           ! 2*dsigma(i) to prevent optimizing compilers from eliminating
           ! this code.
           do i = 1,k
              dsigma(i) = la_${ri}$lamc3(dsigma(i),dsigma(i)) - dsigma(i)
           end do
           ! keep a copy of z.
           call la_${ri}$copy(k,z,1,q,1)
           ! normalize z.
           rho = la_${ri}$nrm2(k,z,1)
           call la_${ri}$lascl('G',0,0,rho,one,k,1,z,k,info)
           rho = rho*rho
           ! find the new singular values.
           do j = 1,k
              call la_${ri}$lasd4(k,j,dsigma,z,u(1,j),rho,d(j),vt(1,j),info)

              ! if the zero finder fails, report the convergence failure.
              if (info /= 0) then
                 return
              end if
           end do
           ! compute updated z.
           do i = 1,k
              z(i) = u(i,k)*vt(i,k)
              do j = 1,i - 1
                 z(i) = z(i)*(u(i,j)*vt(i,j)/(dsigma(i) - dsigma(j))/(dsigma(i &
                           ) + dsigma(j)))
              end do
              do j = i,k - 1
                 z(i) = z(i)*(u(i,j)*vt(i,j)/(dsigma(i) - dsigma(j + 1))/(dsigma( &
                           i) + dsigma(j + 1)))
              end do
              z(i) = sign(sqrt(abs(z(i))),q(i,1))
           end do
           ! compute left singular vectors of the modified diagonal matrix,
           ! and store related information for the right singular vectors.
           do i = 1,k
              vt(1,i) = z(1)/u(1,i)/vt(1,i)
              u(1,i) = negone
              do j = 2,k
                 vt(j,i) = z(j)/u(j,i)/vt(j,i)
                 u(j,i) = dsigma(j)*vt(j,i)
              end do
              temp = la_${ri}$nrm2(k,u(1,i),1)
              q(1,i) = u(1,i)/temp
              do j = 2,k
                 jc = idxc(j)
                 q(j,i) = u(jc,i)/temp
              end do
           end do
           ! update the left singular vector matrix.
           if (k == 2) then
              call la_${ri}$gemm('N','N',n,k,k,one,u2,ldu2,q,ldq,zero,u,ldu)
              go to 100
           end if
           if (ctot(1) > 0) then
              call la_${ri}$gemm('N','N',nl,k,ctot(1),one,u2(1,2),ldu2,q(2,1),ldq, &
                         zero,u(1,1),ldu)
              if (ctot(3) > 0) then
                 ktemp = 2 + ctot(1) + ctot(2)
                 call la_${ri}$gemm('N','N',nl,k,ctot(3),one,u2(1,ktemp),ldu2,q( &
                           ktemp,1),ldq,one,u(1,1),ldu)
              end if
           else if (ctot(3) > 0) then
              ktemp = 2 + ctot(1) + ctot(2)
              call la_${ri}$gemm('N','N',nl,k,ctot(3),one,u2(1,ktemp),ldu2,q(ktemp, &
                        1),ldq,zero,u(1,1),ldu)
           else
              call la_${ri}$lacpy('F',nl,k,u2,ldu2,u,ldu)
           end if
           call la_${ri}$copy(k,q(1,1),ldq,u(nlp1,1),ldu)
           ktemp = 2 + ctot(1)
           ctemp = ctot(2) + ctot(3)
           call la_${ri}$gemm('N','N',nr,k,ctemp,one,u2(nlp2,ktemp),ldu2,q(ktemp,1), &
                     ldq,zero,u(nlp2,1),ldu)
           ! generate the right singular vectors.
           100 continue
           do i = 1,k
              temp = la_${ri}$nrm2(k,vt(1,i),1)
              q(i,1) = vt(1,i)/temp
              do j = 2,k
                 jc = idxc(j)
                 q(i,j) = vt(jc,i)/temp
              end do
           end do
           ! update the right singular vector matrix.
           if (k == 2) then
              call la_${ri}$gemm('N','N',k,m,k,one,q,ldq,vt2,ldvt2,zero,vt,ldvt)

              return
           end if
           ktemp = 1 + ctot(1)
           call la_${ri}$gemm('N','N',k,nlp1,ktemp,one,q(1,1),ldq,vt2(1,1),ldvt2, &
                     zero,vt(1,1),ldvt)
           ktemp = 2 + ctot(1) + ctot(2)
           if (ktemp <= ldvt2) call la_${ri}$gemm('N','N',k,nlp1,ctot(3),one,q(1,ktemp), &
                     ldq,vt2(ktemp,1),ldvt2,one,vt(1,1),ldvt)
           ktemp = ctot(1) + 1
           nrp1 = nr + sqre
           if (ktemp > 1) then
              do i = 1,k
                 q(i,ktemp) = q(i,1)
              end do
              do i = nlp2,m
                 vt2(ktemp,i) = vt2(1,i)
              end do
           end if
           ctemp = 1 + ctot(2) + ctot(3)
           call la_${ri}$gemm('N','N',k,nrp1,ctemp,one,q(1,ktemp),ldq,vt2(ktemp,nlp2) &
                     ,ldvt2,zero,vt(1,nlp2),ldvt)
           return
     end subroutine la_${ri}$lasd3
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD6: computes the SVD of an updated upper bidiagonal matrix B
     !> obtained by merging two smaller ones by appending a row. This
     !> routine is used only for the problem which requires all singular
     !> values and optionally singular vector matrices in factored form.
     !> B is an N-by-M matrix with N = NL + NR + 1 and M = N + SQRE.
     !> A related subroutine, ${ri.upper()}$LASD1, handles the case in which all singular
     !> values and singular vectors of the bidiagonal matrix are desired.
     !> ${ri.upper()}$LASD6 computes the SVD as follows:
     !> ( D1(in)    0    0       0 )
     !> B = U(in) * (   Z1**T   a   Z2**T    b ) * VT(in)
     !> (   0       0   D2(in)   0 )
     !> = U(out) * ( D(out) 0) * VT(out)
     !> where Z**T = (Z1**T a Z2**T b) = u**T VT**T, and u is a vector of dimension M
     !> with ALPHA and BETA in the NL+1 and NL+2 th entries and zeros
     !> elsewhere; and the entry b is empty if SQRE = 0.
     !> The singular values of B can be computed using D1, D2, the first
     !> components of all the right singular vectors of the lower block, and
     !> the last components of all the right singular vectors of the upper
     !> block. These components are stored and updated in VF and VL,
     !> respectively, in ${ri.upper()}$LASD6. Hence U and VT are not explicitly
     !> referenced.
     !> The singular values are stored in D. The algorithm consists of two
     !> stages:
     !> The first stage consists of deflating the size of the problem
     !> when there are multiple singular values or if there is a zero
     !> in the Z vector. For each such occurrence the dimension of the
     !> secular equation problem is reduced by one. This stage is
     !> performed by the routine ${ri.upper()}$LASD7.
     !> The second stage consists of calculating the updated
     !> singular values. This is done by finding the roots of the
     !> secular equation via the routine ${ri.upper()}$LASD4 (as called by ${ri.upper()}$LASD8).
     !> This routine also updates VF and VL and computes the distances
     !> between the updated singular values and the old singular
     !> values.
     !> ${ri.upper()}$LASD6 is called from ${ri.upper()}$LASDA.

     pure subroutine la_${ri}$lasd6(icompq,nl,nr,sqre,d,vf,vl,alpha,beta,idxq,perm, &
     givptr,givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,work,iwork,info)
        use la_constants_${rk}$

        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: givptr,info,k
           integer(ilp),intent(in) :: icompq,ldgcol,ldgnum,nl,nr,sqre
           real(${rk}$),intent(inout) :: alpha,beta
           real(${rk}$),intent(out) :: c,s
           ! Array Arguments
           integer(ilp),intent(out) :: givcol(ldgcol,*),iwork(*),perm(*)
           integer(ilp),intent(inout) :: idxq(*)
           real(${rk}$),intent(inout) :: d(*),vf(*),vl(*)
           real(${rk}$),intent(out) :: difl(*),difr(*),givnum(ldgnum,*),poles(ldgnum,*),work(*), &
                     z(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,idx,idxc,idxp,isigma,ivfw,ivlw,iw,m,n,n1,n2
           real(${rk}$) :: orgnrm
           ! Intrinsic Functions
           intrinsic :: abs,max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           n = nl + nr + 1
           m = n + sqre
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (nl < 1) then
              info = -2
           else if (nr < 1) then
              info = -3
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -4
           else if (ldgcol < n) then
              info = -14
           else if (ldgnum < n) then
              info = -16
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD6',-info)
              return
           end if
           ! the following values are for bookkeeping purposes only.  they are
           ! integer pointers which indicate the portion of the workspace
           ! used by a particular array in la_${ri}$lasd7 and la_${ri}$lasd8.
           isigma = 1
           iw = isigma + n
           ivfw = iw + m
           ivlw = ivfw + m
           idx = 1
           idxc = idx + n
           idxp = idxc + n
           ! scale.
           orgnrm = max(abs(alpha),abs(beta))
           d(nl + 1) = zero
           do i = 1,n
              if (abs(d(i)) > orgnrm) then
                 orgnrm = abs(d(i))
              end if
           end do
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,1,d,n,info)
           alpha = alpha/orgnrm
           beta = beta/orgnrm
           ! sort and deflate singular values.
           call la_${ri}$lasd7(icompq,nl,nr,sqre,k,d,z,work(iw),vf,work(ivfw),vl, &
           work(ivlw),alpha,beta,work(isigma),iwork(idx),iwork(idxp),idxq,perm, &
                     givptr,givcol,ldgcol,givnum,ldgnum,c,s,info)
           ! solve secular equation, compute difl, difr, and update vf, vl.
           call la_${ri}$lasd8(icompq,k,d,z,vf,vl,difl,difr,ldgnum,work(isigma),work( &
                     iw),info)
           ! report the possible convergence failure.
           if (info /= 0) then
              return
           end if
           ! save the poles if icompq = 1.
           if (icompq == 1) then
              call la_${ri}$copy(k,d,1,poles(1,1),1)
              call la_${ri}$copy(k,work(isigma),1,poles(1,2),1)
           end if
           ! unscale.
           call la_${ri}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
           ! prepare the idxq sorting permutation.
           n1 = k
           n2 = n - k
           call la_${ri}$lamrg(n1,n2,d,1,-1,idxq)
           return
     end subroutine la_${ri}$lasd6
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD2: merges the two sets of singular values together into a single
     !> sorted set.  Then it tries to deflate the size of the problem.
     !> There are two ways in which deflation can occur:  when two or more
     !> singular values are close together or if there is a tiny entry in the
     !> Z vector.  For each such occurrence the order of the related secular
     !> equation problem is reduced by one.
     !> ${ri.upper()}$LASD2 is called from ${ri.upper()}$LASD1.

     pure subroutine la_${ri}$lasd2(nl,nr,sqre,k,d,z,alpha,beta,u,ldu,vt,ldvt,dsigma, &
               u2,ldu2,vt2,ldvt2,idxp,idx,idxc,idxq,coltyp,info)
        use la_constants_${rk}$,only:zero,one,two,eight
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info,k
           integer(ilp),intent(in) :: ldu,ldu2,ldvt,ldvt2,nl,nr,sqre
           real(${rk}$),intent(in) :: alpha,beta
           ! Array Arguments
           integer(ilp),intent(out) :: coltyp(*),idx(*),idxc(*),idxp(*)
           integer(ilp),intent(inout) :: idxq(*)
           real(${rk}$),intent(inout) :: d(*),u(ldu,*),vt(ldvt,*)
           real(${rk}$),intent(out) :: dsigma(*),u2(ldu2,*),vt2(ldvt2,*),z(*)
        ! =====================================================================

           ! Local Arrays
           integer(ilp) :: ctot(4),psm(4)
           ! Local Scalars
           integer(ilp) :: ct,i,idxi,idxj,idxjp,j,jp,jprev,k2,m,n,nlp1,nlp2
           real(${rk}$) :: c,eps,hlftol,s,tau,tol,z1
           ! Intrinsic Functions
           intrinsic :: abs,max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (nl < 1) then
              info = -1
           else if (nr < 1) then
              info = -2
           else if ((sqre /= 1) .and. (sqre /= 0)) then
              info = -3
           end if
           n = nl + nr + 1
           m = n + sqre
           if (ldu < n) then
              info = -10
           else if (ldvt < m) then
              info = -12
           else if (ldu2 < n) then
              info = -15
           else if (ldvt2 < m) then
              info = -17
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD2',-info)
              return
           end if
           nlp1 = nl + 1
           nlp2 = nl + 2
           ! generate the first part of the vector z; and move the singular
           ! values in the first part of d one position backward.
           z1 = alpha*vt(nlp1,nlp1)
           z(1) = z1
           do i = nl,1,-1
              z(i + 1) = alpha*vt(i,nlp1)
              d(i + 1) = d(i)
              idxq(i + 1) = idxq(i) + 1
           end do
           ! generate the second part of the vector z.
           do i = nlp2,m
              z(i) = beta*vt(i,nlp2)
           end do
           ! initialize some reference arrays.
           do i = 2,nlp1
              coltyp(i) = 1
           end do
           do i = nlp2,n
              coltyp(i) = 2
           end do
           ! sort the singular values into increasing order
           do i = nlp2,n
              idxq(i) = idxq(i) + nlp1
           end do
           ! dsigma, idxc, idxc, and the first column of u2
           ! are used as storage space.
           do i = 2,n
              dsigma(i) = d(idxq(i))
              u2(i,1) = z(idxq(i))
              idxc(i) = coltyp(idxq(i))
           end do
           call la_${ri}$lamrg(nl,nr,dsigma(2),1,1,idx(2))
           do i = 2,n
              idxi = 1 + idx(i)
              d(i) = dsigma(idxi)
              z(i) = u2(idxi,1)
              coltyp(i) = idxc(idxi)
           end do
           ! calculate the allowable deflation tolerance
           eps = la_${ri}$lamch('EPSILON')
           tol = max(abs(alpha),abs(beta))
           tol = eight*eps*max(abs(d(n)),tol)
           ! there are 2 kinds of deflation -- first a value in the z-vector
           ! is small, second two (or more) singular values are very close
           ! together (their difference is small).
           ! if the value in the z-vector is small, we simply permute the
           ! array so that the corresponding singular value is moved to the
           ! end.
           ! if two values in the d-vector are close, we perform a two-sided
           ! rotation designed to make one of the corresponding z-vector
           ! entries zero, and then permute the array so that the deflated
           ! singular value is moved to the end.
           ! if there are multiple singular values then the problem deflates.
           ! here the number of equal singular values are found.  as each equal
           ! singular value is found, an elementary reflector is computed to
           ! rotate the corresponding singular subspace so that the
           ! corresponding components of z are zero in this new basis.
           k = 1
           k2 = n + 1
           do j = 2,n
              if (abs(z(j)) <= tol) then
                 ! deflate due to small z component.
                 k2 = k2 - 1
                 idxp(k2) = j
                 coltyp(j) = 4
                 if (j == n) go to 120
              else
                 jprev = j
                 go to 90
              end if
           end do
           90 continue
           j = jprev
           100 continue
           j = j + 1
           if (j > n) go to 110
           if (abs(z(j)) <= tol) then
              ! deflate due to small z component.
              k2 = k2 - 1
              idxp(k2) = j
              coltyp(j) = 4
           else
              ! check if singular values are close enough to allow deflation.
              if (abs(d(j) - d(jprev)) <= tol) then
                 ! deflation is possible.
                 s = z(jprev)
                 c = z(j)
                 ! find sqrt(a**2+b**2) without overflow or
                 ! destructive underflow.
                 tau = la_${ri}$lapy2(c,s)
                 c = c/tau
                 s = -s/tau
                 z(j) = tau
                 z(jprev) = zero
                 ! apply back the givens rotation to the left and right
                 ! singular vector matrices.
                 idxjp = idxq(idx(jprev) + 1)
                 idxj = idxq(idx(j) + 1)
                 if (idxjp <= nlp1) then
                    idxjp = idxjp - 1
                 end if
                 if (idxj <= nlp1) then
                    idxj = idxj - 1
                 end if
                 call la_${ri}$rot(n,u(1,idxjp),1,u(1,idxj),1,c,s)
                 call la_${ri}$rot(m,vt(idxjp,1),ldvt,vt(idxj,1),ldvt,c,s)
                 if (coltyp(j) /= coltyp(jprev)) then
                    coltyp(j) = 3
                 end if
                 coltyp(jprev) = 4
                 k2 = k2 - 1
                 idxp(k2) = jprev
                 jprev = j
              else
                 k = k + 1
                 u2(k,1) = z(jprev)
                 dsigma(k) = d(jprev)
                 idxp(k) = jprev
                 jprev = j
              end if
           end if
           go to 100
           110 continue
           ! record the last singular value.
           k = k + 1
           u2(k,1) = z(jprev)
           dsigma(k) = d(jprev)
           idxp(k) = jprev
           120 continue
           ! count up the total number of the various types of columns, then
           ! form a permutation which positions the four column types into
           ! four groups of uniform structure (although one or more of these
           ! groups may be empty).
           do j = 1,4
              ctot(j) = 0
           end do
           do j = 2,n
              ct = coltyp(j)
              ctot(ct) = ctot(ct) + 1
           end do
           ! psm(*) = position in submatrix (of types 1 through 4)
           psm(1) = 2
           psm(2) = 2 + ctot(1)
           psm(3) = psm(2) + ctot(2)
           psm(4) = psm(3) + ctot(3)
           ! fill out the idxc array so that the permutation which it induces
           ! will place all type-1 columns first, all type-2 columns next,
           ! then all type-3's, and finally all type-4's, starting from the
           ! second column. this applies similarly to the rows of vt.
           do j = 2,n
              jp = idxp(j)
              ct = coltyp(jp)
              idxc(psm(ct)) = j
              psm(ct) = psm(ct) + 1
           end do
           ! sort the singular values and corresponding singular vectors into
           ! dsigma, u2, and vt2 respectively.  the singular values/vectors
           ! which were not deflated go into the first k slots of dsigma, u2,
           ! and vt2 respectively, while those which were deflated go into the
           ! last n - k slots, except that the first column/row will be treated
           ! separately.
           do j = 2,n
              jp = idxp(j)
              dsigma(j) = d(jp)
              idxj = idxq(idx(idxp(idxc(j))) + 1)
              if (idxj <= nlp1) then
                 idxj = idxj - 1
              end if
              call la_${ri}$copy(n,u(1,idxj),1,u2(1,j),1)
              call la_${ri}$copy(m,vt(idxj,1),ldvt,vt2(j,1),ldvt2)
           end do
           ! determine dsigma(1), dsigma(2) and z(1)
           dsigma(1) = zero
           hlftol = tol/two
           if (abs(dsigma(2)) <= hlftol) dsigma(2) = hlftol
           if (m > n) then
              z(1) = la_${ri}$lapy2(z1,z(m))
              if (z(1) <= tol) then
                 c = one
                 s = zero
                 z(1) = tol
              else
                 c = z1/z(1)
                 s = z(m)/z(1)
              end if
           else
              if (abs(z1) <= tol) then
                 z(1) = tol
              else
                 z(1) = z1
              end if
           end if
           ! move the rest of the updating row to z.
           call la_${ri}$copy(k - 1,u2(2,1),1,z(2),1)
           ! determine the first column of u2, the first row of vt2 and the
           ! last row of vt.
           call la_${ri}$laset('A',n,1,zero,zero,u2,ldu2)
           u2(nlp1,1) = one
           if (m > n) then
              do i = 1,nlp1
                 vt(m,i) = -s*vt(nlp1,i)
                 vt2(1,i) = c*vt(nlp1,i)
              end do
              do i = nlp2,m
                 vt2(1,i) = s*vt(m,i)
                 vt(m,i) = c*vt(m,i)
              end do
           else
              call la_${ri}$copy(m,vt(nlp1,1),ldvt,vt2(1,1),ldvt2)
           end if
           if (m > n) then
              call la_${ri}$copy(m,vt(m,1),ldvt,vt2(m,1),ldvt2)
           end if
           ! the deflated singular values and their corresponding vectors go
           ! into the back of d, u, and v respectively.
           if (n > k) then
              call la_${ri}$copy(n - k,dsigma(k + 1),1,d(k + 1),1)
              call la_${ri}$lacpy('A',n,n - k,u2(1,k + 1),ldu2,u(1,k + 1),ldu)
              call la_${ri}$lacpy('A',n - k,m,vt2(k + 1,1),ldvt2,vt(k + 1,1),ldvt)
           end if
           ! copy ctot into coltyp for referencing in la_${ri}$lasd3.
           do j = 1,4
              coltyp(j) = ctot(j)
           end do
           return
     end subroutine la_${ri}$lasd2
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASD1: computes the SVD of an upper bidiagonal N-by-M matrix B,
     !> where N = NL + NR + 1 and M = N + SQRE. ${ri.upper()}$LASD1 is called from ${ri.upper()}$LASD0.
     !> A related subroutine ${ri.upper()}$LASD7 handles the case in which the singular
     !> values (and the singular vectors in factored form) are desired.
     !> ${ri.upper()}$LASD1 computes the SVD as follows:
     !> ( D1(in)    0    0       0 )
     !> B = U(in) * (   Z1**T   a   Z2**T    b ) * VT(in)
     !> (   0       0   D2(in)   0 )
     !> = U(out) * ( D(out) 0) * VT(out)
     !> where Z**T = (Z1**T a Z2**T b) = u**T VT**T, and u is a vector of dimension M
     !> with ALPHA and BETA in the NL+1 and NL+2 th entries and zeros
     !> elsewhere; and the entry b is empty if SQRE = 0.
     !> The left singular vectors of the original matrix are stored in U, and
     !> the transpose of the right singular vectors are stored in VT, and the
     !> singular values are in D.  The algorithm consists of three stages:
     !> The first stage consists of deflating the size of the problem
     !> when there are multiple singular values or when there are zeros in
     !> the Z vector.  For each such occurrence the dimension of the
     !> secular equation problem is reduced by one.  This stage is
     !> performed by the routine ${ri.upper()}$LASD2.
     !> The second stage consists of calculating the updated
     !> singular values. This is done by finding the square roots of the
     !> roots of the secular equation via the routine ${ri.upper()}$LASD4 (as called
     !> by ${ri.upper()}$LASD3). This routine also calculates the singular vectors of
     !> the current problem.
     !> The final stage consists of computing the updated singular vectors
     !> directly using the updated singular values.  The singular vectors
     !> for the current problem are multiplied with the singular vectors
     !> from the overall problem.

     pure subroutine la_${ri}$lasd1(nl,nr,sqre,d,alpha,beta,u,ldu,vt,ldvt,idxq,iwork, &
               work,info)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldu,ldvt,nl,nr,sqre
           real(${rk}$),intent(inout) :: alpha,beta
           ! Array Arguments
           integer(ilp),intent(inout) :: idxq(*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: d(*),u(ldu,*),vt(ldvt,*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: coltyp,i,idx,idxc,idxp,iq,isigma,iu2,ivt2,iz,k,ldq,ldu2, &
                     ldvt2,m,n,n1,n2
           real(${rk}$) :: orgnrm
           ! Intrinsic Functions
           intrinsic :: abs,max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (nl < 1) then
              info = -1
           else if (nr < 1) then
              info = -2
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -3
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD1',-info)
              return
           end if
           n = nl + nr + 1
           m = n + sqre
           ! the following values are for bookkeeping purposes only.  they are
           ! integer pointers which indicate the portion of the workspace
           ! used by a particular array in la_${ri}$lasd2 and la_${ri}$lasd3.
           ldu2 = n
           ldvt2 = m
           iz = 1
           isigma = iz + m
           iu2 = isigma + n
           ivt2 = iu2 + ldu2*n
           iq = ivt2 + ldvt2*m
           idx = 1
           idxc = idx + n
           coltyp = idxc + n
           idxp = coltyp + n
           ! scale.
           orgnrm = max(abs(alpha),abs(beta))
           d(nl + 1) = zero
           do i = 1,n
              if (abs(d(i)) > orgnrm) then
                 orgnrm = abs(d(i))
              end if
           end do
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,1,d,n,info)
           alpha = alpha/orgnrm
           beta = beta/orgnrm
           ! deflate singular values.
           call la_${ri}$lasd2(nl,nr,sqre,k,d,work(iz),alpha,beta,u,ldu,vt,ldvt,work( &
            isigma),work(iu2),ldu2,work(ivt2),ldvt2,iwork(idxp),iwork(idx),iwork( &
                      idxc),idxq,iwork(coltyp),info)
           ! solve secular equation and update singular vectors.
           ldq = k
           call la_${ri}$lasd3(nl,nr,sqre,k,d,work(iq),ldq,work(isigma),u,ldu,work( &
           iu2),ldu2,vt,ldvt,work(ivt2),ldvt2,iwork(idxc),iwork(coltyp),work(iz), &
                     info)
#:if rk == "sp"
           ! report the possible convergence failure.
#:else
           ! report the convergence failure.
#:endif
           if (info /= 0) then
              return
           end if
           ! unscale.
           call la_${ri}$lascl('G',0,0,one,orgnrm,n,1,d,n,info)
           ! prepare the idxq sorting permutation.
           n1 = k
           n2 = n - k
           call la_${ri}$lamrg(n1,n2,d,1,-1,idxq)
           return
     end subroutine la_${ri}$lasd1
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$BDSDC: computes the singular value decomposition (SVD) of a real
     !> N-by-N (upper or lower) bidiagonal matrix B:  B = U * S * VT,
     !> using a divide and conquer method, where S is a diagonal matrix
     !> with non-negative diagonal elements (the singular values of B), and
     !> U and VT are orthogonal matrices of left and right singular vectors,
     !> respectively. ${ri.upper()}$BDSDC can be used to compute all singular values,
     !> and optionally, singular vectors or singular vectors in compact form.
     !> This code makes very mild assumptions about floating point
     !> arithmetic. It will work on machines with a guard digit in
     !> add/subtract, or on those binary machines without guard digits
     !> which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2.
     !> It could conceivably fail on hexadecimal or decimal machines
     !> without guard digits, but we know of none.  See ${ri.upper()}$LASD3 for details.
     !> The code currently calls ${ri.upper()}$LASDQ if singular values only are desired.
     !> However, it can be slightly modified to compute singular values
     !> using the divide and conquer method.

     pure subroutine la_${ri}$bdsdc(uplo,compq,n,d,e,u,ldu,vt,ldvt,q,iq,work,iwork, &
               info)
        use la_constants_${rk}$,only:zero,one,two
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: compq,uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldu,ldvt,n
           ! Array Arguments
           integer(ilp),intent(out) :: iq(*),iwork(*)
           real(${rk}$),intent(inout) :: d(*),e(*)
           real(${rk}$),intent(out) :: q(*),u(ldu,*),vt(ldvt,*),work(*)
        ! =====================================================================
        ! changed dimension statement in comment describing e from (n) to
        ! (n-1).  sven, 17 feb 05.
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: difl,difr,givcol,givnum,givptr,i,ic,icompq,ierr,ii,is,iu, &
           iuplo,ivt,j,k,kk,mlvl,nm1,nsize,perm,poles,qstart,smlsiz,smlszp,sqre, &
                     start,wstart,z
           real(${rk}$) :: cs,eps,orgnrm,p,r,sn
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: real,abs,int,log,sign
#:else
           intrinsic :: abs,real,int,log,sign
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           iuplo = 0
           if (la_lsame(uplo,'U')) iuplo = 1
           if (la_lsame(uplo,'L')) iuplo = 2
           if (la_lsame(compq,'N')) then
              icompq = 0
           else if (la_lsame(compq,'P')) then
              icompq = 1
           else if (la_lsame(compq,'I')) then
              icompq = 2
           else
              icompq = -1
           end if
           if (iuplo == 0) then
              info = -1
           else if (icompq < 0) then
              info = -2
           else if (n < 0) then
              info = -3
           else if ((ldu < 1) .or. ((icompq == 2) .and. (ldu < n))) then
              info = -7
           else if ((ldvt < 1) .or. ((icompq == 2) .and. (ldvt < n))) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$BDSDC',-info)
              return
           end if
           ! quick return if possible
           if (n == 0) return
           smlsiz = la_ilaenv(9,'${ri.upper()}$BDSDC',' ',0,0,0,0)
           if (n == 1) then
              if (icompq == 1) then
                 q(1) = sign(one,d(1))
                 q(1 + smlsiz*n) = one
              else if (icompq == 2) then
                 u(1,1) = sign(one,d(1))
                 vt(1,1) = one
              end if
              d(1) = abs(d(1))
              return
           end if
           nm1 = n - 1
           ! if matrix lower bidiagonal, rotate to be upper bidiagonal
           ! by applying givens rotations on the left
           wstart = 1
           qstart = 3
           if (icompq == 1) then
              call la_${ri}$copy(n,d,1,q(1),1)
              call la_${ri}$copy(n - 1,e,1,q(n + 1),1)
           end if
           if (iuplo == 2) then
              qstart = 5
              if (icompq == 2) wstart = 2*n - 1
              do i = 1,n - 1
                 call la_${ri}$lartg(d(i),e(i),cs,sn,r)
                 d(i) = r
                 e(i) = sn*d(i + 1)
                 d(i + 1) = cs*d(i + 1)
                 if (icompq == 1) then
                    q(i + 2*n) = cs
                    q(i + 3*n) = sn
                 else if (icompq == 2) then
                    work(i) = cs
                    work(nm1 + i) = -sn
                 end if
              end do
           end if
           ! if icompq = 0, use la_${ri}$lasdq to compute the singular values.
           if (icompq == 0) then
              ! ignore wstart, instead using work( 1 ), since the two vectors
              ! for cs and -sn above are added only if icompq == 2,
              ! and adding them exceeds documented work size of 4*n.
              call la_${ri}$lasdq('U',0,n,0,0,0,d,e,vt,ldvt,u,ldu,u,ldu,work(1), &
                        info)
              go to 40
           end if
           ! if n is smaller than the minimum divide size smlsiz, then solve
           ! the problem with another solver.
           if (n <= smlsiz) then
              if (icompq == 2) then
                 call la_${ri}$laset('A',n,n,zero,one,u,ldu)
                 call la_${ri}$laset('A',n,n,zero,one,vt,ldvt)
                 call la_${ri}$lasdq('U',0,n,n,n,0,d,e,vt,ldvt,u,ldu,u,ldu,work( &
                           wstart),info)
              else if (icompq == 1) then
                 iu = 1
                 ivt = iu + n
                 call la_${ri}$laset('A',n,n,zero,one,q(iu + (qstart - 1)*n),n)
                 call la_${ri}$laset('A',n,n,zero,one,q(ivt + (qstart - 1)*n),n)
                 call la_${ri}$lasdq('U',0,n,n,n,0,d,e,q(ivt + (qstart - 1)*n),n,q(iu + ( &
                           qstart - 1)*n),n,q(iu + (qstart - 1)*n),n,work(wstart),info)
              end if
              go to 40
           end if
           if (icompq == 2) then
              call la_${ri}$laset('A',n,n,zero,one,u,ldu)
              call la_${ri}$laset('A',n,n,zero,one,vt,ldvt)
           end if
           ! scale.
           orgnrm = la_${ri}$lanst('M',n,d,e)
           if (orgnrm == zero) return
           call la_${ri}$lascl('G',0,0,orgnrm,one,n,1,d,n,ierr)
           call la_${ri}$lascl('G',0,0,orgnrm,one,nm1,1,e,nm1,ierr)
#:if rk == "sp"
           eps = la_${ri}$lamch('EPSILON')
#:else
           eps = (0.9e+0_${rk}$)*la_${ri}$lamch('EPSILON')
#:endif
           mlvl = int(log(real(n,KIND=${rk}$)/real(smlsiz + 1,KIND=${rk}$))/log(two),KIND=ilp) + &
                     1
           smlszp = smlsiz + 1
           if (icompq == 1) then
              iu = 1
              ivt = 1 + smlsiz
              difl = ivt + smlszp
              difr = difl + mlvl
              z = difr + mlvl*2
              ic = z + mlvl
              is = ic + 1
              poles = is + 1
              givnum = poles + 2*mlvl
              k = 1
              givptr = 2
              perm = 3
              givcol = perm + mlvl
           end if
           do i = 1,n
              if (abs(d(i)) < eps) then
                 d(i) = sign(eps,d(i))
              end if
           end do
           start = 1
           sqre = 0
           loop_30: do i = 1,nm1
              if ((abs(e(i)) < eps) .or. (i == nm1)) then
                 ! subproblem found. first determine its size and then
                 ! apply divide and conquer on it.
                 if (i < nm1) then
                    ! a subproblem with e(i) small for i < nm1.
                    nsize = i - start + 1
                 else if (abs(e(i)) >= eps) then
                    ! a subproblem with e(nm1) not too small but i = nm1.
                    nsize = n - start + 1
                 else
                    ! a subproblem with e(nm1) small. this implies an
                    ! 1-by-1 subproblem at d(n). solve this 1-by-1 problem
                    ! first.
                    nsize = i - start + 1
                    if (icompq == 2) then
                       u(n,n) = sign(one,d(n))
                       vt(n,n) = one
                    else if (icompq == 1) then
                       q(n + (qstart - 1)*n) = sign(one,d(n))
                       q(n + (smlsiz + qstart - 1)*n) = one
                    end if
                    d(n) = abs(d(n))
                 end if
                 if (icompq == 2) then
                    call la_${ri}$lasd0(nsize,sqre,d(start),e(start),u(start,start), &
                              ldu,vt(start,start),ldvt,smlsiz,iwork,work(wstart),info)
                 else
                    call la_${ri}$lasda(icompq,smlsiz,nsize,sqre,d(start),e(start),q( &
                    start + (iu + qstart - 2)*n),n,q(start + (ivt + qstart - 2)*n),iq(start + k*n),q( &
                     start + (difl + qstart - 2)*n),q(start + (difr + qstart - 2)*n),q(start + (z + &
                     qstart - 2)*n),q(start + (poles + qstart - 2)*n),iq(start + givptr*n),iq( &
                     start + givcol*n),n,iq(start + perm*n),q(start + (givnum + qstart - 2)*n),q( &
                     start + (ic + qstart - 2)*n),q(start + (is + qstart - 2)*n),work(wstart),iwork, &
                                info)
                 end if
                 if (info /= 0) then
                    return
                 end if
                 start = i + 1
              end if
           end do loop_30
           ! unscale
           call la_${ri}$lascl('G',0,0,one,orgnrm,n,1,d,n,ierr)
           40 continue
           ! use selection sort to minimize swaps of singular vectors
           do ii = 2,n
              i = ii - 1
              kk = i
              p = d(i)
              do j = ii,n
                 if (d(j) > p) then
                    kk = j
                    p = d(j)
                 end if
              end do
              if (kk /= i) then
                 d(kk) = d(i)
                 d(i) = p
                 if (icompq == 1) then
                    iq(i) = kk
                 else if (icompq == 2) then
                    call la_${ri}$swap(n,u(1,i),1,u(1,kk),1)
                    call la_${ri}$swap(n,vt(i,1),ldvt,vt(kk,1),ldvt)
                 end if
              else if (icompq == 1) then
                 iq(i) = i
              end if
           end do
           ! if icompq = 1, use iq(n,1) as the indicator for uplo
           if (icompq == 1) then
              if (iuplo == 1) then
                 iq(n) = 1
              else
                 iq(n) = 0
              end if
           end if
           ! if b is lower bidiagonal, update u by those givens rotations
           ! which rotated b to be upper bidiagonal
           if ((iuplo == 2) .and. (icompq == 2)) call la_${ri}$lasr('L','V','B',n,n,work(1) &
                     ,work(n),u,ldu)
           return
     end subroutine la_${ri}$bdsdc
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> Using a divide and conquer approach, ${ri.upper()}$LASD0: computes the singular
     !> value decomposition (SVD) of a real upper bidiagonal N-by-M
     !> matrix B with diagonal D and offdiagonal E, where M = N + SQRE.
     !> The algorithm computes orthogonal matrices U and VT such that
     !> B = U * S * VT. The singular values S are overwritten on D.
     !> A related subroutine, ${ri.upper()}$LASDA, computes only the singular values,
     !> and optionally, the singular vectors in compact form.

     pure subroutine la_${ri}$lasd0(n,sqre,d,e,u,ldu,vt,ldvt,smlsiz,iwork,work,info)

        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldu,ldvt,n,smlsiz,sqre
           ! Array Arguments
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: d(*),e(*)
           real(${rk}$),intent(out) :: u(ldu,*),vt(ldvt,*),work(*)
        ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,i1,ic,idxq,idxqc,im1,inode,itemp,iwk,j,lf,ll,lvl,m,ncc, &
                      nd,ndb1,ndiml,ndimr,nl,nlf,nlp1,nlvl,nr,nrf,nrp1,sqrei
           real(${rk}$) :: alpha,beta
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -1
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -2
           end if
           m = n + sqre
           if (ldu < n) then
              info = -6
           else if (ldvt < m) then
              info = -8
           else if (smlsiz < 3) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASD0',-info)
              return
           end if
           ! if the input matrix is too small, call la_${ri}$lasdq to find the svd.
           if (n <= smlsiz) then
              call la_${ri}$lasdq('U',sqre,n,m,n,0,d,e,vt,ldvt,u,ldu,u,ldu,work, &
                        info)
              return
           end if
           ! set up the computation tree.
           inode = 1
           ndiml = inode + n
           ndimr = ndiml + n
           idxq = ndimr + n
           iwk = idxq + n
           call la_${ri}$lasdt(n,nlvl,nd,iwork(inode),iwork(ndiml),iwork(ndimr),smlsiz &
                     )
           ! for the nodes on bottom level of the tree, solve
           ! their subproblems by la_${ri}$lasdq.
           ndb1 = (nd + 1)/2
           ncc = 0
           loop_30: do i = ndb1,nd
           ! ic : center row of each node
           ! nl : number of rows of left  subproblem
           ! nr : number of rows of right subproblem
           ! nlf: starting row of the left   subproblem
           ! nrf: starting row of the right  subproblem
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nlp1 = nl + 1
              nr = iwork(ndimr + i1)
              nrp1 = nr + 1
              nlf = ic - nl
              nrf = ic + 1
              sqrei = 1
              call la_${ri}$lasdq('U',sqrei,nl,nlp1,nl,ncc,d(nlf),e(nlf),vt(nlf,nlf) &
                        ,ldvt,u(nlf,nlf),ldu,u(nlf,nlf),ldu,work,info)
              if (info /= 0) then
                 return
              end if
              itemp = idxq + nlf - 2
              do j = 1,nl
                 iwork(itemp + j) = j
              end do
              if (i == nd) then
                 sqrei = sqre
              else
                 sqrei = 1
              end if
              nrp1 = nr + sqrei
              call la_${ri}$lasdq('U',sqrei,nr,nrp1,nr,ncc,d(nrf),e(nrf),vt(nrf,nrf) &
                        ,ldvt,u(nrf,nrf),ldu,u(nrf,nrf),ldu,work,info)
              if (info /= 0) then
                 return
              end if
              itemp = idxq + ic
              do j = 1,nr
                 iwork(itemp + j - 1) = j
              end do
           end do loop_30
           ! now conquer each subproblem bottom-up.
           loop_50: do lvl = nlvl,1,-1
              ! find the first node lf and last node ll on the
              ! current level lvl.
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              do i = lf,ll
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 if ((sqre == 0) .and. (i == ll)) then
                    sqrei = sqre
                 else
                    sqrei = 1
                 end if
                 idxqc = idxq + nlf - 1
                 alpha = d(ic)
                 beta = e(ic)
                 call la_${ri}$lasd1(nl,nr,sqrei,d(nlf),alpha,beta,u(nlf,nlf),ldu,vt( &
                           nlf,nlf),ldvt,iwork(idxqc),iwork(iwk),work,info)
              ! report the possible convergence failure.
                 if (info /= 0) then
                    return
                 end if
              end do
           end do loop_50
           return
     end subroutine la_${ri}$lasd0
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> Using a divide and conquer approach, ${ri.upper()}$LASDA: computes the singular
     !> value decomposition (SVD) of a real upper bidiagonal N-by-M matrix
     !> B with diagonal D and offdiagonal E, where M = N + SQRE. The
     !> algorithm computes the singular values in the SVD B = U * S * VT.
     !> The orthogonal matrices U and VT are optionally computed in
     !> compact form.
     !> A related subroutine, ${ri.upper()}$LASD0, computes the singular values and
     !> the singular vectors in explicit form.

     pure subroutine la_${ri}$lasda(icompq,smlsiz,n,sqre,d,e,u,ldu,vt,k,difl,difr,z, &
               poles,givptr,givcol,ldgcol,perm,givnum,c,s,work,iwork,info)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: icompq,ldgcol,ldu,n,smlsiz,sqre
           integer(ilp),intent(out) :: info
           ! Array Arguments
           integer(ilp),intent(out) :: givcol(ldgcol,*),givptr(*),iwork(*),k(*),perm(ldgcol, &
                     *)
           real(${rk}$),intent(out) :: c(*),difl(ldu,*),difr(ldu,*),givnum(ldu,*),poles(ldu,*), &
                     s(*),u(ldu,*),vt(ldu,*),work(*),z(ldu,*)
           real(${rk}$),intent(inout) :: d(*),e(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,i1,ic,idxq,idxqi,im1,inode,itemp,iwk,j,lf,ll,lvl,lvl2, &
           m,ncc,nd,ndb1,ndiml,ndimr,nl,nlf,nlp1,nlvl,nr,nrf,nrp1,nru,nwork1, &
                     nwork2,smlszp,sqrei,vf,vfi,vl,vli
           real(${rk}$) :: alpha,beta
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if ((icompq < 0) .or. (icompq > 1)) then
              info = -1
           else if (smlsiz < 3) then
              info = -2
           else if (n < 0) then
              info = -3
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -4
           else if (ldu < (n + sqre)) then
              info = -8
           else if (ldgcol < n) then
              info = -17
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASDA',-info)
              return
           end if
           m = n + sqre
           ! if the input matrix is too small, call la_${ri}$lasdq to find the svd.
           if (n <= smlsiz) then
              if (icompq == 0) then
                 call la_${ri}$lasdq('U',sqre,n,0,0,0,d,e,vt,ldu,u,ldu,u,ldu,work, &
                           info)
              else
                 call la_${ri}$lasdq('U',sqre,n,m,n,0,d,e,vt,ldu,u,ldu,u,ldu,work, &
                           info)
              end if
              return
           end if
           ! book-keeping and  set up the computation tree.
           inode = 1
           ndiml = inode + n
           ndimr = ndiml + n
           idxq = ndimr + n
           iwk = idxq + n
           ncc = 0
           nru = 0
           smlszp = smlsiz + 1
           vf = 1
           vl = vf + m
           nwork1 = vl + m
           nwork2 = nwork1 + smlszp*smlszp
           call la_${ri}$lasdt(n,nlvl,nd,iwork(inode),iwork(ndiml),iwork(ndimr),smlsiz &
                     )
           ! for the nodes on bottom level of the tree, solve
           ! their subproblems by la_${ri}$lasdq.
           ndb1 = (nd + 1)/2
           loop_30: do i = ndb1,nd
              ! ic : center row of each node
              ! nl : number of rows of left  subproblem
              ! nr : number of rows of right subproblem
              ! nlf: starting row of the left   subproblem
              ! nrf: starting row of the right  subproblem
              i1 = i - 1
              ic = iwork(inode + i1)
              nl = iwork(ndiml + i1)
              nlp1 = nl + 1
              nr = iwork(ndimr + i1)
              nlf = ic - nl
              nrf = ic + 1
              idxqi = idxq + nlf - 2
              vfi = vf + nlf - 1
              vli = vl + nlf - 1
              sqrei = 1
              if (icompq == 0) then
                 call la_${ri}$laset('A',nlp1,nlp1,zero,one,work(nwork1),smlszp)
                 call la_${ri}$lasdq('U',sqrei,nl,nlp1,nru,ncc,d(nlf),e(nlf),work( &
                 nwork1),smlszp,work(nwork2),nl,work(nwork2),nl,work(nwork2),info)

                 itemp = nwork1 + nl*smlszp
                 call la_${ri}$copy(nlp1,work(nwork1),1,work(vfi),1)
                 call la_${ri}$copy(nlp1,work(itemp),1,work(vli),1)
              else
                 call la_${ri}$laset('A',nl,nl,zero,one,u(nlf,1),ldu)
                 call la_${ri}$laset('A',nlp1,nlp1,zero,one,vt(nlf,1),ldu)
                 call la_${ri}$lasdq('U',sqrei,nl,nlp1,nl,ncc,d(nlf),e(nlf),vt(nlf,1 &
                           ),ldu,u(nlf,1),ldu,u(nlf,1),ldu,work(nwork1),info)
                 call la_${ri}$copy(nlp1,vt(nlf,1),1,work(vfi),1)
                 call la_${ri}$copy(nlp1,vt(nlf,nlp1),1,work(vli),1)
              end if
              if (info /= 0) then
                 return
              end if
              do j = 1,nl
                 iwork(idxqi + j) = j
              end do
              if ((i == nd) .and. (sqre == 0)) then
                 sqrei = 0
              else
                 sqrei = 1
              end if
              idxqi = idxqi + nlp1
              vfi = vfi + nlp1
              vli = vli + nlp1
              nrp1 = nr + sqrei
              if (icompq == 0) then
                 call la_${ri}$laset('A',nrp1,nrp1,zero,one,work(nwork1),smlszp)
                 call la_${ri}$lasdq('U',sqrei,nr,nrp1,nru,ncc,d(nrf),e(nrf),work( &
                 nwork1),smlszp,work(nwork2),nr,work(nwork2),nr,work(nwork2),info)

                 itemp = nwork1 + (nrp1 - 1)*smlszp
                 call la_${ri}$copy(nrp1,work(nwork1),1,work(vfi),1)
                 call la_${ri}$copy(nrp1,work(itemp),1,work(vli),1)
              else
                 call la_${ri}$laset('A',nr,nr,zero,one,u(nrf,1),ldu)
                 call la_${ri}$laset('A',nrp1,nrp1,zero,one,vt(nrf,1),ldu)
                 call la_${ri}$lasdq('U',sqrei,nr,nrp1,nr,ncc,d(nrf),e(nrf),vt(nrf,1 &
                           ),ldu,u(nrf,1),ldu,u(nrf,1),ldu,work(nwork1),info)
                 call la_${ri}$copy(nrp1,vt(nrf,1),1,work(vfi),1)
                 call la_${ri}$copy(nrp1,vt(nrf,nrp1),1,work(vli),1)
              end if
              if (info /= 0) then
                 return
              end if
              do j = 1,nr
                 iwork(idxqi + j) = j
              end do
           end do loop_30
           ! now conquer each subproblem bottom-up.
           j = 2**nlvl
           loop_50: do lvl = nlvl,1,-1
              lvl2 = lvl*2 - 1
              ! find the first node lf and last node ll on
              ! the current level lvl.
              if (lvl == 1) then
                 lf = 1
                 ll = 1
              else
                 lf = 2**(lvl - 1)
                 ll = 2*lf - 1
              end if
              loop_40: do i = lf,ll
                 im1 = i - 1
                 ic = iwork(inode + im1)
                 nl = iwork(ndiml + im1)
                 nr = iwork(ndimr + im1)
                 nlf = ic - nl
                 nrf = ic + 1
                 if (i == ll) then
                    sqrei = sqre
                 else
                    sqrei = 1
                 end if
                 vfi = vf + nlf - 1
                 vli = vl + nlf - 1
                 idxqi = idxq + nlf - 1
                 alpha = d(ic)
                 beta = e(ic)
                 if (icompq == 0) then
                    call la_${ri}$lasd6(icompq,nl,nr,sqrei,d(nlf),work(vfi),work(vli), &
                    alpha,beta,iwork(idxqi),perm,givptr(1),givcol,ldgcol,givnum,ldu, &
                    poles,difl,difr,z,k(1),c(1),s(1),work(nwork1),iwork(iwk), &
                              info)
                 else
                    j = j - 1
                    call la_${ri}$lasd6(icompq,nl,nr,sqrei,d(nlf),work(vfi),work(vli), &
                    alpha,beta,iwork(idxqi),perm(nlf,lvl),givptr(j),givcol(nlf,lvl2), &
                     ldgcol,givnum(nlf,lvl2),ldu,poles(nlf,lvl2),difl(nlf,lvl),difr( &
                     nlf,lvl2),z(nlf,lvl),k(j),c(j),s(j),work(nwork1),iwork(iwk &
                               ),info)
                 end if
                 if (info /= 0) then
                    return
                 end if
              end do loop_40
           end do loop_50
           return
     end subroutine la_${ri}$lasda
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LASDQ: computes the singular value decomposition (SVD) of a real
     !> (upper or lower) bidiagonal matrix with diagonal D and offdiagonal
     !> E, accumulating the transformations if desired. Letting B denote
     !> the input bidiagonal matrix, the algorithm computes orthogonal
     !> matrices Q and P such that B = Q * S * P**T (P**T denotes the transpose
     !> of P). The singular values S are overwritten on D.
     !> The input matrix U  is changed to U  * Q  if desired.
     !> The input matrix VT is changed to P**T * VT if desired.
     !> The input matrix C  is changed to Q**T * C  if desired.
     !> See "Computing  Small Singular Values of Bidiagonal Matrices With
     !> Guaranteed High Relative Accuracy," by J. Demmel and W. Kahan,
     !> LAPACK Working Note #3, for a detailed description of the algorithm.

     pure subroutine la_${ri}$lasdq(uplo,sqre,n,ncvt,nru,ncc,d,e,vt,ldvt,u,ldu,c,ldc, &
               work,info)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldc,ldu,ldvt,n,ncc,ncvt,nru,sqre
           ! Array Arguments
           real(${rk}$),intent(inout) :: c(ldc,*),d(*),e(*),u(ldu,*),vt(ldvt,*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: rotate
           integer(ilp) :: i,isub,iuplo,j,np1,sqre1
           real(${rk}$) :: cs,r,smin,sn
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           iuplo = 0
           if (la_lsame(uplo,'U')) iuplo = 1
           if (la_lsame(uplo,'L')) iuplo = 2
           if (iuplo == 0) then
              info = -1
           else if ((sqre < 0) .or. (sqre > 1)) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (ncvt < 0) then
              info = -4
           else if (nru < 0) then
              info = -5
           else if (ncc < 0) then
              info = -6
           else if ((ncvt == 0 .and. ldvt < 1) .or. (ncvt > 0 .and. ldvt < max(1,n))) then
              info = -10
           else if (ldu < max(1,nru)) then
              info = -12
           else if ((ncc == 0 .and. ldc < 1) .or. (ncc > 0 .and. ldc < max(1,n))) then
              info = -14
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASDQ',-info)
              return
           end if
           if (n == 0) return
           ! rotate is true if any singular vectors desired, false otherwise
           rotate = (ncvt > 0) .or. (nru > 0) .or. (ncc > 0)
           np1 = n + 1
           sqre1 = sqre
           ! if matrix non-square upper bidiagonal, rotate to be lower
           ! bidiagonal.  the rotations are on the right.
           if ((iuplo == 1) .and. (sqre1 == 1)) then
              do i = 1,n - 1
                 call la_${ri}$lartg(d(i),e(i),cs,sn,r)
                 d(i) = r
                 e(i) = sn*d(i + 1)
                 d(i + 1) = cs*d(i + 1)
                 if (rotate) then
                    work(i) = cs
                    work(n + i) = sn
                 end if
              end do
              call la_${ri}$lartg(d(n),e(n),cs,sn,r)
              d(n) = r
              e(n) = zero
              if (rotate) then
                 work(n) = cs
                 work(n + n) = sn
              end if
              iuplo = 2
              sqre1 = 0
              ! update singular vectors if desired.
              if (ncvt > 0) call la_${ri}$lasr('L','V','F',np1,ncvt,work(1),work(np1),vt, &
                        ldvt)
           end if
           ! if matrix lower bidiagonal, rotate to be upper bidiagonal
           ! by applying givens rotations on the left.
           if (iuplo == 2) then
              do i = 1,n - 1
                 call la_${ri}$lartg(d(i),e(i),cs,sn,r)
                 d(i) = r
                 e(i) = sn*d(i + 1)
                 d(i + 1) = cs*d(i + 1)
                 if (rotate) then
                    work(i) = cs
                    work(n + i) = sn
                 end if
              end do
              ! if matrix (n+1)-by-n lower bidiagonal, one additional
              ! rotation is needed.
              if (sqre1 == 1) then
                 call la_${ri}$lartg(d(n),e(n),cs,sn,r)
                 d(n) = r
                 if (rotate) then
                    work(n) = cs
                    work(n + n) = sn
                 end if
              end if
              ! update singular vectors if desired.
              if (nru > 0) then
                 if (sqre1 == 0) then
                    call la_${ri}$lasr('R','V','F',nru,n,work(1),work(np1),u,ldu)

                 else
                    call la_${ri}$lasr('R','V','F',nru,np1,work(1),work(np1),u,ldu)

                 end if
              end if
              if (ncc > 0) then
                 if (sqre1 == 0) then
                    call la_${ri}$lasr('L','V','F',n,ncc,work(1),work(np1),c,ldc)

                 else
                    call la_${ri}$lasr('L','V','F',np1,ncc,work(1),work(np1),c,ldc)

                 end if
              end if
           end if
           ! call la_${ri}$bdsqr to compute the svd of the reduced real
           ! n-by-n upper bidiagonal matrix.
           call la_${ri}$bdsqr('U',n,ncvt,nru,ncc,d,e,vt,ldvt,u,ldu,c,ldc,work,info)

           ! sort the singular values into ascending order (insertion sort on
           ! singular values, but only one transposition per singular vector)
           do i = 1,n
              ! scan for smallest d(i).
              isub = i
              smin = d(i)
              do j = i + 1,n
                 if (d(j) < smin) then
                    isub = j
                    smin = d(j)
                 end if
              end do
              if (isub /= i) then
                 ! swap singular values and vectors.
                 d(isub) = d(i)
                 d(i) = smin
                 if (ncvt > 0) call la_${ri}$swap(ncvt,vt(isub,1),ldvt,vt(i,1),ldvt)

                 if (nru > 0) call la_${ri}$swap(nru,u(1,isub),1,u(1,i),1)
                 if (ncc > 0) call la_${ri}$swap(ncc,c(isub,1),ldc,c(i,1),ldc)
              end if
           end do
           return
     end subroutine la_${ri}$lasdq
#:endfor

end module la_lapack_eigv_svd_bidiag_dc
