#:include "common.fypp"
!> RZ factorization: trapezoidal reduction and its reflectors
module la_lapack_orthogonal_factors_rz
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level2_gen
     use la_blas_level2_tri
     use la_blas_level3_gen
     use la_blas_level3_tri
     use la_lapack_aux
     use la_lapack_blas_like_l1
     use la_lapack_householder_reflectors
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$larz
     public :: la_${ri}$larzb
     public :: la_${ri}$larzt
     public :: la_${ri}$ormr3
     public :: la_${ri}$ormrz
     public :: la_${ri}$latrz
     public :: la_${ri}$tzrzf
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$larz
     public :: la_${ri}$larzb
     public :: la_${ri}$larzt
     public :: la_${ri}$latrz
     public :: la_${ri}$tzrzf
     public :: la_${ri}$unmr3
     public :: la_${ri}$unmrz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZ: applies a real elementary reflector H to a real M-by-N
     !> matrix C, from either the left or the right. H is represented in the
     !> form
     !> H = I - tau * v * v**T
     !> where tau is a real scalar and v is a real vector.
     !> If tau = 0, then H is taken to be the unit matrix.
     !> H is a product of k elementary reflectors as returned by ${ri.upper()}$TZRZF.

     pure subroutine la_${ri}$larz(side,m,n,l,v,incv,tau,c,ldc,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side
           integer(ilp),intent(in) :: incv,l,ldc,m,n
           real(${rk}$),intent(in) :: tau
           ! Array Arguments
           real(${rk}$),intent(inout) :: c(ldc,*)
           real(${rk}$),intent(in) :: v(*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Executable Statements
           if (la_lsame(side,'L')) then
              ! form  h * c
              if (tau /= zero) then
                 ! w( 1:n ) = c( 1, 1:n )
                 call la_${ri}$copy(n,c,ldc,work,1)
                 ! w( 1:n ) = w( 1:n ) + c( m-l+1:m, 1:n )**t * v( 1:l )
                 call la_${ri}$gemv('TRANSPOSE',l,n,one,c(m - l + 1,1),ldc,v,incv,one,work, &
                            1)
                 ! c( 1, 1:n ) = c( 1, 1:n ) - tau * w( 1:n )
                 call la_${ri}$axpy(n,-tau,work,1,c,ldc)
                 ! c( m-l+1:m, 1:n ) = c( m-l+1:m, 1:n ) - ...
                                     ! tau * v( 1:l ) * w( 1:n )**t
                 call la_${ri}$ger(l,n,-tau,v,incv,work,1,c(m - l + 1,1),ldc)
              end if
           else
              ! form  c * h
              if (tau /= zero) then
                 ! w( 1:m ) = c( 1:m, 1 )
                 call la_${ri}$copy(m,c,1,work,1)
                 ! w( 1:m ) = w( 1:m ) + c( 1:m, n-l+1:n, 1:n ) * v( 1:l )
                 call la_${ri}$gemv('NO TRANSPOSE',m,l,one,c(1,n - l + 1),ldc,v,incv,one, &
                           work,1)
                 ! c( 1:m, 1 ) = c( 1:m, 1 ) - tau * w( 1:m )
                 call la_${ri}$axpy(m,-tau,work,1,c,1)
                 ! c( 1:m, n-l+1:n ) = c( 1:m, n-l+1:n ) - ...
                                     ! tau * w( 1:m ) * v( 1:l )**t
                 call la_${ri}$ger(m,l,-tau,work,1,v,incv,c(1,n - l + 1),ldc)
              end if
           end if
           return
     end subroutine la_${ri}$larz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZB: applies a real block reflector H or its transpose H**T to
     !> a real distributed M-by-N  C from the left or the right.
     !> Currently, only STOREV = 'R' and DIRECT = 'B' are supported.

     pure subroutine la_${ri}$larzb(side,trans,direct,storev,m,n,k,l,v,ldv,t,ldt,c, &
               ldc,work,ldwork)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,side,storev,trans
           integer(ilp),intent(in) :: k,l,ldc,ldt,ldv,ldwork,m,n
           ! Array Arguments
           real(${rk}$),intent(inout) :: c(ldc,*),t(ldt,*),v(ldv,*)
           real(${rk}$),intent(out) :: work(ldwork,*)
        ! =====================================================================

           ! Local Scalars
           character :: transt
           integer(ilp) :: i,info,j
           ! Executable Statements
           ! quick return if possible
           if (m <= 0 .or. n <= 0) return
           ! check for currently supported options
           info = 0
           if (.not. la_lsame(direct,'B')) then
              info = -3
           else if (.not. la_lsame(storev,'R')) then
              info = -4
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LARZB',-info)
              return
           end if
           if (la_lsame(trans,'N')) then
              transt = 'T'
           else
              transt = 'N'
           end if
           if (la_lsame(side,'L')) then
              ! form  h * c  or  h**t * c
              ! w( 1:n, 1:k ) = c( 1:k, 1:n )**t
              do j = 1,k
                 call la_${ri}$copy(n,c(j,1),ldc,work(1,j),1)
              end do
              ! w( 1:n, 1:k ) = w( 1:n, 1:k ) + ...
                              ! c( m-l+1:m, 1:n )**t * v( 1:k, 1:l )**t
              if (l > 0) call la_${ri}$gemm('TRANSPOSE','TRANSPOSE',n,k,l,one,c(m - l + 1,1), &
                        ldc,v,ldv,one,work,ldwork)
              ! w( 1:n, 1:k ) = w( 1:n, 1:k ) * t**t  or  w( 1:m, 1:k ) * t
              call la_${ri}$trmm('RIGHT','LOWER',transt,'NON-UNIT',n,k,one,t,ldt,work, &
                        ldwork)
              ! c( 1:k, 1:n ) = c( 1:k, 1:n ) - w( 1:n, 1:k )**t
              do j = 1,n
                 do i = 1,k
                    c(i,j) = c(i,j) - work(j,i)
                 end do
              end do
              ! c( m-l+1:m, 1:n ) = c( m-l+1:m, 1:n ) - ...
                                  ! v( 1:k, 1:l )**t * w( 1:n, 1:k )**t
              if (l > 0) call la_${ri}$gemm('TRANSPOSE','TRANSPOSE',l,n,k,-one,v,ldv,work, &
                        ldwork,one,c(m - l + 1,1),ldc)
           else if (la_lsame(side,'R')) then
              ! form  c * h  or  c * h**t
              ! w( 1:m, 1:k ) = c( 1:m, 1:k )
              do j = 1,k
                 call la_${ri}$copy(m,c(1,j),1,work(1,j),1)
              end do
              ! w( 1:m, 1:k ) = w( 1:m, 1:k ) + ...
                              ! c( 1:m, n-l+1:n ) * v( 1:k, 1:l )**t
              if (l > 0) call la_${ri}$gemm('NO TRANSPOSE','TRANSPOSE',m,k,l,one,c(1,n - l + 1), &
                         ldc,v,ldv,one,work,ldwork)
              ! w( 1:m, 1:k ) = w( 1:m, 1:k ) * t  or  w( 1:m, 1:k ) * t**t
              call la_${ri}$trmm('RIGHT','LOWER',trans,'NON-UNIT',m,k,one,t,ldt,work, &
                        ldwork)
              ! c( 1:m, 1:k ) = c( 1:m, 1:k ) - w( 1:m, 1:k )
              do j = 1,k
                 do i = 1,m
                    c(i,j) = c(i,j) - work(i,j)
                 end do
              end do
              ! c( 1:m, n-l+1:n ) = c( 1:m, n-l+1:n ) - ...
                                  ! w( 1:m, 1:k ) * v( 1:k, 1:l )
              if (l > 0) call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',m,l,k,-one,work, &
                        ldwork,v,ldv,one,c(1,n - l + 1),ldc)
           end if
           return
     end subroutine la_${ri}$larzb
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZT: forms the triangular factor T of a real block reflector
     !> H of order > n, which is defined as a product of k elementary
     !> reflectors.
     !> If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
     !> If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
     !> If STOREV = 'C', the vector which defines the elementary reflector
     !> H(i) is stored in the i-th column of the array V, and
     !> H  =  I - V * T * V**T
     !> If STOREV = 'R', the vector which defines the elementary reflector
     !> H(i) is stored in the i-th row of the array V, and
     !> H  =  I - V**T * T * V
     !> Currently, only STOREV = 'R' and DIRECT = 'B' are supported.

     pure subroutine la_${ri}$larzt(direct,storev,n,k,v,ldv,tau,t,ldt)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,storev
           integer(ilp),intent(in) :: k,ldt,ldv,n
           ! Array Arguments
           real(${rk}$),intent(out) :: t(ldt,*)
           real(${rk}$),intent(in) :: tau(*)
           real(${rk}$),intent(inout) :: v(ldv,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,info,j
           ! Executable Statements
           ! check for currently supported options
           info = 0
           if (.not. la_lsame(direct,'B')) then
              info = -1
           else if (.not. la_lsame(storev,'R')) then
              info = -2
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LARZT',-info)
              return
           end if
           do i = k,1,-1
              if (tau(i) == zero) then
                 ! h(i)  =  i
                 do j = i,k
                    t(j,i) = zero
                 end do
              else
                 ! general case
                 if (i < k) then
                    ! t(i+1:k,i) = - tau(i) * v(i+1:k,1:n) * v(i,1:n)**t
                    call la_${ri}$gemv('NO TRANSPOSE',k - i,n,-tau(i),v(i + 1,1),ldv,v(i, &
                              1),ldv,zero,t(i + 1,i),1)
                    ! t(i+1:k,i) = t(i+1:k,i+1:k) * t(i+1:k,i)
                    call la_${ri}$trmv('LOWER','NO TRANSPOSE','NON-UNIT',k - i,t(i + 1,i + 1), &
                              ldt,t(i + 1,i),1)
                 end if
                 t(i,i) = tau(i)
              end if
           end do
           return
     end subroutine la_${ri}$larzt
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$ORMR3: overwrites the general real m by n matrix C with
     !> Q * C  if SIDE = 'L' and TRANS = 'N', or
     !> Q**T* C  if SIDE = 'L' and TRANS = 'C', or
     !> C * Q  if SIDE = 'R' and TRANS = 'N', or
     !> C * Q**T if SIDE = 'R' and TRANS = 'C',
     !> where Q is a real orthogonal matrix defined as the product of k
     !> elementary reflectors
     !> Q = H(1) H(2) . . . H(k)
     !> as returned by ${ri.upper()}$TZRZF. Q is of order m if SIDE = 'L' and of order n
     !> if SIDE = 'R'.

     pure subroutine la_${ri}$ormr3(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,info)

        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: k,l,lda,ldc,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*),tau(*)
           real(${rk}$),intent(inout) :: c(ldc,*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================
           ! Local Scalars
           logical(lk) :: left,notran
           integer(ilp) :: i,i1,i2,i3,ic,ja,jc,mi,ni,nq
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input arguments
           info = 0
           left = la_lsame(side,'L')
           notran = la_lsame(trans,'N')
           ! nq is the order of q
           if (left) then
              nq = m
           else
              nq = n
           end if
           if (.not. left .and. .not. la_lsame(side,'R')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T')) then
              info = -2
           else if (m < 0) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0 .or. k > nq) then
              info = -5
           else if (l < 0 .or. (left .and. (l > m)) .or. (.not. left .and. (l > n))) then
              info = -6
           else if (lda < max(1,k)) then
              info = -8
           else if (ldc < max(1,m)) then
              info = -11
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$ORMR3',-info)
              return
           end if
           ! quick return if possible
           if (m == 0 .or. n == 0 .or. k == 0) return
           if ((left .and. .not. notran .or. .not. left .and. notran)) then
              i1 = 1
              i2 = k
              i3 = 1
           else
              i1 = k
              i2 = 1
              i3 = -1
           end if
           if (left) then
              ni = n
              ja = m - l + 1
              jc = 1
           else
              mi = m
              ja = n - l + 1
              ic = 1
           end if
           do i = i1,i2,i3
              if (left) then
                 ! h(i) or h(i)**t is applied to c(i:m,1:n)
                 mi = m - i + 1
                 ic = i
              else
                 ! h(i) or h(i)**t is applied to c(1:m,i:n)
                 ni = n - i + 1
                 jc = i
              end if
              ! apply h(i) or h(i)**t
              call la_${ri}$larz(side,mi,ni,l,a(i,ja),lda,tau(i),c(ic,jc),ldc, &
                        work)
           end do
           return
     end subroutine la_${ri}$ormr3
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$ORMRZ: overwrites the general real M-by-N matrix C with
     !> SIDE = 'L'     SIDE = 'R'
     !> TRANS = 'N':      Q * C          C * Q
     !> TRANS = 'T':      Q**T * C       C * Q**T
     !> where Q is a real orthogonal matrix defined as the product of k
     !> elementary reflectors
     !> Q = H(1) H(2) . . . H(k)
     !> as returned by ${ri.upper()}$TZRZF. Q is of order M if SIDE = 'L' and of order N
     !> if SIDE = 'R'.

     pure subroutine la_${ri}$ormrz(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,lwork, &
               info)
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: k,l,lda,ldc,lwork,m,n
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*),c(ldc,*)
           real(${rk}$),intent(in) :: tau(*)
           real(${rk}$),intent(out) :: work(*)
        ! =====================================================================
           ! Parameters
           integer(ilp),parameter :: nbmax = 64
           integer(ilp),parameter :: ldt = nbmax + 1
           integer(ilp),parameter :: tsize = ldt*nbmax

           ! Local Scalars
           logical(lk) :: left,lquery,notran
           character :: transt
           integer(ilp) :: i,i1,i2,i3,ib,ic,iinfo,iwt,ja,jc,ldwork,lwkopt,mi,nb, &
                     nbmin,ni,nq,nw
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           ! test the input arguments
           info = 0
           left = la_lsame(side,'L')
           notran = la_lsame(trans,'N')
           lquery = (lwork == -1)
           ! nq is the order of q and nw is the minimum dimension of work
           if (left) then
              nq = m
              nw = max(1,n)
           else
              nq = n
              nw = max(1,m)
           end if
           if (.not. left .and. .not. la_lsame(side,'R')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T')) then
              info = -2
           else if (m < 0) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0 .or. k > nq) then
              info = -5
           else if (l < 0 .or. (left .and. (l > m)) .or. (.not. left .and. (l > n))) then
              info = -6
           else if (lda < max(1,k)) then
              info = -8
           else if (ldc < max(1,m)) then
              info = -11
           else if (lwork < nw .and. .not. lquery) then
              info = -13
           end if
           if (info == 0) then
              ! compute the workspace requirements
              if (m == 0 .or. n == 0) then
                 lwkopt = 1
              else
                 nb = min(nbmax,la_ilaenv(1,'${ri.upper()}$ORMRQ',side//trans,m,n,k,-1))

                 lwkopt = nw*nb + tsize
              end if
              work(1) = lwkopt
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$ORMRZ',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (m == 0 .or. n == 0) then
#:if rk != "sp"
              work(1) = 1
#:endif
              return
           end if
           nbmin = 2
           ldwork = nw
           if (nb > 1 .and. nb < k) then
              if (lwork < lwkopt) then
                 nb = (lwork - tsize)/ldwork
                 nbmin = max(2,la_ilaenv(2,'${ri.upper()}$ORMRQ',side//trans,m,n,k,-1))
              end if
           end if
           if (nb < nbmin .or. nb >= k) then
              ! use unblocked code
              call la_${ri}$ormr3(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,iinfo)

           else
              ! use blocked code
              iwt = 1 + nw*nb
              if ((left .and. .not. notran) .or. (.not. left .and. notran)) then
                 i1 = 1
                 i2 = k
                 i3 = nb
              else
                 i1 = ((k - 1)/nb)*nb + 1
                 i2 = 1
                 i3 = -nb
              end if
              if (left) then
                 ni = n
                 jc = 1
                 ja = m - l + 1
              else
                 mi = m
                 ic = 1
                 ja = n - l + 1
              end if
              if (notran) then
                 transt = 'T'
              else
                 transt = 'N'
              end if
              do i = i1,i2,i3
                 ib = min(nb,k - i + 1)
                 ! form the triangular factor of the block reflector
                 ! h = h(i+ib-1) . . . h(i+1) h(i)
                 call la_${ri}$larzt('BACKWARD','ROWWISE',l,ib,a(i,ja),lda,tau(i),work( &
                            iwt),ldt)
                 if (left) then
                    ! h or h**t is applied to c(i:m,1:n)
                    mi = m - i + 1
                    ic = i
                 else
                    ! h or h**t is applied to c(1:m,i:n)
                    ni = n - i + 1
                    jc = i
                 end if
                 ! apply h or h**t
                 call la_${ri}$larzb(side,transt,'BACKWARD','ROWWISE',mi,ni,ib,l,a(i,ja) &
                           ,lda,work(iwt),ldt,c(ic,jc),ldc,work,ldwork)
              end do
           end if
           work(1) = lwkopt
           return
     end subroutine la_${ri}$ormrz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LATRZ: factors the M-by-(M+L) real upper trapezoidal matrix
     !> [ A1 A2 ] = [ A(1:M,1:M) A(1:M,N-L+1:N) ] as ( R  0 ) * Z, by means
     !> of orthogonal transformations.  Z is an (M+L)-by-(M+L) orthogonal
     !> matrix and, R and A1 are M-by-M upper triangular matrices.

     pure subroutine la_${ri}$latrz(m,n,l,a,lda,tau,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: l,lda,m,n
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*)
           real(${rk}$),intent(out) :: tau(*),work(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           ! Executable Statements
           ! test the input arguments
           ! quick return if possible
           if (m == 0) then
              return
           else if (m == n) then
              do i = 1,n
                 tau(i) = zero
              end do
              return
           end if
           do i = m,1,-1
              ! generate elementary reflector h(i) to annihilate
              ! [ a(i,i) a(i,n-l+1:n) ]
              call la_${ri}$larfg(l + 1,a(i,i),a(i,n - l + 1),lda,tau(i))
              ! apply h(i) to a(1:i-1,i:n) from the right
              call la_${ri}$larz('RIGHT',i - 1,n - i + 1,l,a(i,n - l + 1),lda,tau(i),a(1,i), &
                        lda,work)
           end do
           return
     end subroutine la_${ri}$latrz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$TZRZF: reduces the M-by-N ( M<=N ) real upper trapezoidal matrix A
     !> to upper triangular form by means of orthogonal transformations.
     !> The upper trapezoidal matrix A is factored as
     !> A = ( R  0 ) * Z,
     !> where Z is an N-by-N orthogonal matrix and R is an M-by-M upper
     !> triangular matrix.

     pure subroutine la_${ri}$tzrzf(m,n,a,lda,tau,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,lwork,m,n
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*)
           real(${rk}$),intent(out) :: tau(*),work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: i,ib,iws,ki,kk,ldwork,lwkmin,lwkopt,m1,mu,nb,nbmin, &
                     nx
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           ! test the input arguments
           info = 0
           lquery = (lwork == -1)
           if (m < 0) then
              info = -1
           else if (n < m) then
              info = -2
           else if (lda < max(1,m)) then
              info = -4
           end if
           if (info == 0) then
              if (m == 0 .or. m == n) then
                 lwkopt = 1
                 lwkmin = 1
              else
                 ! determine the block size.
                 nb = la_ilaenv(1,'${ri.upper()}$GERQF',' ',m,n,-1,-1)
                 lwkopt = m*nb
                 lwkmin = max(1,m)
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -7
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$TZRZF',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (m == 0) then
              return
           else if (m == n) then
              do i = 1,n
                 tau(i) = zero
              end do
              return
           end if
           nbmin = 2
           nx = 1
           iws = m
           if (nb > 1 .and. nb < m) then
              ! determine when to cross over from blocked to unblocked code.
              nx = max(0,la_ilaenv(3,'${ri.upper()}$GERQF',' ',m,n,-1,-1))
              if (nx < m) then
                 ! determine if workspace is large enough for blocked code.
                 ldwork = m
                 iws = ldwork*nb
                 if (lwork < iws) then
                    ! not enough workspace to use optimal nb:  reduce nb and
                    ! determine the minimum value of nb.
                    nb = lwork/ldwork
                    nbmin = max(2,la_ilaenv(2,'${ri.upper()}$GERQF',' ',m,n,-1,-1))
                 end if
              end if
           end if
           if (nb >= nbmin .and. nb < m .and. nx < m) then
              ! use blocked code initially.
              ! the last kk rows are handled by the block method.
              m1 = min(m + 1,n)
              ki = ((m - nx - 1)/nb)*nb
              kk = min(m,ki + nb)
              do i = m - kk + ki + 1,m - kk + 1,-nb
                 ib = min(m - i + 1,nb)
                 ! compute the tz factorization of the current block
                 ! a(i:i+ib-1,i:n)
                 call la_${ri}$latrz(ib,n - i + 1,n - m,a(i,i),lda,tau(i),work)
                 if (i > 1) then
                    ! form the triangular factor of the block reflector
                    ! h = h(i+ib-1) . . . h(i+1) h(i)
                    call la_${ri}$larzt('BACKWARD','ROWWISE',n - m,ib,a(i,m1),lda,tau(i), &
                              work,ldwork)
                    ! apply h to a(1:i-1,i:n) from the right
                    call la_${ri}$larzb('RIGHT','NO TRANSPOSE','BACKWARD','ROWWISE',i - 1,n - i + 1, &
                     ib,n - m,a(i,m1),lda,work,ldwork,a(1,i),lda,work(ib + 1),ldwork)

                 end if
              end do
              mu = i + nb - 1
           else
              mu = m
           end if
           ! use unblocked code to factor the last or only block
           if (mu > 0) call la_${ri}$latrz(mu,n,n - m,a,lda,tau,work)
           work(1) = lwkopt
           return
     end subroutine la_${ri}$tzrzf
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZ: applies a complex elementary reflector H to a complex
     !> M-by-N matrix C, from either the left or the right. H is represented
     !> in the form
     !> H = I - tau * v * v**H
     !> where tau is a complex scalar and v is a complex vector.
     !> If tau = 0, then H is taken to be the unit matrix.
     !> To apply H**H (the conjugate transpose of H), supply conjg(tau) instead
     !> tau.
     !> H is a product of k elementary reflectors as returned by ${ri.upper()}$TZRZF.

     pure subroutine la_${ri}$larz(side,m,n,l,v,incv,tau,c,ldc,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side
           integer(ilp),intent(in) :: incv,l,ldc,m,n
           complex(${rk}$),intent(in) :: tau
           ! Array Arguments
           complex(${rk}$),intent(inout) :: c(ldc,*)
           complex(${rk}$),intent(in) :: v(*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Executable Statements
           if (la_lsame(side,'L')) then
              ! form  h * c
              if (tau /= czero) then
                 ! w( 1:n ) = conjg( c( 1, 1:n ) )
                 call la_${ri}$copy(n,c,ldc,work,1)
                 call la_${ri}$lacgv(n,work,1)
                 ! w( 1:n ) = conjg( w( 1:n ) + c( m-l+1:m, 1:n )**h * v( 1:l ) )
                 call la_${ri}$gemv('CONJUGATE TRANSPOSE',l,n,cone,c(m - l + 1,1),ldc,v,incv, &
                            cone,work,1)
                 call la_${ri}$lacgv(n,work,1)
                 ! c( 1, 1:n ) = c( 1, 1:n ) - tau * w( 1:n )
                 call la_${ri}$axpy(n,-tau,work,1,c,ldc)
                 ! c( m-l+1:m, 1:n ) = c( m-l+1:m, 1:n ) - ...
                                     ! tau * v( 1:l ) * w( 1:n )**h
                 call la_${ri}$geru(l,n,-tau,v,incv,work,1,c(m - l + 1,1),ldc)
              end if
           else
              ! form  c * h
              if (tau /= czero) then
                 ! w( 1:m ) = c( 1:m, 1 )
                 call la_${ri}$copy(m,c,1,work,1)
                 ! w( 1:m ) = w( 1:m ) + c( 1:m, n-l+1:n, 1:n ) * v( 1:l )
                 call la_${ri}$gemv('NO TRANSPOSE',m,l,cone,c(1,n - l + 1),ldc,v,incv,cone, &
                           work,1)
                 ! c( 1:m, 1 ) = c( 1:m, 1 ) - tau * w( 1:m )
                 call la_${ri}$axpy(m,-tau,work,1,c,1)
                 ! c( 1:m, n-l+1:n ) = c( 1:m, n-l+1:n ) - ...
                                     ! tau * w( 1:m ) * v( 1:l )**h
                 call la_${ri}$gerc(m,l,-tau,work,1,v,incv,c(1,n - l + 1),ldc)
              end if
           end if
           return
     end subroutine la_${ri}$larz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZB: applies a complex block reflector H or its transpose H**H
     !> to a complex distributed M-by-N  C from the left or the right.
     !> Currently, only STOREV = 'R' and DIRECT = 'B' are supported.

     pure subroutine la_${ri}$larzb(side,trans,direct,storev,m,n,k,l,v,ldv,t,ldt,c, &
               ldc,work,ldwork)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,side,storev,trans
           integer(ilp),intent(in) :: k,l,ldc,ldt,ldv,ldwork,m,n
           ! Array Arguments
           complex(${rk}$),intent(inout) :: c(ldc,*),t(ldt,*),v(ldv,*)
           complex(${rk}$),intent(out) :: work(ldwork,*)
        ! =====================================================================

           ! Local Scalars
           character :: transt
           integer(ilp) :: i,info,j
           ! Executable Statements
           ! quick return if possible
           if (m <= 0 .or. n <= 0) return
           ! check for currently supported options
           info = 0
           if (.not. la_lsame(direct,'B')) then
              info = -3
           else if (.not. la_lsame(storev,'R')) then
              info = -4
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LARZB',-info)
              return
           end if
           if (la_lsame(trans,'N')) then
              transt = 'C'
           else
              transt = 'N'
           end if
           if (la_lsame(side,'L')) then
              ! form  h * c  or  h**h * c
              ! w( 1:n, 1:k ) = c( 1:k, 1:n )**h
              do j = 1,k
                 call la_${ri}$copy(n,c(j,1),ldc,work(1,j),1)
              end do
              ! w( 1:n, 1:k ) = w( 1:n, 1:k ) + ...
                              ! c( m-l+1:m, 1:n )**h * v( 1:k, 1:l )**t
              if (l > 0) call la_${ri}$gemm('TRANSPOSE','CONJUGATE TRANSPOSE',n,k,l,cone,c(m - &
                        l + 1,1),ldc,v,ldv,cone,work,ldwork)
              ! w( 1:n, 1:k ) = w( 1:n, 1:k ) * t**t  or  w( 1:m, 1:k ) * t
              call la_${ri}$trmm('RIGHT','LOWER',transt,'NON-UNIT',n,k,cone,t,ldt,work, &
                        ldwork)
              ! c( 1:k, 1:n ) = c( 1:k, 1:n ) - w( 1:n, 1:k )**h
              do j = 1,n
                 do i = 1,k
                    c(i,j) = c(i,j) - work(j,i)
                 end do
              end do
              ! c( m-l+1:m, 1:n ) = c( m-l+1:m, 1:n ) - ...
                                  ! v( 1:k, 1:l )**h * w( 1:n, 1:k )**h
              if (l > 0) call la_${ri}$gemm('TRANSPOSE','TRANSPOSE',l,n,k,-cone,v,ldv,work, &
                        ldwork,cone,c(m - l + 1,1),ldc)
           else if (la_lsame(side,'R')) then
              ! form  c * h  or  c * h**h
              ! w( 1:m, 1:k ) = c( 1:m, 1:k )
              do j = 1,k
                 call la_${ri}$copy(m,c(1,j),1,work(1,j),1)
              end do
              ! w( 1:m, 1:k ) = w( 1:m, 1:k ) + ...
                              ! c( 1:m, n-l+1:n ) * v( 1:k, 1:l )**h
              if (l > 0) call la_${ri}$gemm('NO TRANSPOSE','TRANSPOSE',m,k,l,cone,c(1,n - l + 1) &
                        ,ldc,v,ldv,cone,work,ldwork)
              ! w( 1:m, 1:k ) = w( 1:m, 1:k ) * conjg( t )  or
                              ! w( 1:m, 1:k ) * t**h
              do j = 1,k
                 call la_${ri}$lacgv(k - j + 1,t(j,j),1)
              end do
              call la_${ri}$trmm('RIGHT','LOWER',trans,'NON-UNIT',m,k,cone,t,ldt,work, &
                        ldwork)
              do j = 1,k
                 call la_${ri}$lacgv(k - j + 1,t(j,j),1)
              end do
              ! c( 1:m, 1:k ) = c( 1:m, 1:k ) - w( 1:m, 1:k )
              do j = 1,k
                 do i = 1,m
                    c(i,j) = c(i,j) - work(i,j)
                 end do
              end do
              ! c( 1:m, n-l+1:n ) = c( 1:m, n-l+1:n ) - ...
                                  ! w( 1:m, 1:k ) * conjg( v( 1:k, 1:l ) )
              do j = 1,l
                 call la_${ri}$lacgv(k,v(1,j),1)
              end do
              if (l > 0) call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',m,l,k,-cone,work, &
                        ldwork,v,ldv,cone,c(1,n - l + 1),ldc)
              do j = 1,l
                 call la_${ri}$lacgv(k,v(1,j),1)
              end do
           end if
           return
     end subroutine la_${ri}$larzb
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARZT: forms the triangular factor T of a complex block reflector
     !> H of order > n, which is defined as a product of k elementary
     !> reflectors.
     !> If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
     !> If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
     !> If STOREV = 'C', the vector which defines the elementary reflector
     !> H(i) is stored in the i-th column of the array V, and
     !> H  =  I - V * T * V**H
     !> If STOREV = 'R', the vector which defines the elementary reflector
     !> H(i) is stored in the i-th row of the array V, and
     !> H  =  I - V**H * T * V
     !> Currently, only STOREV = 'R' and DIRECT = 'B' are supported.

     pure subroutine la_${ri}$larzt(direct,storev,n,k,v,ldv,tau,t,ldt)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,storev
           integer(ilp),intent(in) :: k,ldt,ldv,n
           ! Array Arguments
           complex(${rk}$),intent(out) :: t(ldt,*)
           complex(${rk}$),intent(in) :: tau(*)
           complex(${rk}$),intent(inout) :: v(ldv,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,info,j
           ! Executable Statements
           ! check for currently supported options
           info = 0
           if (.not. la_lsame(direct,'B')) then
              info = -1
           else if (.not. la_lsame(storev,'R')) then
              info = -2
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LARZT',-info)
              return
           end if
           do i = k,1,-1
              if (tau(i) == czero) then
                 ! h(i)  =  i
                 do j = i,k
                    t(j,i) = czero
                 end do
              else
                 ! general case
                 if (i < k) then
                    ! t(i+1:k,i) = - tau(i) * v(i+1:k,1:n) * v(i,1:n)**h
                    call la_${ri}$lacgv(n,v(i,1),ldv)
                    call la_${ri}$gemv('NO TRANSPOSE',k - i,n,-tau(i),v(i + 1,1),ldv,v(i, &
                              1),ldv,czero,t(i + 1,i),1)
                    call la_${ri}$lacgv(n,v(i,1),ldv)
                    ! t(i+1:k,i) = t(i+1:k,i+1:k) * t(i+1:k,i)
                    call la_${ri}$trmv('LOWER','NO TRANSPOSE','NON-UNIT',k - i,t(i + 1,i + 1), &
                              ldt,t(i + 1,i),1)
                 end if
                 t(i,i) = tau(i)
              end if
           end do
           return
     end subroutine la_${ri}$larzt
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LATRZ: factors the M-by-(M+L) complex upper trapezoidal matrix
     !> [ A1 A2 ] = [ A(1:M,1:M) A(1:M,N-L+1:N) ] as ( R  0 ) * Z by means
     !> of unitary transformations, where  Z is an (M+L)-by-(M+L) unitary
     !> matrix and, R and A1 are M-by-M upper triangular matrices.

     pure subroutine la_${ri}$latrz(m,n,l,a,lda,tau,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: l,lda,m,n
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(out) :: tau(*),work(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           complex(${rk}$) :: alpha
           ! Intrinsic Functions
           intrinsic :: conjg
           ! Executable Statements
           ! quick return if possible
           if (m == 0) then
              return
           else if (m == n) then
              do i = 1,n
                 tau(i) = czero
              end do
              return
           end if
           do i = m,1,-1
              ! generate elementary reflector h(i) to annihilate
              ! [ a(i,i) a(i,n-l+1:n) ]
              call la_${ri}$lacgv(l,a(i,n - l + 1),lda)
              alpha = conjg(a(i,i))
              call la_${ri}$larfg(l + 1,alpha,a(i,n - l + 1),lda,tau(i))
              tau(i) = conjg(tau(i))
              ! apply h(i) to a(1:i-1,i:n) from the right
              call la_${ri}$larz('RIGHT',i - 1,n - i + 1,l,a(i,n - l + 1),lda,conjg(tau(i)),a( &
                        1,i),lda,work)
              a(i,i) = conjg(alpha)
           end do
           return
     end subroutine la_${ri}$latrz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$TZRZF: reduces the M-by-N ( M<=N ) complex upper trapezoidal matrix A
     !> to upper triangular form by means of unitary transformations.
     !> The upper trapezoidal matrix A is factored as
     !> A = ( R  0 ) * Z,
     !> where Z is an N-by-N unitary matrix and R is an M-by-M upper
     !> triangular matrix.

     pure subroutine la_${ri}$tzrzf(m,n,a,lda,tau,work,lwork,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,lwork,m,n
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(out) :: tau(*),work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lquery
           integer(ilp) :: i,ib,iws,ki,kk,ldwork,lwkmin,lwkopt,m1,mu,nb,nbmin, &
                     nx
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           ! test the input arguments
           info = 0
           lquery = (lwork == -1)
           if (m < 0) then
              info = -1
           else if (n < m) then
              info = -2
           else if (lda < max(1,m)) then
              info = -4
           end if
           if (info == 0) then
              if (m == 0 .or. m == n) then
                 lwkopt = 1
                 lwkmin = 1
              else
                 ! determine the block size.
                 nb = la_ilaenv(1,'${ri.upper()}$GERQF',' ',m,n,-1,-1)
                 lwkopt = m*nb
                 lwkmin = max(1,m)
              end if
              work(1) = lwkopt
              if (lwork < lwkmin .and. .not. lquery) then
                 info = -7
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$TZRZF',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (m == 0) then
              return
           else if (m == n) then
              do i = 1,n
                 tau(i) = czero
              end do
              return
           end if
           nbmin = 2
           nx = 1
           iws = m
           if (nb > 1 .and. nb < m) then
              ! determine when to cross over from blocked to unblocked code.
              nx = max(0,la_ilaenv(3,'${ri.upper()}$GERQF',' ',m,n,-1,-1))
              if (nx < m) then
                 ! determine if workspace is large enough for blocked code.
                 ldwork = m
                 iws = ldwork*nb
                 if (lwork < iws) then
                    ! not enough workspace to use optimal nb:  reduce nb and
                    ! determine the minimum value of nb.
                    nb = lwork/ldwork
                    nbmin = max(2,la_ilaenv(2,'${ri.upper()}$GERQF',' ',m,n,-1,-1))
                 end if
              end if
           end if
           if (nb >= nbmin .and. nb < m .and. nx < m) then
              ! use blocked code initially.
              ! the last kk rows are handled by the block method.
              m1 = min(m + 1,n)
              ki = ((m - nx - 1)/nb)*nb
              kk = min(m,ki + nb)
              do i = m - kk + ki + 1,m - kk + 1,-nb
                 ib = min(m - i + 1,nb)
                 ! compute the tz factorization of the current block
                 ! a(i:i+ib-1,i:n)
                 call la_${ri}$latrz(ib,n - i + 1,n - m,a(i,i),lda,tau(i),work)
                 if (i > 1) then
                    ! form the triangular factor of the block reflector
                    ! h = h(i+ib-1) . . . h(i+1) h(i)
                    call la_${ri}$larzt('BACKWARD','ROWWISE',n - m,ib,a(i,m1),lda,tau(i), &
                              work,ldwork)
                    ! apply h to a(1:i-1,i:n) from the right
                    call la_${ri}$larzb('RIGHT','NO TRANSPOSE','BACKWARD','ROWWISE',i - 1,n - i + 1, &
                     ib,n - m,a(i,m1),lda,work,ldwork,a(1,i),lda,work(ib + 1),ldwork)

                 end if
              end do
              mu = i + nb - 1
           else
              mu = m
           end if
           ! use unblocked code to factor the last or only block
           if (mu > 0) call la_${ri}$latrz(mu,n,n - m,a,lda,tau,work)
           work(1) = lwkopt
           return
     end subroutine la_${ri}$tzrzf
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$UNMR3: overwrites the general complex m by n matrix C with
     !> Q * C  if SIDE = 'L' and TRANS = 'N', or
     !> Q**H* C  if SIDE = 'L' and TRANS = 'C', or
     !> C * Q  if SIDE = 'R' and TRANS = 'N', or
     !> C * Q**H if SIDE = 'R' and TRANS = 'C',
     !> where Q is a complex unitary matrix defined as the product of k
     !> elementary reflectors
     !> Q = H(1) H(2) . . . H(k)
     !> as returned by ${ri.upper()}$TZRZF. Q is of order m if SIDE = 'L' and of order n
     !> if SIDE = 'R'.

     pure subroutine la_${ri}$unmr3(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,info)

        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: k,l,lda,ldc,m,n
           ! Array Arguments
           complex(${rk}$),intent(in) :: a(lda,*),tau(*)
           complex(${rk}$),intent(inout) :: c(ldc,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================
           ! Local Scalars
           logical(lk) :: left,notran
           integer(ilp) :: i,i1,i2,i3,ic,ja,jc,mi,ni,nq
           complex(${rk}$) :: taui
           ! Intrinsic Functions
           intrinsic :: conjg,max
           ! Executable Statements
           ! test the input arguments
           info = 0
           left = la_lsame(side,'L')
           notran = la_lsame(trans,'N')
           ! nq is the order of q
           if (left) then
              nq = m
           else
              nq = n
           end if
           if (.not. left .and. .not. la_lsame(side,'R')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'C')) then
              info = -2
           else if (m < 0) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0 .or. k > nq) then
              info = -5
           else if (l < 0 .or. (left .and. (l > m)) .or. (.not. left .and. (l > n))) then
              info = -6
           else if (lda < max(1,k)) then
              info = -8
           else if (ldc < max(1,m)) then
              info = -11
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$UNMR3',-info)
              return
           end if
           ! quick return if possible
           if (m == 0 .or. n == 0 .or. k == 0) return
           if ((left .and. .not. notran .or. .not. left .and. notran)) then
              i1 = 1
              i2 = k
              i3 = 1
           else
              i1 = k
              i2 = 1
              i3 = -1
           end if
           if (left) then
              ni = n
              ja = m - l + 1
              jc = 1
           else
              mi = m
              ja = n - l + 1
              ic = 1
           end if
           do i = i1,i2,i3
              if (left) then
                 ! h(i) or h(i)**h is applied to c(i:m,1:n)
                 mi = m - i + 1
                 ic = i
              else
                 ! h(i) or h(i)**h is applied to c(1:m,i:n)
                 ni = n - i + 1
                 jc = i
              end if
              ! apply h(i) or h(i)**h
              if (notran) then
                 taui = tau(i)
              else
                 taui = conjg(tau(i))
              end if
              call la_${ri}$larz(side,mi,ni,l,a(i,ja),lda,taui,c(ic,jc),ldc,work)

           end do
           return
     end subroutine la_${ri}$unmr3
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$UNMRZ: overwrites the general complex M-by-N matrix C with
     !> SIDE = 'L'     SIDE = 'R'
     !> TRANS = 'N':      Q * C          C * Q
     !> TRANS = 'C':      Q**H * C       C * Q**H
     !> where Q is a complex unitary matrix defined as the product of k
     !> elementary reflectors
     !> Q = H(1) H(2) . . . H(k)
     !> as returned by ${ri.upper()}$TZRZF. Q is of order M if SIDE = 'L' and of order N
     !> if SIDE = 'R'.

     pure subroutine la_${ri}$unmrz(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,lwork, &
               info)
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: side,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: k,l,lda,ldc,lwork,m,n
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,*),c(ldc,*)
           complex(${rk}$),intent(in) :: tau(*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================
           ! Parameters
           integer(ilp),parameter :: nbmax = 64
           integer(ilp),parameter :: ldt = nbmax + 1
           integer(ilp),parameter :: tsize = ldt*nbmax

           ! Local Scalars
           logical(lk) :: left,lquery,notran
           character :: transt
           integer(ilp) :: i,i1,i2,i3,ib,ic,iinfo,iwt,ja,jc,ldwork,lwkopt,mi,nb, &
                     nbmin,ni,nq,nw
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           ! test the input arguments
           info = 0
           left = la_lsame(side,'L')
           notran = la_lsame(trans,'N')
           lquery = (lwork == -1)
           ! nq is the order of q and nw is the minimum dimension of work
           if (left) then
              nq = m
              nw = max(1,n)
           else
              nq = n
              nw = max(1,m)
           end if
           if (.not. left .and. .not. la_lsame(side,'R')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'C')) then
              info = -2
           else if (m < 0) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0 .or. k > nq) then
              info = -5
           else if (l < 0 .or. (left .and. (l > m)) .or. (.not. left .and. (l > n))) then
              info = -6
           else if (lda < max(1,k)) then
              info = -8
           else if (ldc < max(1,m)) then
              info = -11
#:if rk == "sp"
           else if (lwork < nw .and. .not. lquery) then
#:else
           else if (lwork < max(1,nw) .and. .not. lquery) then
#:endif
              info = -13
           end if
           if (info == 0) then
              ! compute the workspace requirements
              if (m == 0 .or. n == 0) then
                 lwkopt = 1
              else
                 nb = min(nbmax,la_ilaenv(1,'${ri.upper()}$UNMRQ',side//trans,m,n,k,-1))

                 lwkopt = nw*nb + tsize
              end if
              work(1) = lwkopt
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$UNMRZ',-info)
              return
           else if (lquery) then
              return
           end if
           ! quick return if possible
           if (m == 0 .or. n == 0) then
              return
           end if
#:if rk == "sp"
           ! determine the block size.
#:else
           ! determine the block size.  nb may be at most nbmax, where nbmax
           ! is used to define the local array t.
#:endif
           nb = min(nbmax,la_ilaenv(1,'${ri.upper()}$UNMRQ',side//trans,m,n,k,-1))
           nbmin = 2
           ldwork = nw
           if (nb > 1 .and. nb < k) then
              if (lwork < lwkopt) then
                 nb = (lwork - tsize)/ldwork
                 nbmin = max(2,la_ilaenv(2,'${ri.upper()}$UNMRQ',side//trans,m,n,k,-1))
              end if
           end if
           if (nb < nbmin .or. nb >= k) then
              ! use unblocked code
              call la_${ri}$unmr3(side,trans,m,n,k,l,a,lda,tau,c,ldc,work,iinfo)

           else
              ! use blocked code
              iwt = 1 + nw*nb
              if ((left .and. .not. notran) .or. (.not. left .and. notran)) then
                 i1 = 1
                 i2 = k
                 i3 = nb
              else
                 i1 = ((k - 1)/nb)*nb + 1
                 i2 = 1
                 i3 = -nb
              end if
              if (left) then
                 ni = n
                 jc = 1
                 ja = m - l + 1
              else
                 mi = m
                 ic = 1
                 ja = n - l + 1
              end if
              if (notran) then
                 transt = 'C'
              else
                 transt = 'N'
              end if
              do i = i1,i2,i3
                 ib = min(nb,k - i + 1)
                 ! form the triangular factor of the block reflector
                 ! h = h(i+ib-1) . . . h(i+1) h(i)
                 call la_${ri}$larzt('BACKWARD','ROWWISE',l,ib,a(i,ja),lda,tau(i),work( &
                            iwt),ldt)
                 if (left) then
                    ! h or h**h is applied to c(i:m,1:n)
                    mi = m - i + 1
                    ic = i
                 else
                    ! h or h**h is applied to c(1:m,i:n)
                    ni = n - i + 1
                    jc = i
                 end if
                 ! apply h or h**h
                 call la_${ri}$larzb(side,transt,'BACKWARD','ROWWISE',mi,ni,ib,l,a(i,ja) &
                           ,lda,work(iwt),ldt,c(ic,jc),ldc,work,ldwork)
              end do
           end if
           work(1) = lwkopt
           return
     end subroutine la_${ri}$unmrz
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

end module la_lapack_orthogonal_factors_rz
