#:include "common.fypp"
#:include "la_lapack_interfaces.fypp"
!> Kind-agnostic LAPACK interface linking to internal or external implementations
module la_lapack
     use la_constants
     use la_blas
     use la_lapack_aux
     use la_lapack_auxiliary
     use la_lapack_blas_like_base
     use la_lapack_blas_like_l1
     use la_lapack_blas_like_l2
     use la_lapack_blas_like_l3
     use la_lapack_blas_like_mnorm
     use la_lapack_blas_like_scalar
     use la_lapack_givens_jacobi_rot
     use la_lapack_householder_reflectors
     use la_lapack_solve_aux
     use la_lapack_others_sm
     use la_lapack_solve_chol
     use la_lapack_solve_chol_comp
     use la_lapack_solve_ldl
     use la_lapack_solve_ldl_comp
     use la_lapack_solve_ldl_comp2
     use la_lapack_solve_ldl_comp3
     use la_lapack_solve_ldl_comp4
     use la_lapack_solve_lu
     use la_lapack_solve_lu_comp
     use la_lapack_solve_tri_comp
     use la_lapack_cosine_sine
     use la_lapack_eigv_gen_aux
     use la_lapack_eigv_gen_hess
     use la_lapack_lsq_constrained
     use la_lapack_orthogonal_factors_ql
     use la_lapack_orthogonal_factors_qr
     use la_lapack_orthogonal_factors_rz
     use la_lapack_svd_bidiag_qr
     use la_lapack_svd_comp2
     use la_lapack_eigv_comp
     use la_lapack_eigv_comp2
     use la_lapack_eigv_gen
     use la_lapack_eigv_gen2
     use la_lapack_eigv_gen3
     use la_lapack_eigv_svd_bidiag_dc
     use la_lapack_eigv_svd_drivers
     use la_lapack_eigv_svd_drivers2
     use la_lapack_eigv_sym
     use la_lapack_eigv_sym_comp
     use la_lapack_eigv_tridiag
     use la_lapack_eigv_tridiag2
     use la_lapack_eigv_tridiag3
     use la_lapack_lsq
     use la_lapack_lsq_aux
     use la_lapack_svd_comp
     implicit none(type,external)
     public

#:for generic, doc, entries, stubs in LA_LAPACK_INTERFACES
#:for line in doc
          !> ${line}$
#:endfor
          interface ${generic}$
#:for specific, internal, stub in entries
#:if LA_GUARD[specific[0]]
#ifdef ${LA_GUARD[specific[0]]}$
#:endif
#:if stub
#ifdef LA_EXTERNAL_LAPACK
$:stubs[stub].format(**LA_BY_INITIAL[specific[0]])
#else
               module procedure la_${internal}$
#endif
#:else
               module procedure la_${internal}$
#:endif
#:if LA_GUARD[specific[0]]
#endif
#:endif
#:endfor
          end interface ${generic}$

#:endfor
end module la_lapack
