#:include "common.fypp" 
#!if WITH_QP 
module la_lapack_w
     use la_constants
     use la_blas
     use la_lapack_aux
     use la_lapack_s
     use la_lapack_c
     use la_lapack_d
     use la_lapack_z
#!if WITH_QP 
     use la_lapack_q
#!endif 
     use la_lapack_auxiliary
     use la_lapack_blas_like_base
     use la_lapack_blas_like_l1
     use la_lapack_blas_like_l2
     use la_lapack_blas_like_l3
     use la_lapack_blas_like_mnorm
     use la_lapack_blas_like_scalar
     use la_lapack_givens_jacobi_rot
     use la_lapack_householder_reflectors
     use la_lapack_solve_aux
     use la_lapack_solve_chol_comp
     use la_lapack_solve_lu_comp
     use la_lapack_solve_tri_comp
     use la_lapack_cosine_sine
     use la_lapack_eigv_gen_aux
     use la_lapack_eigv_gen_hess
     use la_lapack_orthogonal_factors_ql
     use la_lapack_orthogonal_factors_qr
     use la_lapack_orthogonal_factors_rz
     use la_lapack_svd_bidiag_qr
     use la_lapack_svd_comp2
     implicit none(type,external)
     private


     public :: sp,dp,qp,lk,ilp

     ! 128-bit real constants 
     real(qp),    parameter, private ::     negone = -1.00_qp
     real(qp),    parameter, private ::       zero = 0.00_qp
     real(qp),    parameter, private ::       half = 0.50_qp
     real(qp),    parameter, private ::        one = 1.00_qp
     real(qp),    parameter, private ::        two = 2.00_qp
     real(qp),    parameter, private ::      three = 3.00_qp
     real(qp),    parameter, private ::       four = 4.00_qp
     real(qp),    parameter, private ::      eight = 8.00_qp
     real(qp),    parameter, private ::        ten = 10.00_qp

     ! 128-bit complex constants 
     complex(qp), parameter, private :: czero   = ( 0.0_qp,0.0_qp)
     complex(qp), parameter, private :: chalf   = ( 0.5_qp,0.0_qp)
     complex(qp), parameter, private :: cone    = ( 1.0_qp,0.0_qp)
     complex(qp), parameter, private :: cnegone = (-1.0_qp,0.0_qp)

     ! 128-bit scaling constants 
     integer,     parameter, private :: maxexp = maxexponent(zero) 
     integer,     parameter, private :: minexp = minexponent(zero) 
     real(qp),    parameter, private :: rradix = real(radix(zero),qp) 
     real(qp),    parameter, private :: ulp    = epsilon(zero) 
     real(qp),    parameter, private :: eps    = ulp*half 
     real(qp),    parameter, private :: safmin = rradix**max(minexp-1,1-maxexp) 
     real(qp),    parameter, private :: safmax = one/safmin 
     real(qp),    parameter, private :: smlnum = safmin/ulp 
     real(qp),    parameter, private :: bignum = safmax*ulp 
     real(qp),    parameter, private :: rtmin  = sqrt(smlnum) 
     real(qp),    parameter, private :: rtmax  = sqrt(bignum) 

     ! 128-bit Blue's scaling constants 
     ! ssml>=1/s and sbig==1/S with s,S as defined in https://doi.org/10.1145/355769.355771 
     real(qp),    parameter, private :: tsml   = rradix**ceiling((minexp-1)*half) 
     real(qp),    parameter, private :: tbig   = rradix**floor((maxexp-digits(zero)+1)*half) 
     real(qp),    parameter, private :: ssml   = rradix**(-floor((minexp-digits(zero))*half)) 
     real(qp),    parameter, private :: sbig   = rradix**(-ceiling((maxexp+digits(zero)-1)*half)) 


     contains

end module la_lapack_w
#!endif
