#:include "common.fypp"
!> LU drivers: general, banded and tridiagonal systems
module la_lapack_solve_lu
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level3_gen
     use la_lapack_auxiliary
     use la_lapack_blas_like_base
     use la_lapack_blas_like_mnorm
     use la_lapack_solve_lu_comp
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$gtsv
     public :: la_${ri}$gbsv
     public :: la_${ri}$gbsvx
     public :: la_${ri}$gtsvx
#:if rkl is not None
     public :: la_${ri}$${ril}$gesv
#:endif
     public :: la_${ri}$gesv
     public :: la_${ri}$gesvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$gtsv
     public :: la_${ri}$gbsv
     public :: la_${ri}$gbsvx
     public :: la_${ri}$gtsvx
#:if rkl is not None
     public :: la_${ri}$${ril}$gesv
#:endif
     public :: la_${ri}$gesv
     public :: la_${ri}$gesvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GTSV:  solves the equation
     !> A*X = B,
     !> where A is an n by n tridiagonal matrix, by Gaussian elimination with
     !> partial pivoting.
     !> Note that the equation  A**T*X = B  may be solved by interchanging the
     !> order of the arguments DU and DL.

     pure subroutine la_${ri}$gtsv(n,nrhs,dl,d,du,b,ldb,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldb,n,nrhs
           ! Array Arguments
           real(${rk}$),intent(inout) :: b(ldb,*),d(*),dl(*),du(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: fact,temp
           ! Intrinsic Functions
           intrinsic :: abs,max
           ! Executable Statements
           info = 0
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (ldb < max(1,n)) then
              info = -7
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GTSV ',-info)
              return
           end if
           if (n == 0) return
           if (nrhs == 1) then
              loop_10: do i = 1,n - 2
                 if (abs(d(i)) >= abs(dl(i))) then
                    ! no row interchange required
                    if (d(i) /= zero) then
                       fact = dl(i)/d(i)
                       d(i + 1) = d(i + 1) - fact*du(i)
                       b(i + 1,1) = b(i + 1,1) - fact*b(i,1)
                    else
                       info = i
                       return
                    end if
                    dl(i) = zero
                 else
                    ! interchange rows i and i+1
                    fact = d(i)/dl(i)
                    d(i) = dl(i)
                    temp = d(i + 1)
                    d(i + 1) = du(i) - fact*temp
                    dl(i) = du(i + 1)
                    du(i + 1) = -fact*dl(i)
                    du(i) = temp
                    temp = b(i,1)
                    b(i,1) = b(i + 1,1)
                    b(i + 1,1) = temp - fact*b(i + 1,1)
                 end if
              end do loop_10
              if (n > 1) then
                 i = n - 1
                 if (abs(d(i)) >= abs(dl(i))) then
                    if (d(i) /= zero) then
                       fact = dl(i)/d(i)
                       d(i + 1) = d(i + 1) - fact*du(i)
                       b(i + 1,1) = b(i + 1,1) - fact*b(i,1)
                    else
                       info = i
                       return
                    end if
                 else
                    fact = d(i)/dl(i)
                    d(i) = dl(i)
                    temp = d(i + 1)
                    d(i + 1) = du(i) - fact*temp
                    du(i) = temp
                    temp = b(i,1)
                    b(i,1) = b(i + 1,1)
                    b(i + 1,1) = temp - fact*b(i + 1,1)
                 end if
              end if
              if (d(n) == zero) then
                 info = n
                 return
              end if
           else
              loop_40: do i = 1,n - 2
                 if (abs(d(i)) >= abs(dl(i))) then
                    ! no row interchange required
                    if (d(i) /= zero) then
                       fact = dl(i)/d(i)
                       d(i + 1) = d(i + 1) - fact*du(i)
                       do j = 1,nrhs
                          b(i + 1,j) = b(i + 1,j) - fact*b(i,j)
                       end do
                    else
                       info = i
                       return
                    end if
                    dl(i) = zero
                 else
                    ! interchange rows i and i+1
                    fact = d(i)/dl(i)
                    d(i) = dl(i)
                    temp = d(i + 1)
                    d(i + 1) = du(i) - fact*temp
                    dl(i) = du(i + 1)
                    du(i + 1) = -fact*dl(i)
                    du(i) = temp
                    do j = 1,nrhs
                       temp = b(i,j)
                       b(i,j) = b(i + 1,j)
                       b(i + 1,j) = temp - fact*b(i + 1,j)
                    end do
                 end if
              end do loop_40
              if (n > 1) then
                 i = n - 1
                 if (abs(d(i)) >= abs(dl(i))) then
                    if (d(i) /= zero) then
                       fact = dl(i)/d(i)
                       d(i + 1) = d(i + 1) - fact*du(i)
                       do j = 1,nrhs
                          b(i + 1,j) = b(i + 1,j) - fact*b(i,j)
                       end do
                    else
                       info = i
                       return
                    end if
                 else
                    fact = d(i)/dl(i)
                    d(i) = dl(i)
                    temp = d(i + 1)
                    d(i + 1) = du(i) - fact*temp
                    du(i) = temp
                    do j = 1,nrhs
                       temp = b(i,j)
                       b(i,j) = b(i + 1,j)
                       b(i + 1,j) = temp - fact*b(i + 1,j)
                    end do
                 end if
              end if
              if (d(n) == zero) then
                 info = n
                 return
              end if
           end if
           ! back solve with the matrix u from the factorization.
           if (nrhs <= 2) then
              j = 1
              70 continue
              b(n,j) = b(n,j)/d(n)
              if (n > 1) b(n - 1,j) = (b(n - 1,j) - du(n - 1)*b(n,j))/d(n - 1)
              do i = n - 2,1,-1
                 b(i,j) = (b(i,j) - du(i)*b(i + 1,j) - dl(i)*b(i + 2,j))/d(i)

              end do
              if (j < nrhs) then
                 j = j + 1
                 go to 70
              end if
           else
              do j = 1,nrhs
                 b(n,j) = b(n,j)/d(n)
                 if (n > 1) b(n - 1,j) = (b(n - 1,j) - du(n - 1)*b(n,j))/d(n - 1)
                 do i = n - 2,1,-1
                    b(i,j) = (b(i,j) - du(i)*b(i + 1,j) - dl(i)*b(i + 2,j))/d(i)

                 end do
              end do
           end if
           return
     end subroutine la_${ri}$gtsv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GBSV: computes the solution to a real system of linear equations
     !> A * X = B, where A is a band matrix of order N with KL subdiagonals
     !> and KU superdiagonals, and X and B are N-by-NRHS matrices.
     !> The LU decomposition with partial pivoting and row interchanges is
     !> used to factor A as A = L * U, where L is a product of permutation
     !> and unit lower triangular matrices with KL subdiagonals, and U is
     !> upper triangular with KL+KU superdiagonals.  The factored form of A
     !> is then used to solve the system of equations A * X = B.

     pure subroutine la_${ri}$gbsv(n,kl,ku,nrhs,ab,ldab,ipiv,b,ldb,info)
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: kl,ku,ldab,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           real(${rk}$),intent(inout) :: ab(ldab,*),b(ldb,*)
        ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -1
           else if (kl < 0) then
              info = -2
           else if (ku < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (ldab < 2*kl + ku + 1) then
              info = -6
           else if (ldb < max(n,1)) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GBSV ',-info)
              return
           end if
           ! compute the lu factorization of the band matrix a.
           call la_${ri}$gbtrf(n,n,kl,ku,ab,ldab,ipiv,info)
           if (info == 0) then
              ! solve the system a*x = b, overwriting b with x.
              call la_${ri}$gbtrs('NO TRANSPOSE',n,kl,ku,nrhs,ab,ldab,ipiv,b,ldb,info)

           end if
           return
     end subroutine la_${ri}$gbsv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GBSVX: uses the LU factorization to compute the solution to a real
     !> system of linear equations A * X = B, A**T * X = B, or A**H * X = B,
     !> where A is a band matrix of order N with KL subdiagonals and KU
     !> superdiagonals, and X and B are N-by-NRHS matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     subroutine la_${ri}$gbsvx(fact,trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,equed,r, &
               c,b,ldb,x,ldx,rcond,ferr,berr,work,iwork,info)
        use la_constants_${rk}$,only:zero,one
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(inout) :: equed
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: kl,ku,ldab,ldafb,ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: ab(ldab,*),afb(ldafb,*),b(ldb,*),c(*),r(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),work(*),x(ldx,*)
#:if rk == "sp"
        ! =====================================================================
        ! moved setting of info = n+1 so info does not subsequently get
        ! overwritten.  sven, 17 mar 05.
#:endif
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: colequ,equil,nofact,notran,rowequ
           character :: norm
           integer(ilp) :: i,infequ,j,j1,j2
           real(${rk}$) :: amax,anorm,bignum,colcnd,rcmax,rcmin,rowcnd,rpvgrw,smlnum
           ! Intrinsic Functions
           intrinsic :: abs,max,min
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           equil = la_lsame(fact,'E')
           notran = la_lsame(trans,'N')
           if (nofact .or. equil) then
              equed = 'N'
              rowequ = .false.
              colequ = .false.
           else
              rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
              colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              smlnum = la_${ri}$lamch('SAFE MINIMUM')
              bignum = one/smlnum
           end if
           ! test the input parameters.
           if (.not. nofact .and. .not. equil .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (kl < 0) then
              info = -4
           else if (ku < 0) then
              info = -5
           else if (nrhs < 0) then
              info = -6
           else if (ldab < kl + ku + 1) then
              info = -8
           else if (ldafb < 2*kl + ku + 1) then
              info = -10
           else if (la_lsame(fact,'F') .and. .not. (rowequ .or. colequ .or. la_lsame( &
                     equed,'N'))) then
              info = -12
           else
              if (rowequ) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,r(j))
                    rcmax = max(rcmax,r(j))
                 end do
                 if (rcmin <= zero) then
                    info = -13
                 else if (n > 0) then
                    rowcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    rowcnd = one
                 end if
              end if
              if (colequ .and. info == 0) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,c(j))
                    rcmax = max(rcmax,c(j))
                 end do
                 if (rcmin <= zero) then
                    info = -14
                 else if (n > 0) then
                    colcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    colcnd = one
                 end if
              end if
              if (info == 0) then
                 if (ldb < max(1,n)) then
                    info = -16
                 else if (ldx < max(1,n)) then
                    info = -18
                 end if
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GBSVX',-info)
              return
           end if
           if (equil) then
              ! compute row and column scalings to equilibrate the matrix a.
              call la_${ri}$gbequ(n,n,kl,ku,ab,ldab,r,c,rowcnd,colcnd,amax,infequ)

              if (infequ == 0) then
                 ! equilibrate the matrix.
                 call la_${ri}$laqgb(n,n,kl,ku,ab,ldab,r,c,rowcnd,colcnd,amax,equed)

                 rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
                 colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              end if
           end if
           ! scale the right hand side.
           if (notran) then
              if (rowequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       b(i,j) = r(i)*b(i,j)
                    end do
                 end do
              end if
           else if (colequ) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = c(i)*b(i,j)
                 end do
              end do
           end if
           if (nofact .or. equil) then
              ! compute the lu factorization of the band matrix a.
              do j = 1,n
                 j1 = max(j - ku,1)
                 j2 = min(j + kl,n)
                 call la_${ri}$copy(j2 - j1 + 1,ab(ku + 1 - j + j1,j),1,afb(kl + ku + 1 - j + j1,j),1)

              end do
              call la_${ri}$gbtrf(n,n,kl,ku,afb,ldafb,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 ! compute the reciprocal pivot growth factor of the
                 ! leading rank-deficient info columns of a.
                 anorm = zero
                 do j = 1,info
                    do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                       anorm = max(anorm,abs(ab(i,j)))
                    end do
                 end do
                 rpvgrw = la_${ri}$lantb('M','U','N',info,min(info - 1,kl + ku),afb(max(1, &
                           kl + ku + 2 - info),1),ldafb,work)
                 if (rpvgrw == zero) then
                    rpvgrw = one
                 else
                    rpvgrw = anorm/rpvgrw
                 end if
                 work(1) = rpvgrw
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a and the
           ! reciprocal pivot growth factor rpvgrw.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$langb(norm,n,kl,ku,ab,ldab,work)
           rpvgrw = la_${ri}$lantb('M','U','N',n,kl + ku,afb,ldafb,work)
           if (rpvgrw == zero) then
              rpvgrw = one
           else
              rpvgrw = la_${ri}$langb('M',n,kl,ku,ab,ldab,work)/rpvgrw
           end if
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gbcon(norm,n,kl,ku,afb,ldafb,ipiv,anorm,rcond,work,iwork,info)

           ! compute the solution matrix x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$gbtrs(trans,n,kl,ku,nrhs,afb,ldafb,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solution and
           ! compute error bounds and backward error estimates for it.
           call la_${ri}$gbrfs(trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,b,ldb,x,ldx, &
                     ferr,berr,work,iwork,info)
           ! transform the solution matrix x to a solution of the original
           ! system.
           if (notran) then
              if (colequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       x(i,j) = c(i)*x(i,j)
                    end do
                 end do
                 do j = 1,nrhs
                    ferr(j) = ferr(j)/colcnd
                 end do
              end if
           else if (rowequ) then
              do j = 1,nrhs
                 do i = 1,n
                    x(i,j) = r(i)*x(i,j)
                 end do
              end do
              do j = 1,nrhs
                 ferr(j) = ferr(j)/rowcnd
              end do
           end if
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ri}$lamch('EPSILON')) info = n + 1
           work(1) = rpvgrw
           return
     end subroutine la_${ri}$gbsvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GTSVX: uses the LU factorization to compute the solution to a real
     !> system of linear equations A * X = B or A**T * X = B,
     !> where A is a tridiagonal matrix of order N and X and B are N-by-NRHS
     !> matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     pure subroutine la_${ri}$gtsvx(fact,trans,n,nrhs,dl,d,du,dlf,df,duf,du2,ipiv,b, &
               ldb,x,ldx,rcond,ferr,berr,work,iwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(in) :: b(ldb,*),d(*),dl(*),du(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),work(*),x(ldx,*)
           real(${rk}$),intent(inout) :: df(*),dlf(*),du2(*),duf(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: nofact,notran
           character :: norm
           real(${rk}$) :: anorm
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           notran = la_lsame(trans,'N')
           if (.not. nofact .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -14
           else if (ldx < max(1,n)) then
              info = -16
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GTSVX',-info)
              return
           end if
           if (nofact) then
              ! compute the lu factorization of a.
              call la_${ri}$copy(n,d,1,df,1)
              if (n > 1) then
                 call la_${ri}$copy(n - 1,dl,1,dlf,1)
                 call la_${ri}$copy(n - 1,du,1,duf,1)
              end if
              call la_${ri}$gttrf(n,dlf,df,duf,du2,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$langt(norm,n,dl,d,du)
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gtcon(norm,n,dlf,df,duf,du2,ipiv,anorm,rcond,work,iwork,info)

           ! compute the solution vectors x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$gttrs(trans,n,nrhs,dlf,df,duf,du2,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solutions and
           ! compute error bounds and backward error estimates for them.
           call la_${ri}$gtrfs(trans,n,nrhs,dl,d,du,dlf,df,duf,du2,ipiv,b,ldb,x,ldx, &
                     ferr,berr,work,iwork,info)
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ri}$lamch('EPSILON')) info = n + 1
           return
     end subroutine la_${ri}$gtsvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
#:if rkl is not None
     !> ${ri.upper()}$${ril.upper()}$GESV: computes the solution to a real system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> ${ri.upper()}$${ril.upper()}$GESV first attempts to factorize the matrix in SINGLE PRECISION
     !> and use this factorization within an iterative refinement procedure
     !> to produce a solution with ${LA_PRECISION[rk].upper()}$ PRECISION normwise backward error
     !> quality (see below). If the approach fails the method switches to a
     !> ${LA_PRECISION[rk].upper()}$ PRECISION factorization and solve.
     !> The iterative refinement is not going to be a winning strategy if
     !> the ratio SINGLE PRECISION performance over ${LA_PRECISION[rk].upper()}$ PRECISION
     !> performance is too small. A reasonable strategy should take the
     !> number of right-hand sides and the size of the matrix into account.
     !> This might be done with a call to ILAENV in the future. Up to now, we
     !> always try iterative refinement.
     !> The iterative refinement process is stopped if
     !> ITER > ITERMAX
     !> or for all the RHS we have:
     !> RNRM < SQRT(N)*XNRM*ANRM*EPS*BWDMAX
     !> where
     !> o ITER is the number of the current iteration in the iterative
     !> refinement process
     !> o RNRM is the infinity-norm of the residual
     !> o XNRM is the infinity-norm of the solution
     !> o ANRM is the infinity-operator-norm of the matrix A
     !> o EPS is the machine epsilon returned by ${ri.upper()}$LAMCH('Epsilon')
     !> The value ITERMAX and BWDMAX are fixed to 30 and 1.0D+00
     !> respectively.

     subroutine la_${ri}$${ril}$gesv(n,nrhs,a,lda,ipiv,b,ldb,x,ldx,work,swork,iter,info)
        use la_constants_${rk}$,only:negone,one

        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info,iter
           integer(ilp),intent(in) :: lda,ldb,ldx,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           real(${rkl}$),intent(out) :: swork(*)
           real(${rk}$),intent(inout) :: a(lda,*)
           real(${rk}$),intent(in) :: b(ldb,*)
           real(${rk}$),intent(out) :: work(n,*),x(ldx,*)
        ! =====================================================================
           ! Parameters
           logical(lk),parameter :: doitref = .true.
           integer(ilp),parameter :: itermax = 30
           real(${rk}$),parameter :: bwdmax = 1.0e+00_${rk}$

           ! Local Scalars
           integer(ilp) :: i,iiter,ptsa,ptsx
           real(${rk}$) :: anrm,cte,eps,rnrm,xnrm
           ! Intrinsic Functions
           intrinsic :: abs,real,max,sqrt
           ! Executable Statements
           info = 0
           iter = 0
           ! test the input parameters.
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -7
           else if (ldx < max(1,n)) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$${ril.upper()}$GESV',-info)
              return
           end if
           ! quick return if (n==0).
           if (n == 0) return
           ! skip ${LA_PRECISION[rkl]}$ precision iterative refinement if a priori slower
           ! than ${LA_PRECISION[rk]}$ precision factorization.
           if (.not. doitref) then
              iter = -1
              go to 40
           end if
           ! compute some constants.
           anrm = la_${ri}$lange('I',n,n,a,lda,work)
           eps = la_${ri}$lamch('EPSILON')
           cte = anrm*eps*sqrt(real(n,KIND=${rk}$))*bwdmax
           ! set the indices ptsa, ptsx for referencing sa and sx in swork.
           ptsa = 1
           ptsx = ptsa + n*n
           ! convert b from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision and store the
           ! result in sx.
           call la_${ri}$lag2${ril}$(n,nrhs,b,ldb,swork(ptsx),n,info)
           if (info /= 0) then
              iter = -2
              go to 40
           end if
           ! convert a from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision and store the
           ! result in sa.
           call la_${ri}$lag2${ril}$(n,n,a,lda,swork(ptsa),n,info)
           if (info /= 0) then
              iter = -2
              go to 40
           end if
           ! compute the lu factorization of sa.
           call la_${ril}$getrf(n,n,swork(ptsa),n,ipiv,info)
           if (info /= 0) then
              iter = -3
              go to 40
           end if
           ! solve the system sa*sx = sb.
           call la_${ril}$getrs('NO TRANSPOSE',n,nrhs,swork(ptsa),n,ipiv,swork(ptsx),n, &
                     info)
           ! convert sx back to ${LA_PRECISION[rk]}$ precision
           call la_${ril}$lag2${ri}$(n,nrhs,swork(ptsx),n,x,ldx,info)
           ! compute r = b - ax (r is work).
           call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,work,n)
           call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',n,nrhs,n,negone,a,lda,x,ldx, &
                     one,work,n)
           ! check whether the nrhs normwise backward errors satisfy the
           ! stopping criterion. if yes, set iter=0 and return.
           do i = 1,nrhs
              xnrm = abs(x(la_i${ri}$amax(n,x(1,i),1),i))
              rnrm = abs(work(la_i${ri}$amax(n,work(1,i),1),i))
              if (rnrm > xnrm*cte) go to 10
           end do
           ! if we are here, the nrhs normwise backward errors satisfy the
           ! stopping criterion. we are good to exit.
           iter = 0
           return
           10 continue
           loop_30: do iiter = 1,itermax
              ! convert r (in work) from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision
              ! and store the result in sx.
              call la_${ri}$lag2${ril}$(n,nrhs,work,n,swork(ptsx),n,info)
              if (info /= 0) then
                 iter = -2
                 go to 40
              end if
              ! solve the system sa*sx = sr.
              call la_${ril}$getrs('NO TRANSPOSE',n,nrhs,swork(ptsa),n,ipiv,swork(ptsx), &
                        n,info)
              ! convert sx back to ${LA_PRECISION[rk]}$ precision and update the current
              ! iterate.
              call la_${ril}$lag2${ri}$(n,nrhs,swork(ptsx),n,work,n,info)
              do i = 1,nrhs
                 call la_${ri}$axpy(n,one,work(1,i),1,x(1,i),1)
              end do
              ! compute r = b - ax (r is work).
              call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,work,n)
              call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',n,nrhs,n,negone,a,lda,x, &
                        ldx,one,work,n)
              ! check whether the nrhs normwise backward errors satisfy the
              ! stopping criterion. if yes, set iter=iiter>0 and return.
              do i = 1,nrhs
                 xnrm = abs(x(la_i${ri}$amax(n,x(1,i),1),i))
                 rnrm = abs(work(la_i${ri}$amax(n,work(1,i),1),i))
                 if (rnrm > xnrm*cte) go to 20
              end do
              ! if we are here, the nrhs normwise backward errors satisfy the
              ! stopping criterion, we are good to exit.
              iter = iiter
              return
              20 continue
           end do loop_30
           ! if we are at this place of the code, this is because we have
           ! performed iter=itermax iterations and never satisfied the
           ! stopping criterion, set up the iter flag accordingly and follow up
           ! on ${LA_PRECISION[rk]}$ precision routine.
           iter = -itermax - 1
           40 continue
           ! single-precision iterative refinement failed to converge to a
           ! satisfactory solution, so we resort to ${LA_PRECISION[rk]}$ precision.
           call la_${ri}$getrf(n,n,a,lda,ipiv,info)
           if (info /= 0) return
           call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$getrs('NO TRANSPOSE',n,nrhs,a,lda,ipiv,x,ldx,info)
           return
     end subroutine la_${ri}$${ril}$gesv
#:endif
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GESV: computes the solution to a real system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> The LU decomposition with partial pivoting and row interchanges is
     !> used to factor A as
     !> A = P * L * U,
     !> where P is a permutation matrix, L is unit lower triangular, and U is
     !> upper triangular.  The factored form of A is then used to solve the
     !> system of equations A * X = B.

     pure subroutine la_${ri}$gesv(n,nrhs,a,lda,ipiv,b,ldb,info)
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           real(${rk}$),intent(inout) :: a(lda,*),b(ldb,*)
        ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -7
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GESV ',-info)
              return
           end if
           ! compute the lu factorization of a.
           call la_${ri}$getrf(n,n,a,lda,ipiv,info)
           if (info == 0) then
              ! solve the system a*x = b, overwriting b with x.
              call la_${ri}$getrs('NO TRANSPOSE',n,nrhs,a,lda,ipiv,b,ldb,info)
           end if
           return
     end subroutine la_${ri}$gesv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GESVX: uses the LU factorization to compute the solution to a real
     !> system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     subroutine la_${ri}$gesvx(fact,trans,n,nrhs,a,lda,af,ldaf,ipiv,equed,r,c,b,ldb, &
               x,ldx,rcond,ferr,berr,work,iwork,info)
        use la_constants_${rk}$,only:zero,one
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(inout) :: equed
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldaf,ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           integer(ilp),intent(out) :: iwork(*)
           real(${rk}$),intent(inout) :: a(lda,*),af(ldaf,*),b(ldb,*),c(*),r(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),work(*),x(ldx,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: colequ,equil,nofact,notran,rowequ
           character :: norm
           integer(ilp) :: i,infequ,j
           real(${rk}$) :: amax,anorm,bignum,colcnd,rcmax,rcmin,rowcnd,rpvgrw,smlnum
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           equil = la_lsame(fact,'E')
           notran = la_lsame(trans,'N')
           if (nofact .or. equil) then
              equed = 'N'
              rowequ = .false.
              colequ = .false.
           else
              rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
              colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              smlnum = la_${ri}$lamch('SAFE MINIMUM')
              bignum = one/smlnum
           end if
           ! test the input parameters.
           if (.not. nofact .and. .not. equil .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (lda < max(1,n)) then
              info = -6
           else if (ldaf < max(1,n)) then
              info = -8
           else if (la_lsame(fact,'F') .and. .not. (rowequ .or. colequ .or. la_lsame( &
                     equed,'N'))) then
              info = -10
           else
              if (rowequ) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,r(j))
                    rcmax = max(rcmax,r(j))
                 end do
                 if (rcmin <= zero) then
                    info = -11
                 else if (n > 0) then
                    rowcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    rowcnd = one
                 end if
              end if
              if (colequ .and. info == 0) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,c(j))
                    rcmax = max(rcmax,c(j))
                 end do
                 if (rcmin <= zero) then
                    info = -12
                 else if (n > 0) then
                    colcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    colcnd = one
                 end if
              end if
              if (info == 0) then
                 if (ldb < max(1,n)) then
                    info = -14
                 else if (ldx < max(1,n)) then
                    info = -16
                 end if
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GESVX',-info)
              return
           end if
           if (equil) then
              ! compute row and column scalings to equilibrate the matrix a.
              call la_${ri}$geequ(n,n,a,lda,r,c,rowcnd,colcnd,amax,infequ)
              if (infequ == 0) then
                 ! equilibrate the matrix.
                 call la_${ri}$laqge(n,n,a,lda,r,c,rowcnd,colcnd,amax,equed)
                 rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
                 colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              end if
           end if
           ! scale the right hand side.
           if (notran) then
              if (rowequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       b(i,j) = r(i)*b(i,j)
                    end do
                 end do
              end if
           else if (colequ) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = c(i)*b(i,j)
                 end do
              end do
           end if
           if (nofact .or. equil) then
              ! compute the lu factorization of a.
              call la_${ri}$lacpy('FULL',n,n,a,lda,af,ldaf)
              call la_${ri}$getrf(n,n,af,ldaf,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 ! compute the reciprocal pivot growth factor of the
                 ! leading rank-deficient info columns of a.
                 rpvgrw = la_${ri}$lantr('M','U','N',info,info,af,ldaf,work)
                 if (rpvgrw == zero) then
                    rpvgrw = one
                 else
                    rpvgrw = la_${ri}$lange('M',n,info,a,lda,work)/rpvgrw
                 end if
                 work(1) = rpvgrw
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a and the
           ! reciprocal pivot growth factor rpvgrw.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$lange(norm,n,n,a,lda,work)
           rpvgrw = la_${ri}$lantr('M','U','N',n,n,af,ldaf,work)
           if (rpvgrw == zero) then
              rpvgrw = one
           else
              rpvgrw = la_${ri}$lange('M',n,n,a,lda,work)/rpvgrw
           end if
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gecon(norm,n,af,ldaf,anorm,rcond,work,iwork,info)
           ! compute the solution matrix x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$getrs(trans,n,nrhs,af,ldaf,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solution and
           ! compute error bounds and backward error estimates for it.
           call la_${ri}$gerfs(trans,n,nrhs,a,lda,af,ldaf,ipiv,b,ldb,x,ldx,ferr,berr, &
                     work,iwork,info)
           ! transform the solution matrix x to a solution of the original
           ! system.
           if (notran) then
              if (colequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       x(i,j) = c(i)*x(i,j)
                    end do
                 end do
                 do j = 1,nrhs
                    ferr(j) = ferr(j)/colcnd
                 end do
              end if
           else if (rowequ) then
              do j = 1,nrhs
                 do i = 1,n
                    x(i,j) = r(i)*x(i,j)
                 end do
              end do
              do j = 1,nrhs
                 ferr(j) = ferr(j)/rowcnd
              end do
           end if
#:if rk != "sp"
           work(1) = rpvgrw
#:endif
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ri}$lamch('EPSILON')) info = n + 1
#:if rk == "sp"
           work(1) = rpvgrw
#:endif
           return
     end subroutine la_${ri}$gesvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GTSV:  solves the equation
     !> A*X = B,
     !> where A is an N-by-N tridiagonal matrix, by Gaussian elimination with
     !> partial pivoting.
     !> Note that the equation  A**T *X = B  may be solved by interchanging the
     !> order of the arguments DU and DL.

     pure subroutine la_${ri}$gtsv(n,nrhs,dl,d,du,b,ldb,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldb,n,nrhs
           ! Array Arguments
           complex(${rk}$),intent(inout) :: b(ldb,*),d(*),dl(*),du(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: j,k
           complex(${rk}$) :: mult,temp,zdum
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,max,real
#:else
           intrinsic :: abs,real,aimag,max
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           info = 0
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (ldb < max(1,n)) then
              info = -7
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GTSV ',-info)
              return
           end if
           if (n == 0) return
           loop_30: do k = 1,n - 1
              if (dl(k) == czero) then
                 ! subdiagonal is czero, no elimination is required.
                 if (d(k) == czero) then
                    ! diagonal is czero: set info = k and return; a unique
                    ! solution can not be found.
                    info = k
                    return
                 end if
              else if (cabs1(d(k)) >= cabs1(dl(k))) then
                 ! no row interchange required
                 mult = dl(k)/d(k)
                 d(k + 1) = d(k + 1) - mult*du(k)
                 do j = 1,nrhs
                    b(k + 1,j) = b(k + 1,j) - mult*b(k,j)
                 end do
                 if (k < (n - 1)) dl(k) = czero
              else
                 ! interchange rows k and k+1
                 mult = d(k)/dl(k)
                 d(k) = dl(k)
                 temp = d(k + 1)
                 d(k + 1) = du(k) - mult*temp
                 if (k < (n - 1)) then
                    dl(k) = du(k + 1)
                    du(k + 1) = -mult*dl(k)
                 end if
                 du(k) = temp
                 do j = 1,nrhs
                    temp = b(k,j)
                    b(k,j) = b(k + 1,j)
                    b(k + 1,j) = temp - mult*b(k + 1,j)
                 end do
              end if
           end do loop_30
           if (d(n) == czero) then
              info = n
              return
           end if
           ! back solve with the matrix u from the factorization.
           do j = 1,nrhs
              b(n,j) = b(n,j)/d(n)
              if (n > 1) b(n - 1,j) = (b(n - 1,j) - du(n - 1)*b(n,j))/d(n - 1)
              do k = n - 2,1,-1
                 b(k,j) = (b(k,j) - du(k)*b(k + 1,j) - dl(k)*b(k + 2,j))/d(k)

              end do
           end do
           return
     end subroutine la_${ri}$gtsv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GBSV: computes the solution to a complex system of linear equations
     !> A * X = B, where A is a band matrix of order N with KL subdiagonals
     !> and KU superdiagonals, and X and B are N-by-NRHS matrices.
     !> The LU decomposition with partial pivoting and row interchanges is
     !> used to factor A as A = L * U, where L is a product of permutation
     !> and unit lower triangular matrices with KL subdiagonals, and U is
     !> upper triangular with KL+KU superdiagonals.  The factored form of A
     !> is then used to solve the system of equations A * X = B.

     pure subroutine la_${ri}$gbsv(n,kl,ku,nrhs,ab,ldab,ipiv,b,ldb,info)
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: kl,ku,ldab,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: ab(ldab,*),b(ldb,*)
        ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -1
           else if (kl < 0) then
              info = -2
           else if (ku < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (ldab < 2*kl + ku + 1) then
              info = -6
           else if (ldb < max(n,1)) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GBSV ',-info)
              return
           end if
           ! compute the lu factorization of the band matrix a.
           call la_${ri}$gbtrf(n,n,kl,ku,ab,ldab,ipiv,info)
           if (info == 0) then
              ! solve the system a*x = b, overwriting b with x.
              call la_${ri}$gbtrs('NO TRANSPOSE',n,kl,ku,nrhs,ab,ldab,ipiv,b,ldb,info)

           end if
           return
     end subroutine la_${ri}$gbsv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GBSVX: uses the LU factorization to compute the solution to a complex
     !> system of linear equations A * X = B, A**T * X = B, or A**H * X = B,
     !> where A is a band matrix of order N with KL subdiagonals and KU
     !> superdiagonals, and X and B are N-by-NRHS matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     subroutine la_${ri}$gbsvx(fact,trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,equed,r, &
               c,b,ldb,x,ldx,rcond,ferr,berr,work,rwork,info)
        use la_constants_${rk}$,only:zero,one
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(inout) :: equed
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: kl,ku,ldab,ldafb,ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),rwork(*)
           real(${rk}$),intent(inout) :: c(*),r(*)
           complex(${rk}$),intent(inout) :: ab(ldab,*),afb(ldafb,*),b(ldb,*)
           complex(${rk}$),intent(out) :: work(*),x(ldx,*)
        ! =====================================================================
        ! moved setting of info = n+1 so info does not subsequently get
        ! overwritten.  sven, 17 mar 05.
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: colequ,equil,nofact,notran,rowequ
           character :: norm
           integer(ilp) :: i,infequ,j,j1,j2
           real(${rk}$) :: amax,anorm,bignum,colcnd,rcmax,rcmin,rowcnd,rpvgrw,smlnum
           ! Intrinsic Functions
           intrinsic :: abs,max,min
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           equil = la_lsame(fact,'E')
           notran = la_lsame(trans,'N')
           if (nofact .or. equil) then
              equed = 'N'
              rowequ = .false.
              colequ = .false.
           else
              rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
              colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              smlnum = la_${ci}$lamch('SAFE MINIMUM')
              bignum = one/smlnum
           end if
           ! test the input parameters.
           if (.not. nofact .and. .not. equil .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (kl < 0) then
              info = -4
           else if (ku < 0) then
              info = -5
           else if (nrhs < 0) then
              info = -6
           else if (ldab < kl + ku + 1) then
              info = -8
           else if (ldafb < 2*kl + ku + 1) then
              info = -10
           else if (la_lsame(fact,'F') .and. .not. (rowequ .or. colequ .or. la_lsame( &
                     equed,'N'))) then
              info = -12
           else
              if (rowequ) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,r(j))
                    rcmax = max(rcmax,r(j))
                 end do
                 if (rcmin <= zero) then
                    info = -13
                 else if (n > 0) then
                    rowcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    rowcnd = one
                 end if
              end if
              if (colequ .and. info == 0) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,c(j))
                    rcmax = max(rcmax,c(j))
                 end do
                 if (rcmin <= zero) then
                    info = -14
                 else if (n > 0) then
                    colcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    colcnd = one
                 end if
              end if
              if (info == 0) then
                 if (ldb < max(1,n)) then
                    info = -16
                 else if (ldx < max(1,n)) then
                    info = -18
                 end if
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GBSVX',-info)
              return
           end if
           if (equil) then
              ! compute row and column scalings to equilibrate the matrix a.
              call la_${ri}$gbequ(n,n,kl,ku,ab,ldab,r,c,rowcnd,colcnd,amax,infequ)

              if (infequ == 0) then
                 ! equilibrate the matrix.
                 call la_${ri}$laqgb(n,n,kl,ku,ab,ldab,r,c,rowcnd,colcnd,amax,equed)

                 rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
                 colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              end if
           end if
           ! scale the right hand side.
           if (notran) then
              if (rowequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       b(i,j) = r(i)*b(i,j)
                    end do
                 end do
              end if
           else if (colequ) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = c(i)*b(i,j)
                 end do
              end do
           end if
           if (nofact .or. equil) then
              ! compute the lu factorization of the band matrix a.
              do j = 1,n
                 j1 = max(j - ku,1)
                 j2 = min(j + kl,n)
                 call la_${ri}$copy(j2 - j1 + 1,ab(ku + 1 - j + j1,j),1,afb(kl + ku + 1 - j + j1,j),1)

              end do
              call la_${ri}$gbtrf(n,n,kl,ku,afb,ldafb,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 ! compute the reciprocal pivot growth factor of the
                 ! leading rank-deficient info columns of a.
                 anorm = zero
                 do j = 1,info
                    do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                       anorm = max(anorm,abs(ab(i,j)))
                    end do
                 end do
                 rpvgrw = la_${ri}$lantb('M','U','N',info,min(info - 1,kl + ku),afb(max(1, &
                           kl + ku + 2 - info),1),ldafb,rwork)
                 if (rpvgrw == zero) then
                    rpvgrw = one
                 else
                    rpvgrw = anorm/rpvgrw
                 end if
                 rwork(1) = rpvgrw
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a and the
           ! reciprocal pivot growth factor rpvgrw.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$langb(norm,n,kl,ku,ab,ldab,rwork)
           rpvgrw = la_${ri}$lantb('M','U','N',n,kl + ku,afb,ldafb,rwork)
           if (rpvgrw == zero) then
              rpvgrw = one
           else
              rpvgrw = la_${ri}$langb('M',n,kl,ku,ab,ldab,rwork)/rpvgrw
           end if
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gbcon(norm,n,kl,ku,afb,ldafb,ipiv,anorm,rcond,work,rwork,info)

           ! compute the solution matrix x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$gbtrs(trans,n,kl,ku,nrhs,afb,ldafb,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solution and
           ! compute error bounds and backward error estimates for it.
           call la_${ri}$gbrfs(trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,b,ldb,x,ldx, &
                     ferr,berr,work,rwork,info)
           ! transform the solution matrix x to a solution of the original
           ! system.
           if (notran) then
              if (colequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       x(i,j) = c(i)*x(i,j)
                    end do
                 end do
                 do j = 1,nrhs
                    ferr(j) = ferr(j)/colcnd
                 end do
              end if
           else if (rowequ) then
              do j = 1,nrhs
                 do i = 1,n
                    x(i,j) = r(i)*x(i,j)
                 end do
              end do
              do j = 1,nrhs
                 ferr(j) = ferr(j)/rowcnd
              end do
           end if
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ci}$lamch('EPSILON')) info = n + 1
           rwork(1) = rpvgrw
           return
     end subroutine la_${ri}$gbsvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GTSVX: uses the LU factorization to compute the solution to a complex
     !> system of linear equations A * X = B, A**T * X = B, or A**H * X = B,
     !> where A is a tridiagonal matrix of order N and X and B are N-by-NRHS
     !> matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     pure subroutine la_${ri}$gtsvx(fact,trans,n,nrhs,dl,d,du,dlf,df,duf,du2,ipiv,b, &
               ldb,x,ldx,rcond,ferr,berr,work,rwork,info)
        use la_constants_${rk}$
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),rwork(*)
           complex(${rk}$),intent(in) :: b(ldb,*),d(*),dl(*),du(*)
           complex(${rk}$),intent(inout) :: df(*),dlf(*),du2(*),duf(*)
           complex(${rk}$),intent(out) :: work(*),x(ldx,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: nofact,notran
           character :: norm
           real(${rk}$) :: anorm
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           notran = la_lsame(trans,'N')
           if (.not. nofact .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -14
           else if (ldx < max(1,n)) then
              info = -16
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GTSVX',-info)
              return
           end if
           if (nofact) then
              ! compute the lu factorization of a.
              call la_${ri}$copy(n,d,1,df,1)
              if (n > 1) then
                 call la_${ri}$copy(n - 1,dl,1,dlf,1)
                 call la_${ri}$copy(n - 1,du,1,duf,1)
              end if
              call la_${ri}$gttrf(n,dlf,df,duf,du2,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$langt(norm,n,dl,d,du)
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gtcon(norm,n,dlf,df,duf,du2,ipiv,anorm,rcond,work,info)
           ! compute the solution vectors x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$gttrs(trans,n,nrhs,dlf,df,duf,du2,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solutions and
           ! compute error bounds and backward error estimates for them.
           call la_${ri}$gtrfs(trans,n,nrhs,dl,d,du,dlf,df,duf,du2,ipiv,b,ldb,x,ldx, &
                     ferr,berr,work,rwork,info)
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ci}$lamch('EPSILON')) info = n + 1
           return
     end subroutine la_${ri}$gtsvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
#:if rkl is not None
     !> ${ri.upper()}$${ril.upper()}$GESV: computes the solution to a complex system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> ${ri.upper()}$${ril.upper()}$GESV first attempts to factorize the matrix in COMPLEX and use this
     !> factorization within an iterative refinement procedure to produce a
     !> solution with COMPLEX*16 normwise backward error quality (see below).
     !> If the approach fails the method switches to a COMPLEX*16
     !> factorization and solve.
     !> The iterative refinement is not going to be a winning strategy if
     !> the ratio COMPLEX performance over COMPLEX*16 performance is too
     !> small. A reasonable strategy should take the number of right-hand
     !> sides and the size of the matrix into account. This might be done
     !> with a call to ILAENV in the future. Up to now, we always try
     !> iterative refinement.
     !> The iterative refinement process is stopped if
     !> ITER > ITERMAX
     !> or for all the RHS we have:
     !> RNRM < SQRT(N)*XNRM*ANRM*EPS*BWDMAX
     !> where
     !> o ITER is the number of the current iteration in the iterative
     !> refinement process
     !> o RNRM is the infinity-norm of the residual
     !> o XNRM is the infinity-norm of the solution
     !> o ANRM is the infinity-operator-norm of the matrix A
     !> o EPS is the machine epsilon returned by ${ci.upper()}$LAMCH('Epsilon')
     !> The value ITERMAX and BWDMAX are fixed to 30 and 1.0D+00
     !> respectively.

     subroutine la_${ri}$${ril}$gesv(n,nrhs,a,lda,ipiv,b,ldb,x,ldx,work,swork,rwork,iter, &
               info)
        use la_constants_${rk}$,only:cone,cnegone
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info,iter
           integer(ilp),intent(in) :: lda,ldb,ldx,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rkl}$),intent(out) :: swork(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(in) :: b(ldb,*)
           complex(${rk}$),intent(out) :: work(n,*),x(ldx,*)
        ! =====================================================================
           ! Parameters
           logical(lk),parameter :: doitref = .true.
           integer(ilp),parameter :: itermax = 30
           real(${rk}$),parameter :: bwdmax = 1.0e+00_${rk}$

           ! Local Scalars
           integer(ilp) :: i,iiter,ptsa,ptsx
           real(${rk}$) :: anrm,cte,eps,rnrm,xnrm
           complex(${rk}$) :: zdum
           ! Intrinsic Functions
           intrinsic :: abs,real,max,sqrt
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           info = 0
           iter = 0
           ! test the input parameters.
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -7
           else if (ldx < max(1,n)) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$${ril.upper()}$GESV',-info)
              return
           end if
           ! quick return if (n==0).
           if (n == 0) return
           ! skip ${LA_PRECISION[rkl]}$ precision iterative refinement if a priori slower
           ! than ${LA_PRECISION[rk]}$ precision factorization.
           if (.not. doitref) then
              iter = -1
              go to 40
           end if
           ! compute some constants.
           anrm = la_${ri}$lange('I',n,n,a,lda,rwork)
           eps = la_${ci}$lamch('EPSILON')
           cte = anrm*eps*sqrt(real(n,KIND=${rk}$))*bwdmax
           ! set the indices ptsa, ptsx for referencing sa and sx in swork.
           ptsa = 1
           ptsx = ptsa + n*n
           ! convert b from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision and store the
           ! result in sx.
           call la_${ri}$lag2${ril}$(n,nrhs,b,ldb,swork(ptsx),n,info)
           if (info /= 0) then
              iter = -2
              go to 40
           end if
           ! convert a from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision and store the
           ! result in sa.
           call la_${ri}$lag2${ril}$(n,n,a,lda,swork(ptsa),n,info)
           if (info /= 0) then
              iter = -2
              go to 40
           end if
           ! compute the lu factorization of sa.
           call la_${ril}$getrf(n,n,swork(ptsa),n,ipiv,info)
           if (info /= 0) then
              iter = -3
              go to 40
           end if
           ! solve the system sa*sx = sb.
           call la_${ril}$getrs('NO TRANSPOSE',n,nrhs,swork(ptsa),n,ipiv,swork(ptsx),n, &
                     info)
           ! convert sx back to ${LA_PRECISION[rk]}$ precision
           call la_${ril}$lag2${ri}$(n,nrhs,swork(ptsx),n,x,ldx,info)
           ! compute r = b - ax (r is work).
           call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,work,n)
           call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',n,nrhs,n,cnegone,a,lda,x,ldx, &
                     cone,work,n)
           ! check whether the nrhs normwise backward errors satisfy the
           ! stopping criterion. if yes, set iter=0 and return.
           do i = 1,nrhs
              xnrm = cabs1(x(la_i${ri}$amax(n,x(1,i),1),i))
              rnrm = cabs1(work(la_i${ri}$amax(n,work(1,i),1),i))
              if (rnrm > xnrm*cte) go to 10
           end do
           ! if we are here, the nrhs normwise backward errors satisfy the
           ! stopping criterion. we are good to exit.
           iter = 0
           return
           10 continue
           loop_30: do iiter = 1,itermax
              ! convert r (in work) from ${LA_PRECISION[rk]}$ precision to ${LA_PRECISION[rkl]}$ precision
              ! and store the result in sx.
              call la_${ri}$lag2${ril}$(n,nrhs,work,n,swork(ptsx),n,info)
              if (info /= 0) then
                 iter = -2
                 go to 40
              end if
              ! solve the system sa*sx = sr.
              call la_${ril}$getrs('NO TRANSPOSE',n,nrhs,swork(ptsa),n,ipiv,swork(ptsx), &
                        n,info)
              ! convert sx back to ${LA_PRECISION[rk]}$ precision and update the current
              ! iterate.
              call la_${ril}$lag2${ri}$(n,nrhs,swork(ptsx),n,work,n,info)
              do i = 1,nrhs
                 call la_${ri}$axpy(n,cone,work(1,i),1,x(1,i),1)
              end do
              ! compute r = b - ax (r is work).
              call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,work,n)
              call la_${ri}$gemm('NO TRANSPOSE','NO TRANSPOSE',n,nrhs,n,cnegone,a,lda,x, &
                        ldx,cone,work,n)
              ! check whether the nrhs normwise backward errors satisfy the
              ! stopping criterion. if yes, set iter=iiter>0 and return.
              do i = 1,nrhs
                 xnrm = cabs1(x(la_i${ri}$amax(n,x(1,i),1),i))
                 rnrm = cabs1(work(la_i${ri}$amax(n,work(1,i),1),i))
                 if (rnrm > xnrm*cte) go to 20
              end do
              ! if we are here, the nrhs normwise backward errors satisfy the
              ! stopping criterion, we are good to exit.
              iter = iiter
              return
              20 continue
           end do loop_30
           ! if we are at this place of the code, this is because we have
           ! performed iter=itermax iterations and never satisfied the stopping
           ! criterion, set up the iter flag accordingly and follow up on double
           ! precision routine.
           iter = -itermax - 1
           40 continue
           ! single-precision iterative refinement failed to converge to a
           ! satisfactory solution, so we resort to ${LA_PRECISION[rk]}$ precision.
           call la_${ri}$getrf(n,n,a,lda,ipiv,info)
           if (info /= 0) return
           call la_${ri}$lacpy('ALL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$getrs('NO TRANSPOSE',n,nrhs,a,lda,ipiv,x,ldx,info)
           return
     end subroutine la_${ri}$${ril}$gesv
#:endif
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GESV: computes the solution to a complex system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> The LU decomposition with partial pivoting and row interchanges is
     !> used to factor A as
     !> A = P * L * U,
     !> where P is a permutation matrix, L is unit lower triangular, and U is
     !> upper triangular.  The factored form of A is then used to solve the
     !> system of equations A * X = B.

     pure subroutine la_${ri}$gesv(n,nrhs,a,lda,ipiv,b,ldb,info)
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*),b(ldb,*)
        ! =====================================================================
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (n < 0) then
              info = -1
           else if (nrhs < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (ldb < max(1,n)) then
              info = -7
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GESV ',-info)
              return
           end if
           ! compute the lu factorization of a.
           call la_${ri}$getrf(n,n,a,lda,ipiv,info)
           if (info == 0) then
              ! solve the system a*x = b, overwriting b with x.
              call la_${ri}$getrs('NO TRANSPOSE',n,nrhs,a,lda,ipiv,b,ldb,info)
           end if
           return
     end subroutine la_${ri}$gesv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$GESVX: uses the LU factorization to compute the solution to a complex
     !> system of linear equations
     !> A * X = B,
     !> where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
     !> Error bounds on the solution and a condition estimate are also
     !> provided.

     subroutine la_${ri}$gesvx(fact,trans,n,nrhs,a,lda,af,ldaf,ipiv,equed,r,c,b,ldb, &
               x,ldx,rcond,ferr,berr,work,rwork,info)
        use la_constants_${rk}$,only:zero,one
        ! -- lapack driver routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(inout) :: equed
           character,intent(in) :: fact,trans
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldaf,ldb,ldx,n,nrhs
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(inout) :: ipiv(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),rwork(*)
           real(${rk}$),intent(inout) :: c(*),r(*)
           complex(${rk}$),intent(inout) :: a(lda,*),af(ldaf,*),b(ldb,*)
           complex(${rk}$),intent(out) :: work(*),x(ldx,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: colequ,equil,nofact,notran,rowequ
           character :: norm
           integer(ilp) :: i,infequ,j
           real(${rk}$) :: amax,anorm,bignum,colcnd,rcmax,rcmin,rowcnd,rpvgrw,smlnum
           ! Intrinsic Functions
           intrinsic :: max,min
           ! Executable Statements
           info = 0
           nofact = la_lsame(fact,'N')
           equil = la_lsame(fact,'E')
           notran = la_lsame(trans,'N')
           if (nofact .or. equil) then
              equed = 'N'
              rowequ = .false.
              colequ = .false.
           else
              rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
              colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              smlnum = la_${ci}$lamch('SAFE MINIMUM')
              bignum = one/smlnum
           end if
           ! test the input parameters.
           if (.not. nofact .and. .not. equil .and. .not. la_lsame(fact,'F')) then
              info = -1
           else if (.not. notran .and. .not. la_lsame(trans,'T') .and. .not. la_lsame( &
                     trans,'C')) then
              info = -2
           else if (n < 0) then
              info = -3
           else if (nrhs < 0) then
              info = -4
           else if (lda < max(1,n)) then
              info = -6
           else if (ldaf < max(1,n)) then
              info = -8
           else if (la_lsame(fact,'F') .and. .not. (rowequ .or. colequ .or. la_lsame( &
                     equed,'N'))) then
              info = -10
           else
              if (rowequ) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,r(j))
                    rcmax = max(rcmax,r(j))
                 end do
                 if (rcmin <= zero) then
                    info = -11
                 else if (n > 0) then
                    rowcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    rowcnd = one
                 end if
              end if
              if (colequ .and. info == 0) then
                 rcmin = bignum
                 rcmax = zero
                 do j = 1,n
                    rcmin = min(rcmin,c(j))
                    rcmax = max(rcmax,c(j))
                 end do
                 if (rcmin <= zero) then
                    info = -12
                 else if (n > 0) then
                    colcnd = max(rcmin,smlnum)/min(rcmax,bignum)
                 else
                    colcnd = one
                 end if
              end if
              if (info == 0) then
                 if (ldb < max(1,n)) then
                    info = -14
                 else if (ldx < max(1,n)) then
                    info = -16
                 end if
              end if
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$GESVX',-info)
              return
           end if
           if (equil) then
              ! compute row and column scalings to equilibrate the matrix a.
              call la_${ri}$geequ(n,n,a,lda,r,c,rowcnd,colcnd,amax,infequ)
              if (infequ == 0) then
                 ! equilibrate the matrix.
                 call la_${ri}$laqge(n,n,a,lda,r,c,rowcnd,colcnd,amax,equed)
                 rowequ = la_lsame(equed,'R') .or. la_lsame(equed,'B')
                 colequ = la_lsame(equed,'C') .or. la_lsame(equed,'B')
              end if
           end if
           ! scale the right hand side.
           if (notran) then
              if (rowequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       b(i,j) = r(i)*b(i,j)
                    end do
                 end do
              end if
           else if (colequ) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = c(i)*b(i,j)
                 end do
              end do
           end if
           if (nofact .or. equil) then
              ! compute the lu factorization of a.
              call la_${ri}$lacpy('FULL',n,n,a,lda,af,ldaf)
              call la_${ri}$getrf(n,n,af,ldaf,ipiv,info)
              ! return if info is non-zero.
              if (info > 0) then
                 ! compute the reciprocal pivot growth factor of the
                 ! leading rank-deficient info columns of a.
                 rpvgrw = la_${ri}$lantr('M','U','N',info,info,af,ldaf,rwork)
                 if (rpvgrw == zero) then
                    rpvgrw = one
                 else
                    rpvgrw = la_${ri}$lange('M',n,info,a,lda,rwork)/rpvgrw
                 end if
                 rwork(1) = rpvgrw
                 rcond = zero
                 return
              end if
           end if
           ! compute the norm of the matrix a and the
           ! reciprocal pivot growth factor rpvgrw.
           if (notran) then
              norm = '1'
           else
              norm = 'I'
           end if
           anorm = la_${ri}$lange(norm,n,n,a,lda,rwork)
           rpvgrw = la_${ri}$lantr('M','U','N',n,n,af,ldaf,rwork)
           if (rpvgrw == zero) then
              rpvgrw = one
           else
              rpvgrw = la_${ri}$lange('M',n,n,a,lda,rwork)/rpvgrw
           end if
           ! compute the reciprocal of the condition number of a.
           call la_${ri}$gecon(norm,n,af,ldaf,anorm,rcond,work,rwork,info)
           ! compute the solution matrix x.
           call la_${ri}$lacpy('FULL',n,nrhs,b,ldb,x,ldx)
           call la_${ri}$getrs(trans,n,nrhs,af,ldaf,ipiv,x,ldx,info)
           ! use iterative refinement to improve the computed solution and
           ! compute error bounds and backward error estimates for it.
           call la_${ri}$gerfs(trans,n,nrhs,a,lda,af,ldaf,ipiv,b,ldb,x,ldx,ferr,berr, &
                     work,rwork,info)
           ! transform the solution matrix x to a solution of the original
           ! system.
           if (notran) then
              if (colequ) then
                 do j = 1,nrhs
                    do i = 1,n
                       x(i,j) = c(i)*x(i,j)
                    end do
                 end do
                 do j = 1,nrhs
                    ferr(j) = ferr(j)/colcnd
                 end do
              end if
           else if (rowequ) then
              do j = 1,nrhs
                 do i = 1,n
                    x(i,j) = r(i)*x(i,j)
                 end do
              end do
              do j = 1,nrhs
                 ferr(j) = ferr(j)/rowcnd
              end do
           end if
           ! set info = n+1 if the matrix is singular to working precision.
           if (rcond < la_${ci}$lamch('EPSILON')) info = n + 1
           rwork(1) = rpvgrw
           return
     end subroutine la_${ri}$gesvx
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

end module la_lapack_solve_lu
