#:include "common.fypp"
!> Hermitian indefinite components: Bunch-Kaufman factorization, solve, inverse
module la_lapack_solve_ldl_comp3
     use la_constants
     use la_blas_aux
     use la_blas_level1
     use la_blas_level2_gen
     use la_blas_level2_pac
     use la_blas_level3_gen
     use la_blas_level3_tri
     use la_lapack_aux
     use la_lapack_auxiliary
     use la_lapack_blas_like_l1
     use la_lapack_blas_like_scalar
     use la_lapack_solve_aux
     use la_lapack_solve_ldl_comp
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$heswapr
     public :: la_${ri}$hetf2
     public :: la_${ri}$hetri
     public :: la_${ri}$hetrs_3
     public :: la_${ri}$hptrf
     public :: la_${ri}$hptri
     public :: la_${ri}$lahef
     public :: la_${ri}$heequb
     public :: la_${ri}$hetrf
     public :: la_${ri}$hetrs
     public :: la_${ri}$hetrs2
     public :: la_${ri}$hptrs
     public :: la_${ri}$hecon
     public :: la_${ri}$herfs
     public :: la_${ri}$hpcon
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HESWAPR: applies an elementary permutation on the rows and the columns of
     !> a hermitian matrix.

     pure subroutine la_${ri}$heswapr(uplo,n,a,lda,i1,i2)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(in) :: i1,i2,lda,n
           ! Array Arguments
           complex(${rk}$),intent(inout) :: a(lda,n)
        ! =====================================================================
           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i
           complex(${rk}$) :: tmp
           ! Executable Statements
           upper = la_lsame(uplo,'U')
           if (upper) then
               ! upper
               ! first swap
                ! - swap column i1 and i2 from i1 to i1-1
              call la_${ri}$swap(i1 - 1,a(1,i1),1,a(1,i2),1)
                ! second swap :
                ! - swap a(i1,i1) and a(i2,i2)
                ! - swap row i1 from i1+1 to i2-1 with col i2 from i1+1 to i2-1
                ! - swap a(i2,i1) and a(i1,i2)
              tmp = a(i1,i1)
              a(i1,i1) = a(i2,i2)
              a(i2,i2) = tmp
              do i = 1,i2 - i1 - 1
                 tmp = a(i1,i1 + i)
                 a(i1,i1 + i) = conjg(a(i1 + i,i2))
                 a(i1 + i,i2) = conjg(tmp)
              end do
               a(i1,i2) = conjg(a(i1,i2))
                ! third swap
                ! - swap row i1 and i2 from i2+1 to n
              do i = i2 + 1,n
                 tmp = a(i1,i)
                 a(i1,i) = a(i2,i)
                 a(i2,i) = tmp
              end do
             else
               ! lower
               ! first swap
                ! - swap row i1 and i2 from 1 to i1-1
              call la_${ri}$swap(i1 - 1,a(i1,1),lda,a(i2,1),lda)
               ! second swap :
                ! - swap a(i1,i1) and a(i2,i2)
                ! - swap col i1 from i1+1 to i2-1 with row i2 from i1+1 to i2-1
                ! - swap a(i2,i1) and a(i1,i2)
               tmp = a(i1,i1)
               a(i1,i1) = a(i2,i2)
               a(i2,i2) = tmp
               do i = 1,i2 - i1 - 1
                  tmp = a(i1 + i,i1)
                  a(i1 + i,i1) = conjg(a(i2,i1 + i))
                  a(i2,i1 + i) = conjg(tmp)
               end do
               a(i2,i1) = conjg(a(i2,i1))
               ! third swap
                ! - swap col i1 and i2 from i2+1 to n
               do i = i2 + 1,n
                  tmp = a(i,i1)
                  a(i,i1) = a(i,i2)
                  a(i,i2) = tmp
               end do
           end if
     end subroutine la_${ri}$heswapr
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETF2: computes the factorization of a complex Hermitian matrix A
     !> using the Bunch-Kaufman diagonal pivoting method:
     !> A = U*D*U**H  or  A = L*D*L**H
     !> where U (or L) is a product of permutation and unit upper (lower)
     !> triangular matrices, U**H is the conjugate transpose of U, and D is
     !> Hermitian and block diagonal with 1-by-1 and 2-by-2 diagonal blocks.
     !> This is the unblocked version of the algorithm, calling Level 2 BLAS.

     pure subroutine la_${ri}$hetf2(uplo,n,a,lda,ipiv,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
        ! =====================================================================
           ! Parameters
           real(${rk}$),parameter :: sevten = 17.0e+0_${rk}$

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,imax,j,jmax,k,kk,kp,kstep
           real(${rk}$) :: absakk,alpha,colmax,d,d11,d22,r1,rowmax,tt
           complex(${rk}$) :: d12,d21,t,wk,wkm1,wkp1,zdum
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,cmplx,conjg,max,real,sqrt
#:else
           intrinsic :: abs,real,cmplx,conjg,aimag,max,sqrt
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETF2',-info)
              return
           end if
           ! initialize alpha for use in choosing pivot block size.
           alpha = (one + sqrt(sevten))/eight
           if (upper) then
              ! factorize a as u*d*u**h using the upper triangle of a
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2
              k = n
              10 continue
              ! if k < 1, exit from loop
              if (k < 1) go to 90
              kstep = 1
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(a(k,k),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value.
              ! determine both colmax and imax.
              if (k > 1) then
                 imax = la_i${ri}$amax(k - 1,a(1,k),1)
                 colmax = cabs1(a(imax,k))
              else
                 colmax = zero
              end if
              if ((max(absakk,colmax) == zero) .or. la_${ci}$isnan(absakk)) then
#:if rk == "sp"
                 ! column k is or underflow, or contains a nan:
#:else
                 ! column k is zero or underflow, or contains a nan:
#:endif
                 ! set info and continue
                 if (info == 0) info = k
                 kp = k
                 a(k,k) = real(a(k,k),KIND=${rk}$)
              else
#:if rk != "sp"
                 ! ============================================================
                 ! test for interchange
#:endif
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! jmax is the column-index of the largest off-diagonal
#:if rk == "sp"
                    ! element in row imax, and rowmax is its absolute value
#:else
                    ! element in row imax, and rowmax is its absolute value.
                    ! determine only rowmax.
#:endif
                    jmax = imax + la_i${ri}$amax(k - imax,a(imax,imax + 1),lda)
                    rowmax = cabs1(a(imax,jmax))
                    if (imax > 1) then
                       jmax = la_i${ri}$amax(imax - 1,a(1,imax),1)
                       rowmax = max(rowmax,cabs1(a(jmax,imax)))
                    end if
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    else if (abs(real(a(imax,imax),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                    else
                       ! interchange rows and columns k-1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                 end if
#:if rk != "sp"
                 ! ============================================================
#:endif
                 kk = k - kstep + 1
                 if (kp /= kk) then
                    ! interchange rows and columns kk and kp in the leading
                    ! submatrix a(1:k,1:k)
                    call la_${ri}$swap(kp - 1,a(1,kk),1,a(1,kp),1)
                    do j = kp + 1,kk - 1
                       t = conjg(a(j,kk))
                       a(j,kk) = conjg(a(kp,j))
                       a(kp,j) = t
                    end do
                    a(kp,kk) = conjg(a(kp,kk))
                    r1 = real(a(kk,kk),KIND=${rk}$)
                    a(kk,kk) = real(a(kp,kp),KIND=${rk}$)
                    a(kp,kp) = r1
                    if (kstep == 2) then
                       a(k,k) = real(a(k,k),KIND=${rk}$)
                       t = a(k - 1,k)
                       a(k - 1,k) = a(kp,k)
                       a(kp,k) = t
                    end if
                 else
                    a(k,k) = real(a(k,k),KIND=${rk}$)
                    if (kstep == 2) a(k - 1,k - 1) = real(a(k - 1,k - 1),KIND=${rk}$)
                 end if
                 ! update the leading submatrix
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column k now holds
                    ! w(k) = u(k)*d(k)
                    ! where u(k) is the k-th column of u
                    ! perform a rank-1 update of a(1:k-1,1:k-1) as
                    ! a := a - u(k)*d(k)*u(k)**h = a - w(k)*1/d(k)*w(k)**h
                    r1 = one/real(a(k,k),KIND=${rk}$)
                    call la_${ri}$her(uplo,k - 1,-r1,a(1,k),1,a,lda)
                    ! store u(k) in column k
                    call la_${ri}$${ci}$scal(k - 1,r1,a(1,k),1)
                 else
                    ! 2-by-2 pivot block d(k): columns k and k-1 now hold
                    ! ( w(k-1) w(k) ) = ( u(k-1) u(k) )*d(k)
                    ! where u(k) and u(k-1) are the k-th and (k-1)-th columns
                    ! of u
                    ! perform a rank-2 update of a(1:k-2,1:k-2) as
                    ! a := a - ( u(k-1) u(k) )*d(k)*( u(k-1) u(k) )**h
                       ! = a - ( w(k-1) w(k) )*inv(d(k))*( w(k-1) w(k) )**h
                    if (k > 2) then
                       d = la_${ci}$lapy2(real(a(k - 1,k),KIND=${rk}$),aimag(a(k - 1,k)))

                       d22 = real(a(k - 1,k - 1),KIND=${rk}$)/d
                       d11 = real(a(k,k),KIND=${rk}$)/d
                       tt = one/(d11*d22 - one)
                       d12 = a(k - 1,k)/d
                       d = tt/d
                       do j = k - 2,1,-1
                          wkm1 = d*(d11*a(j,k - 1) - conjg(d12)*a(j,k))
                          wk = d*(d22*a(j,k) - d12*a(j,k - 1))
                          do i = j,1,-1
                             a(i,j) = a(i,j) - a(i,k)*conjg(wk) - a(i,k - 1)*conjg( &
                                       wkm1)
                          end do
                          a(j,k) = wk
                          a(j,k - 1) = wkm1
                          a(j,j) = cmplx(real(a(j,j),KIND=${rk}$),zero,KIND=${rk}$)
                       end do
                    end if
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k - 1) = -kp
              end if
              ! decrease k and return to the start of the main loop
              k = k - kstep
              go to 10
           else
              ! factorize a as l*d*l**h using the lower triangle of a
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2
              k = 1
              50 continue
              ! if k > n, exit from loop
              if (k > n) go to 90
              kstep = 1
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(a(k,k),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value.
              ! determine both colmax and imax.
              if (k < n) then
                 imax = k + la_i${ri}$amax(n - k,a(k + 1,k),1)
                 colmax = cabs1(a(imax,k))
              else
                 colmax = zero
              end if
              if ((max(absakk,colmax) == zero) .or. la_${ci}$isnan(absakk)) then
#:if rk == "sp"
                 ! column k is zero or underflow, contains a nan:
#:else
                 ! column k is zero or underflow, or contains a nan:
#:endif
                 ! set info and continue
                 if (info == 0) info = k
                 kp = k
                 a(k,k) = real(a(k,k),KIND=${rk}$)
              else
#:if rk != "sp"
                 ! ============================================================
                 ! test for interchange
#:endif
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! jmax is the column-index of the largest off-diagonal
#:if rk == "sp"
                    ! element in row imax, and rowmax is its absolute value
#:else
                    ! element in row imax, and rowmax is its absolute value.
                    ! determine only rowmax.
#:endif
                    jmax = k - 1 + la_i${ri}$amax(imax - k,a(imax,k),lda)
                    rowmax = cabs1(a(imax,jmax))
                    if (imax < n) then
                       jmax = imax + la_i${ri}$amax(n - imax,a(imax + 1,imax),1)
                       rowmax = max(rowmax,cabs1(a(jmax,imax)))
                    end if
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    else if (abs(real(a(imax,imax),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                    else
                       ! interchange rows and columns k+1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                 end if
#:if rk != "sp"
                 ! ============================================================
#:endif
                 kk = k + kstep - 1
                 if (kp /= kk) then
                    ! interchange rows and columns kk and kp in the trailing
                    ! submatrix a(k:n,k:n)
                    if (kp < n) call la_${ri}$swap(n - kp,a(kp + 1,kk),1,a(kp + 1,kp),1)

                    do j = kk + 1,kp - 1
                       t = conjg(a(j,kk))
                       a(j,kk) = conjg(a(kp,j))
                       a(kp,j) = t
                    end do
                    a(kp,kk) = conjg(a(kp,kk))
                    r1 = real(a(kk,kk),KIND=${rk}$)
                    a(kk,kk) = real(a(kp,kp),KIND=${rk}$)
                    a(kp,kp) = r1
                    if (kstep == 2) then
                       a(k,k) = real(a(k,k),KIND=${rk}$)
                       t = a(k + 1,k)
                       a(k + 1,k) = a(kp,k)
                       a(kp,k) = t
                    end if
                 else
                    a(k,k) = real(a(k,k),KIND=${rk}$)
                    if (kstep == 2) a(k + 1,k + 1) = real(a(k + 1,k + 1),KIND=${rk}$)
                 end if
                 ! update the trailing submatrix
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column k now holds
                    ! w(k) = l(k)*d(k)
                    ! where l(k) is the k-th column of l
                    if (k < n) then
                       ! perform a rank-1 update of a(k+1:n,k+1:n) as
                       ! a := a - l(k)*d(k)*l(k)**h = a - w(k)*(1/d(k))*w(k)**h
                       r1 = one/real(a(k,k),KIND=${rk}$)
                       call la_${ri}$her(uplo,n - k,-r1,a(k + 1,k),1,a(k + 1,k + 1),lda)

                       ! store l(k) in column k
                       call la_${ri}$${ci}$scal(n - k,r1,a(k + 1,k),1)
                    end if
                 else
                    ! 2-by-2 pivot block d(k)
                    if (k < n - 1) then
                       ! perform a rank-2 update of a(k+2:n,k+2:n) as
                       ! a := a - ( l(k) l(k+1) )*d(k)*( l(k) l(k+1) )**h
                          ! = a - ( w(k) w(k+1) )*inv(d(k))*( w(k) w(k+1) )**h
                       ! where l(k) and l(k+1) are the k-th and (k+1)-th
                       ! columns of l
                       d = la_${ci}$lapy2(real(a(k + 1,k),KIND=${rk}$),aimag(a(k + 1,k)))

                       d11 = real(a(k + 1,k + 1),KIND=${rk}$)/d
                       d22 = real(a(k,k),KIND=${rk}$)/d
                       tt = one/(d11*d22 - one)
                       d21 = a(k + 1,k)/d
                       d = tt/d
                       do j = k + 2,n
                          wk = d*(d11*a(j,k) - d21*a(j,k + 1))
                          wkp1 = d*(d22*a(j,k + 1) - conjg(d21)*a(j,k))
                          do i = j,n
                             a(i,j) = a(i,j) - a(i,k)*conjg(wk) - a(i,k + 1)*conjg( &
                                       wkp1)
                          end do
                          a(j,k) = wk
                          a(j,k + 1) = wkp1
                          a(j,j) = cmplx(real(a(j,j),KIND=${rk}$),zero,KIND=${rk}$)
                       end do
                    end if
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k + 1) = -kp
              end if
              ! increase k and return to the start of the main loop
              k = k + kstep
              go to 50
           end if
           90 continue
           return
     end subroutine la_${ri}$hetf2
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETRI: computes the inverse of a complex Hermitian indefinite matrix
     !> A using the factorization A = U*D*U**H or A = L*D*L**H computed by
     !> ${ri.upper()}$HETRF.

     pure subroutine la_${ri}$hetri(uplo,n,a,lda,ipiv,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: j,k,kp,kstep
           real(${rk}$) :: ak,akp1,d,t
           complex(${rk}$) :: akkp1,temp
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,conjg,max,real
#:else
           intrinsic :: abs,real,conjg,max
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETRI',-info)
              return
           end if
           ! quick return if possible
           if (n == 0) return
           ! check that the diagonal matrix d is nonsingular.
           if (upper) then
              ! upper triangular storage: examine d from bottom to top
              do info = n,1,-1
                 if (ipiv(info) > 0 .and. a(info,info) == czero) return
              end do
           else
              ! lower triangular storage: examine d from top to bottom.
              do info = 1,n
                 if (ipiv(info) > 0 .and. a(info,info) == czero) return
              end do
           end if
           info = 0
           if (upper) then
              ! compute inv(a) from the factorization a = u*d*u**h.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              30 continue
              ! if k > n, exit from loop.
              if (k > n) go to 50
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! invert the diagonal block.
                 a(k,k) = one/real(a(k,k),KIND=${rk}$)
                 ! compute column k of the inverse.
                 if (k > 1) then
                    call la_${ri}$copy(k - 1,a(1,k),1,work,1)
                    call la_${ri}$hemv(uplo,k - 1,-cone,a,lda,work,1,czero,a(1,k),1)

                    a(k,k) = a(k,k) - real(la_${ri}$dotc(k - 1,work,1,a(1,k),1), &
                              KIND=${rk}$)
                 end if
                 kstep = 1
              else
                 ! 2 x 2 diagonal block
                 ! invert the diagonal block.
                 t = abs(a(k,k + 1))
                 ak = real(a(k,k),KIND=${rk}$)/t
                 akp1 = real(a(k + 1,k + 1),KIND=${rk}$)/t
                 akkp1 = a(k,k + 1)/t
                 d = t*(ak*akp1 - one)
                 a(k,k) = akp1/d
                 a(k + 1,k + 1) = ak/d
                 a(k,k + 1) = -akkp1/d
                 ! compute columns k and k+1 of the inverse.
                 if (k > 1) then
                    call la_${ri}$copy(k - 1,a(1,k),1,work,1)
                    call la_${ri}$hemv(uplo,k - 1,-cone,a,lda,work,1,czero,a(1,k),1)

                    a(k,k) = a(k,k) - real(la_${ri}$dotc(k - 1,work,1,a(1,k),1), &
                              KIND=${rk}$)
                    a(k,k + 1) = a(k,k + 1) - la_${ri}$dotc(k - 1,a(1,k),1,a(1,k + 1),1)

                    call la_${ri}$copy(k - 1,a(1,k + 1),1,work,1)
                    call la_${ri}$hemv(uplo,k - 1,-cone,a,lda,work,1,czero,a(1,k + 1),1)

                    a(k + 1,k + 1) = a(k + 1,k + 1) - real(la_${ri}$dotc(k - 1,work,1,a(1,k + 1), &
                              1),KIND=${rk}$)
                 end if
                 kstep = 2
              end if
              kp = abs(ipiv(k))
              if (kp /= k) then
                 ! interchange rows and columns k and kp in the leading
                 ! submatrix a(1:k+1,1:k+1)
                 call la_${ri}$swap(kp - 1,a(1,k),1,a(1,kp),1)
                 do j = kp + 1,k - 1
                    temp = conjg(a(j,k))
                    a(j,k) = conjg(a(kp,j))
                    a(kp,j) = temp
                 end do
                 a(kp,k) = conjg(a(kp,k))
                 temp = a(k,k)
                 a(k,k) = a(kp,kp)
                 a(kp,kp) = temp
                 if (kstep == 2) then
                    temp = a(k,k + 1)
                    a(k,k + 1) = a(kp,k + 1)
                    a(kp,k + 1) = temp
                 end if
              end if
              k = k + kstep
              go to 30
              50 continue
           else
              ! compute inv(a) from the factorization a = l*d*l**h.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = n
              60 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 80
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! invert the diagonal block.
                 a(k,k) = one/real(a(k,k),KIND=${rk}$)
                 ! compute column k of the inverse.
                 if (k < n) then
                    call la_${ri}$copy(n - k,a(k + 1,k),1,work,1)
                    call la_${ri}$hemv(uplo,n - k,-cone,a(k + 1,k + 1),lda,work,1,czero,a(k + &
                              1,k),1)
                    a(k,k) = a(k,k) - real(la_${ri}$dotc(n - k,work,1,a(k + 1,k),1), &
                              KIND=${rk}$)
                 end if
                 kstep = 1
              else
                 ! 2 x 2 diagonal block
                 ! invert the diagonal block.
                 t = abs(a(k,k - 1))
                 ak = real(a(k - 1,k - 1),KIND=${rk}$)/t
                 akp1 = real(a(k,k),KIND=${rk}$)/t
                 akkp1 = a(k,k - 1)/t
                 d = t*(ak*akp1 - one)
                 a(k - 1,k - 1) = akp1/d
                 a(k,k) = ak/d
                 a(k,k - 1) = -akkp1/d
                 ! compute columns k-1 and k of the inverse.
                 if (k < n) then
                    call la_${ri}$copy(n - k,a(k + 1,k),1,work,1)
                    call la_${ri}$hemv(uplo,n - k,-cone,a(k + 1,k + 1),lda,work,1,czero,a(k + &
                              1,k),1)
                    a(k,k) = a(k,k) - real(la_${ri}$dotc(n - k,work,1,a(k + 1,k),1), &
                              KIND=${rk}$)
                    a(k,k - 1) = a(k,k - 1) - la_${ri}$dotc(n - k,a(k + 1,k),1,a(k + 1,k - 1),1 &
                              )
                    call la_${ri}$copy(n - k,a(k + 1,k - 1),1,work,1)
                    call la_${ri}$hemv(uplo,n - k,-cone,a(k + 1,k + 1),lda,work,1,czero,a(k + &
                              1,k - 1),1)
                    a(k - 1,k - 1) = a(k - 1,k - 1) - real(la_${ri}$dotc(n - k,work,1,a(k + 1,k - 1) &
                              ,1),KIND=${rk}$)
                 end if
                 kstep = 2
              end if
              kp = abs(ipiv(k))
              if (kp /= k) then
                 ! interchange rows and columns k and kp in the trailing
                 ! submatrix a(k-1:n,k-1:n)
                 if (kp < n) call la_${ri}$swap(n - kp,a(kp + 1,k),1,a(kp + 1,kp),1)
                 do j = k + 1,kp - 1
                    temp = conjg(a(j,k))
                    a(j,k) = conjg(a(kp,j))
                    a(kp,j) = temp
                 end do
                 a(kp,k) = conjg(a(kp,k))
                 temp = a(k,k)
                 a(k,k) = a(kp,kp)
                 a(kp,kp) = temp
                 if (kstep == 2) then
                    temp = a(k,k - 1)
                    a(k,k - 1) = a(kp,k - 1)
                    a(kp,k - 1) = temp
                 end if
              end if
              k = k - kstep
              go to 60
              80 continue
           end if
           return
     end subroutine la_${ri}$hetri
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETRS_3: solves a system of linear equations A * X = B with a complex
     !> Hermitian matrix A using the factorization computed
#:if rk == "sp"
     !> by ${ri.upper()}$HETRF_RK or CHETRF_BK:
#:else
     !> by ${ri.upper()}$HETRF_RK or ZHETRF_BK:
#:endif
     !> A = P*U*D*(U**H)*(P**T) or A = P*L*D*(L**H)*(P**T),
     !> where U (or L) is unit upper (or lower) triangular matrix,
     !> U**H (or L**H) is the conjugate of U (or L), P is a permutation
     !> matrix, P**T is the transpose of P, and D is Hermitian and block
     !> diagonal with 1-by-1 and 2-by-2 diagonal blocks.
     !> This algorithm is using Level 3 BLAS.

     pure subroutine la_${ri}$hetrs_3(uplo,n,nrhs,a,lda,e,ipiv,b,ldb,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(in) :: a(lda,*),e(*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,j,k,kp
           real(${rk}$) :: s
           complex(${rk}$) :: ak,akm1,akm1k,bk,bkm1,denom
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,conjg,max,real
#:else
           intrinsic :: abs,real,conjg,max
#:endif
           ! Executable Statements
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (nrhs < 0) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldb < max(1,n)) then
              info = -9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETRS_3',-info)
              return
           end if
           ! quick return if possible
           if (n == 0 .or. nrhs == 0) return
           if (upper) then
              ! begin upper
              ! solve a*x = b, where a = u*d*u**h.
              ! p**t * b
              ! interchange rows k and ipiv(k) of matrix b in the same order
              ! that the formation order of ipiv(i) vector for upper case.
              ! (we can do the simple loop over ipiv with decrement -1,
              ! since the abs value of ipiv(i) represents the row index
              ! of the interchange with row i in both 1x1 and 2x2 pivot cases)
              do k = n,1,-1
                 kp = abs(ipiv(k))
                 if (kp /= k) then
                    call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 end if
              end do
              ! compute (u \p**t * b) -> b    [ (u \p**t * b) ]
              call la_${ri}$trsm('L','U','N','U',n,nrhs,cone,a,lda,b,ldb)
              ! compute d \ b -> b   [ d \ (u \p**t * b) ]
              i = n
              do while (i >= 1)
                 if (ipiv(i) > 0) then
                    s = real(cone,KIND=${rk}$)/real(a(i,i),KIND=${rk}$)
                    call la_${ri}$${ci}$scal(nrhs,s,b(i,1),ldb)
                 else if (i > 1) then
                    akm1k = e(i)
                    akm1 = a(i - 1,i - 1)/akm1k
                    ak = a(i,i)/conjg(akm1k)
                    denom = akm1*ak - cone
                    do j = 1,nrhs
                       bkm1 = b(i - 1,j)/akm1k
                       bk = b(i,j)/conjg(akm1k)
                       b(i - 1,j) = (ak*bkm1 - bk)/denom
                       b(i,j) = (akm1*bk - bkm1)/denom
                    end do
                    i = i - 1
                 end if
                 i = i - 1
              end do
              ! compute (u**h \ b) -> b   [ u**h \ (d \ (u \p**t * b) ) ]
              call la_${ri}$trsm('L','U','C','U',n,nrhs,cone,a,lda,b,ldb)
              ! p * b  [ p * (u**h \ (d \ (u \p**t * b) )) ]
              ! interchange rows k and ipiv(k) of matrix b in reverse order
              ! from the formation order of ipiv(i) vector for upper case.
              ! (we can do the simple loop over ipiv with increment 1,
              ! since the abs value of ipiv(i) represents the row index
              ! of the interchange with row i in both 1x1 and 2x2 pivot cases)
              do k = 1,n,1
                 kp = abs(ipiv(k))
                 if (kp /= k) then
                    call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 end if
              end do
           else
              ! begin lower
              ! solve a*x = b, where a = l*d*l**h.
              ! p**t * b
              ! interchange rows k and ipiv(k) of matrix b in the same order
              ! that the formation order of ipiv(i) vector for lower case.
              ! (we can do the simple loop over ipiv with increment 1,
              ! since the abs value of ipiv(i) represents the row index
              ! of the interchange with row i in both 1x1 and 2x2 pivot cases)
              do k = 1,n,1
                 kp = abs(ipiv(k))
                 if (kp /= k) then
                    call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 end if
              end do
              ! compute (l \p**t * b) -> b    [ (l \p**t * b) ]
              call la_${ri}$trsm('L','L','N','U',n,nrhs,cone,a,lda,b,ldb)
              ! compute d \ b -> b   [ d \ (l \p**t * b) ]
              i = 1
              do while (i <= n)
                 if (ipiv(i) > 0) then
                    s = real(cone,KIND=${rk}$)/real(a(i,i),KIND=${rk}$)
                    call la_${ri}$${ci}$scal(nrhs,s,b(i,1),ldb)
                 else if (i < n) then
                    akm1k = e(i)
                    akm1 = a(i,i)/conjg(akm1k)
                    ak = a(i + 1,i + 1)/akm1k
                    denom = akm1*ak - cone
                    do j = 1,nrhs
                       bkm1 = b(i,j)/conjg(akm1k)
                       bk = b(i + 1,j)/akm1k
                       b(i,j) = (ak*bkm1 - bk)/denom
                       b(i + 1,j) = (akm1*bk - bkm1)/denom
                    end do
                    i = i + 1
                 end if
                 i = i + 1
              end do
              ! compute (l**h \ b) -> b   [ l**h \ (d \ (l \p**t * b) ) ]
              call la_${ri}$trsm('L','L','C','U',n,nrhs,cone,a,lda,b,ldb)
              ! p * b  [ p * (l**h \ (d \ (l \p**t * b) )) ]
              ! interchange rows k and ipiv(k) of matrix b in reverse order
              ! from the formation order of ipiv(i) vector for lower case.
              ! (we can do the simple loop over ipiv with decrement -1,
              ! since the abs value of ipiv(i) represents the row index
              ! of the interchange with row i in both 1x1 and 2x2 pivot cases)
              do k = n,1,-1
                 kp = abs(ipiv(k))
                 if (kp /= k) then
                    call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 end if
              end do
              ! end lower
           end if
           return
     end subroutine la_${ri}$hetrs_3
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HPTRF: computes the factorization of a complex Hermitian packed
     !> matrix A using the Bunch-Kaufman diagonal pivoting method:
     !> A = U*D*U**H  or  A = L*D*L**H
     !> where U (or L) is a product of permutation and unit upper (lower)
     !> triangular matrices, and D is Hermitian and block diagonal with
     !> 1-by-1 and 2-by-2 diagonal blocks.

     pure subroutine la_${ri}$hptrf(uplo,n,ap,ipiv,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: n
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: ap(*)
        ! =====================================================================
           ! Parameters
           real(${rk}$),parameter :: sevten = 17.0e+0_${rk}$

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,imax,j,jmax,k,kc,kk,knc,kp,kpc,kstep,kx,npp
           real(${rk}$) :: absakk,alpha,colmax,d,d11,d22,r1,rowmax,tt
           complex(${rk}$) :: d12,d21,t,wk,wkm1,wkp1,zdum
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,cmplx,conjg,max,real,sqrt
#:else
           intrinsic :: abs,real,cmplx,conjg,aimag,max,sqrt
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HPTRF',-info)
              return
           end if
           ! initialize alpha for use in choosing pivot block size.
           alpha = (one + sqrt(sevten))/eight
           if (upper) then
              ! factorize a as u*d*u**h using the upper triangle of a
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2
              k = n
              kc = (n - 1)*n/2 + 1
              10 continue
              knc = kc
              ! if k < 1, exit from loop
              if (k < 1) go to 110
              kstep = 1
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(ap(kc + k - 1),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value
              if (k > 1) then
                 imax = la_i${ri}$amax(k - 1,ap(kc),1)
                 colmax = cabs1(ap(kc + imax - 1))
              else
                 colmax = zero
              end if
              if (max(absakk,colmax) == zero) then
                 ! column k is zero: set info and continue
                 if (info == 0) info = k
                 kp = k
                 ap(kc + k - 1) = real(ap(kc + k - 1),KIND=${rk}$)
              else
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! jmax is the column-index of the largest off-diagonal
                    ! element in row imax, and rowmax is its absolute value
                    rowmax = zero
                    jmax = imax
                    kx = imax*(imax + 1)/2 + imax
                    do j = imax + 1,k
                       if (cabs1(ap(kx)) > rowmax) then
                          rowmax = cabs1(ap(kx))
                          jmax = j
                       end if
                       kx = kx + j
                    end do
                    kpc = (imax - 1)*imax/2 + 1
                    if (imax > 1) then
                       jmax = la_i${ri}$amax(imax - 1,ap(kpc),1)
                       rowmax = max(rowmax,cabs1(ap(kpc + jmax - 1)))
                    end if
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    else if (abs(real(ap(kpc + imax - 1),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                    else
                       ! interchange rows and columns k-1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                 end if
                 kk = k - kstep + 1
                 if (kstep == 2) knc = knc - k + 1
                 if (kp /= kk) then
                    ! interchange rows and columns kk and kp in the leading
                    ! submatrix a(1:k,1:k)
                    call la_${ri}$swap(kp - 1,ap(knc),1,ap(kpc),1)
                    kx = kpc + kp - 1
                    do j = kp + 1,kk - 1
                       kx = kx + j - 1
                       t = conjg(ap(knc + j - 1))
                       ap(knc + j - 1) = conjg(ap(kx))
                       ap(kx) = t
                    end do
                    ap(kx + kk - 1) = conjg(ap(kx + kk - 1))
                    r1 = real(ap(knc + kk - 1),KIND=${rk}$)
                    ap(knc + kk - 1) = real(ap(kpc + kp - 1),KIND=${rk}$)
                    ap(kpc + kp - 1) = r1
                    if (kstep == 2) then
                       ap(kc + k - 1) = real(ap(kc + k - 1),KIND=${rk}$)
                       t = ap(kc + k - 2)
                       ap(kc + k - 2) = ap(kc + kp - 1)
                       ap(kc + kp - 1) = t
                    end if
                 else
                    ap(kc + k - 1) = real(ap(kc + k - 1),KIND=${rk}$)
                    if (kstep == 2) ap(kc - 1) = real(ap(kc - 1),KIND=${rk}$)
                 end if
                 ! update the leading submatrix
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column k now holds
                    ! w(k) = u(k)*d(k)
                    ! where u(k) is the k-th column of u
                    ! perform a rank-1 update of a(1:k-1,1:k-1) as
                    ! a := a - u(k)*d(k)*u(k)**h = a - w(k)*1/d(k)*w(k)**h
                    r1 = one/real(ap(kc + k - 1),KIND=${rk}$)
                    call la_${ri}$hpr(uplo,k - 1,-r1,ap(kc),1,ap)
                    ! store u(k) in column k
                    call la_${ri}$${ci}$scal(k - 1,r1,ap(kc),1)
                 else
                    ! 2-by-2 pivot block d(k): columns k and k-1 now hold
                    ! ( w(k-1) w(k) ) = ( u(k-1) u(k) )*d(k)
                    ! where u(k) and u(k-1) are the k-th and (k-1)-th columns
                    ! of u
                    ! perform a rank-2 update of a(1:k-2,1:k-2) as
                    ! a := a - ( u(k-1) u(k) )*d(k)*( u(k-1) u(k) )**h
                       ! = a - ( w(k-1) w(k) )*inv(d(k))*( w(k-1) w(k) )**h
                    if (k > 2) then
                       d = la_${ci}$lapy2(real(ap(k - 1 + (k - 1)*k/2),KIND=${rk}$),aimag(ap(k - 1 + ( &
                                 k - 1)*k/2)))
                       d22 = real(ap(k - 1 + (k - 2)*(k - 1)/2),KIND=${rk}$)/d
                       d11 = real(ap(k + (k - 1)*k/2),KIND=${rk}$)/d
                       tt = one/(d11*d22 - one)
                       d12 = ap(k - 1 + (k - 1)*k/2)/d
                       d = tt/d
                       do j = k - 2,1,-1
                          wkm1 = d*(d11*ap(j + (k - 2)*(k - 1)/2) - conjg(d12)*ap(j + (k - 1)*k &
                                    /2))
                          wk = d*(d22*ap(j + (k - 1)*k/2) - d12*ap(j + (k - 2)*(k - 1)/2))

                          do i = j,1,-1
                             ap(i + (j - 1)*j/2) = ap(i + (j - 1)*j/2) - ap(i + (k - 1)*k/2) &
                                       *conjg(wk) - ap(i + (k - 2)*(k - 1)/2)*conjg(wkm1)
                          end do
                          ap(j + (k - 1)*k/2) = wk
                          ap(j + (k - 2)*(k - 1)/2) = wkm1
                          ap(j + (j - 1)*j/2) = cmplx(real(ap(j + (j - 1)*j/2),KIND=${rk}$), &
                                    zero,KIND=${rk}$)
                       end do
                    end if
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k - 1) = -kp
              end if
              ! decrease k and return to the start of the main loop
              k = k - kstep
              kc = knc - k
              go to 10
           else
              ! factorize a as l*d*l**h using the lower triangle of a
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2
              k = 1
              kc = 1
              npp = n*(n + 1)/2
              60 continue
              knc = kc
              ! if k > n, exit from loop
              if (k > n) go to 110
              kstep = 1
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(ap(kc),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value
              if (k < n) then
                 imax = k + la_i${ri}$amax(n - k,ap(kc + 1),1)
                 colmax = cabs1(ap(kc + imax - k))
              else
                 colmax = zero
              end if
              if (max(absakk,colmax) == zero) then
                 ! column k is zero: set info and continue
                 if (info == 0) info = k
                 kp = k
                 ap(kc) = real(ap(kc),KIND=${rk}$)
              else
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! jmax is the column-index of the largest off-diagonal
                    ! element in row imax, and rowmax is its absolute value
                    rowmax = zero
                    kx = kc + imax - k
                    do j = k,imax - 1
                       if (cabs1(ap(kx)) > rowmax) then
                          rowmax = cabs1(ap(kx))
                          jmax = j
                       end if
                       kx = kx + n - j
                    end do
                    kpc = npp - (n - imax + 1)*(n - imax + 2)/2 + 1
                    if (imax < n) then
                       jmax = imax + la_i${ri}$amax(n - imax,ap(kpc + 1),1)
                       rowmax = max(rowmax,cabs1(ap(kpc + jmax - imax)))
                    end if
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    else if (abs(real(ap(kpc),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                    else
                       ! interchange rows and columns k+1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                 end if
                 kk = k + kstep - 1
                 if (kstep == 2) knc = knc + n - k + 1
                 if (kp /= kk) then
                    ! interchange rows and columns kk and kp in the trailing
                    ! submatrix a(k:n,k:n)
                    if (kp < n) call la_${ri}$swap(n - kp,ap(knc + kp - kk + 1),1,ap(kpc + 1),1)

                    kx = knc + kp - kk
                    do j = kk + 1,kp - 1
                       kx = kx + n - j + 1
                       t = conjg(ap(knc + j - kk))
                       ap(knc + j - kk) = conjg(ap(kx))
                       ap(kx) = t
                    end do
                    ap(knc + kp - kk) = conjg(ap(knc + kp - kk))
                    r1 = real(ap(knc),KIND=${rk}$)
                    ap(knc) = real(ap(kpc),KIND=${rk}$)
                    ap(kpc) = r1
                    if (kstep == 2) then
                       ap(kc) = real(ap(kc),KIND=${rk}$)
                       t = ap(kc + 1)
                       ap(kc + 1) = ap(kc + kp - k)
                       ap(kc + kp - k) = t
                    end if
                 else
                    ap(kc) = real(ap(kc),KIND=${rk}$)
                    if (kstep == 2) ap(knc) = real(ap(knc),KIND=${rk}$)
                 end if
                 ! update the trailing submatrix
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column k now holds
                    ! w(k) = l(k)*d(k)
                    ! where l(k) is the k-th column of l
                    if (k < n) then
                       ! perform a rank-1 update of a(k+1:n,k+1:n) as
                       ! a := a - l(k)*d(k)*l(k)**h = a - w(k)*(1/d(k))*w(k)**h
                       r1 = one/real(ap(kc),KIND=${rk}$)
                       call la_${ri}$hpr(uplo,n - k,-r1,ap(kc + 1),1,ap(kc + n - k + 1))
                       ! store l(k) in column k
                       call la_${ri}$${ci}$scal(n - k,r1,ap(kc + 1),1)
                    end if
                 else
                    ! 2-by-2 pivot block d(k): columns k and k+1 now hold
                    ! ( w(k) w(k+1) ) = ( l(k) l(k+1) )*d(k)
                    ! where l(k) and l(k+1) are the k-th and (k+1)-th columns
                    ! of l
                    if (k < n - 1) then
                       ! perform a rank-2 update of a(k+2:n,k+2:n) as
                       ! a := a - ( l(k) l(k+1) )*d(k)*( l(k) l(k+1) )**h
                          ! = a - ( w(k) w(k+1) )*inv(d(k))*( w(k) w(k+1) )**h
                       ! where l(k) and l(k+1) are the k-th and (k+1)-th
                       ! columns of l
                       d = la_${ci}$lapy2(real(ap(k + 1 + (k - 1)*(2*n - k)/2),KIND=${rk}$),aimag( &
                                 ap(k + 1 + (k - 1)*(2*n - k)/2)))
                       d11 = real(ap(k + 1 + k*(2*n - k - 1)/2),KIND=${rk}$)/d
                       d22 = real(ap(k + (k - 1)*(2*n - k)/2),KIND=${rk}$)/d
                       tt = one/(d11*d22 - one)
                       d21 = ap(k + 1 + (k - 1)*(2*n - k)/2)/d
                       d = tt/d
                       do j = k + 2,n
                          wk = d*(d11*ap(j + (k - 1)*(2*n - k)/2) - d21*ap(j + k*(2*n - k - 1)/2) &
                                     )
                          wkp1 = d*(d22*ap(j + k*(2*n - k - 1)/2) - conjg(d21)*ap(j + (k - 1)*( &
                                    2*n - k)/2))
                          do i = j,n
                             ap(i + (j - 1)*(2*n - j)/2) = ap(i + (j - 1)*(2*n - j)/2) - ap( &
                             i + (k - 1)*(2*n - k)/2)*conjg(wk) - ap(i + k*(2*n - k - 1)/2) &
                                       *conjg(wkp1)
                          end do
                          ap(j + (k - 1)*(2*n - k)/2) = wk
                          ap(j + k*(2*n - k - 1)/2) = wkp1
                          ap(j + (j - 1)*(2*n - j)/2) = cmplx(real(ap(j + (j - 1)*(2*n - j)/2 &
                                    ),KIND=${rk}$),zero,KIND=${rk}$)
                       end do
                    end if
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k + 1) = -kp
              end if
              ! increase k and return to the start of the main loop
              k = k + kstep
              kc = knc + n - k + 2
              go to 60
           end if
           110 continue
           return
     end subroutine la_${ri}$hptrf
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HPTRI: computes the inverse of a complex Hermitian indefinite matrix
     !> A in packed storage using the factorization A = U*D*U**H or
     !> A = L*D*L**H computed by ${ri.upper()}$HPTRF.

     pure subroutine la_${ri}$hptri(uplo,n,ap,ipiv,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: n
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(inout) :: ap(*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: j,k,kc,kcnext,kp,kpc,kstep,kx,npp
           real(${rk}$) :: ak,akp1,d,t
           complex(${rk}$) :: akkp1,temp
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,conjg,real
#:else
           intrinsic :: abs,real,conjg
#:endif
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HPTRI',-info)
              return
           end if
           ! quick return if possible
           if (n == 0) return
           ! check that the diagonal matrix d is nonsingular.
           if (upper) then
              ! upper triangular storage: examine d from bottom to top
              kp = n*(n + 1)/2
              do info = n,1,-1
                 if (ipiv(info) > 0 .and. ap(kp) == czero) return
                 kp = kp - info
              end do
           else
              ! lower triangular storage: examine d from top to bottom.
              kp = 1
              do info = 1,n
                 if (ipiv(info) > 0 .and. ap(kp) == czero) return
                 kp = kp + n - info + 1
              end do
           end if
           info = 0
           if (upper) then
              ! compute inv(a) from the factorization a = u*d*u**h.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              kc = 1
              30 continue
              ! if k > n, exit from loop.
              if (k > n) go to 50
              kcnext = kc + k
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! invert the diagonal block.
                 ap(kc + k - 1) = one/real(ap(kc + k - 1),KIND=${rk}$)
                 ! compute column k of the inverse.
                 if (k > 1) then
                    call la_${ri}$copy(k - 1,ap(kc),1,work,1)
                    call la_${ri}$hpmv(uplo,k - 1,-cone,ap,work,1,czero,ap(kc),1)
                    ap(kc + k - 1) = ap(kc + k - 1) - real(la_${ri}$dotc(k - 1,work,1,ap(kc),1), &
                              KIND=${rk}$)
                 end if
                 kstep = 1
              else
                 ! 2 x 2 diagonal block
                 ! invert the diagonal block.
                 t = abs(ap(kcnext + k - 1))
                 ak = real(ap(kc + k - 1),KIND=${rk}$)/t
                 akp1 = real(ap(kcnext + k),KIND=${rk}$)/t
                 akkp1 = ap(kcnext + k - 1)/t
                 d = t*(ak*akp1 - one)
                 ap(kc + k - 1) = akp1/d
                 ap(kcnext + k) = ak/d
                 ap(kcnext + k - 1) = -akkp1/d
                 ! compute columns k and k+1 of the inverse.
                 if (k > 1) then
                    call la_${ri}$copy(k - 1,ap(kc),1,work,1)
                    call la_${ri}$hpmv(uplo,k - 1,-cone,ap,work,1,czero,ap(kc),1)
                    ap(kc + k - 1) = ap(kc + k - 1) - real(la_${ri}$dotc(k - 1,work,1,ap(kc),1), &
                              KIND=${rk}$)
                    ap(kcnext + k - 1) = ap(kcnext + k - 1) - la_${ri}$dotc(k - 1,ap(kc),1,ap( &
                              kcnext),1)
                    call la_${ri}$copy(k - 1,ap(kcnext),1,work,1)
                    call la_${ri}$hpmv(uplo,k - 1,-cone,ap,work,1,czero,ap(kcnext),1)

                    ap(kcnext + k) = ap(kcnext + k) - real(la_${ri}$dotc(k - 1,work,1,ap(kcnext &
                              ),1),KIND=${rk}$)
                 end if
                 kstep = 2
                 kcnext = kcnext + k + 1
              end if
              kp = abs(ipiv(k))
              if (kp /= k) then
                 ! interchange rows and columns k and kp in the leading
                 ! submatrix a(1:k+1,1:k+1)
                 kpc = (kp - 1)*kp/2 + 1
                 call la_${ri}$swap(kp - 1,ap(kc),1,ap(kpc),1)
                 kx = kpc + kp - 1
                 do j = kp + 1,k - 1
                    kx = kx + j - 1
                    temp = conjg(ap(kc + j - 1))
                    ap(kc + j - 1) = conjg(ap(kx))
                    ap(kx) = temp
                 end do
                 ap(kc + kp - 1) = conjg(ap(kc + kp - 1))
                 temp = ap(kc + k - 1)
                 ap(kc + k - 1) = ap(kpc + kp - 1)
                 ap(kpc + kp - 1) = temp
                 if (kstep == 2) then
                    temp = ap(kc + k + k - 1)
                    ap(kc + k + k - 1) = ap(kc + k + kp - 1)
                    ap(kc + k + kp - 1) = temp
                 end if
              end if
              k = k + kstep
              kc = kcnext
              go to 30
              50 continue
           else
              ! compute inv(a) from the factorization a = l*d*l**h.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              npp = n*(n + 1)/2
              k = n
              kc = npp
              60 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 80
              kcnext = kc - (n - k + 2)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! invert the diagonal block.
                 ap(kc) = one/real(ap(kc),KIND=${rk}$)
                 ! compute column k of the inverse.
                 if (k < n) then
                    call la_${ri}$copy(n - k,ap(kc + 1),1,work,1)
                    call la_${ri}$hpmv(uplo,n - k,-cone,ap(kc + n - k + 1),work,1,czero,ap(kc + 1) &
                              ,1)
                    ap(kc) = ap(kc) - real(la_${ri}$dotc(n - k,work,1,ap(kc + 1),1), &
                              KIND=${rk}$)
                 end if
                 kstep = 1
              else
                 ! 2 x 2 diagonal block
                 ! invert the diagonal block.
                 t = abs(ap(kcnext + 1))
                 ak = real(ap(kcnext),KIND=${rk}$)/t
                 akp1 = real(ap(kc),KIND=${rk}$)/t
                 akkp1 = ap(kcnext + 1)/t
                 d = t*(ak*akp1 - one)
                 ap(kcnext) = akp1/d
                 ap(kc) = ak/d
                 ap(kcnext + 1) = -akkp1/d
                 ! compute columns k-1 and k of the inverse.
                 if (k < n) then
                    call la_${ri}$copy(n - k,ap(kc + 1),1,work,1)
                    call la_${ri}$hpmv(uplo,n - k,-cone,ap(kc + (n - k + 1)),work,1,czero,ap( &
                              kc + 1),1)
                    ap(kc) = ap(kc) - real(la_${ri}$dotc(n - k,work,1,ap(kc + 1),1), &
                              KIND=${rk}$)
                    ap(kcnext + 1) = ap(kcnext + 1) - la_${ri}$dotc(n - k,ap(kc + 1),1,ap(kcnext + &
                              2),1)
                    call la_${ri}$copy(n - k,ap(kcnext + 2),1,work,1)
                    call la_${ri}$hpmv(uplo,n - k,-cone,ap(kc + (n - k + 1)),work,1,czero,ap( &
                              kcnext + 2),1)
                    ap(kcnext) = ap(kcnext) - real(la_${ri}$dotc(n - k,work,1,ap(kcnext + 2), &
                              1),KIND=${rk}$)
                 end if
                 kstep = 2
                 kcnext = kcnext - (n - k + 3)
              end if
              kp = abs(ipiv(k))
              if (kp /= k) then
                 ! interchange rows and columns k and kp in the trailing
                 ! submatrix a(k-1:n,k-1:n)
                 kpc = npp - (n - kp + 1)*(n - kp + 2)/2 + 1
                 if (kp < n) call la_${ri}$swap(n - kp,ap(kc + kp - k + 1),1,ap(kpc + 1),1)
                 kx = kc + kp - k
                 do j = k + 1,kp - 1
                    kx = kx + n - j + 1
                    temp = conjg(ap(kc + j - k))
                    ap(kc + j - k) = conjg(ap(kx))
                    ap(kx) = temp
                 end do
                 ap(kc + kp - k) = conjg(ap(kc + kp - k))
                 temp = ap(kc)
                 ap(kc) = ap(kpc)
                 ap(kpc) = temp
                 if (kstep == 2) then
                    temp = ap(kc - n + k - 1)
                    ap(kc - n + k - 1) = ap(kc - n + kp - 1)
                    ap(kc - n + kp - 1) = temp
                 end if
              end if
              k = k - kstep
              kc = kcnext
              go to 60
              80 continue
           end if
           return
     end subroutine la_${ri}$hptri
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LAHEF: computes a partial factorization of a complex Hermitian
     !> matrix A using the Bunch-Kaufman diagonal pivoting method. The
     !> partial factorization has the form:
     !> A  =  ( I  U12 ) ( A11  0  ) (  I      0     )  if UPLO = 'U', or:
     !> ( 0  U22 ) (  0   D  ) ( U12**H U22**H )
     !> A  =  ( L11  0 ) (  D   0  ) ( L11**H L21**H )  if UPLO = 'L'
     !> ( L21  I ) (  0  A22 ) (  0      I     )
     !> where the order of D is at most NB. The actual order is returned in
     !> the argument KB, and is either NB or NB-1, or N if N <= NB.
     !> Note that U**H denotes the conjugate transpose of U.
     !> ${ri.upper()}$LAHEF is an auxiliary routine called by ${ri.upper()}$HETRF. It uses blocked code
     !> (calling Level 3 BLAS) to update the submatrix A11 (if UPLO = 'U') or
     !> A22 (if UPLO = 'L').

     pure subroutine la_${ri}$lahef(uplo,n,nb,kb,a,lda,ipiv,w,ldw,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info,kb
           integer(ilp),intent(in) :: lda,ldw,n,nb
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(out) :: w(ldw,*)
        ! =====================================================================
           ! Parameters
           real(${rk}$),parameter :: sevten = 17.0e+0_${rk}$

           ! Local Scalars
           integer(ilp) :: imax,j,jb,jj,jmax,jp,k,kk,kkw,kp,kstep,kw
           real(${rk}$) :: absakk,alpha,colmax,r1,rowmax,t
           complex(${rk}$) :: d11,d21,d22,z
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,conjg,max,min,real,sqrt
#:else
           intrinsic :: abs,real,conjg,aimag,max,min,sqrt
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(z) = abs(real(z,KIND=${rk}$)) + abs(aimag(z))
           ! Executable Statements
           info = 0
           ! initialize alpha for use in choosing pivot block size.
           alpha = (one + sqrt(sevten))/eight
           if (la_lsame(uplo,'U')) then
              ! factorize the trailing columns of a using the upper triangle
              ! of a and working backwards, and compute the matrix w = u12*d
              ! for use in updating a11 (note that conjg(w) is actually stored)
              ! k is the main loop index, decreasing from n in steps of 1 or 2
#:if rk != "sp"
              ! kw is the column of w which corresponds to column k of a
#:endif
              k = n
              10 continue
#:if rk == "sp"
              ! kw is the column of w which corresponds to column k of a
#:endif
              kw = nb + k - n
              ! exit from loop
              if ((k <= n - nb + 1 .and. nb < n) .or. k < 1) go to 30
              kstep = 1
              ! copy column k of a to column kw of w and update it
              call la_${ri}$copy(k - 1,a(1,k),1,w(1,kw),1)
              w(k,kw) = real(a(k,k),KIND=${rk}$)
              if (k < n) then
                 call la_${ri}$gemv('NO TRANSPOSE',k,n - k,-cone,a(1,k + 1),lda,w(k,kw + 1), &
                           ldw,cone,w(1,kw),1)
                 w(k,kw) = real(w(k,kw),KIND=${rk}$)
              end if
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(w(k,kw),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value.
              ! determine both colmax and imax.
              if (k > 1) then
                 imax = la_i${ri}$amax(k - 1,w(1,kw),1)
                 colmax = cabs1(w(imax,kw))
              else
                 colmax = zero
              end if
              if (max(absakk,colmax) == zero) then
                 ! column k is zero or underflow: set info and continue
                 if (info == 0) info = k
                 kp = k
                 a(k,k) = real(a(k,k),KIND=${rk}$)
              else
                 ! ============================================================
                 ! begin pivot search
                 ! case(1)
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! begin pivot search along imax row
                    ! copy column imax to column kw-1 of w and update it
                    call la_${ri}$copy(imax - 1,a(1,imax),1,w(1,kw - 1),1)
                    w(imax,kw - 1) = real(a(imax,imax),KIND=${rk}$)
                    call la_${ri}$copy(k - imax,a(imax,imax + 1),lda,w(imax + 1,kw - 1),1)

                    call la_${ri}$lacgv(k - imax,w(imax + 1,kw - 1),1)
                    if (k < n) then
                       call la_${ri}$gemv('NO TRANSPOSE',k,n - k,-cone,a(1,k + 1),lda,w(imax, &
                                  kw + 1),ldw,cone,w(1,kw - 1),1)
                       w(imax,kw - 1) = real(w(imax,kw - 1),KIND=${rk}$)
                    end if
                    ! jmax is the column-index of the largest off-diagonal
                    ! element in row imax, and rowmax is its absolute value.
                    ! determine only rowmax.
                    jmax = imax + la_i${ri}$amax(k - imax,w(imax + 1,kw - 1),1)
                    rowmax = cabs1(w(jmax,kw - 1))
                    if (imax > 1) then
                       jmax = la_i${ri}$amax(imax - 1,w(1,kw - 1),1)
                       rowmax = max(rowmax,cabs1(w(jmax,kw - 1)))
                    end if
                    ! case(2)
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    ! case(3)
                    else if (abs(real(w(imax,kw - 1),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                       ! copy column kw-1 of w to column kw of w
                       call la_${ri}$copy(k,w(1,kw - 1),1,w(1,kw),1)
                    ! case(4)
                    else
                       ! interchange rows and columns k-1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                    ! end pivot search along imax row
                 end if
                 ! end pivot search
                 ! ============================================================
                 ! kk is the column of a where pivoting step stopped
                 kk = k - kstep + 1
                 ! kkw is the column of w which corresponds to column kk of a
                 kkw = nb + kk - n
                 ! interchange rows and columns kp and kk.
                 ! updated column kp is already stored in column kkw of w.
                 if (kp /= kk) then
                    ! copy non-updated column kk to column kp of submatrix a
                    ! at step k. no need to copy element into column k
                    ! (or k and k-1 for 2-by-2 pivot) of a, since these columns
                    ! will be later overwritten.
                    a(kp,kp) = real(a(kk,kk),KIND=${rk}$)
                    call la_${ri}$copy(kk - 1 - kp,a(kp + 1,kk),1,a(kp,kp + 1),lda)
                    call la_${ri}$lacgv(kk - 1 - kp,a(kp,kp + 1),lda)
                    if (kp > 1) call la_${ri}$copy(kp - 1,a(1,kk),1,a(1,kp),1)
                    ! interchange rows kk and kp in last k+1 to n columns of a
                    ! (columns k (or k and k-1 for 2-by-2 pivot) of a will be
                    ! later overwritten). interchange rows kk and kp
                    ! in last kkw to nb columns of w.
                    if (k < n) call la_${ri}$swap(n - k,a(kk,k + 1),lda,a(kp,k + 1),lda)
                    call la_${ri}$swap(n - kk + 1,w(kk,kkw),ldw,w(kp,kkw),ldw)
                 end if
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column kw of w now holds
                    ! w(kw) = u(k)*d(k),
                    ! where u(k) is the k-th column of u
                    ! (1) store subdiag. elements of column u(k)
                    ! and 1-by-1 block d(k) in column k of a.
                    ! (note: diagonal element u(k,k) is a unit element
                    ! and not stored)
                       ! a(k,k) := d(k,k) = w(k,kw)
                       ! a(1:k-1,k) := u(1:k-1,k) = w(1:k-1,kw)/d(k,k)
                    ! (note: no need to use for hermitian matrix
                    ! a( k, k ) = real( w( k, k),KIND=${rk}$) to separately copy diagonal
                    ! element d(k,k) from w (potentially saves only one load))
                    call la_${ri}$copy(k,w(1,kw),1,a(1,k),1)
                    if (k > 1) then
                       ! (note: no need to check if a(k,k) is not zero,
                        ! since that was ensured earlier in pivot search:
                        ! case a(k,k) = 0 falls into 2x2 pivot case(4))
                       r1 = one/real(a(k,k),KIND=${rk}$)
                       call la_${ri}$${ci}$scal(k - 1,r1,a(1,k),1)
                       ! (2) conjugate column w(kw)
                       call la_${ri}$lacgv(k - 1,w(1,kw),1)
                    end if
                 else
                    ! 2-by-2 pivot block d(k): columns kw and kw-1 of w now hold
                    ! ( w(kw-1) w(kw) ) = ( u(k-1) u(k) )*d(k)
                    ! where u(k) and u(k-1) are the k-th and (k-1)-th columns
                    ! of u
                    ! (1) store u(1:k-2,k-1) and u(1:k-2,k) and 2-by-2
                    ! block d(k-1:k,k-1:k) in columns k-1 and k of a.
                    ! (note: 2-by-2 diagonal block u(k-1:k,k-1:k) is a unit
                    ! block and not stored)
                       ! a(k-1:k,k-1:k) := d(k-1:k,k-1:k) = w(k-1:k,kw-1:kw)
                       ! a(1:k-2,k-1:k) := u(1:k-2,k:k-1:k) =
                       ! = w(1:k-2,kw-1:kw) * ( d(k-1:k,k-1:k)**(-1) )
                    if (k > 2) then
                       ! factor out the columns of the inverse of 2-by-2 pivot
                       ! block d, so that each column contains 1, to reduce the
                       ! number of flops when we multiply panel
                       ! ( w(kw-1) w(kw) ) by this inverse, i.e. by d**(-1).
                       ! d**(-1) = ( d11 cj(d21) )**(-1) =
                                 ! ( d21    d22 )
                       ! = 1/(d11*d22-|d21|**2) * ( ( d22) (-cj(d21) ) ) =
                                                ! ( (-d21) (     d11 ) )
                       ! = 1/(|d21|**2) * 1/((d11/cj(d21))*(d22/d21)-1) *
                         ! * ( d21*( d22/d21 ) conj(d21)*(           - 1 ) ) =
                           ! (     (      -1 )           ( d11/conj(d21) ) )
                       ! = 1/(|d21|**2) * 1/(d22*d11-1) *
                         ! * ( d21*( d11 ) conj(d21)*(  -1 ) ) =
                           ! (     (  -1 )           ( d22 ) )
                       ! = (1/|d21|**2) * t * ( d21*( d11 ) conj(d21)*(  -1 ) ) =
                                            ! (     (  -1 )           ( d22 ) )
                       ! = ( (t/conj(d21))*( d11 ) (t/d21)*(  -1 ) ) =
                         ! (               (  -1 )         ( d22 ) )
                       ! = ( conj(d21)*( d11 ) d21*(  -1 ) )
                         ! (           (  -1 )     ( d22 ) ),
                       ! where d11 = d22/d21,
                             ! d22 = d11/conj(d21),
                             ! d21 = t/d21,
                             ! t = 1/(d22*d11-1).
                       ! (note: no need to check for division by zero,
                        ! since that was ensured earlier in pivot search:
                        ! (a) d21 != 0, since in 2x2 pivot case(4)
                            ! |d21| should be larger than |d11| and |d22|;
                        ! (b) (d22*d11 - 1) != 0, since from (a),
                            ! both |d11| < 1, |d22| < 1, hence |d22*d11| << 1.)
                       d21 = w(k - 1,kw)
                       d11 = w(k,kw)/conjg(d21)
                       d22 = w(k - 1,kw - 1)/d21
                       t = one/(real(d11*d22,KIND=${rk}$) - one)
                       d21 = t/d21
                       ! update elements in columns a(k-1) and a(k) as
                       ! dot products of rows of ( w(kw-1) w(kw) ) and columns
                       ! of d**(-1)
                       do j = 1,k - 2
                          a(j,k - 1) = d21*(d11*w(j,kw - 1) - w(j,kw))
                          a(j,k) = conjg(d21)*(d22*w(j,kw) - w(j,kw - 1))
                       end do
                    end if
                    ! copy d(k) to a
                    a(k - 1,k - 1) = w(k - 1,kw - 1)
                    a(k - 1,k) = w(k - 1,kw)
                    a(k,k) = w(k,kw)
                    ! (2) conjugate columns w(kw) and w(kw-1)
                    call la_${ri}$lacgv(k - 1,w(1,kw),1)
                    call la_${ri}$lacgv(k - 2,w(1,kw - 1),1)
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k - 1) = -kp
              end if
              ! decrease k and return to the start of the main loop
              k = k - kstep
              go to 10
              30 continue
              ! update the upper triangle of a11 (= a(1:k,1:k)) as
              ! a11 := a11 - u12*d*u12**h = a11 - u12*w**h
              ! computing blocks of nb columns at a time (note that conjg(w) is
              ! actually stored)
              do j = ((k - 1)/nb)*nb + 1,1,-nb
                 jb = min(nb,k - j + 1)
                 ! update the upper triangle of the diagonal block
                 do jj = j,j + jb - 1
                    a(jj,jj) = real(a(jj,jj),KIND=${rk}$)
                    call la_${ri}$gemv('NO TRANSPOSE',jj - j + 1,n - k,-cone,a(j,k + 1),lda,w(jj, &
                               kw + 1),ldw,cone,a(j,jj),1)
                    a(jj,jj) = real(a(jj,jj),KIND=${rk}$)
                 end do
                 ! update the rectangular superdiagonal block
                 call la_${ri}$gemm('NO TRANSPOSE','TRANSPOSE',j - 1,jb,n - k,-cone,a(1,k + 1), &
                           lda,w(j,kw + 1),ldw,cone,a(1,j),lda)
              end do
              ! put u12 in standard form by partially undoing the interchanges
#:if rk == "sp"
              ! in of rows in columns k+1:n looping backwards from k+1 to n
#:else
              ! in columns k+1:n looping backwards from k+1 to n
#:endif
              j = k + 1
              60 continue
#:if rk == "sp"
                 ! undo the interchanges (if any) of rows j and jp
                 ! at each step j
#:else
                 ! undo the interchanges (if any) of rows jj and jp at each
                 ! step j
#:endif
                 ! (here, j is a diagonal index)
                 jj = j
                 jp = ipiv(j)
                 if (jp < 0) then
                    jp = -jp
                    ! (here, j is a diagonal index)
                    j = j + 1
                 end if
                 ! (note: here, j is used to determine row length. length n-j+1
                 ! of the rows to swap back doesn't include diagonal element)
                 j = j + 1
                 if (jp /= jj .and. j <= n) call la_${ri}$swap(n - j + 1,a(jp,j),lda,a(jj,j), &
                           lda)
#:if rk == "sp"
              if (j <= n) go to 60
#:else
              if (j < n) go to 60
#:endif
              ! set kb to the number of columns factorized
              kb = n - k
           else
              ! factorize the leading columns of a using the lower triangle
              ! of a and working forwards, and compute the matrix w = l21*d
              ! for use in updating a22 (note that conjg(w) is actually stored)
              ! k is the main loop index, increasing from 1 in steps of 1 or 2
              k = 1
              70 continue
              ! exit from loop
              if ((k >= nb .and. nb < n) .or. k > n) go to 90
              kstep = 1
              ! copy column k of a to column k of w and update it
              w(k,k) = real(a(k,k),KIND=${rk}$)
              if (k < n) call la_${ri}$copy(n - k,a(k + 1,k),1,w(k + 1,k),1)
              call la_${ri}$gemv('NO TRANSPOSE',n - k + 1,k - 1,-cone,a(k,1),lda,w(k,1),ldw, &
                         cone,w(k,k),1)
              w(k,k) = real(w(k,k),KIND=${rk}$)
              ! determine rows and columns to be interchanged and whether
              ! a 1-by-1 or 2-by-2 pivot block will be used
              absakk = abs(real(w(k,k),KIND=${rk}$))
              ! imax is the row-index of the largest off-diagonal element in
              ! column k, and colmax is its absolute value.
              ! determine both colmax and imax.
              if (k < n) then
                 imax = k + la_i${ri}$amax(n - k,w(k + 1,k),1)
                 colmax = cabs1(w(imax,k))
              else
                 colmax = zero
              end if
              if (max(absakk,colmax) == zero) then
                 ! column k is zero or underflow: set info and continue
                 if (info == 0) info = k
                 kp = k
                 a(k,k) = real(a(k,k),KIND=${rk}$)
              else
                 ! ============================================================
                 ! begin pivot search
                 ! case(1)
                 if (absakk >= alpha*colmax) then
                    ! no interchange, use 1-by-1 pivot block
                    kp = k
                 else
                    ! begin pivot search along imax row
                    ! copy column imax to column k+1 of w and update it
                    call la_${ri}$copy(imax - k,a(imax,k),lda,w(k,k + 1),1)
                    call la_${ri}$lacgv(imax - k,w(k,k + 1),1)
                    w(imax,k + 1) = real(a(imax,imax),KIND=${rk}$)
                    if (imax < n) call la_${ri}$copy(n - imax,a(imax + 1,imax),1,w(imax + 1,k + 1), &
                              1)
                    call la_${ri}$gemv('NO TRANSPOSE',n - k + 1,k - 1,-cone,a(k,1),lda,w(imax, &
                              1),ldw,cone,w(k,k + 1),1)
                    w(imax,k + 1) = real(w(imax,k + 1),KIND=${rk}$)
                    ! jmax is the column-index of the largest off-diagonal
                    ! element in row imax, and rowmax is its absolute value.
                    ! determine only rowmax.
                    jmax = k - 1 + la_i${ri}$amax(imax - k,w(k,k + 1),1)
                    rowmax = cabs1(w(jmax,k + 1))
                    if (imax < n) then
                       jmax = imax + la_i${ri}$amax(n - imax,w(imax + 1,k + 1),1)
                       rowmax = max(rowmax,cabs1(w(jmax,k + 1)))
                    end if
                    ! case(2)
                    if (absakk >= alpha*colmax*(colmax/rowmax)) then
                       ! no interchange, use 1-by-1 pivot block
                       kp = k
                    ! case(3)
                    else if (abs(real(w(imax,k + 1),KIND=${rk}$)) >= alpha*rowmax) then
                       ! interchange rows and columns k and imax, use 1-by-1
                       ! pivot block
                       kp = imax
                       ! copy column k+1 of w to column k of w
                       call la_${ri}$copy(n - k + 1,w(k,k + 1),1,w(k,k),1)
                    ! case(4)
                    else
                       ! interchange rows and columns k+1 and imax, use 2-by-2
                       ! pivot block
                       kp = imax
                       kstep = 2
                    end if
                    ! end pivot search along imax row
                 end if
                 ! end pivot search
                 ! ============================================================
                 ! kk is the column of a where pivoting step stopped
                 kk = k + kstep - 1
                 ! interchange rows and columns kp and kk.
                 ! updated column kp is already stored in column kk of w.
                 if (kp /= kk) then
                    ! copy non-updated column kk to column kp of submatrix a
                    ! at step k. no need to copy element into column k
                    ! (or k and k+1 for 2-by-2 pivot) of a, since these columns
                    ! will be later overwritten.
                    a(kp,kp) = real(a(kk,kk),KIND=${rk}$)
                    call la_${ri}$copy(kp - kk - 1,a(kk + 1,kk),1,a(kp,kk + 1),lda)
                    call la_${ri}$lacgv(kp - kk - 1,a(kp,kk + 1),lda)
                    if (kp < n) call la_${ri}$copy(n - kp,a(kp + 1,kk),1,a(kp + 1,kp),1)

                    ! interchange rows kk and kp in first k-1 columns of a
                    ! (columns k (or k and k+1 for 2-by-2 pivot) of a will be
                    ! later overwritten). interchange rows kk and kp
                    ! in first kk columns of w.
                    if (k > 1) call la_${ri}$swap(k - 1,a(kk,1),lda,a(kp,1),lda)
                    call la_${ri}$swap(kk,w(kk,1),ldw,w(kp,1),ldw)
                 end if
                 if (kstep == 1) then
                    ! 1-by-1 pivot block d(k): column k of w now holds
                    ! w(k) = l(k)*d(k),
                    ! where l(k) is the k-th column of l
                    ! (1) store subdiag. elements of column l(k)
                    ! and 1-by-1 block d(k) in column k of a.
                    ! (note: diagonal element l(k,k) is a unit element
                    ! and not stored)
                       ! a(k,k) := d(k,k) = w(k,k)
                       ! a(k+1:n,k) := l(k+1:n,k) = w(k+1:n,k)/d(k,k)
                    ! (note: no need to use for hermitian matrix
                    ! a( k, k ) = real( w( k, k),KIND=${rk}$) to separately copy diagonal
                    ! element d(k,k) from w (potentially saves only one load))
                    call la_${ri}$copy(n - k + 1,w(k,k),1,a(k,k),1)
                    if (k < n) then
                       ! (note: no need to check if a(k,k) is not zero,
                        ! since that was ensured earlier in pivot search:
                        ! case a(k,k) = 0 falls into 2x2 pivot case(4))
                       r1 = one/real(a(k,k),KIND=${rk}$)
                       call la_${ri}$${ci}$scal(n - k,r1,a(k + 1,k),1)
                       ! (2) conjugate column w(k)
                       call la_${ri}$lacgv(n - k,w(k + 1,k),1)
                    end if
                 else
                    ! 2-by-2 pivot block d(k): columns k and k+1 of w now hold
                    ! ( w(k) w(k+1) ) = ( l(k) l(k+1) )*d(k)
                    ! where l(k) and l(k+1) are the k-th and (k+1)-th columns
                    ! of l
                    ! (1) store l(k+2:n,k) and l(k+2:n,k+1) and 2-by-2
                    ! block d(k:k+1,k:k+1) in columns k and k+1 of a.
                    ! (note: 2-by-2 diagonal block l(k:k+1,k:k+1) is a unit
                    ! block and not stored)
                       ! a(k:k+1,k:k+1) := d(k:k+1,k:k+1) = w(k:k+1,k:k+1)
                       ! a(k+2:n,k:k+1) := l(k+2:n,k:k+1) =
                       ! = w(k+2:n,k:k+1) * ( d(k:k+1,k:k+1)**(-1) )
                    if (k < n - 1) then
                       ! factor out the columns of the inverse of 2-by-2 pivot
                       ! block d, so that each column contains 1, to reduce the
                       ! number of flops when we multiply panel
                       ! ( w(kw-1) w(kw) ) by this inverse, i.e. by d**(-1).
                       ! d**(-1) = ( d11 cj(d21) )**(-1) =
                                 ! ( d21    d22 )
                       ! = 1/(d11*d22-|d21|**2) * ( ( d22) (-cj(d21) ) ) =
                                                ! ( (-d21) (     d11 ) )
                       ! = 1/(|d21|**2) * 1/((d11/cj(d21))*(d22/d21)-1) *
                         ! * ( d21*( d22/d21 ) conj(d21)*(           - 1 ) ) =
                           ! (     (      -1 )           ( d11/conj(d21) ) )
                       ! = 1/(|d21|**2) * 1/(d22*d11-1) *
                         ! * ( d21*( d11 ) conj(d21)*(  -1 ) ) =
                           ! (     (  -1 )           ( d22 ) )
                       ! = (1/|d21|**2) * t * ( d21*( d11 ) conj(d21)*(  -1 ) ) =
                                            ! (     (  -1 )           ( d22 ) )
                       ! = ( (t/conj(d21))*( d11 ) (t/d21)*(  -1 ) ) =
                         ! (               (  -1 )         ( d22 ) )
                       ! = ( conj(d21)*( d11 ) d21*(  -1 ) )
#:if rk == "sp"
                         ! (           (  -1 )     ( d22 ) )
#:else
                         ! (           (  -1 )     ( d22 ) ),
#:endif
                       ! where d11 = d22/d21,
                             ! d22 = d11/conj(d21),
                             ! d21 = t/d21,
                             ! t = 1/(d22*d11-1).
                       ! (note: no need to check for division by zero,
                        ! since that was ensured earlier in pivot search:
                        ! (a) d21 != 0, since in 2x2 pivot case(4)
                            ! |d21| should be larger than |d11| and |d22|;
                        ! (b) (d22*d11 - 1) != 0, since from (a),
                            ! both |d11| < 1, |d22| < 1, hence |d22*d11| << 1.)
                       d21 = w(k + 1,k)
                       d11 = w(k + 1,k + 1)/d21
                       d22 = w(k,k)/conjg(d21)
                       t = one/(real(d11*d22,KIND=${rk}$) - one)
                       d21 = t/d21
                       ! update elements in columns a(k) and a(k+1) as
                       ! dot products of rows of ( w(k) w(k+1) ) and columns
                       ! of d**(-1)
                       do j = k + 2,n
                          a(j,k) = conjg(d21)*(d11*w(j,k) - w(j,k + 1))
                          a(j,k + 1) = d21*(d22*w(j,k + 1) - w(j,k))
                       end do
                    end if
                    ! copy d(k) to a
                    a(k,k) = w(k,k)
                    a(k + 1,k) = w(k + 1,k)
                    a(k + 1,k + 1) = w(k + 1,k + 1)
                    ! (2) conjugate columns w(k) and w(k+1)
                    call la_${ri}$lacgv(n - k,w(k + 1,k),1)
                    call la_${ri}$lacgv(n - k - 1,w(k + 2,k + 1),1)
                 end if
              end if
              ! store details of the interchanges in ipiv
              if (kstep == 1) then
                 ipiv(k) = kp
              else
                 ipiv(k) = -kp
                 ipiv(k + 1) = -kp
              end if
              ! increase k and return to the start of the main loop
              k = k + kstep
              go to 70
              90 continue
              ! update the lower triangle of a22 (= a(k:n,k:n)) as
              ! a22 := a22 - l21*d*l21**h = a22 - l21*w**h
              ! computing blocks of nb columns at a time (note that conjg(w) is
              ! actually stored)
              do j = k,n,nb
                 jb = min(nb,n - j + 1)
                 ! update the lower triangle of the diagonal block
                 do jj = j,j + jb - 1
                    a(jj,jj) = real(a(jj,jj),KIND=${rk}$)
                    call la_${ri}$gemv('NO TRANSPOSE',j + jb - jj,k - 1,-cone,a(jj,1),lda,w(jj, &
                               1),ldw,cone,a(jj,jj),1)
                    a(jj,jj) = real(a(jj,jj),KIND=${rk}$)
                 end do
                 ! update the rectangular subdiagonal block
                 if (j + jb <= n) call la_${ri}$gemm('NO TRANSPOSE','TRANSPOSE',n - j - jb + 1,jb,k - 1,- &
                           cone,a(j + jb,1),lda,w(j,1),ldw,cone,a(j + jb,j),lda)
              end do
              ! put l21 in standard form by partially undoing the interchanges
              ! of rows in columns 1:k-1 looping backwards from k-1 to 1
              j = k - 1
              120 continue
#:if rk == "sp"
                 ! undo the interchanges (if any) of rows j and jp
                 ! at each step j
#:else
                 ! undo the interchanges (if any) of rows jj and jp at each
                 ! step j
#:endif
                 ! (here, j is a diagonal index)
                 jj = j
                 jp = ipiv(j)
                 if (jp < 0) then
                    jp = -jp
                    ! (here, j is a diagonal index)
                    j = j - 1
                 end if
                 ! (note: here, j is used to determine row length. length j
                 ! of the rows to swap back doesn't include diagonal element)
                 j = j - 1
                 if (jp /= jj .and. j >= 1) call la_${ri}$swap(j,a(jp,1),lda,a(jj,1),lda)

#:if rk == "sp"
              if (j >= 1) go to 120
#:else
              if (j > 1) go to 120
#:endif
              ! set kb to the number of columns factorized
              kb = k - 1
           end if
           return
     end subroutine la_${ri}$lahef
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HEEQUB: computes row and column scalings intended to equilibrate a
     !> Hermitian matrix A (with respect to the Euclidean norm) and reduce
     !> its condition number. The scale factors S are computed by the BIN
     !> algorithm (see references) so that the scaled matrix B with elements
     !> B(i,j) = S(i)*A(i,j)*S(j) has a condition number within a factor N of
     !> the smallest possible condition number over all possible diagonal
     !> scalings.

     pure subroutine la_${ri}$heequb(uplo,n,a,lda,s,scond,amax,work,info)
        use la_constants_${rk}$,only:zero,one
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,n
           real(${rk}$),intent(out) :: amax,scond
           character,intent(in) :: uplo
           ! Array Arguments
           complex(${rk}$),intent(in) :: a(lda,*)
           complex(${rk}$),intent(out) :: work(*)
           real(${rk}$),intent(out) :: s(*)
        ! =====================================================================
           ! Parameters
           integer(ilp),parameter :: max_iter = 100

           ! Local Scalars
           integer(ilp) :: i,j,iter
           real(${rk}$) :: avg,std,tol,c0,c1,c2,t,u,si,d,base,smin,smax,smlnum,bignum, &
                     scale,sumsq
           logical(lk) :: up
           complex(${rk}$) :: zdum
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,int,log,max,min,real,sqrt
#:else
           intrinsic :: abs,real,aimag,int,log,max,min,sqrt
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           ! test the input parameters.
           info = 0
           if (.not. (la_lsame(uplo,'U') .or. la_lsame(uplo,'L'))) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HEEQUB',-info)
              return
           end if
           up = la_lsame(uplo,'U')
           amax = zero
           ! quick return if possible.
           if (n == 0) then
              scond = one
              return
           end if
           do i = 1,n
              s(i) = zero
           end do
           amax = zero
           if (up) then
              do j = 1,n
                 do i = 1,j - 1
                    s(i) = max(s(i),cabs1(a(i,j)))
                    s(j) = max(s(j),cabs1(a(i,j)))
                    amax = max(amax,cabs1(a(i,j)))
                 end do
                 s(j) = max(s(j),cabs1(a(j,j)))
                 amax = max(amax,cabs1(a(j,j)))
              end do
           else
              do j = 1,n
                 s(j) = max(s(j),cabs1(a(j,j)))
                 amax = max(amax,cabs1(a(j,j)))
                 do i = j + 1,n
                    s(i) = max(s(i),cabs1(a(i,j)))
                    s(j) = max(s(j),cabs1(a(i,j)))
                    amax = max(amax,cabs1(a(i,j)))
                 end do
              end do
           end if
           do j = 1,n
              s(j) = 1.0_${rk}$/s(j)
           end do
           tol = one/sqrt(2.0_${rk}$*n)
           do iter = 1,max_iter
              scale = zero
              sumsq = zero
              ! beta = |a|s
              do i = 1,n
                 work(i) = zero
              end do
              if (up) then
                 do j = 1,n
                    do i = 1,j - 1
                       work(i) = work(i) + cabs1(a(i,j))*s(j)
                       work(j) = work(j) + cabs1(a(i,j))*s(i)
                    end do
                    work(j) = work(j) + cabs1(a(j,j))*s(j)
                 end do
              else
                 do j = 1,n
                    work(j) = work(j) + cabs1(a(j,j))*s(j)
                    do i = j + 1,n
                       work(i) = work(i) + cabs1(a(i,j))*s(j)
                       work(j) = work(j) + cabs1(a(i,j))*s(i)
                    end do
                 end do
              end if
              ! avg = s^t beta / n
              avg = zero
              do i = 1,n
                 avg = avg + real(s(i)*work(i),KIND=${rk}$)
              end do
              avg = avg/n
              std = zero
              do i = n + 1,2*n
                 work(i) = s(i - n)*work(i - n) - avg
              end do
              call la_${ri}$lassq(n,work(n + 1),1,scale,sumsq)
              std = scale*sqrt(sumsq/n)
              if (std < tol*avg) goto 999
              do i = 1,n
                 t = cabs1(a(i,i))
                 si = s(i)
                 c2 = (n - 1)*t
#:if rk == "sp"
                 c1 = real((n - 2)*(work(i) - t*si),KIND=${rk}$)
                 c0 = real(-(t*si)*si + 2*work(i)*si - n*avg,KIND=${rk}$)
#:else
                 c1 = (n - 2)*(real(work(i),KIND=${rk}$) - t*si)
                 c0 = -(t*si)*si + 2*real(work(i),KIND=${rk}$)*si - n*avg
#:endif
                 d = c1*c1 - 4*c0*c2
                 if (d <= 0) then
                    info = -1
                    return
                 end if
                 si = -2*c0/(c1 + sqrt(d))
                 d = si - s(i)
                 u = zero
                 if (up) then
                    do j = 1,i
                       t = cabs1(a(j,i))
                       u = u + s(j)*t
                       work(j) = work(j) + d*t
                    end do
                    do j = i + 1,n
                       t = cabs1(a(i,j))
                       u = u + s(j)*t
                       work(j) = work(j) + d*t
                    end do
                 else
                    do j = 1,i
                       t = cabs1(a(i,j))
                       u = u + s(j)*t
                       work(j) = work(j) + d*t
                    end do
                    do j = i + 1,n
                       t = cabs1(a(j,i))
                       u = u + s(j)*t
                       work(j) = work(j) + d*t
                    end do
                 end if
#:if rk == "sp"
                 avg = avg + real((u + work(i))*d/n,KIND=${rk}$)
#:else
                 avg = avg + (u + real(work(i),KIND=${rk}$))*d/n
#:endif
                 s(i) = si
              end do
           end do
           999 continue
           smlnum = la_${ci}$lamch('SAFEMIN')
           bignum = one/smlnum
           smin = bignum
           smax = zero
           t = one/sqrt(avg)
           base = la_${ci}$lamch('B')
           u = one/log(base)
           do i = 1,n
              s(i) = base**int(u*log(s(i)*t),KIND=ilp)
              smin = min(smin,s(i))
              smax = max(smax,s(i))
           end do
           scond = max(smin,smlnum)/min(smax,bignum)
     end subroutine la_${ri}$heequb
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETRF: computes the factorization of a complex Hermitian matrix A
     !> using the Bunch-Kaufman diagonal pivoting method.  The form of the
     !> factorization is
     !> A = U*D*U**H  or  A = L*D*L**H
     !> where U (or L) is a product of permutation and unit upper (lower)
     !> triangular matrices, and D is Hermitian and block diagonal with
     !> 1-by-1 and 2-by-2 diagonal blocks.
     !> This is the blocked version of the algorithm, calling Level 3 BLAS.

     pure subroutine la_${ri}$hetrf(uplo,n,a,lda,ipiv,work,lwork,info)
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,lwork,n
           ! Array Arguments
           integer(ilp),intent(out) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================
           ! Local Scalars
           logical(lk) :: lquery,upper
           integer(ilp) :: iinfo,iws,j,k,kb,ldwork,lwkopt,nb,nbmin
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           lquery = (lwork == -1)
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (lwork < 1 .and. .not. lquery) then
              info = -7
           end if
           if (info == 0) then
              ! determine the block size
              nb = la_ilaenv(1,'${ri.upper()}$HETRF',uplo,n,-1,-1,-1)
              lwkopt = n*nb
              work(1) = lwkopt
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETRF',-info)
              return
           else if (lquery) then
              return
           end if
           nbmin = 2
           ldwork = n
           if (nb > 1 .and. nb < n) then
              iws = ldwork*nb
              if (lwork < iws) then
                 nb = max(lwork/ldwork,1)
                 nbmin = max(2,la_ilaenv(2,'${ri.upper()}$HETRF',uplo,n,-1,-1,-1))
              end if
           else
              iws = 1
           end if
           if (nb < nbmin) nb = n
           if (upper) then
              ! factorize a as u*d*u**h using the upper triangle of a
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! kb, where kb is the number of columns factorized by la_${ri}$lahef;
              ! kb is either nb or nb-1, or k for the last block
              k = n
              10 continue
              ! if k < 1, exit from loop
              if (k < 1) go to 40
              if (k > nb) then
                 ! factorize columns k-kb+1:k of a and use blocked code to
                 ! update columns 1:k-kb
                 call la_${ri}$lahef(uplo,k,nb,kb,a,lda,ipiv,work,n,iinfo)
              else
                 ! use unblocked code to factorize columns 1:k of a
                 call la_${ri}$hetf2(uplo,k,a,lda,ipiv,iinfo)
                 kb = k
              end if
              ! set info on the first occurrence of a zero pivot
              if (info == 0 .and. iinfo > 0) info = iinfo
              ! decrease k and return to the start of the main loop
              k = k - kb
              go to 10
           else
              ! factorize a as l*d*l**h using the lower triangle of a
              ! k is the main loop index, increasing from 1 to n in steps of
              ! kb, where kb is the number of columns factorized by la_${ri}$lahef;
              ! kb is either nb or nb-1, or n-k+1 for the last block
              k = 1
              20 continue
              ! if k > n, exit from loop
              if (k > n) go to 40
              if (k <= n - nb) then
                 ! factorize columns k:k+kb-1 of a and use blocked code to
                 ! update columns k+kb:n
                 call la_${ri}$lahef(uplo,n - k + 1,nb,kb,a(k,k),lda,ipiv(k),work,n, &
                           iinfo)
              else
                 ! use unblocked code to factorize columns k:n of a
                 call la_${ri}$hetf2(uplo,n - k + 1,a(k,k),lda,ipiv(k),iinfo)
                 kb = n - k + 1
              end if
              ! set info on the first occurrence of a zero pivot
              if (info == 0 .and. iinfo > 0) info = iinfo + k - 1
              ! adjust ipiv
              do j = k,k + kb - 1
                 if (ipiv(j) > 0) then
                    ipiv(j) = ipiv(j) + k - 1
                 else
                    ipiv(j) = ipiv(j) - k + 1
                 end if
              end do
              ! increase k and return to the start of the main loop
              k = k + kb
              go to 20
           end if
           40 continue
           work(1) = lwkopt
           return
     end subroutine la_${ri}$hetrf
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETRS: solves a system of linear equations A*X = B with a complex
     !> Hermitian matrix A using the factorization A = U*D*U**H or
     !> A = L*D*L**H computed by ${ri.upper()}$HETRF.

     pure subroutine la_${ri}$hetrs(uplo,n,nrhs,a,lda,ipiv,b,ldb,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(in) :: a(lda,*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: j,k,kp
           real(${rk}$) :: s
           complex(${rk}$) :: ak,akm1,akm1k,bk,bkm1,denom
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: conjg,max,real
#:else
           intrinsic :: real,conjg,max
#:endif
           ! Executable Statements
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (nrhs < 0) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldb < max(1,n)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETRS',-info)
              return
           end if
           ! quick return if possible
           if (n == 0 .or. nrhs == 0) return
           if (upper) then
              ! solve a*x = b, where a = u*d*u**h.
              ! first solve u*d*x = b, overwriting b with x.
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = n
              10 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 30
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(u(k)), where u(k) is the transformation
                 ! stored in column k of a.
                 call la_${ri}$geru(k - 1,nrhs,-cone,a(1,k),1,b(k,1),ldb,b(1,1),ldb &
                           )
                 ! multiply by the inverse of the diagonal block.
                 s = real(cone,KIND=${rk}$)/real(a(k,k),KIND=${rk}$)
                 call la_${ri}$${ci}$scal(nrhs,s,b(k,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k-1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k - 1) call la_${ri}$swap(nrhs,b(k - 1,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(u(k)), where u(k) is the transformation
                 ! stored in columns k-1 and k of a.
                 call la_${ri}$geru(k - 2,nrhs,-cone,a(1,k),1,b(k,1),ldb,b(1,1),ldb &
                           )
                 call la_${ri}$geru(k - 2,nrhs,-cone,a(1,k - 1),1,b(k - 1,1),ldb,b(1,1), &
                           ldb)
                 ! multiply by the inverse of the diagonal block.
                 akm1k = a(k - 1,k)
                 akm1 = a(k - 1,k - 1)/akm1k
                 ak = a(k,k)/conjg(akm1k)
                 denom = akm1*ak - cone
                 do j = 1,nrhs
                    bkm1 = b(k - 1,j)/akm1k
                    bk = b(k,j)/conjg(akm1k)
                    b(k - 1,j) = (ak*bkm1 - bk)/denom
                    b(k,j) = (akm1*bk - bkm1)/denom
                 end do
                 k = k - 2
              end if
              go to 10
              30 continue
              ! next solve u**h *x = b, overwriting b with x.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              40 continue
              ! if k > n, exit from loop.
              if (k > n) go to 50
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! multiply by inv(u**h(k)), where u(k) is the transformation
                 ! stored in column k of a.
                 if (k > 1) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,a(1,k), &
                              1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                 end if
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! multiply by inv(u**h(k+1)), where u(k+1) is the transformation
                 ! stored in columns k and k+1 of a.
                 if (k > 1) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,a(1,k), &
                              1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k + 1,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,a(1,k + 1) &
                              ,1,cone,b(k + 1,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k + 1,1),ldb)
                 end if
                 ! interchange rows k and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k + 2
              end if
              go to 40
              50 continue
           else
              ! solve a*x = b, where a = l*d*l**h.
              ! first solve l*d*x = b, overwriting b with x.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              60 continue
              ! if k > n, exit from loop.
              if (k > n) go to 80
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(l(k)), where l(k) is the transformation
                 ! stored in column k of a.
                 if (k < n) call la_${ri}$geru(n - k,nrhs,-cone,a(k + 1,k),1,b(k,1),ldb,b( &
                           k + 1,1),ldb)
                 ! multiply by the inverse of the diagonal block.
                 s = real(cone,KIND=${rk}$)/real(a(k,k),KIND=${rk}$)
                 call la_${ri}$${ci}$scal(nrhs,s,b(k,1),ldb)
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k+1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k + 1) call la_${ri}$swap(nrhs,b(k + 1,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(l(k)), where l(k) is the transformation
                 ! stored in columns k and k+1 of a.
                 if (k < n - 1) then
                    call la_${ri}$geru(n - k - 1,nrhs,-cone,a(k + 2,k),1,b(k,1),ldb,b(k + 2, &
                              1),ldb)
                    call la_${ri}$geru(n - k - 1,nrhs,-cone,a(k + 2,k + 1),1,b(k + 1,1),ldb,b( &
                              k + 2,1),ldb)
                 end if
                 ! multiply by the inverse of the diagonal block.
                 akm1k = a(k + 1,k)
                 akm1 = a(k,k)/conjg(akm1k)
                 ak = a(k + 1,k + 1)/akm1k
                 denom = akm1*ak - cone
                 do j = 1,nrhs
                    bkm1 = b(k,j)/conjg(akm1k)
                    bk = b(k + 1,j)/akm1k
                    b(k,j) = (ak*bkm1 - bk)/denom
                    b(k + 1,j) = (akm1*bk - bkm1)/denom
                 end do
                 k = k + 2
              end if
              go to 60
              80 continue
              ! next solve l**h *x = b, overwriting b with x.
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = n
              90 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 100
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! multiply by inv(l**h(k)), where l(k) is the transformation
                 ! stored in column k of a.
                 if (k < n) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              a(k + 1,k),1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                 end if
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! multiply by inv(l**h(k-1)), where l(k-1) is the transformation
                 ! stored in columns k-1 and k of a.
                 if (k < n) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              a(k + 1,k),1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k - 1,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              a(k + 1,k - 1),1,cone,b(k - 1,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k - 1,1),ldb)
                 end if
                 ! interchange rows k and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k - 2
              end if
              go to 90
              100 continue
           end if
           return
     end subroutine la_${ri}$hetrs
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HETRS2: solves a system of linear equations A*X = B with a complex
     !> Hermitian matrix A using the factorization A = U*D*U**H or
     !> A = L*D*L**H computed by ${ri.upper()}$HETRF and converted by ${ri.upper()}$SYCONV.

     pure subroutine la_${ri}$hetrs2(uplo,n,nrhs,a,lda,ipiv,b,ldb,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(inout) :: a(lda,*),b(ldb,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,iinfo,j,k,kp
           real(${rk}$) :: s
           complex(${rk}$) :: ak,akm1,akm1k,bk,bkm1,denom
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: conjg,max,real
#:else
           intrinsic :: real,conjg,max
#:endif
           ! Executable Statements
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (nrhs < 0) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldb < max(1,n)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HETRS2',-info)
              return
           end if
           ! quick return if possible
           if (n == 0 .or. nrhs == 0) return
           ! convert a
           call la_${ri}$syconv(uplo,'C',n,a,lda,ipiv,work,iinfo)
           if (upper) then
              ! solve a*x = b, where a = u*d*u**h.
             ! p**t * b
             k = n
             do while (k >= 1)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k-1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp == -ipiv(k - 1)) call la_${ri}$swap(nrhs,b(k - 1,1),ldb,b(kp,1),ldb &
                           )
                 k = k - 2
              end if
             end do
        ! compute (u \p**t * b) -> b    [ (u \p**t * b) ]
             call la_${ri}$trsm('L','U','N','U',n,nrhs,cone,a,lda,b,ldb)
        ! compute d \ b -> b   [ d \ (u \p**t * b) ]
              i = n
              do while (i >= 1)
                 if (ipiv(i) > 0) then
                   s = real(cone,KIND=${rk}$)/real(a(i,i),KIND=${rk}$)
                   call la_${ri}$${ci}$scal(nrhs,s,b(i,1),ldb)
                 elseif (i > 1) then
                    if (ipiv(i - 1) == ipiv(i)) then
                       akm1k = work(i)
                       akm1 = a(i - 1,i - 1)/akm1k
                       ak = a(i,i)/conjg(akm1k)
                       denom = akm1*ak - cone
                       do j = 1,nrhs
                          bkm1 = b(i - 1,j)/akm1k
                          bk = b(i,j)/conjg(akm1k)
                          b(i - 1,j) = (ak*bkm1 - bk)/denom
                          b(i,j) = (akm1*bk - bkm1)/denom
                       end do
                    i = i - 1
                    end if
                 end if
                 i = i - 1
              end do
            ! compute (u**h \ b) -> b   [ u**h \ (d \ (u \p**t * b) ) ]
              call la_${ri}$trsm('L','U','C','U',n,nrhs,cone,a,lda,b,ldb)
             ! p * b  [ p * (u**h \ (d \ (u \p**t * b) )) ]
             k = 1
             do while (k <= n)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k-1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (k < n .and. kp == -ipiv(k + 1)) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp, &
                            1),ldb)
                 k = k + 2
              end if
             end do
           else
              ! solve a*x = b, where a = l*d*l**h.
             ! p**t * b
             k = 1
             do while (k <= n)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k and -ipiv(k+1).
                 kp = -ipiv(k + 1)
                 if (kp == -ipiv(k)) call la_${ri}$swap(nrhs,b(k + 1,1),ldb,b(kp,1),ldb)

                 k = k + 2
              end if
             end do
        ! compute (l \p**t * b) -> b    [ (l \p**t * b) ]
             call la_${ri}$trsm('L','L','N','U',n,nrhs,cone,a,lda,b,ldb)
        ! compute d \ b -> b   [ d \ (l \p**t * b) ]
              i = 1
              do while (i <= n)
                 if (ipiv(i) > 0) then
                   s = real(cone,KIND=${rk}$)/real(a(i,i),KIND=${rk}$)
                   call la_${ri}$${ci}$scal(nrhs,s,b(i,1),ldb)
                 else
                       akm1k = work(i)
                       akm1 = a(i,i)/conjg(akm1k)
                       ak = a(i + 1,i + 1)/akm1k
                       denom = akm1*ak - cone
                       do j = 1,nrhs
                          bkm1 = b(i,j)/conjg(akm1k)
                          bk = b(i + 1,j)/akm1k
                          b(i,j) = (ak*bkm1 - bk)/denom
                          b(i + 1,j) = (akm1*bk - bkm1)/denom
                       end do
                       i = i + 1
                 end if
                 i = i + 1
              end do
        ! compute (l**h \ b) -> b   [ l**h \ (d \ (l \p**t * b) ) ]
             call la_${ri}$trsm('L','L','C','U',n,nrhs,cone,a,lda,b,ldb)
             ! p * b  [ p * (l**h \ (d \ (l \p**t * b) )) ]
             k = n
             do while (k >= 1)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k-1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (k > 1 .and. kp == -ipiv(k - 1)) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp, &
                           1),ldb)
                 k = k - 2
              end if
             end do
           end if
           ! revert a
           call la_${ri}$syconv(uplo,'R',n,a,lda,ipiv,work,iinfo)
           return
     end subroutine la_${ri}$hetrs2
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HPTRS: solves a system of linear equations A*X = B with a complex
     !> Hermitian matrix A stored in packed format using the factorization
     !> A = U*D*U**H or A = L*D*L**H computed by ${ri.upper()}$HPTRF.

     pure subroutine la_${ri}$hptrs(uplo,n,nrhs,ap,ipiv,b,ldb,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: ldb,n,nrhs
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(in) :: ap(*)
           complex(${rk}$),intent(inout) :: b(ldb,*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: j,k,kc,kp
           real(${rk}$) :: s
           complex(${rk}$) :: ak,akm1,akm1k,bk,bkm1,denom
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: conjg,max,real
#:else
           intrinsic :: real,conjg,max
#:endif
           ! Executable Statements
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (nrhs < 0) then
              info = -3
           else if (ldb < max(1,n)) then
              info = -7
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HPTRS',-info)
              return
           end if
           ! quick return if possible
           if (n == 0 .or. nrhs == 0) return
           if (upper) then
              ! solve a*x = b, where a = u*d*u**h.
              ! first solve u*d*x = b, overwriting b with x.
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = n
              kc = n*(n + 1)/2 + 1
              10 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 30
              kc = kc - k
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(u(k)), where u(k) is the transformation
                 ! stored in column k of a.
                 call la_${ri}$geru(k - 1,nrhs,-cone,ap(kc),1,b(k,1),ldb,b(1,1),ldb)

                 ! multiply by the inverse of the diagonal block.
                 s = real(cone,KIND=${rk}$)/real(ap(kc + k - 1),KIND=${rk}$)
                 call la_${ri}$${ci}$scal(nrhs,s,b(k,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k-1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k - 1) call la_${ri}$swap(nrhs,b(k - 1,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(u(k)), where u(k) is the transformation
                 ! stored in columns k-1 and k of a.
                 call la_${ri}$geru(k - 2,nrhs,-cone,ap(kc),1,b(k,1),ldb,b(1,1),ldb)

                 call la_${ri}$geru(k - 2,nrhs,-cone,ap(kc - (k - 1)),1,b(k - 1,1),ldb,b(1, &
                           1),ldb)
                 ! multiply by the inverse of the diagonal block.
                 akm1k = ap(kc + k - 2)
                 akm1 = ap(kc - 1)/akm1k
                 ak = ap(kc + k - 1)/conjg(akm1k)
                 denom = akm1*ak - cone
                 do j = 1,nrhs
                    bkm1 = b(k - 1,j)/akm1k
                    bk = b(k,j)/conjg(akm1k)
                    b(k - 1,j) = (ak*bkm1 - bk)/denom
                    b(k,j) = (akm1*bk - bkm1)/denom
                 end do
                 kc = kc - k + 1
                 k = k - 2
              end if
              go to 10
              30 continue
              ! next solve u**h *x = b, overwriting b with x.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              kc = 1
              40 continue
              ! if k > n, exit from loop.
              if (k > n) go to 50
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! multiply by inv(u**h(k)), where u(k) is the transformation
                 ! stored in column k of a.
                 if (k > 1) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,ap(kc), &
                              1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                 end if
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 kc = kc + k
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! multiply by inv(u**h(k+1)), where u(k+1) is the transformation
                 ! stored in columns k and k+1 of a.
                 if (k > 1) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,ap(kc), &
                              1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k + 1,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',k - 1,nrhs,-cone,b,ldb,ap(kc + k), &
                               1,cone,b(k + 1,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k + 1,1),ldb)
                 end if
                 ! interchange rows k and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 kc = kc + 2*k + 1
                 k = k + 2
              end if
              go to 40
              50 continue
           else
              ! solve a*x = b, where a = l*d*l**h.
              ! first solve l*d*x = b, overwriting b with x.
              ! k is the main loop index, increasing from 1 to n in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = 1
              kc = 1
              60 continue
              ! if k > n, exit from loop.
              if (k > n) go to 80
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(l(k)), where l(k) is the transformation
                 ! stored in column k of a.
                 if (k < n) call la_${ri}$geru(n - k,nrhs,-cone,ap(kc + 1),1,b(k,1),ldb,b(k + &
                           1,1),ldb)
                 ! multiply by the inverse of the diagonal block.
                 s = real(cone,KIND=${rk}$)/real(ap(kc),KIND=${rk}$)
                 call la_${ri}$${ci}$scal(nrhs,s,b(k,1),ldb)
                 kc = kc + n - k + 1
                 k = k + 1
              else
                 ! 2 x 2 diagonal block
                 ! interchange rows k+1 and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k + 1) call la_${ri}$swap(nrhs,b(k + 1,1),ldb,b(kp,1),ldb)
                 ! multiply by inv(l(k)), where l(k) is the transformation
                 ! stored in columns k and k+1 of a.
                 if (k < n - 1) then
                    call la_${ri}$geru(n - k - 1,nrhs,-cone,ap(kc + 2),1,b(k,1),ldb,b(k + 2, &
                              1),ldb)
                    call la_${ri}$geru(n - k - 1,nrhs,-cone,ap(kc + n - k + 2),1,b(k + 1,1),ldb,b( &
                              k + 2,1),ldb)
                 end if
                 ! multiply by the inverse of the diagonal block.
                 akm1k = ap(kc + 1)
                 akm1 = ap(kc)/conjg(akm1k)
                 ak = ap(kc + n - k + 1)/akm1k
                 denom = akm1*ak - cone
                 do j = 1,nrhs
                    bkm1 = b(k,j)/conjg(akm1k)
                    bk = b(k + 1,j)/akm1k
                    b(k,j) = (ak*bkm1 - bk)/denom
                    b(k + 1,j) = (akm1*bk - bkm1)/denom
                 end do
                 kc = kc + 2*(n - k) + 1
                 k = k + 2
              end if
              go to 60
              80 continue
              ! next solve l**h *x = b, overwriting b with x.
              ! k is the main loop index, decreasing from n to 1 in steps of
              ! 1 or 2, depending on the size of the diagonal blocks.
              k = n
              kc = n*(n + 1)/2 + 1
              90 continue
              ! if k < 1, exit from loop.
              if (k < 1) go to 100
              kc = kc - (n - k + 1)
              if (ipiv(k) > 0) then
                 ! 1 x 1 diagonal block
                 ! multiply by inv(l**h(k)), where l(k) is the transformation
                 ! stored in column k of a.
                 if (k < n) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              ap(kc + 1),1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                 end if
                 ! interchange rows k and ipiv(k).
                 kp = ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 k = k - 1
              else
                 ! 2 x 2 diagonal block
                 ! multiply by inv(l**h(k-1)), where l(k-1) is the transformation
                 ! stored in columns k-1 and k of a.
                 if (k < n) then
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              ap(kc + 1),1,cone,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k - 1,1),ldb)
                    call la_${ri}$gemv('CONJUGATE TRANSPOSE',n - k,nrhs,-cone,b(k + 1,1),ldb, &
                              ap(kc - (n - k)),1,cone,b(k - 1,1),ldb)
                    call la_${ri}$lacgv(nrhs,b(k - 1,1),ldb)
                 end if
                 ! interchange rows k and -ipiv(k).
                 kp = -ipiv(k)
                 if (kp /= k) call la_${ri}$swap(nrhs,b(k,1),ldb,b(kp,1),ldb)
                 kc = kc - (n - k + 2)
                 k = k - 2
              end if
              go to 90
              100 continue
           end if
           return
     end subroutine la_${ri}$hptrs
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HECON: estimates the reciprocal of the condition number of a complex
     !> Hermitian matrix A using the factorization A = U*D*U**H or
     !> A = L*D*L**H computed by ${ri.upper()}$HETRF.
     !> An estimate is obtained for norm(inv(A)), and the reciprocal of the
     !> condition number is computed as RCOND = 1 / (ANORM * norm(inv(A))).

     pure subroutine la_${ri}$hecon(uplo,n,a,lda,ipiv,anorm,rcond,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,n
           real(${rk}$),intent(in) :: anorm
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(in) :: a(lda,*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,kase
           real(${rk}$) :: ainvnm
           ! Local Arrays
           integer(ilp) :: isave(3)
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (lda < max(1,n)) then
              info = -4
           else if (anorm < zero) then
              info = -6
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HECON',-info)
              return
           end if
           ! quick return if possible
           rcond = zero
           if (n == 0) then
              rcond = one
              return
           else if (anorm <= zero) then
              return
           end if
           ! check that the diagonal matrix d is nonsingular.
           if (upper) then
              ! upper triangular storage: examine d from bottom to top
              do i = n,1,-1
                 if (ipiv(i) > 0 .and. a(i,i) == zero) return
              end do
           else
              ! lower triangular storage: examine d from top to bottom.
              do i = 1,n
                 if (ipiv(i) > 0 .and. a(i,i) == zero) return
              end do
           end if
           ! estimate the 1-norm of the inverse.
           kase = 0
           30 continue
           call la_${ri}$lacn2(n,work(n + 1),work,ainvnm,kase,isave)
           if (kase /= 0) then
              ! multiply by inv(l*d*l**h) or inv(u*d*u**h).
              call la_${ri}$hetrs(uplo,n,1,a,lda,ipiv,work,n,info)
              go to 30
           end if
           ! compute the estimate of the reciprocal condition number.
           if (ainvnm /= zero) rcond = (one/ainvnm)/anorm
           return
     end subroutine la_${ri}$hecon
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HERFS: improves the computed solution to a system of linear
     !> equations when the coefficient matrix is Hermitian indefinite, and
     !> provides error bounds and backward error estimates for the solution.

     pure subroutine la_${ri}$herfs(uplo,n,nrhs,a,lda,af,ldaf,ipiv,b,ldb,x,ldx,ferr, &
               berr,work,rwork,info)
        use la_constants_${rk}$,only:zero,two,three,cone
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: lda,ldaf,ldb,ldx,n,nrhs
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           real(${rk}$),intent(out) :: berr(*),ferr(*),rwork(*)
           complex(${rk}$),intent(in) :: a(lda,*),af(ldaf,*),b(ldb,*)
           complex(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(inout) :: x(ldx,*)
        ! =====================================================================
           ! Parameters
           integer(ilp),parameter :: itmax = 5

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: count,i,j,k,kase,nz
           real(${rk}$) :: eps,lstres,s,safe1,safe2,safmin,xk
           complex(${rk}$) :: zdum
           ! Local Arrays
           integer(ilp) :: isave(3)
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,max,real
#:else
           intrinsic :: abs,real,aimag,max
#:endif
           ! Statement Functions
           real(${rk}$) :: cabs1
           ! Statement Function Definitions
           cabs1(zdum) = abs(real(zdum,KIND=${rk}$)) + abs(aimag(zdum))
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (nrhs < 0) then
              info = -3
           else if (lda < max(1,n)) then
              info = -5
           else if (ldaf < max(1,n)) then
              info = -7
           else if (ldb < max(1,n)) then
              info = -10
           else if (ldx < max(1,n)) then
              info = -12
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HERFS',-info)
              return
           end if
           ! quick return if possible
           if (n == 0 .or. nrhs == 0) then
              do j = 1,nrhs
                 ferr(j) = zero
                 berr(j) = zero
              end do
              return
           end if
           ! nz = maximum number of nonzero elements in each row of a, plus 1
           nz = n + 1
           eps = la_${ci}$lamch('EPSILON')
           safmin = la_${ci}$lamch('SAFE MINIMUM')
           safe1 = nz*safmin
           safe2 = safe1/eps
           ! do for each right hand side
           loop_140: do j = 1,nrhs
              count = 1
              lstres = three
              20 continue
              ! loop until stopping criterion is satisfied.
              ! compute residual r = b - a * x
              call la_${ri}$copy(n,b(1,j),1,work,1)
              call la_${ri}$hemv(uplo,n,-cone,a,lda,x(1,j),1,cone,work,1)
              ! compute componentwise relative backward error from formula
              ! max(i) ( abs(r(i)) / ( abs(a)*abs(x) + abs(b) )(i) )
              ! where abs(z) is the componentwise absolute value of the matrix
              ! or vector z.  if the i-th component of the denominator is less
              ! than safe2, then safe1 is added to the i-th components of the
              ! numerator and denominator before dividing.
              do i = 1,n
                 rwork(i) = cabs1(b(i,j))
              end do
              ! compute abs(a)*abs(x) + abs(b).
              if (upper) then
                 do k = 1,n
                    s = zero
                    xk = cabs1(x(k,j))
                    do i = 1,k - 1
                       rwork(i) = rwork(i) + cabs1(a(i,k))*xk
                       s = s + cabs1(a(i,k))*cabs1(x(i,j))
                    end do
                    rwork(k) = rwork(k) + abs(real(a(k,k),KIND=${rk}$))*xk + s
                 end do
              else
                 do k = 1,n
                    s = zero
                    xk = cabs1(x(k,j))
                    rwork(k) = rwork(k) + abs(real(a(k,k),KIND=${rk}$))*xk
                    do i = k + 1,n
                       rwork(i) = rwork(i) + cabs1(a(i,k))*xk
                       s = s + cabs1(a(i,k))*cabs1(x(i,j))
                    end do
                    rwork(k) = rwork(k) + s
                 end do
              end if
              s = zero
              do i = 1,n
                 if (rwork(i) > safe2) then
                    s = max(s,cabs1(work(i))/rwork(i))
                 else
                    s = max(s, (cabs1(work(i)) + safe1)/(rwork(i) + safe1))
                 end if
              end do
              berr(j) = s
              ! test stopping criterion. continue iterating if
                 ! 1) the residual berr(j) is larger than machine epsilon, and
                 ! 2) berr(j) decreased by at least a factor of 2 during the
                    ! last iteration, and
                 ! 3) at most itmax iterations tried.
              if (berr(j) > eps .and. two*berr(j) <= lstres .and. count <= itmax) then
                 ! update solution and try again.
                 call la_${ri}$hetrs(uplo,n,1,af,ldaf,ipiv,work,n,info)
                 call la_${ri}$axpy(n,cone,work,1,x(1,j),1)
                 lstres = berr(j)
                 count = count + 1
                 go to 20
              end if
              ! bound error from formula
              ! norm(x - xtrue) / norm(x) .le. ferr =
              ! norm( abs(inv(a))*
                 ! ( abs(r) + nz*eps*( abs(a)*abs(x)+abs(b) ))) / norm(x)
              ! where
                ! norm(z) is the magnitude of the largest component of z
                ! inv(a) is the inverse of a
                ! abs(z) is the componentwise absolute value of the matrix or
                   ! vector z
                ! nz is the maximum number of nonzeros in any row of a, plus 1
                ! eps is machine epsilon
              ! the i-th component of abs(r)+nz*eps*(abs(a)*abs(x)+abs(b))
              ! is incremented by safe1 if the i-th component of
              ! abs(a)*abs(x) + abs(b) is less than safe2.
              ! use la_${ri}$lacn2 to estimate the infinity-norm of the matrix
                 ! inv(a) * diag(w),
              ! where w = abs(r) + nz*eps*( abs(a)*abs(x)+abs(b) )))
              do i = 1,n
                 if (rwork(i) > safe2) then
                    rwork(i) = cabs1(work(i)) + nz*eps*rwork(i)
                 else
                    rwork(i) = cabs1(work(i)) + nz*eps*rwork(i) + safe1
                 end if
              end do
              kase = 0
              100 continue
              call la_${ri}$lacn2(n,work(n + 1),work,ferr(j),kase,isave)
              if (kase /= 0) then
                 if (kase == 1) then
                    ! multiply by diag(w)*inv(a**h).
                    call la_${ri}$hetrs(uplo,n,1,af,ldaf,ipiv,work,n,info)
                    do i = 1,n
                       work(i) = rwork(i)*work(i)
                    end do
                 else if (kase == 2) then
                    ! multiply by inv(a)*diag(w).
                    do i = 1,n
                       work(i) = rwork(i)*work(i)
                    end do
                    call la_${ri}$hetrs(uplo,n,1,af,ldaf,ipiv,work,n,info)
                 end if
                 go to 100
              end if
              ! normalize error.
              lstres = zero
              do i = 1,n
                 lstres = max(lstres,cabs1(x(i,j)))
              end do
              if (lstres /= zero) ferr(j) = ferr(j)/lstres
           end do loop_140
           return
     end subroutine la_${ri}$herfs
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$HPCON: estimates the reciprocal of the condition number of a complex
     !> Hermitian packed matrix A using the factorization A = U*D*U**H or
     !> A = L*D*L**H computed by ${ri.upper()}$HPTRF.
     !> An estimate is obtained for norm(inv(A)), and the reciprocal of the
     !> condition number is computed as RCOND = 1 / (ANORM * norm(inv(A))).

     pure subroutine la_${ri}$hpcon(uplo,n,ap,ipiv,anorm,rcond,work,info)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: uplo
           integer(ilp),intent(out) :: info
           integer(ilp),intent(in) :: n
           real(${rk}$),intent(in) :: anorm
           real(${rk}$),intent(out) :: rcond
           ! Array Arguments
           integer(ilp),intent(in) :: ipiv(*)
           complex(${rk}$),intent(in) :: ap(*)
           complex(${rk}$),intent(out) :: work(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: upper
           integer(ilp) :: i,ip,kase
           real(${rk}$) :: ainvnm
           ! Local Arrays
           integer(ilp) :: isave(3)
           ! Executable Statements
           ! test the input parameters.
           info = 0
           upper = la_lsame(uplo,'U')
           if (.not. upper .and. .not. la_lsame(uplo,'L')) then
              info = -1
           else if (n < 0) then
              info = -2
           else if (anorm < zero) then
              info = -5
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HPCON',-info)
              return
           end if
           ! quick return if possible
           rcond = zero
           if (n == 0) then
              rcond = one
              return
           else if (anorm <= zero) then
              return
           end if
           ! check that the diagonal matrix d is nonsingular.
           if (upper) then
              ! upper triangular storage: examine d from bottom to top
              ip = n*(n + 1)/2
              do i = n,1,-1
                 if (ipiv(i) > 0 .and. ap(ip) == zero) return
                 ip = ip - i
              end do
           else
              ! lower triangular storage: examine d from top to bottom.
              ip = 1
              do i = 1,n
                 if (ipiv(i) > 0 .and. ap(ip) == zero) return
                 ip = ip + n - i + 1
              end do
           end if
           ! estimate the 1-norm of the inverse.
           kase = 0
           30 continue
           call la_${ri}$lacn2(n,work(n + 1),work,ainvnm,kase,isave)
           if (kase /= 0) then
              ! multiply by inv(l*d*l**h) or inv(u*d*u**h).
              call la_${ri}$hptrs(uplo,n,1,ap,ipiv,work,n,info)
              go to 30
           end if
           ! compute the estimate of the reciprocal condition number.
           if (ainvnm /= zero) rcond = (one/ainvnm)/anorm
           return
     end subroutine la_${ri}$hpcon
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

end module la_lapack_solve_ldl_comp3
