#:include "common.fypp"
!> BLAS-like matrix norms
module la_lapack_blas_like_mnorm
     use la_constants
     use la_blas_aux
     use la_lapack_blas_like_l1
     use la_lapack_blas_like_scalar
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     public :: la_${ri}$langb
     public :: la_${ri}$lange
     public :: la_${ri}$langt
     public :: la_${ri}$lanhs
     public :: la_${ri}$lansb
     public :: la_${ri}$lansf
     public :: la_${ri}$lansp
     public :: la_${ri}$lanst
     public :: la_${ri}$lansy
     public :: la_${ri}$lantb
     public :: la_${ri}$lantp
     public :: la_${ri}$lantr
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     public :: la_${ri}$langb
     public :: la_${ri}$lange
     public :: la_${ri}$langt
     public :: la_${ri}$lanhb
     public :: la_${ri}$lanhe
     public :: la_${ri}$lanhf
     public :: la_${ri}$lanhp
     public :: la_${ri}$lanhs
     public :: la_${ri}$lanht
     public :: la_${ri}$lansb
     public :: la_${ri}$lansp
     public :: la_${ri}$lansy
     public :: la_${ri}$lantb
     public :: la_${ri}$lantp
     public :: la_${ri}$lantr
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANGB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n band matrix  A,  with kl sub-diagonals and ku super-diagonals.

     real(${rk}$) function la_${ri}$langb(norm,n,kl,ku,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: kl,ku,ldab,n
           ! Array Arguments
           real(${rk}$),intent(in) :: ab(ldab,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,k,l
           real(${rk}$) :: scale,sum,value,temp
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                    temp = abs(ab(i,j))
                    if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                    sum = sum + abs(ab(i,j))
                 end do
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,n
                 work(i) = zero
              end do
              do j = 1,n
                 k = ku + 1 - j
                 do i = max(1,j - ku),min(n,j + kl)
                    work(i) = work(i) + abs(ab(k + i,j))
                 end do
              end do
              value = zero
              do i = 1,n
                 temp = work(i)
                 if (value < temp .or. la_${ri}$isnan(temp)) value = temp
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 l = max(1,j - ku)
                 k = ku + 1 - j + l
                 call la_${ri}$lassq(min(n,j + kl) - l + 1,ab(k,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$langb = value
           return
     end function la_${ri}$langb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANGE:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> real matrix A.

     real(${rk}$) function la_${ri}$lange(norm,m,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value,temp
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (min(m,n) == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = 1,m
                    temp = abs(a(i,j))
                    if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = 1,m
                    sum = sum + abs(a(i,j))
                 end do
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,m
                 work(i) = zero
              end do
              do j = 1,n
                 do i = 1,m
                    work(i) = work(i) + abs(a(i,j))
                 end do
              end do
              value = zero
              do i = 1,m
                 temp = work(i)
                 if (value < temp .or. la_${ri}$isnan(temp)) value = temp
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 call la_${ri}$lassq(m,a(1,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lange = value
           return
     end function la_${ri}$lange
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANGT:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> real tridiagonal matrix A.

     pure real(${rk}$) function la_${ri}$langt(norm,n,dl,d,du)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: d(*),dl(*),du(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           real(${rk}$) :: anorm,scale,sum,temp
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n <= 0) then
              anorm = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              anorm = abs(d(n))
              do i = 1,n - 1
                 if (anorm < abs(dl(i)) .or. la_${ri}$isnan(abs(dl(i)))) anorm = abs(dl(i))

                 if (anorm < abs(d(i)) .or. la_${ri}$isnan(abs(d(i)))) anorm = abs(d(i))

                 if (anorm < abs(du(i)) .or. la_${ri}$isnan(abs(du(i)))) anorm = abs(du(i))

              end do
           else if (la_lsame(norm,'O') .or. norm == '1') then
              ! find norm1(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(dl(1))
                 temp = abs(d(n)) + abs(du(n - 1))
                 if (anorm < temp .or. la_${ri}$isnan(temp)) anorm = temp
                 do i = 2,n - 1
                    temp = abs(d(i)) + abs(dl(i)) + abs(du(i - 1))
                    if (anorm < temp .or. la_${ri}$isnan(temp)) anorm = temp
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(du(1))
                 temp = abs(d(n)) + abs(dl(n - 1))
                 if (anorm < temp .or. la_${ri}$isnan(temp)) anorm = temp
                 do i = 2,n - 1
                    temp = abs(d(i)) + abs(du(i)) + abs(dl(i - 1))
                    if (anorm < temp .or. la_${ri}$isnan(temp)) anorm = temp
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              call la_${ri}$lassq(n,d,1,scale,sum)
              if (n > 1) then
                 call la_${ri}$lassq(n - 1,dl,1,scale,sum)
                 call la_${ri}$lassq(n - 1,du,1,scale,sum)
              end if
              anorm = scale*sqrt(sum)
           end if
           la_${ri}$langt = anorm
           return
     end function la_${ri}$langt
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANHS:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> Hessenberg matrix A.

     real(${rk}$) function la_${ri}$lanhs(norm,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = 1,min(n,j + 1)
                    sum = abs(a(i,j))
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = 1,min(n,j + 1)
                    sum = sum + abs(a(i,j))
                 end do
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,n
                 work(i) = zero
              end do
              do j = 1,n
                 do i = 1,min(n,j + 1)
                    work(i) = work(i) + abs(a(i,j))
                 end do
              end do
              value = zero
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 call la_${ri}$lassq(min(n,j + 1),a(1,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lanhs = value
           return
     end function la_${ri}$lanhs
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANSB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n symmetric band matrix A,  with k super-diagonals.

     real(${rk}$) function la_${ri}$lansb(norm,uplo,n,k,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: k,ldab,n
           ! Array Arguments
           real(${rk}$),intent(in) :: ab(ldab,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,l
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = max(k + 2 - j,1),k + 1
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                 end do
              else
                 do j = 1,n
                    do i = 1,min(n + 1 - j,k + 1)
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    l = k + 1 - j
                    do i = max(1,j - k),j - 1
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(ab(k + 1,j))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(ab(1,j))
                    l = 1 - j
                    do i = j + 1,min(n,j + k)
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (k > 0) then
                 if (la_lsame(uplo,'U')) then
                    do j = 2,n
                       call la_${ri}$lassq(min(j - 1,k),ab(max(k + 2 - j,1),j),1,scale,sum)

                    end do
                    l = k + 1
                 else
                    do j = 1,n - 1
                       call la_${ri}$lassq(min(n - j,k),ab(2,j),1,scale,sum)
                    end do
                    l = 1
                 end if
                 sum = 2*sum
              else
                 l = 1
              end if
              call la_${ri}$lassq(n,ab(l,1),ldab,scale,sum)
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansb = value
           return
     end function la_${ri}$lansb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANSF: returns the value of the one norm, or the Frobenius norm, or
     !> the infinity norm, or the element of largest absolute value of a
     !> real symmetric matrix A in RFP format.

     real(${rk}$) function la_${ri}$lansf(norm,transr,uplo,n,a,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,transr,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(0:*)
           real(${rk}$),intent(out) :: work(0:*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,ifm,ilu,noe,n1,k,l,lda
           real(${rk}$) :: scale,s,value,aa,temp
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,sqrt
#:else
           intrinsic :: abs,max,sqrt
#:endif
           ! Executable Statements
           if (n == 0) then
              la_${ri}$lansf = zero
              return
           else if (n == 1) then
              la_${ri}$lansf = abs(a(0))
              return
           end if
           ! set noe = 1 if n is odd. if n is even set noe=0
           noe = 1
           if (mod(n,2) == 0) noe = 0
           ! set ifm = 0 when form='t or 't' and 1 otherwise
           ifm = 1
           if (la_lsame(transr,'T')) ifm = 0
           ! set ilu = 0 when uplo='u or 'u' and 1 otherwise
           ilu = 1
           if (la_lsame(uplo,'U')) ilu = 0
           ! set lda = (n+1)/2 when ifm = 0
           ! set lda = n when ifm = 1 and noe = 1
           ! set lda = n+1 when ifm = 1 and noe = 0
           if (ifm == 1) then
              if (noe == 1) then
                 lda = n
              else
                 ! noe=0
                 lda = n + 1
              end if
           else
              ! ifm=0
              lda = (n + 1)/2
           end if
           if (la_lsame(norm,'M')) then
             ! find max(abs(a(i,j))).
              k = (n + 1)/2
              value = zero
              if (noe == 1) then
                 ! n is odd
                 if (ifm == 1) then
                 ! a is n by k
                    do j = 0,k - 1
                       do i = 0,n - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end do
                 else
                    ! xpose case; a is k by n
                    do j = 0,n - 1
                       do i = 0,k - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end do
                 end if
              else
                 ! n is even
                 if (ifm == 1) then
                    ! a is n+1 by k
                    do j = 0,k - 1
                       do i = 0,n
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end do
                 else
                    ! xpose case; a is k by n+1
                    do j = 0,n
                       do i = 0,k - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              if (ifm == 1) then
                 k = n/2
                 if (noe == 1) then
                    ! n is odd
                    if (ilu == 0) then
                       do i = 0,k - 1
                          work(i) = zero
                       end do
                       do j = 0,k
                          s = zero
                          do i = 0,k + j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(i,j+k)
                             s = s + aa
                             work(i) = work(i) + aa
                          end do
                          aa = abs(a(i + j*lda))
                          ! -> a(j+k,j+k)
                          work(j + k) = s + aa
                          if (i == k + k) go to 10
                          i = i + 1
                          aa = abs(a(i + j*lda))
                          ! -> a(j,j)
                          work(j) = work(j) + aa
                          s = zero
                          do l = j + 1,k - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       10 continue
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu = 1
                       k = k + 1
                       ! k=(n+1)/2 for n odd and ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = k - 1,0,-1
                          s = zero
                          do i = 0,j - 2
                             aa = abs(a(i + j*lda))
                             ! -> a(j+k,i+k)
                             s = s + aa
                             work(i + k) = work(i + k) + aa
                          end do
                          if (j > 0) then
                             aa = abs(a(i + j*lda))
                             ! -> a(j+k,j+k)
                             s = s + aa
                             work(i + k) = work(i + k) + s
                             ! i=j
                             i = i + 1
                          end if
                          aa = abs(a(i + j*lda))
                          ! -> a(j,j)
                          work(j) = aa
                          s = zero
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end if
                 else
                    ! n is even
                    if (ilu == 0) then
                       do i = 0,k - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 1
                          s = zero
                          do i = 0,k + j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(i,j+k)
                             s = s + aa
                             work(i) = work(i) + aa
                          end do
                          aa = abs(a(i + j*lda))
                          ! -> a(j+k,j+k)
                          work(j + k) = s + aa
                          i = i + 1
                          aa = abs(a(i + j*lda))
                          ! -> a(j,j)
                          work(j) = work(j) + aa
                          s = zero
                          do l = j + 1,k - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu = 1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = k - 1,0,-1
                          s = zero
                          do i = 0,j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(j+k,i+k)
                             s = s + aa
                             work(i + k) = work(i + k) + aa
                          end do
                          aa = abs(a(i + j*lda))
                          ! -> a(j+k,j+k)
                          s = s + aa
                          work(i + k) = work(i + k) + s
                          ! i=j
                          i = i + 1
                          aa = abs(a(i + j*lda))
                          ! -> a(j,j)
                          work(j) = aa
                          s = zero
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end if
                 end if
              else
                 ! ifm=0
                 k = n/2
                 if (noe == 1) then
                    ! n is odd
                    if (ilu == 0) then
                       n1 = k
                       ! n/2
                       k = k + 1
                       ! k is the row size and lda
                       do i = n1,n - 1
                          work(i) = zero
                       end do
                       do j = 0,n1 - 1
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,n1+i)
                             work(i + n1) = work(i + n1) + aa
                             s = s + aa
                          end do
                          work(j) = s
                       end do
                       ! j=n1=k-1 is special
                       s = abs(a(0 + j*lda))
                       ! a(k-1,k-1)
                       do i = 1,k - 1
                          aa = abs(a(i + j*lda))
                          ! a(k-1,i+n1)
                          work(i + n1) = work(i + n1) + aa
                          s = s + aa
                       end do
                       work(j) = work(j) + s
                       do j = k,n - 1
                          s = zero
                          do i = 0,j - k - 1
                             aa = abs(a(i + j*lda))
                             ! a(i,j-k)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          ! i=j-k
                          aa = abs(a(i + j*lda))
                          ! a(j-k,j-k)
                          s = s + aa
                          work(j - k) = work(j - k) + s
                          i = i + 1
                          s = abs(a(i + j*lda))
                          ! a(j,j)
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(j,l)
                             work(l) = work(l) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu=1
                       k = k + 1
                       ! k=(n+1)/2 for n odd and ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 2
                          ! process
                          s = zero
                          do i = 0,j - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          aa = abs(a(i + j*lda))
                          ! i=j so process of a(j,j)
                          s = s + aa
                          work(j) = s
                          ! is initialised here
                          i = i + 1
                          ! i=j process a(j+k,j+k)
                          aa = abs(a(i + j*lda))
                          s = aa
                          do l = k + j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(l,k+j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(k + j) = work(k + j) + s
                       end do
                       ! j=k-1 is special :process col a(k-1,0:k-1)
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(k,i)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(a(i + j*lda))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = s
                       ! done with col j=k+1
                       do j = k,n - 1
                          ! process col j of a = a(j,0:k-1)
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end if
                 else
                    ! n is even
                    if (ilu == 0) then
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 1
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i+k)
                             work(i + k) = work(i + k) + aa
                             s = s + aa
                          end do
                          work(j) = s
                       end do
                       ! j=k
                       aa = abs(a(0 + j*lda))
                       ! a(k,k)
                       s = aa
                       do i = 1,k - 1
                          aa = abs(a(i + j*lda))
                          ! a(k,k+i)
                          work(i + k) = work(i + k) + aa
                          s = s + aa
                       end do
                       work(j) = work(j) + s
                       do j = k + 1,n - 1
                          s = zero
                          do i = 0,j - 2 - k
                             aa = abs(a(i + j*lda))
                             ! a(i,j-k-1)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                           ! i=j-1-k
                          aa = abs(a(i + j*lda))
                          ! a(j-k-1,j-k-1)
                          s = s + aa
                          work(j - k - 1) = work(j - k - 1) + s
                          i = i + 1
                          aa = abs(a(i + j*lda))
                          ! a(j,j)
                          s = aa
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(j,l)
                             work(l) = work(l) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       ! j=n
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(i,k-1)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(a(i + j*lda))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = work(i) + s
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       ! j=0 is special :process col a(k:n-1,k)
                       s = abs(a(0))
                       ! a(k,k)
                       do i = 1,k - 1
                          aa = abs(a(i))
                          ! a(k+i,k)
                          work(i + k) = work(i + k) + aa
                          s = s + aa
                       end do
                       work(k) = work(k) + s
                       do j = 1,k - 1
                          ! process
                          s = zero
                          do i = 0,j - 2
                             aa = abs(a(i + j*lda))
                             ! a(j-1,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          aa = abs(a(i + j*lda))
                          ! i=j-1 so process of a(j-1,j-1)
                          s = s + aa
                          work(j - 1) = s
                          ! is initialised here
                          i = i + 1
                          ! i=j process a(j+k,j+k)
                          aa = abs(a(i + j*lda))
                          s = aa
                          do l = k + j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(l,k+j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(k + j) = work(k + j) + s
                       end do
                       ! j=k is special :process col a(k,0:k-1)
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(k,i)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(a(i + j*lda))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = s
                       ! done with col j=k+1
                       do j = k + 1,n
                          ! process col j-1 of a = a(j-1,0:k-1)
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j-1,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          work(j - 1) = work(j - 1) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ri}$isnan(temp)) value = temp
                       end do
                    end if
                 end if
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
             ! find normf(a).
              k = (n + 1)/2
              scale = zero
              s = one
              if (noe == 1) then
                 ! n is odd
                 if (ifm == 1) then
                    ! a is normal
                    if (ilu == 0) then
                       ! a is upper
                       do j = 0,k - 3
                          call la_${ri}$lassq(k - j - 2,a(k + j + 1 + j*lda),1,scale,s)
                          ! l at a(k,0)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k + j - 1,a(0 + j*lda),1,scale,s)
                          ! trap u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k - 1,a(k),lda + 1,scale,s)
                       ! tri l at a(k,0)
                       call la_${ri}$lassq(k,a(k - 1),lda + 1,scale,s)
                       ! tri u at a(k-1,0)
                    else
                       ! ilu=1
                       do j = 0,k - 1
                          call la_${ri}$lassq(n - j - 1,a(j + 1 + j*lda),1,scale,s)
                          ! trap l at a(0,0)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(j,a(0 + (1 + j)*lda),1,scale,s)
                          ! u at a(0,1)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(0),lda + 1,scale,s)
                       ! tri l at a(0,0)
                       call la_${ri}$lassq(k - 1,a(0 + lda),lda + 1,scale,s)
                       ! tri u at a(0,1)
                    end if
                 else
                    ! a is xpose
                    if (ilu == 0) then
                       ! a**t is upper
                       do j = 1,k - 2
                          call la_${ri}$lassq(j,a(0 + (k + j)*lda),1,scale,s)
                          ! u at a(0,k)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k-1 rect. at a(0,0)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + (j + k - 1)*lda),1,scale,s)
                          ! l at a(0,k-1)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k - 1,a(0 + k*lda),lda + 1,scale,s)
                       ! tri u at a(0,k)
                       call la_${ri}$lassq(k,a(0 + (k - 1)*lda),lda + 1,scale,s)
                       ! tri l at a(0,k-1)
                    else
                       ! a**t is lower
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + j*lda),1,scale,s)
                          ! u at a(0,0)
                       end do
                       do j = k,n - 1
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k-1 rect. at a(0,k)
                       end do
                       do j = 0,k - 3
                          call la_${ri}$lassq(k - j - 2,a(j + 2 + j*lda),1,scale,s)
                          ! l at a(1,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(0),lda + 1,scale,s)
                       ! tri u at a(0,0)
                       call la_${ri}$lassq(k - 1,a(1),lda + 1,scale,s)
                       ! tri l at a(1,0)
                    end if
                 end if
              else
                 ! n is even
                 if (ifm == 1) then
                    ! a is normal
                    if (ilu == 0) then
                       ! a is upper
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(k + j + 2 + j*lda),1,scale,s)
                          ! l at a(k+1,0)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k + j,a(0 + j*lda),1,scale,s)
                          ! trap u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(k + 1),lda + 1,scale,s)
                       ! tri l at a(k+1,0)
                       call la_${ri}$lassq(k,a(k),lda + 1,scale,s)
                       ! tri u at a(k,0)
                    else
                       ! ilu=1
                       do j = 0,k - 1
                          call la_${ri}$lassq(n - j - 1,a(j + 2 + j*lda),1,scale,s)
                          ! trap l at a(1,0)
                       end do
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + j*lda),1,scale,s)
                          ! u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(1),lda + 1,scale,s)
                       ! tri l at a(1,0)
                       call la_${ri}$lassq(k,a(0),lda + 1,scale,s)
                       ! tri u at a(0,0)
                    end if
                 else
                    ! a is xpose
                    if (ilu == 0) then
                       ! a**t is upper
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + (k + 1 + j)*lda),1,scale,s)
                          ! u at a(0,k+1)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k rect. at a(0,0)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + (j + k)*lda),1,scale,s)
                          ! l at a(0,k)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(0 + (k + 1)*lda),lda + 1,scale,s)
                       ! tri u at a(0,k+1)
                       call la_${ri}$lassq(k,a(0 + k*lda),lda + 1,scale,s)
                       ! tri l at a(0,k)
                    else
                       ! a**t is lower
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + (j + 1)*lda),1,scale,s)
                          ! u at a(0,1)
                       end do
                       do j = k + 1,n
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k rect. at a(0,k+1)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + j*lda),1,scale,s)
                          ! l at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       call la_${ri}$lassq(k,a(lda),lda + 1,scale,s)
                       ! tri l at a(0,1)
                       call la_${ri}$lassq(k,a(0),lda + 1,scale,s)
                       ! tri u at a(0,0)
                    end if
                 end if
              end if
              value = scale*sqrt(s)
           end if
           la_${ri}$lansf = value
           return
     end function la_${ri}$lansf
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANSP:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> real symmetric matrix A,  supplied in packed form.

     real(${rk}$) function la_${ri}$lansp(norm,uplo,n,ap,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: ap(*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,k
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 k = 1
                 do j = 1,n
                    do i = k,k + j - 1
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                    k = k + j
                 end do
              else
                 k = 1
                 do j = 1,n
                    do i = k,k + n - j
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                    k = k + n - j + 1
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              k = 1
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    work(j) = sum + abs(ap(k))
                    k = k + 1
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(ap(k))
                    k = k + 1
                    do i = j + 1,n
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              k = 2
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,ap(k),1,scale,sum)
                    k = k + j
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,ap(k),1,scale,sum)
                    k = k + n - j + 1
                 end do
              end if
              sum = 2*sum
              k = 1
              do i = 1,n
                 if (ap(k) /= zero) then
                    absa = abs(ap(k))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
                 if (la_lsame(uplo,'U')) then
                    k = k + i + 1
                 else
                    k = k + n - i + 1
                 end if
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansp = value
           return
     end function la_${ri}$lansp
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANST:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> real symmetric tridiagonal matrix A.

     pure real(${rk}$) function la_${ri}$lanst(norm,n,d,e)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: d(*),e(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           real(${rk}$) :: anorm,scale,sum
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n <= 0) then
              anorm = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              anorm = abs(d(n))
              do i = 1,n - 1
                 sum = abs(d(i))
                 if (anorm < sum .or. la_${ri}$isnan(sum)) anorm = sum
                 sum = abs(e(i))
                 if (anorm < sum .or. la_${ri}$isnan(sum)) anorm = sum
              end do
           else if (la_lsame(norm,'O') .or. norm == '1' .or. la_lsame(norm,'I')) &
                     then
              ! find norm1(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(e(1))
                 sum = abs(e(n - 1)) + abs(d(n))
                 if (anorm < sum .or. la_${ri}$isnan(sum)) anorm = sum
                 do i = 2,n - 1
                    sum = abs(d(i)) + abs(e(i)) + abs(e(i - 1))
                    if (anorm < sum .or. la_${ri}$isnan(sum)) anorm = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (n > 1) then
                 call la_${ri}$lassq(n - 1,e,1,scale,sum)
                 sum = 2*sum
              end if
              call la_${ri}$lassq(n,d,1,scale,sum)
              anorm = scale*sqrt(sum)
           end if
           la_${ri}$lanst = anorm
           return
     end function la_${ri}$lanst
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANSY:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> real symmetric matrix A.

     real(${rk}$) function la_${ri}$lansy(norm,uplo,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = 1,j
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                 end do
              else
                 do j = 1,n
                    do i = j,n
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(a(j,j))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(a(j,j))
                    do i = j + 1,n
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,a(1,j),1,scale,sum)
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,a(j + 1,j),1,scale,sum)
                 end do
              end if
              sum = 2*sum
              call la_${ri}$lassq(n,a,lda + 1,scale,sum)
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansy = value
           return
     end function la_${ri}$lansy
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANTB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n triangular band matrix A,  with ( k + 1 ) diagonals.

     real(${rk}$) function la_${ri}$lantb(norm,uplo,diag,n,k,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: k,ldab,n
           ! Array Arguments
           real(${rk}$),intent(in) :: ab(ldab,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j,l
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = max(k + 2 - j,1),k
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = 2,min(n + 1 - j,k + 1)
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = max(k + 2 - j,1),k + 1
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = 1,min(n + 1 - j,k + 1)
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = max(k + 2 - j,1),k
                          sum = sum + abs(ab(i,j))
                       end do
                    else
                       sum = zero
                       do i = max(k + 2 - j,1),k + 1
                          sum = sum + abs(ab(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = 2,min(n + 1 - j,k + 1)
                          sum = sum + abs(ab(i,j))
                       end do
                    else
                       sum = zero
                       do i = 1,min(n + 1 - j,k + 1)
                          sum = sum + abs(ab(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              value = zero
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       l = k + 1 - j
                       do i = max(1,j - k),j - 1
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       l = k + 1 - j
                       do i = max(1,j - k),j
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       l = 1 - j
                       do i = j + 1,min(n,j + k)
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       l = 1 - j
                       do i = j,min(n,j + k)
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 end if
              end if
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    if (k > 0) then
                       do j = 2,n
                          call la_${ri}$lassq(min(j - 1,k),ab(max(k + 2 - j,1),j),1,scale, &
                                    sum)
                       end do
                    end if
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(j,k + 1),ab(max(k + 2 - j,1),j),1,scale,sum)

                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    if (k > 0) then
                       do j = 1,n - 1
                          call la_${ri}$lassq(min(n - j,k),ab(2,j),1,scale,sum)
                       end do
                    end if
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(n - j + 1,k + 1),ab(1,j),1,scale,sum)
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantb = value
           return
     end function la_${ri}$lantb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANTP:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> triangular matrix A, supplied in packed form.

     real(${rk}$) function la_${ri}$lantp(norm,uplo,diag,n,ap,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: ap(*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j,k
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              k = 1
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = k,k + j - 2
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                       k = k + j
                    end do
                 else
                    do j = 1,n
                       do i = k + 1,k + n - j
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                       k = k + n - j + 1
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = k,k + j - 1
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                       k = k + j
                    end do
                 else
                    do j = 1,n
                       do i = k,k + n - j
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                       k = k + n - j + 1
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              k = 1
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = k,k + j - 2
                          sum = sum + abs(ap(i))
                       end do
                    else
                       sum = zero
                       do i = k,k + j - 1
                          sum = sum + abs(ap(i))
                       end do
                    end if
                    k = k + j
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = k + 1,k + n - j
                          sum = sum + abs(ap(i))
                       end do
                    else
                       sum = zero
                       do i = k,k + n - j
                          sum = sum + abs(ap(i))
                       end do
                    end if
                    k = k + n - j + 1
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              k = 1
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       do i = 1,j - 1
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                       k = k + 1
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = 1,j
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       k = k + 1
                       do i = j + 1,n
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j,n
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 end if
              end if
              value = zero
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    k = 2
                    do j = 2,n
                       call la_${ri}$lassq(j - 1,ap(k),1,scale,sum)
                       k = k + j
                    end do
                 else
                    scale = zero
                    sum = one
                    k = 1
                    do j = 1,n
                       call la_${ri}$lassq(j,ap(k),1,scale,sum)
                       k = k + j
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    k = 2
                    do j = 1,n - 1
                       call la_${ri}$lassq(n - j,ap(k),1,scale,sum)
                       k = k + n - j + 1
                    end do
                 else
                    scale = zero
                    sum = one
                    k = 1
                    do j = 1,n
                       call la_${ri}$lassq(n - j + 1,ap(k),1,scale,sum)
                       k = k + n - j + 1
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantp = value
           return
     end function la_${ri}$lantp
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
     !> ${ri.upper()}$LANTR:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> trapezoidal or triangular matrix A.

     real(${rk}$) function la_${ri}$lantr(norm,uplo,diag,m,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(out) :: work(*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (min(m,n) == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = 1,min(m,j - 1)
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = j + 1,m
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = 1,min(m,j)
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = j,m
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if ((udiag) .and. (j <= m)) then
                       sum = one
                       do i = 1,j - 1
                          sum = sum + abs(a(i,j))
                       end do
                    else
                       sum = zero
                       do i = 1,min(m,j)
                          sum = sum + abs(a(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = j + 1,m
                          sum = sum + abs(a(i,j))
                       end do
                    else
                       sum = zero
                       do i = j,m
                          sum = sum + abs(a(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ri}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,m
                       work(i) = one
                    end do
                    do j = 1,n
                       do i = 1,min(m,j - 1)
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 else
                    do i = 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = 1,min(m,j)
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,min(m,n)
                       work(i) = one
                    end do
                    do i = n + 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j + 1,m
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 else
                    do i = 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j,m
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 end if
              end if
              value = zero
              do i = 1,m
                 sum = work(i)
                 if (value < sum .or. la_${ri}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = min(m,n)
                    do j = 2,n
                       call la_${ri}$lassq(min(m,j - 1),a(1,j),1,scale,sum)
                    end do
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(m,j),a(1,j),1,scale,sum)
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = min(m,n)
                    do j = 1,n
                       call la_${ri}$lassq(m - j,a(min(m,j + 1),j),1,scale,sum)
                    end do
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(m - j + 1,a(j,j),1,scale,sum)
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantr = value
           return
     end function la_${ri}$lantr
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANGB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n band matrix  A,  with kl sub-diagonals and ku super-diagonals.

     real(${rk}$) function la_${ri}$langb(norm,n,kl,ku,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: kl,ku,ldab,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ab(ldab,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,k,l
           real(${rk}$) :: scale,sum,value,temp
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                    temp = abs(ab(i,j))
                    if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = max(ku + 2 - j,1),min(n + ku + 1 - j,kl + ku + 1)
                    sum = sum + abs(ab(i,j))
                 end do
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,n
                 work(i) = zero
              end do
              do j = 1,n
                 k = ku + 1 - j
                 do i = max(1,j - ku),min(n,j + kl)
                    work(i) = work(i) + abs(ab(k + i,j))
                 end do
              end do
              value = zero
              do i = 1,n
                 temp = work(i)
                 if (value < temp .or. la_${ci}$isnan(temp)) value = temp
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 l = max(1,j - ku)
                 k = ku + 1 - j + l
                 call la_${ri}$lassq(min(n,j + kl) - l + 1,ab(k,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$langb = value
           return
     end function la_${ri}$langb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANGE:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex matrix A.

     real(${rk}$) function la_${ri}$lange(norm,m,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: a(lda,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value,temp
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (min(m,n) == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = 1,m
                    temp = abs(a(i,j))
                    if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = 1,m
                    sum = sum + abs(a(i,j))
                 end do
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,m
                 work(i) = zero
              end do
              do j = 1,n
                 do i = 1,m
                    work(i) = work(i) + abs(a(i,j))
                 end do
              end do
              value = zero
              do i = 1,m
                 temp = work(i)
                 if (value < temp .or. la_${ci}$isnan(temp)) value = temp
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 call la_${ri}$lassq(m,a(1,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lange = value
           return
     end function la_${ri}$lange
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANGT:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex tridiagonal matrix A.

     pure real(${rk}$) function la_${ri}$langt(norm,n,dl,d,du)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: n
           ! Array Arguments
           complex(${rk}$),intent(in) :: d(*),dl(*),du(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           real(${rk}$) :: anorm,scale,sum,temp
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n <= 0) then
              anorm = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              anorm = abs(d(n))
              do i = 1,n - 1
                 if (anorm < abs(dl(i)) .or. la_${ci}$isnan(abs(dl(i)))) anorm = abs(dl(i))

                 if (anorm < abs(d(i)) .or. la_${ci}$isnan(abs(d(i)))) anorm = abs(d(i))

                 if (anorm < abs(du(i)) .or. la_${ci}$isnan(abs(du(i)))) anorm = abs(du(i))

              end do
           else if (la_lsame(norm,'O') .or. norm == '1') then
              ! find norm1(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(dl(1))
                 temp = abs(d(n)) + abs(du(n - 1))
                 if (anorm < temp .or. la_${ci}$isnan(temp)) anorm = temp
                 do i = 2,n - 1
                    temp = abs(d(i)) + abs(dl(i)) + abs(du(i - 1))
                    if (anorm < temp .or. la_${ci}$isnan(temp)) anorm = temp
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(du(1))
                 temp = abs(d(n)) + abs(dl(n - 1))
                 if (anorm < temp .or. la_${ci}$isnan(temp)) anorm = temp
                 do i = 2,n - 1
                    temp = abs(d(i)) + abs(du(i)) + abs(dl(i - 1))
                    if (anorm < temp .or. la_${ci}$isnan(temp)) anorm = temp
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              call la_${ri}$lassq(n,d,1,scale,sum)
              if (n > 1) then
                 call la_${ri}$lassq(n - 1,dl,1,scale,sum)
                 call la_${ri}$lassq(n - 1,du,1,scale,sum)
              end if
              anorm = scale*sqrt(sum)
           end if
           la_${ri}$langt = anorm
           return
     end function la_${ri}$langt
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n hermitian band matrix A,  with k super-diagonals.

     real(${rk}$) function la_${ri}$lanhb(norm,uplo,n,k,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: k,ldab,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ab(ldab,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,l
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,max,min,real,sqrt
#:else
           intrinsic :: abs,real,max,min,sqrt
#:endif
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = max(k + 2 - j,1),k
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    sum = abs(real(ab(k + 1,j),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    sum = abs(real(ab(1,j),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    do i = 2,min(n + 1 - j,k + 1)
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is hermitian).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    l = k + 1 - j
                    do i = max(1,j - k),j - 1
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(real(ab(k + 1,j),KIND=${rk}$))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(real(ab(1,j),KIND=${rk}$))
                    l = 1 - j
                    do i = j + 1,min(n,j + k)
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (k > 0) then
                 if (la_lsame(uplo,'U')) then
                    do j = 2,n
                       call la_${ri}$lassq(min(j - 1,k),ab(max(k + 2 - j,1),j),1,scale,sum)

                    end do
                    l = k + 1
                 else
                    do j = 1,n - 1
                       call la_${ri}$lassq(min(n - j,k),ab(2,j),1,scale,sum)
                    end do
                    l = 1
                 end if
                 sum = 2*sum
              else
                 l = 1
              end if
              do j = 1,n
                 if (real(ab(l,j),KIND=${rk}$) /= zero) then
                    absa = abs(real(ab(l,j),KIND=${rk}$))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lanhb = value
           return
     end function la_${ri}$lanhb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHE:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex hermitian matrix A.

     real(${rk}$) function la_${ri}$lanhe(norm,uplo,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: a(lda,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,real,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = 1,j - 1
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    sum = abs(real(a(j,j),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    sum = abs(real(a(j,j),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    do i = j + 1,n
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is hermitian).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(real(a(j,j),KIND=${rk}$))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(real(a(j,j),KIND=${rk}$))
                    do i = j + 1,n
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,a(1,j),1,scale,sum)
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,a(j + 1,j),1,scale,sum)
                 end do
              end if
              sum = 2*sum
              do i = 1,n
                 if (real(a(i,i),KIND=${rk}$) /= zero) then
                    absa = abs(real(a(i,i),KIND=${rk}$))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lanhe = value
           return
     end function la_${ri}$lanhe
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHF:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex Hermitian matrix A in RFP format.

     real(${rk}$) function la_${ri}$lanhf(norm,transr,uplo,n,a,work)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,transr,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(0:*)
           complex(${rk}$),intent(in) :: a(0:*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,ifm,ilu,noe,n1,k,l,lda
           real(${rk}$) :: scale,s,value,aa,temp
           ! Intrinsic Functions
           intrinsic :: abs,real,sqrt
           ! Executable Statements
           if (n == 0) then
              la_${ri}$lanhf = zero
              return
           else if (n == 1) then
              la_${ri}$lanhf = abs(real(a(0),KIND=${rk}$))
              return
           end if
           ! set noe = 1 if n is odd. if n is even set noe=0
           noe = 1
           if (mod(n,2) == 0) noe = 0
           ! set ifm = 0 when form='c' or 'c' and 1 otherwise
           ifm = 1
           if (la_lsame(transr,'C')) ifm = 0
           ! set ilu = 0 when uplo='u or 'u' and 1 otherwise
           ilu = 1
           if (la_lsame(uplo,'U')) ilu = 0
           ! set lda = (n+1)/2 when ifm = 0
           ! set lda = n when ifm = 1 and noe = 1
           ! set lda = n+1 when ifm = 1 and noe = 0
           if (ifm == 1) then
              if (noe == 1) then
                 lda = n
              else
                 ! noe=0
                 lda = n + 1
              end if
           else
              ! ifm=0
              lda = (n + 1)/2
           end if
           if (la_lsame(norm,'M')) then
             ! find max(abs(a(i,j))).
              k = (n + 1)/2
              value = zero
              if (noe == 1) then
                 ! n is odd
                 if (ifm == 1) then
                    ! a is n by k
                    if (ilu == 1) then
                       ! uplo ='l'
                       j = 0
                       ! -> l(0,0)
                       temp = abs(real(a(j + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do i = 1,n - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       do j = 1,k - 1
                          do i = 0,j - 2
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j - 1
                          ! l(k+j,k+j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j
                          ! -> l(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j + 1,n - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                    else
                       ! uplo = 'u'
                       do j = 0,k - 2
                          do i = 0,k + j - 2
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = k + j - 1
                          ! -> u(i,i)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = i + 1
                          ! =k+j; i -> u(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = k + j + 1,n - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       do i = 0,n - 2
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          ! j=k-1
                       end do
                       ! i=n-1 -> u(n-1,n-1)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                    end if
                 else
                    ! xpose case; a is k by n
                    if (ilu == 1) then
                       ! uplo ='l'
                       do j = 0,k - 2
                          do i = 0,j - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j
                          ! l(i,i)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j + 1
                          ! l(j+k,j+k)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j + 2,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       j = k - 1
                       do i = 0,k - 2
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       i = k - 1
                       ! -> l(i,i) is at a(i,j)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do j = k,n - 1
                          do i = 0,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                    else
                       ! uplo = 'u'
                       do j = 0,k - 2
                          do i = 0,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       j = k - 1
                       ! -> u(j,j) is at a(0,j)
                       temp = abs(real(a(0 + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do i = 1,k - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       do j = k,n - 1
                          do i = 0,j - k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j - k
                          ! -> u(i,i) at a(i,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j - k + 1
                          ! u(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j - k + 2,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                    end if
                 end if
              else
                 ! n is even
                 if (ifm == 1) then
                    ! a is n+1 by k
                    if (ilu == 1) then
                       ! uplo ='l'
                       j = 0
                       ! -> l(k,k)
                       temp = abs(real(a(j + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       temp = abs(real(a(j + 1 + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do i = 2,n
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       do j = 1,k - 1
                          do i = 0,j - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j
                          ! l(k+j,k+j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j + 1
                          ! -> l(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j + 2,n
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                    else
                       ! uplo = 'u'
                       do j = 0,k - 2
                          do i = 0,k + j - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = k + j
                          ! -> u(i,i)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = i + 1
                          ! =k+j+1; i -> u(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = k + j + 2,n
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       do i = 0,n - 2
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          ! j=k-1
                       end do
                       ! i=n-1 -> u(n-1,n-1)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       i = n
                       ! -> u(k-1,k-1)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                    end if
                 else
                    ! xpose case; a is k by n+1
                    if (ilu == 1) then
                       ! uplo ='l'
                       j = 0
                       ! -> l(k,k) at a(0,0)
                       temp = abs(real(a(j + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do i = 1,k - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       do j = 1,k - 1
                          do i = 0,j - 2
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j - 1
                          ! l(i,i)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j
                          ! l(j+k,j+k)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j + 1,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       j = k
                       do i = 0,k - 2
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       i = k - 1
                       ! -> l(i,i) is at a(i,j)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do j = k + 1,n
                          do i = 0,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                    else
                       ! uplo = 'u'
                       do j = 0,k - 1
                          do i = 0,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       j = k
                       ! -> u(j,j) is at a(0,j)
                       temp = abs(real(a(0 + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       do i = 1,k - 1
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       do j = k + 1,n - 1
                          do i = 0,j - k - 2
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                          i = j - k - 1
                          ! -> u(i,i) at a(i,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          i = j - k
                          ! u(j,j)
                          temp = abs(real(a(i + j*lda),KIND=${rk}$))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          do i = j - k + 1,k - 1
                             temp = abs(a(i + j*lda))
                             if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                          end do
                       end do
                       j = n
                       do i = 0,k - 2
                          temp = abs(a(i + j*lda))
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                       i = k - 1
                       ! u(k,k) at a(i,j)
                       temp = abs(real(a(i + j*lda),KIND=${rk}$))
                       if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                    end if
                 end if
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
             ! find normi(a) ( = norm1(a), since a is hermitian).
              if (ifm == 1) then
                 ! a is 'n'
                 k = n/2
                 if (noe == 1) then
                    ! n is odd
                    if (ilu == 0) then
                       ! uplo = 'u'
                       do i = 0,k - 1
                          work(i) = zero
                       end do
                       do j = 0,k
                          s = zero
                          do i = 0,k + j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(i,j+k)
                             s = s + aa
                             work(i) = work(i) + aa
                          end do
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j+k,j+k)
                          work(j + k) = s + aa
                          if (i == k + k) go to 10
                          i = i + 1
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j,j)
                          work(j) = work(j) + aa
                          s = zero
                          do l = j + 1,k - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       10 continue
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu = 1
                       k = k + 1
                       ! k=(n+1)/2 for n odd and ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = k - 1,0,-1
                          s = zero
                          do i = 0,j - 2
                             aa = abs(a(i + j*lda))
                             ! -> a(j+k,i+k)
                             s = s + aa
                             work(i + k) = work(i + k) + aa
                          end do
                          if (j > 0) then
                             aa = abs(real(a(i + j*lda),KIND=${rk}$))
                             ! -> a(j+k,j+k)
                             s = s + aa
                             work(i + k) = work(i + k) + s
                             ! i=j
                             i = i + 1
                          end if
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j,j)
                          work(j) = aa
                          s = zero
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    end if
                 else
                    ! n is even
                    if (ilu == 0) then
                       ! uplo = 'u'
                       do i = 0,k - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 1
                          s = zero
                          do i = 0,k + j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(i,j+k)
                             s = s + aa
                             work(i) = work(i) + aa
                          end do
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j+k,j+k)
                          work(j + k) = s + aa
                          i = i + 1
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j,j)
                          work(j) = work(j) + aa
                          s = zero
                          do l = j + 1,k - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu = 1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = k - 1,0,-1
                          s = zero
                          do i = 0,j - 1
                             aa = abs(a(i + j*lda))
                             ! -> a(j+k,i+k)
                             s = s + aa
                             work(i + k) = work(i + k) + aa
                          end do
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j+k,j+k)
                          s = s + aa
                          work(i + k) = work(i + k) + s
                          ! i=j
                          i = i + 1
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! -> a(j,j)
                          work(j) = aa
                          s = zero
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! -> a(l,j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    end if
                 end if
              else
                 ! ifm=0
                 k = n/2
                 if (noe == 1) then
                    ! n is odd
                    if (ilu == 0) then
                       ! uplo = 'u'
                       n1 = k
                       ! n/2
                       k = k + 1
                       ! k is the row size and lda
                       do i = n1,n - 1
                          work(i) = zero
                       end do
                       do j = 0,n1 - 1
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,n1+i)
                             work(i + n1) = work(i + n1) + aa
                             s = s + aa
                          end do
                          work(j) = s
                       end do
                       ! j=n1=k-1 is special
                       s = abs(real(a(0 + j*lda),KIND=${rk}$))
                       ! a(k-1,k-1)
                       do i = 1,k - 1
                          aa = abs(a(i + j*lda))
                          ! a(k-1,i+n1)
                          work(i + n1) = work(i + n1) + aa
                          s = s + aa
                       end do
                       work(j) = work(j) + s
                       do j = k,n - 1
                          s = zero
                          do i = 0,j - k - 1
                             aa = abs(a(i + j*lda))
                             ! a(i,j-k)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          ! i=j-k
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! a(j-k,j-k)
                          s = s + aa
                          work(j - k) = work(j - k) + s
                          i = i + 1
                          s = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! a(j,j)
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(j,l)
                             work(l) = work(l) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu=1
                       k = k + 1
                       ! k=(n+1)/2 for n odd and ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 2
                          ! process
                          s = zero
                          do i = 0,j - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! i=j so process of a(j,j)
                          s = s + aa
                          work(j) = s
                          ! is initialised here
                          i = i + 1
                          ! i=j process a(j+k,j+k)
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          s = aa
                          do l = k + j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(l,k+j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(k + j) = work(k + j) + s
                       end do
                       ! j=k-1 is special :process col a(k-1,0:k-1)
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(k,i)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(real(a(i + j*lda),KIND=${rk}$))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = s
                       ! done with col j=k+1
                       do j = k,n - 1
                          ! process col j of a = a(j,0:k-1)
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    end if
                 else
                    ! n is even
                    if (ilu == 0) then
                       ! uplo = 'u'
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       do j = 0,k - 1
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j,i+k)
                             work(i + k) = work(i + k) + aa
                             s = s + aa
                          end do
                          work(j) = s
                       end do
                       ! j=k
                       aa = abs(real(a(0 + j*lda),KIND=${rk}$))
                       ! a(k,k)
                       s = aa
                       do i = 1,k - 1
                          aa = abs(a(i + j*lda))
                          ! a(k,k+i)
                          work(i + k) = work(i + k) + aa
                          s = s + aa
                       end do
                       work(j) = work(j) + s
                       do j = k + 1,n - 1
                          s = zero
                          do i = 0,j - 2 - k
                             aa = abs(a(i + j*lda))
                             ! a(i,j-k-1)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          ! i=j-1-k
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! a(j-k-1,j-k-1)
                          s = s + aa
                          work(j - k - 1) = work(j - k - 1) + s
                          i = i + 1
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! a(j,j)
                          s = aa
                          do l = j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(j,l)
                             work(l) = work(l) + aa
                             s = s + aa
                          end do
                          work(j) = work(j) + s
                       end do
                       ! j=n
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(i,k-1)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(real(a(i + j*lda),KIND=${rk}$))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = work(i) + s
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    else
                       ! ilu=1
                       do i = k,n - 1
                          work(i) = zero
                       end do
                       ! j=0 is special :process col a(k:n-1,k)
                       s = abs(real(a(0),KIND=${rk}$))
                       ! a(k,k)
                       do i = 1,k - 1
                          aa = abs(a(i))
                          ! a(k+i,k)
                          work(i + k) = work(i + k) + aa
                          s = s + aa
                       end do
                       work(k) = work(k) + s
                       do j = 1,k - 1
                          ! process
                          s = zero
                          do i = 0,j - 2
                             aa = abs(a(i + j*lda))
                             ! a(j-1,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          ! i=j-1 so process of a(j-1,j-1)
                          s = s + aa
                          work(j - 1) = s
                          ! is initialised here
                          i = i + 1
                          ! i=j process a(j+k,j+k)
                          aa = abs(real(a(i + j*lda),KIND=${rk}$))
                          s = aa
                          do l = k + j + 1,n - 1
                             i = i + 1
                             aa = abs(a(i + j*lda))
                             ! a(l,k+j)
                             s = s + aa
                             work(l) = work(l) + aa
                          end do
                          work(k + j) = work(k + j) + s
                       end do
                       ! j=k is special :process col a(k,0:k-1)
                       s = zero
                       do i = 0,k - 2
                          aa = abs(a(i + j*lda))
                          ! a(k,i)
                          work(i) = work(i) + aa
                          s = s + aa
                       end do
                       ! i=k-1
                       aa = abs(real(a(i + j*lda),KIND=${rk}$))
                       ! a(k-1,k-1)
                       s = s + aa
                       work(i) = s
                       ! done with col j=k+1
                       do j = k + 1,n
                          ! process col j-1 of a = a(j-1,0:k-1)
                          s = zero
                          do i = 0,k - 1
                             aa = abs(a(i + j*lda))
                             ! a(j-1,i)
                             work(i) = work(i) + aa
                             s = s + aa
                          end do
                          work(j - 1) = work(j - 1) + s
                       end do
                       value = work(0)
                       do i = 1,n - 1
                          temp = work(i)
                          if (value < temp .or. la_${ci}$isnan(temp)) value = temp
                       end do
                    end if
                 end if
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
             ! find normf(a).
              k = (n + 1)/2
              scale = zero
              s = one
              if (noe == 1) then
                 ! n is odd
                 if (ifm == 1) then
                    ! a is normal
                    if (ilu == 0) then
                       ! a is upper
                       do j = 0,k - 3
                          call la_${ri}$lassq(k - j - 2,a(k + j + 1 + j*lda),1,scale,s)
                          ! l at a(k,0)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k + j - 1,a(0 + j*lda),1,scale,s)
                          ! trap u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = k - 1
                       ! -> u(k,k) at a(k-1,0)
                       do i = 0,k - 2
                          aa = real(a(l),KIND=${rk}$)
                          ! u(k+i,k+i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! u(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                       aa = real(a(l),KIND=${rk}$)
                       ! u(n-1,n-1)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                    else
                       ! ilu=1
                       do j = 0,k - 1
                          call la_${ri}$lassq(n - j - 1,a(j + 1 + j*lda),1,scale,s)
                          ! trap l at a(0,0)
                       end do
                       do j = 1,k - 2
                          call la_${ri}$lassq(j,a(0 + (1 + j)*lda),1,scale,s)
                          ! u at a(0,1)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       aa = real(a(0),KIND=${rk}$)
                       ! l(0,0) at a(0,0)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                       l = lda
                       ! -> l(k,k) at a(0,1)
                       do i = 1,k - 1
                          aa = real(a(l),KIND=${rk}$)
                          ! l(k-1+i,k-1+i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! l(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                    end if
                 else
                    ! a is xpose
                    if (ilu == 0) then
                       ! a**h is upper
                       do j = 1,k - 2
                          call la_${ri}$lassq(j,a(0 + (k + j)*lda),1,scale,s)
                          ! u at a(0,k)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k-1 rect. at a(0,0)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + (j + k - 1)*lda),1,scale,s)
                          ! l at a(0,k-1)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = 0 + k*lda - lda
                       ! -> u(k-1,k-1) at a(0,k-1)
                       aa = real(a(l),KIND=${rk}$)
                       ! u(k-1,k-1)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                       l = l + lda
                       ! -> u(0,0) at a(0,k)
                       do j = k,n - 1
                          aa = real(a(l),KIND=${rk}$)
                          ! -> u(j-k,j-k)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! -> u(j,j)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                    else
                       ! a**h is lower
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + j*lda),1,scale,s)
                          ! u at a(0,0)
                       end do
                       do j = k,n - 1
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                          ! k by k-1 rect. at a(0,k)
                       end do
                       do j = 0,k - 3
                          call la_${ri}$lassq(k - j - 2,a(j + 2 + j*lda),1,scale,s)
                          ! l at a(1,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = 0
                       ! -> l(0,0) at a(0,0)
                       do i = 0,k - 2
                          aa = real(a(l),KIND=${rk}$)
                          ! l(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! l(k+i,k+i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                       ! l-> k-1 + (k-1)*lda or l(k-1,k-1) at a(k-1,k-1)
                       aa = real(a(l),KIND=${rk}$)
                       ! l(k-1,k-1) at a(k-1,k-1)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                    end if
                 end if
              else
                 ! n is even
                 if (ifm == 1) then
                    ! a is normal
                    if (ilu == 0) then
                       ! a is upper
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(k + j + 2 + j*lda),1,scale,s)
                       ! l at a(k+1,0)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k + j,a(0 + j*lda),1,scale,s)
                       ! trap u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = k
                       ! -> u(k,k) at a(k,0)
                       do i = 0,k - 1
                          aa = real(a(l),KIND=${rk}$)
                          ! u(k+i,k+i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! u(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                    else
                       ! ilu=1
                       do j = 0,k - 1
                          call la_${ri}$lassq(n - j - 1,a(j + 2 + j*lda),1,scale,s)
                          ! trap l at a(1,0)
                       end do
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + j*lda),1,scale,s)
                          ! u at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = 0
                       ! -> l(k,k) at a(0,0)
                       do i = 0,k - 1
                          aa = real(a(l),KIND=${rk}$)
                          ! l(k-1+i,k-1+i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! l(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                    end if
                 else
                    ! a is xpose
                    if (ilu == 0) then
                       ! a**h is upper
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + (k + 1 + j)*lda),1,scale,s)
                       ! u at a(0,k+1)
                       end do
                       do j = 0,k - 1
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                       ! k by k rect. at a(0,0)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + (j + k)*lda),1,scale,s)
                       ! l at a(0,k)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = 0 + k*lda
                       ! -> u(k,k) at a(0,k)
                       aa = real(a(l),KIND=${rk}$)
                       ! u(k,k)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                       l = l + lda
                       ! -> u(0,0) at a(0,k+1)
                       do j = k + 1,n - 1
                          aa = real(a(l),KIND=${rk}$)
                          ! -> u(j-k-1,j-k-1)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! -> u(j,j)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                       ! l=k-1+n*lda
                       ! -> u(k-1,k-1) at a(k-1,n)
                       aa = real(a(l),KIND=${rk}$)
                       ! u(k,k)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                    else
                       ! a**h is lower
                       do j = 1,k - 1
                          call la_${ri}$lassq(j,a(0 + (j + 1)*lda),1,scale,s)
                       ! u at a(0,1)
                       end do
                       do j = k + 1,n
                          call la_${ri}$lassq(k,a(0 + j*lda),1,scale,s)
                       ! k by k rect. at a(0,k+1)
                       end do
                       do j = 0,k - 2
                          call la_${ri}$lassq(k - j - 1,a(j + 1 + j*lda),1,scale,s)
                       ! l at a(0,0)
                       end do
                       s = s + s
                       ! double s for the off diagonal elements
                       l = 0
                       ! -> l(k,k) at a(0,0)
                       aa = real(a(l),KIND=${rk}$)
                       ! l(k,k) at a(0,0)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                       l = lda
                       ! -> l(0,0) at a(0,1)
                       do i = 0,k - 2
                          aa = real(a(l),KIND=${rk}$)
                          ! l(i,i)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          aa = real(a(l + 1),KIND=${rk}$)
                          ! l(k+i+1,k+i+1)
                          if (aa /= zero) then
                             if (scale < aa) then
                                s = one + s*(scale/aa)**2
                                scale = aa
                             else
                                s = s + (aa/scale)**2
                             end if
                          end if
                          l = l + lda + 1
                       end do
                       ! l-> k - 1 + k*lda or l(k-1,k-1) at a(k-1,k)
                       aa = real(a(l),KIND=${rk}$)
                       ! l(k-1,k-1) at a(k-1,k)
                       if (aa /= zero) then
                          if (scale < aa) then
                             s = one + s*(scale/aa)**2
                             scale = aa
                          else
                             s = s + (aa/scale)**2
                          end if
                       end if
                    end if
                 end if
              end if
              value = scale*sqrt(s)
           end if
           la_${ri}$lanhf = value
           return
     end function la_${ri}$lanhf
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHP:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex hermitian matrix A,  supplied in packed form.

     real(${rk}$) function la_${ri}$lanhp(norm,uplo,n,ap,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ap(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,k
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,real,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 k = 0
                 do j = 1,n
                    do i = k + 1,k + j - 1
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    k = k + j
                    sum = abs(real(ap(k),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 k = 1
                 do j = 1,n
                    sum = abs(real(ap(k),KIND=${rk}$))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    do i = k + 1,k + n - j
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    k = k + n - j + 1
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is hermitian).
              value = zero
              k = 1
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    work(j) = sum + abs(real(ap(k),KIND=${rk}$))
                    k = k + 1
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(real(ap(k),KIND=${rk}$))
                    k = k + 1
                    do i = j + 1,n
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              k = 2
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,ap(k),1,scale,sum)
                    k = k + j
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,ap(k),1,scale,sum)
                    k = k + n - j + 1
                 end do
              end if
              sum = 2*sum
              k = 1
              do i = 1,n
                 if (real(ap(k),KIND=${rk}$) /= zero) then
                    absa = abs(real(ap(k),KIND=${rk}$))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
                 if (la_lsame(uplo,'U')) then
                    k = k + i + 1
                 else
                    k = k + n - i + 1
                 end if
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lanhp = value
           return
     end function la_${ri}$lanhp
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHS:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> Hessenberg matrix A.

     real(${rk}$) function la_${ri}$lanhs(norm,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: a(lda,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              do j = 1,n
                 do i = 1,min(n,j + 1)
                    sum = abs(a(i,j))
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end do
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              do j = 1,n
                 sum = zero
                 do i = 1,min(n,j + 1)
                    sum = sum + abs(a(i,j))
                 end do
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              do i = 1,n
                 work(i) = zero
              end do
              do j = 1,n
                 do i = 1,min(n,j + 1)
                    work(i) = work(i) + abs(a(i,j))
                 end do
              end do
              value = zero
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              do j = 1,n
                 call la_${ri}$lassq(min(n,j + 1),a(1,j),1,scale,sum)
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lanhs = value
           return
     end function la_${ri}$lanhs
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANHT:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex Hermitian tridiagonal matrix A.

     pure real(${rk}$) function la_${ri}$lanht(norm,n,d,e)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(in) :: d(*)
           complex(${rk}$),intent(in) :: e(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i
           real(${rk}$) :: anorm,scale,sum
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,sqrt
#:else
           intrinsic :: abs,max,sqrt
#:endif
           ! Executable Statements
           if (n <= 0) then
              anorm = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              anorm = abs(d(n))
              do i = 1,n - 1
                 sum = abs(d(i))
                 if (anorm < sum .or. la_${ci}$isnan(sum)) anorm = sum
                 sum = abs(e(i))
                 if (anorm < sum .or. la_${ci}$isnan(sum)) anorm = sum
              end do
           else if (la_lsame(norm,'O') .or. norm == '1' .or. la_lsame(norm,'I')) &
                     then
              ! find norm1(a).
              if (n == 1) then
                 anorm = abs(d(1))
              else
                 anorm = abs(d(1)) + abs(e(1))
                 sum = abs(e(n - 1)) + abs(d(n))
                 if (anorm < sum .or. la_${ci}$isnan(sum)) anorm = sum
                 do i = 2,n - 1
                    sum = abs(d(i)) + abs(e(i)) + abs(e(i - 1))
                    if (anorm < sum .or. la_${ci}$isnan(sum)) anorm = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (n > 1) then
                 call la_${ri}$lassq(n - 1,e,1,scale,sum)
                 sum = 2*sum
              end if
              call la_${ci}$lassq(n,d,1,scale,sum)
              anorm = scale*sqrt(sum)
           end if
           la_${ri}$lanht = anorm
           return
     end function la_${ri}$lanht
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANSB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n symmetric band matrix A,  with k super-diagonals.

     real(${rk}$) function la_${ri}$lansb(norm,uplo,n,k,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: k,ldab,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ab(ldab,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,l
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = max(k + 2 - j,1),k + 1
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              else
                 do j = 1,n
                    do i = 1,min(n + 1 - j,k + 1)
                       sum = abs(ab(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    l = k + 1 - j
                    do i = max(1,j - k),j - 1
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(ab(k + 1,j))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(ab(1,j))
                    l = 1 - j
                    do i = j + 1,min(n,j + k)
                       absa = abs(ab(l + i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (k > 0) then
                 if (la_lsame(uplo,'U')) then
                    do j = 2,n
                       call la_${ri}$lassq(min(j - 1,k),ab(max(k + 2 - j,1),j),1,scale,sum)

                    end do
                    l = k + 1
                 else
                    do j = 1,n - 1
                       call la_${ri}$lassq(min(n - j,k),ab(2,j),1,scale,sum)
                    end do
                    l = 1
                 end if
                 sum = 2*sum
              else
                 l = 1
              end if
              call la_${ri}$lassq(n,ab(l,1),ldab,scale,sum)
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansb = value
           return
     end function la_${ri}$lansb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANSP:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex symmetric matrix A,  supplied in packed form.

     real(${rk}$) function la_${ri}$lansp(norm,uplo,n,ap,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ap(*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,k
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,real,sqrt
#:else
           intrinsic :: abs,real,aimag,sqrt
#:endif
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 k = 1
                 do j = 1,n
                    do i = k,k + j - 1
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    k = k + j
                 end do
              else
                 k = 1
                 do j = 1,n
                    do i = k,k + n - j
                       sum = abs(ap(i))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                    k = k + n - j + 1
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              k = 1
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    work(j) = sum + abs(ap(k))
                    k = k + 1
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(ap(k))
                    k = k + 1
                    do i = j + 1,n
                       absa = abs(ap(k))
                       sum = sum + absa
                       work(i) = work(i) + absa
                       k = k + 1
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              k = 2
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,ap(k),1,scale,sum)
                    k = k + j
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,ap(k),1,scale,sum)
                    k = k + n - j + 1
                 end do
              end if
              sum = 2*sum
              k = 1
              do i = 1,n
                 if (real(ap(k),KIND=${rk}$) /= zero) then
                    absa = abs(real(ap(k),KIND=${rk}$))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
                 if (aimag(ap(k)) /= zero) then
                    absa = abs(aimag(ap(k)))
                    if (scale < absa) then
                       sum = one + sum*(scale/absa)**2
                       scale = absa
                    else
                       sum = sum + (absa/scale)**2
                    end if
                 end if
                 if (la_lsame(uplo,'U')) then
                    k = k + i + 1
                 else
                    k = k + n - i + 1
                 end if
              end do
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansp = value
           return
     end function la_${ri}$lansp
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANSY:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> complex symmetric matrix A.

     real(${rk}$) function la_${ri}$lansy(norm,uplo,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: norm,uplo
           integer(ilp),intent(in) :: lda,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: a(lda,*)
       ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           real(${rk}$) :: absa,scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    do i = 1,j
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              else
                 do j = 1,n
                    do i = j,n
                       sum = abs(a(i,j))
                       if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                    end do
                 end do
              end if
           else if ((la_lsame(norm,'I')) .or. (la_lsame(norm,'O')) .or. ( &
                     norm == '1')) then
              ! find normi(a) ( = norm1(a), since a is symmetric).
              value = zero
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    sum = zero
                    do i = 1,j - 1
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    work(j) = sum + abs(a(j,j))
                 end do
                 do i = 1,n
                    sum = work(i)
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do i = 1,n
                    work(i) = zero
                 end do
                 do j = 1,n
                    sum = work(j) + abs(a(j,j))
                    do i = j + 1,n
                       absa = abs(a(i,j))
                       sum = sum + absa
                       work(i) = work(i) + absa
                    end do
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              scale = zero
              sum = one
              if (la_lsame(uplo,'U')) then
                 do j = 2,n
                    call la_${ri}$lassq(j - 1,a(1,j),1,scale,sum)
                 end do
              else
                 do j = 1,n - 1
                    call la_${ri}$lassq(n - j,a(j + 1,j),1,scale,sum)
                 end do
              end if
              sum = 2*sum
              call la_${ri}$lassq(n,a,lda + 1,scale,sum)
              value = scale*sqrt(sum)
           end if
           la_${ri}$lansy = value
           return
     end function la_${ri}$lansy
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANTB:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the element of  largest absolute value  of an
     !> n by n triangular band matrix A,  with ( k + 1 ) diagonals.

     real(${rk}$) function la_${ri}$lantb(norm,uplo,diag,n,k,ab,ldab,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: k,ldab,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ab(ldab,*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j,l
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,max,min,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = max(k + 2 - j,1),k
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = 2,min(n + 1 - j,k + 1)
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = max(k + 2 - j,1),k + 1
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = 1,min(n + 1 - j,k + 1)
                          sum = abs(ab(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = max(k + 2 - j,1),k
                          sum = sum + abs(ab(i,j))
                       end do
                    else
                       sum = zero
                       do i = max(k + 2 - j,1),k + 1
                          sum = sum + abs(ab(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = 2,min(n + 1 - j,k + 1)
                          sum = sum + abs(ab(i,j))
                       end do
                    else
                       sum = zero
                       do i = 1,min(n + 1 - j,k + 1)
                          sum = sum + abs(ab(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              value = zero
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       l = k + 1 - j
                       do i = max(1,j - k),j - 1
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       l = k + 1 - j
                       do i = max(1,j - k),j
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       l = 1 - j
                       do i = j + 1,min(n,j + k)
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       l = 1 - j
                       do i = j,min(n,j + k)
                          work(i) = work(i) + abs(ab(l + i,j))
                       end do
                    end do
                 end if
              end if
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    if (k > 0) then
                       do j = 2,n
                          call la_${ri}$lassq(min(j - 1,k),ab(max(k + 2 - j,1),j),1,scale, &
                                    sum)
                       end do
                    end if
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(j,k + 1),ab(max(k + 2 - j,1),j),1,scale,sum)

                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    if (k > 0) then
                       do j = 1,n - 1
                          call la_${ri}$lassq(min(n - j,k),ab(2,j),1,scale,sum)
                       end do
                    end if
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(n - j + 1,k + 1),ab(1,j),1,scale,sum)
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantb = value
           return
     end function la_${ri}$lantb
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANTP:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> triangular matrix A, supplied in packed form.

     real(${rk}$) function la_${ri}$lantp(norm,uplo,diag,n,ap,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: ap(*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j,k
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           if (n == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              k = 1
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = k,k + j - 2
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                       k = k + j
                    end do
                 else
                    do j = 1,n
                       do i = k + 1,k + n - j
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                       k = k + n - j + 1
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = k,k + j - 1
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                       k = k + j
                    end do
                 else
                    do j = 1,n
                       do i = k,k + n - j
                          sum = abs(ap(i))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                       k = k + n - j + 1
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              k = 1
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = k,k + j - 2
                          sum = sum + abs(ap(i))
                       end do
                    else
                       sum = zero
                       do i = k,k + j - 1
                          sum = sum + abs(ap(i))
                       end do
                    end if
                    k = k + j
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = k + 1,k + n - j
                          sum = sum + abs(ap(i))
                       end do
                    else
                       sum = zero
                       do i = k,k + n - j
                          sum = sum + abs(ap(i))
                       end do
                    end if
                    k = k + n - j + 1
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              k = 1
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       do i = 1,j - 1
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                       k = k + 1
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = 1,j
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,n
                       work(i) = one
                    end do
                    do j = 1,n
                       k = k + 1
                       do i = j + 1,n
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 else
                    do i = 1,n
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j,n
                          work(i) = work(i) + abs(ap(k))
                          k = k + 1
                       end do
                    end do
                 end if
              end if
              value = zero
              do i = 1,n
                 sum = work(i)
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    k = 2
                    do j = 2,n
                       call la_${ri}$lassq(j - 1,ap(k),1,scale,sum)
                       k = k + j
                    end do
                 else
                    scale = zero
                    sum = one
                    k = 1
                    do j = 1,n
                       call la_${ri}$lassq(j,ap(k),1,scale,sum)
                       k = k + j
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = n
                    k = 2
                    do j = 1,n - 1
                       call la_${ri}$lassq(n - j,ap(k),1,scale,sum)
                       k = k + n - j + 1
                    end do
                 else
                    scale = zero
                    sum = one
                    k = 1
                    do j = 1,n
                       call la_${ri}$lassq(n - j + 1,ap(k),1,scale,sum)
                       k = k + n - j + 1
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantp = value
           return
     end function la_${ri}$lantp
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
     !> ${ri.upper()}$LANTR:  returns the value of the one norm,  or the Frobenius norm, or
     !> the  infinity norm,  or the  element of  largest absolute value  of a
     !> trapezoidal or triangular matrix A.

     real(${rk}$) function la_${ri}$lantr(norm,uplo,diag,m,n,a,lda,work)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: diag,norm,uplo
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(out) :: work(*)
           complex(${rk}$),intent(in) :: a(lda,*)
       ! =====================================================================

           ! Local Scalars
           logical(lk) :: udiag
           integer(ilp) :: i,j
           real(${rk}$) :: scale,sum,value
           ! Intrinsic Functions
           intrinsic :: abs,min,sqrt
           ! Executable Statements
           if (min(m,n) == 0) then
              value = zero
           else if (la_lsame(norm,'M')) then
              ! find max(abs(a(i,j))).
              if (la_lsame(diag,'U')) then
                 value = one
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = 1,min(m,j - 1)
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = j + 1,m
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              else
                 value = zero
                 if (la_lsame(uplo,'U')) then
                    do j = 1,n
                       do i = 1,min(m,j)
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 else
                    do j = 1,n
                       do i = j,m
                          sum = abs(a(i,j))
                          if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                       end do
                    end do
                 end if
              end if
           else if ((la_lsame(norm,'O')) .or. (norm == '1')) then
              ! find norm1(a).
              value = zero
              udiag = la_lsame(diag,'U')
              if (la_lsame(uplo,'U')) then
                 do j = 1,n
                    if ((udiag) .and. (j <= m)) then
                       sum = one
                       do i = 1,j - 1
                          sum = sum + abs(a(i,j))
                       end do
                    else
                       sum = zero
                       do i = 1,min(m,j)
                          sum = sum + abs(a(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              else
                 do j = 1,n
                    if (udiag) then
                       sum = one
                       do i = j + 1,m
                          sum = sum + abs(a(i,j))
                       end do
                    else
                       sum = zero
                       do i = j,m
                          sum = sum + abs(a(i,j))
                       end do
                    end if
                    if (value < sum .or. la_${ci}$isnan(sum)) value = sum
                 end do
              end if
           else if (la_lsame(norm,'I')) then
              ! find normi(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    do i = 1,m
                       work(i) = one
                    end do
                    do j = 1,n
                       do i = 1,min(m,j - 1)
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 else
                    do i = 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = 1,min(m,j)
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    do i = 1,min(m,n)
                       work(i) = one
                    end do
                    do i = n + 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j + 1,m
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 else
                    do i = 1,m
                       work(i) = zero
                    end do
                    do j = 1,n
                       do i = j,m
                          work(i) = work(i) + abs(a(i,j))
                       end do
                    end do
                 end if
              end if
              value = zero
              do i = 1,m
                 sum = work(i)
                 if (value < sum .or. la_${ci}$isnan(sum)) value = sum
              end do
           else if ((la_lsame(norm,'F')) .or. (la_lsame(norm,'E'))) &
                     then
              ! find normf(a).
              if (la_lsame(uplo,'U')) then
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = min(m,n)
                    do j = 2,n
                       call la_${ri}$lassq(min(m,j - 1),a(1,j),1,scale,sum)
                    end do
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(min(m,j),a(1,j),1,scale,sum)
                    end do
                 end if
              else
                 if (la_lsame(diag,'U')) then
                    scale = one
                    sum = min(m,n)
                    do j = 1,n
                       call la_${ri}$lassq(m - j,a(min(m,j + 1),j),1,scale,sum)
                    end do
                 else
                    scale = zero
                    sum = one
                    do j = 1,n
                       call la_${ri}$lassq(m - j + 1,a(j,j),1,scale,sum)
                    end do
                 end if
              end if
              value = scale*sqrt(sum)
           end if
           la_${ri}$lantr = value
           return
     end function la_${ri}$lantr
#:endfor

end module la_lapack_blas_like_mnorm
