#:include "common.fypp"
!> Givens and Jacobi plane rotations
module la_lapack_givens_jacobi_rot
     use la_constants
     use la_blas_aux
     use la_lapack_auxiliary
     use la_lapack_blas_like_scalar
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$lar2v
     public :: la_${ri}$largv
     public :: la_${ri}$lartg
     public :: la_${ri}$lartgp
     public :: la_${ri}$lartv
     public :: la_${ri}$lasr
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$lacrt
     public :: la_${ri}$lar2v
     public :: la_${ri}$lartg
     public :: la_${ri}$lartv
     public :: la_${ri}$lasr
     public :: la_${ri}$largv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LAR2V: applies a vector of real plane rotations from both sides to
     !> a sequence of 2-by-2 real symmetric matrices, defined by the elements
     !> of the vectors x, y and z. For i = 1,2,...,n
     !> ( x(i)  z(i) ) := (  c(i)  s(i) ) ( x(i)  z(i) ) ( c(i) -s(i) )
     !> ( z(i)  y(i) )    ( -s(i)  c(i) ) ( z(i)  y(i) ) ( s(i)  c(i) )

     pure subroutine la_${ri}$lar2v(n,x,y,z,incx,c,s,incc)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,n
           ! Array Arguments
           real(${rk}$),intent(in) :: c(*),s(*)
           real(${rk}$),intent(inout) :: x(*),y(*),z(*)
        ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,ic,ix
           real(${rk}$) :: ci,si,t1,t2,t3,t4,t5,t6,xi,yi,zi
           ! Executable Statements
           ix = 1
           ic = 1
           do i = 1,n
              xi = x(ix)
              yi = y(ix)
              zi = z(ix)
              ci = c(ic)
              si = s(ic)
              t1 = si*zi
              t2 = ci*zi
              t3 = t2 - si*xi
              t4 = t2 + si*yi
              t5 = ci*xi + t1
              t6 = ci*yi - t1
              x(ix) = ci*t5 + si*t4
              y(ix) = ci*t6 - si*t3
              z(ix) = ci*t4 - si*t5
              ix = ix + incx
              ic = ic + incc
           end do
           return
     end subroutine la_${ri}$lar2v
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARGV: generates a vector of real plane rotations, determined by
     !> elements of the real vectors x and y. For i = 1,2,...,n
     !> (  c(i)  s(i) ) ( x(i) ) = ( a(i) )
     !> ( -s(i)  c(i) ) ( y(i) ) = (   0  )

     pure subroutine la_${ri}$largv(n,x,incx,y,incy,c,incc)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,incy,n
           ! Array Arguments
           real(${rk}$),intent(out) :: c(*)
           real(${rk}$),intent(inout) :: x(*),y(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,ic,ix,iy
           real(${rk}$) :: f,g,t,tt
           ! Intrinsic Functions
           intrinsic :: abs,sqrt
           ! Executable Statements
           ix = 1
           iy = 1
           ic = 1
           loop_10: do i = 1,n
              f = x(ix)
              g = y(iy)
              if (g == zero) then
                 c(ic) = one
              else if (f == zero) then
                 c(ic) = zero
                 y(iy) = one
                 x(ix) = g
              else if (abs(f) > abs(g)) then
                 t = g/f
                 tt = sqrt(one + t*t)
                 c(ic) = one/tt
                 y(iy) = t*c(ic)
                 x(ix) = f*tt
              else
                 t = f/g
                 tt = sqrt(one + t*t)
                 y(iy) = one/tt
                 c(ic) = t*y(iy)
                 x(ix) = g*tt
              end if
              ic = ic + incc
              iy = iy + incy
              ix = ix + incx
           end do loop_10
           return
     end subroutine la_${ri}$largv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> !
     !>
     !> ${ri.upper()}$LARTG: generates a plane rotation so that
     !> [  C  S  ]  .  [ F ]  =  [ R ]
     !> [ -S  C  ]     [ G ]     [ 0 ]
     !> where C**2 + S**2 = 1.
     !> The mathematical formulas used for C and S are
     !> R = sign(F) * sqrt(F**2 + G**2)
     !> C = F / R
     !> S = G / R
     !> Hence C >= 0. The algorithm used to compute these quantities
     !> incorporates scaling to avoid overflow or underflow in computing the
     !> square root of the sum of squares.
     !> This version is discontinuous in R at F = 0 but it returns the same
#:if rk == "sp"
     !> C and S as ${ri.upper()}$LARTG for complex inputs (F,0) and (G,0).
#:else
     !> C and S as ${ci.upper()}$LARTG for complex inputs (F,0) and (G,0).
#:endif
     !> This is a more accurate version of the BLAS1 routine ${ri.upper()}$ROTG,
     !> with the following other differences:
     !> F and G are unchanged on return.
     !> If G=0, then C=1 and S=0.
     !> If F=0 and (G .ne. 0), then C=0 and S=sign(1,G) without doing any
     !> floating point operations (saves work in ${ri.upper()}$BDSQR when
     !> there are zeros on the diagonal).
     !> If F exceeds G in magnitude, C will be positive.
     !> Below, wp=>${rk}$ stands for ${LA_PRECISION[rk]}$ precision from LA_CONSTANTS module.

     pure subroutine la_${ri}$lartg(f,g,c,s,r)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! february 2021
        ! Scalar Arguments
        real(${rk}$),intent(out) :: c,r,s
        real(${rk}$),intent(in) :: f,g
        ! Local Scalars
        real(${rk}$) :: d,f1,fs,g1,gs,p,u,uu
        ! Intrinsic Functions
        intrinsic :: abs,sign,sqrt
        ! Executable Statements
        f1 = abs(f)
        g1 = abs(g)
        if (g == zero) then
           c = one
           s = zero
           r = f
        else if (f == zero) then
           c = zero
           s = sign(one,g)
           r = g1
     else if (f1 > rtmin .and. f1 < rtmax .and. g1 > rtmin .and. g1 < rtmax) &
               then
           d = sqrt(f*f + g*g)
           p = one/d
           c = f1*p
           s = g*sign(p,f)
           r = sign(d,f)
        else
           u = min(safmax,max(safmin,f1,g1))
           uu = one/u
           fs = f*uu
           gs = g*uu
           d = sqrt(fs*fs + gs*gs)
           p = one/d
           c = abs(fs)*p
           s = gs*sign(p,f)
           r = sign(d,f)*u
        end if
        return
     end subroutine la_${ri}$lartg
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARTGP: generates a plane rotation so that
     !> [  CS  SN  ]  .  [ F ]  =  [ R ]   where CS**2 + SN**2 = 1.
     !> [ -SN  CS  ]     [ G ]     [ 0 ]
     !> This is a slower, more accurate version of the Level 1 BLAS routine ${ri.upper()}$ROTG,
     !> with the following other differences:
     !> F and G are unchanged on return.
     !> If G=0, then CS=(+/-)1 and SN=0.
     !> If F=0 and (G .ne. 0), then CS=0 and SN=(+/-)1.
     !> The sign is chosen so that R >= 0.

     pure subroutine la_${ri}$lartgp(f,g,cs,sn,r)
        use la_constants_${rk}$,only:zero,one,two
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           real(${rk}$),intent(out) :: cs,r,sn
           real(${rk}$),intent(in) :: f,g
        ! =====================================================================

           ! Local Scalars
           ! logical            first
           integer(ilp) :: count,i
           real(${rk}$) :: eps,f1,g1,safmin,safmn2,safmx2,scale
           ! Intrinsic Functions
           intrinsic :: abs,int,log,max,sign,sqrt
           ! Save Statement
           ! save               first, safmx2, safmin, safmn2
           ! Data Statements
           ! data               first / .true. /
           ! Executable Statements
           ! if( first ) then
              safmin = la_${ri}$lamch('S')
              eps = la_${ri}$lamch('E')
              safmn2 = la_${ri}$lamch('B')**int(log(safmin/eps)/log(la_${ri}$lamch('B')) &
                         /two,KIND=ilp)
              safmx2 = one/safmn2
              ! first = .false.
           ! end if
           if (g == zero) then
              cs = sign(one,f)
              sn = zero
              r = abs(f)
           else if (f == zero) then
              cs = zero
              sn = sign(one,g)
              r = abs(g)
           else
              f1 = f
              g1 = g
              scale = max(abs(f1),abs(g1))
              if (scale >= safmx2) then
                 count = 0
                 10 continue
                 count = count + 1
                 f1 = f1*safmn2
                 g1 = g1*safmn2
                 scale = max(abs(f1),abs(g1))
                 if (scale >= safmx2 .and. count < 20) go to 10
                 r = sqrt(f1**2 + g1**2)
                 cs = f1/r
                 sn = g1/r
                 do i = 1,count
                    r = r*safmx2
                 end do
              else if (scale <= safmn2) then
                 count = 0
                 30 continue
                 count = count + 1
                 f1 = f1*safmx2
                 g1 = g1*safmx2
                 scale = max(abs(f1),abs(g1))
                 if (scale <= safmn2) go to 30
                 r = sqrt(f1**2 + g1**2)
                 cs = f1/r
                 sn = g1/r
                 do i = 1,count
                    r = r*safmn2
                 end do
              else
                 r = sqrt(f1**2 + g1**2)
                 cs = f1/r
                 sn = g1/r
              end if
              if (r < zero) then
                 cs = -cs
                 sn = -sn
                 r = -r
              end if
           end if
           return
     end subroutine la_${ri}$lartgp
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARTV: applies a vector of real plane rotations to elements of the
     !> real vectors x and y. For i = 1,2,...,n
     !> ( x(i) ) := (  c(i)  s(i) ) ( x(i) )
     !> ( y(i) )    ( -s(i)  c(i) ) ( y(i) )

     pure subroutine la_${ri}$lartv(n,x,incx,y,incy,c,s,incc)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,incy,n
           ! Array Arguments
           real(${rk}$),intent(in) :: c(*),s(*)
           real(${rk}$),intent(inout) :: x(*),y(*)
        ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,ic,ix,iy
           real(${rk}$) :: xi,yi
           ! Executable Statements
           ix = 1
           iy = 1
           ic = 1
           do i = 1,n
              xi = x(ix)
              yi = y(iy)
              x(ix) = c(ic)*xi + s(ic)*yi
              y(iy) = c(ic)*yi - s(ic)*xi
              ix = ix + incx
              iy = iy + incy
              ic = ic + incc
           end do
           return
     end subroutine la_${ri}$lartv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LASR: applies a sequence of plane rotations to a real matrix A,
     !> from either the left or the right.
     !> When SIDE = 'L', the transformation takes the form
     !> A := P*A
     !> and when SIDE = 'R', the transformation takes the form
     !> A := A*P**T
     !> where P is an orthogonal matrix consisting of a sequence of z plane
     !> rotations, with z = M when SIDE = 'L' and z = N when SIDE = 'R',
     !> and P**T is the transpose of P.
     !> When DIRECT = 'F' (Forward sequence), then
     !> P = P(z-1) * ... * P(2) * P(1)
     !> and when DIRECT = 'B' (Backward sequence), then
     !> P = P(1) * P(2) * ... * P(z-1)
     !> where P(k) is a plane rotation matrix defined by the 2-by-2 rotation
     !> R(k) = (  c(k)  s(k) )
     !> = ( -s(k)  c(k) ).
     !> When PIVOT = 'V' (Variable pivot), the rotation is performed
     !> for the plane (k,k+1), i.e., P(k) has the form
     !> P(k) = (  1                                            )
     !> (       ...                                     )
     !> (              1                                )
     !> (                   c(k)  s(k)                  )
     !> (                  -s(k)  c(k)                  )
     !> (                                1              )
     !> (                                     ...       )
     !> (                                            1  )
     !> where R(k) appears as a rank-2 modification to the identity matrix in
     !> rows and columns k and k+1.
     !> When PIVOT = 'T' (Top pivot), the rotation is performed for the
     !> plane (1,k+1), so P(k) has the form
     !> P(k) = (  c(k)                    s(k)                 )
     !> (         1                                     )
     !> (              ...                              )
     !> (                     1                         )
     !> ( -s(k)                    c(k)                 )
     !> (                                 1             )
     !> (                                      ...      )
     !> (                                             1 )
     !> where R(k) appears in rows and columns 1 and k+1.
     !> Similarly, when PIVOT = 'B' (Bottom pivot), the rotation is
     !> performed for the plane (k,z), giving P(k) the form
     !> P(k) = ( 1                                             )
     !> (      ...                                      )
     !> (             1                                 )
     !> (                  c(k)                    s(k) )
     !> (                         1                     )
     !> (                              ...              )
     !> (                                     1         )
     !> (                 -s(k)                    c(k) )
     !> where R(k) appears in rows and columns k and z.  The rotations are
     !> performed without ever forming P(k) explicitly.

     pure subroutine la_${ri}$lasr(side,pivot,direct,m,n,c,s,a,lda)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,pivot,side
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(inout) :: a(lda,*)
           real(${rk}$),intent(in) :: c(*),s(*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,info,j
           real(${rk}$) :: ctemp,stemp,temp
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters
           info = 0
           if (.not. (la_lsame(side,'L') .or. la_lsame(side,'R'))) then
              info = 1
           else if (.not. (la_lsame(pivot,'V') .or. la_lsame(pivot,'T') .or. &
                     la_lsame(pivot,'B'))) then
              info = 2
           else if (.not. (la_lsame(direct,'F') .or. la_lsame(direct,'B'))) &
                     then
              info = 3
           else if (m < 0) then
              info = 4
           else if (n < 0) then
              info = 5
           else if (lda < max(1,m)) then
              info = 9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASR ',info)
              return
           end if
           ! quick return if possible
           if ((m == 0) .or. (n == 0)) return
           if (la_lsame(side,'L')) then
              ! form  p * a
              if (la_lsame(pivot,'V')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,m - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j + 1,i)
                             a(j + 1,i) = ctemp*temp - stemp*a(j,i)
                             a(j,i) = stemp*temp + ctemp*a(j,i)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j + 1,i)
                             a(j + 1,i) = ctemp*temp - stemp*a(j,i)
                             a(j,i) = stemp*temp + ctemp*a(j,i)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'T')) then
                 if (la_lsame(direct,'F')) then
                    do j = 2,m
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = ctemp*temp - stemp*a(1,i)
                             a(1,i) = stemp*temp + ctemp*a(1,i)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m,2,-1
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = ctemp*temp - stemp*a(1,i)
                             a(1,i) = stemp*temp + ctemp*a(1,i)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'B')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,m - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = stemp*a(m,i) + ctemp*temp
                             a(m,i) = ctemp*a(m,i) - stemp*temp
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = stemp*a(m,i) + ctemp*temp
                             a(m,i) = ctemp*a(m,i) - stemp*temp
                          end do
                       end if
                    end do
                 end if
              end if
           else if (la_lsame(side,'R')) then
              ! form a * p**t
              if (la_lsame(pivot,'V')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,n - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j + 1)
                             a(i,j + 1) = ctemp*temp - stemp*a(i,j)
                             a(i,j) = stemp*temp + ctemp*a(i,j)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j + 1)
                             a(i,j + 1) = ctemp*temp - stemp*a(i,j)
                             a(i,j) = stemp*temp + ctemp*a(i,j)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'T')) then
                 if (la_lsame(direct,'F')) then
                    do j = 2,n
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = ctemp*temp - stemp*a(i,1)
                             a(i,1) = stemp*temp + ctemp*a(i,1)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n,2,-1
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = ctemp*temp - stemp*a(i,1)
                             a(i,1) = stemp*temp + ctemp*a(i,1)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'B')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,n - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = stemp*a(i,n) + ctemp*temp
                             a(i,n) = ctemp*a(i,n) - stemp*temp
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = stemp*a(i,n) + ctemp*temp
                             a(i,n) = ctemp*a(i,n) - stemp*temp
                          end do
                       end if
                    end do
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$lasr
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LACRT: performs the operation
     !> (  c  s )( x )  ==> ( x )
     !> ( -s  c )( y )      ( y )
     !> where c and s are complex and the vectors x and y are complex.

     pure subroutine la_${ri}$lacrt(n,cx,incx,cy,incy,c,s)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incx,incy,n
           complex(${rk}$),intent(in) :: c,s
           ! Array Arguments
           complex(${rk}$),intent(inout) :: cx(*),cy(*)
       ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,ix,iy
           complex(${rk}$) :: ctemp
           ! Executable Statements
           if (n <= 0) return
           if (incx == 1 .and. incy == 1) go to 20
           ! code for unequal increments or equal increments not equal to 1
           ix = 1
           iy = 1
           if (incx < 0) ix = (-n + 1)*incx + 1
           if (incy < 0) iy = (-n + 1)*incy + 1
           do i = 1,n
              ctemp = c*cx(ix) + s*cy(iy)
              cy(iy) = c*cy(iy) - s*cx(ix)
              cx(ix) = ctemp
              ix = ix + incx
              iy = iy + incy
           end do
           return
           ! code for both increments equal to 1
           20 continue
           do i = 1,n
              ctemp = c*cx(i) + s*cy(i)
              cy(i) = c*cy(i) - s*cx(i)
              cx(i) = ctemp
           end do
           return
     end subroutine la_${ri}$lacrt
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LAR2V: applies a vector of complex plane rotations with real cosines
     !> from both sides to a sequence of 2-by-2 complex Hermitian matrices,
     !> defined by the elements of the vectors x, y and z. For i = 1,2,...,n
     !> (       x(i)  z(i) ) :=
     !> ( conjg(z(i)) y(i) )
     !> (  c(i) conjg(s(i)) ) (       x(i)  z(i) ) ( c(i) -conjg(s(i)) )
     !> ( -s(i)       c(i)  ) ( conjg(z(i)) y(i) ) ( s(i)        c(i)  )

     pure subroutine la_${ri}$lar2v(n,x,y,z,incx,c,s,incc)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,n
           ! Array Arguments
           real(${rk}$),intent(in) :: c(*)
           complex(${rk}$),intent(in) :: s(*)
           complex(${rk}$),intent(inout) :: x(*),y(*),z(*)
        ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,ic,ix
           real(${rk}$) :: ci,sii,sir,t1i,t1r,t5,t6,xi,yi,zii,zir
           complex(${rk}$) :: si,t2,t3,t4,zi
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: aimag,cmplx,conjg,real
#:else
           intrinsic :: real,cmplx,conjg,aimag
#:endif
           ! Executable Statements
           ix = 1
           ic = 1
           do i = 1,n
              xi = real(x(ix),KIND=${rk}$)
              yi = real(y(ix),KIND=${rk}$)
              zi = z(ix)
              zir = real(zi,KIND=${rk}$)
              zii = aimag(zi)
              ci = c(ic)
              si = s(ic)
              sir = real(si,KIND=${rk}$)
              sii = aimag(si)
              t1r = sir*zir - sii*zii
              t1i = sir*zii + sii*zir
              t2 = ci*zi
              t3 = t2 - conjg(si)*xi
              t4 = conjg(t2) + si*yi
              t5 = ci*xi + t1r
              t6 = ci*yi - t1r
              x(ix) = ci*t5 + (sir*real(t4,KIND=${rk}$) + sii*aimag(t4))
              y(ix) = ci*t6 - (sir*real(t3,KIND=${rk}$) - sii*aimag(t3))
              z(ix) = ci*t3 + conjg(si)*cmplx(t6,t1i,KIND=${rk}$)
              ix = ix + incx
              ic = ic + incc
           end do
           return
     end subroutine la_${ri}$lar2v
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> !
     !>
     !> ${ri.upper()}$LARTG: generates a plane rotation so that
     !> [  C         S  ] . [ F ]  =  [ R ]
     !> [ -conjg(S)  C  ]   [ G ]     [ 0 ]
     !> where C is real and C**2 + |S|**2 = 1.
     !> The mathematical formulas used for C and S are
     !> sgn(x) = {  x / |x|,   x != 0
     !> {  1,         x = 0
     !> R = sgn(F) * sqrt(|F|**2 + |G|**2)
     !> C = |F| / sqrt(|F|**2 + |G|**2)
     !> S = sgn(F) * conjg(G) / sqrt(|F|**2 + |G|**2)
     !> When F and G are real, the formulas simplify to C = F/R and
     !> S = G/R, and the returned values of C, S, and R should be
#:if rk == "sp"
     !> identical to those returned by ${ri.upper()}$LARTG.
#:else
     !> identical to those returned by ${ci.upper()}$LARTG.
#:endif
     !> The algorithm used to compute these quantities incorporates scaling
     !> to avoid overflow or underflow in computing the square root of the
     !> sum of squares.
     !> This is a faster version of the BLAS1 routine ${ri.upper()}$ROTG, except for
     !> the following differences:
     !> F and G are unchanged on return.
     !> If G=0, then C=1 and S=0.
     !> If F=0, then C=0 and S is chosen so that R is real.
     !> Below, wp=>${rk}$ stands for ${LA_PRECISION[rk]}$ precision from LA_CONSTANTS module.

     pure subroutine la_${ri}$lartg(f,g,c,s,r)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! february 2021
        ! Scalar Arguments
        real(${rk}$),intent(out) :: c
        complex(${rk}$),intent(in) :: f,g
        complex(${rk}$),intent(out) :: r,s
        ! Local Scalars
        real(${rk}$) :: d,f1,f2,g1,g2,h2,p,u,uu,v,vv,w
        complex(${rk}$) :: fs,gs,t
        ! Intrinsic Functions
        intrinsic :: abs,aimag,conjg,max,min,real,sqrt
        ! Statement Functions
        real(${rk}$) :: abssq
        ! Statement Function Definitions
        abssq(t) = real(t,KIND=${rk}$)**2 + aimag(t)**2
        ! Executable Statements
        if (g == czero) then
           c = one
           s = czero
           r = f
        else if (f == czero) then
           c = zero
           g1 = max(abs(real(g,KIND=${rk}$)),abs(aimag(g)))
           if (g1 > rtmin .and. g1 < rtmax) then
              ! use unscaled algorithm
              g2 = abssq(g)
              d = sqrt(g2)
              s = conjg(g)/d
              r = d
           else
              ! use scaled algorithm
              u = min(safmax,max(safmin,g1))
              uu = one/u
              gs = g*uu
              g2 = abssq(gs)
              d = sqrt(g2)
              s = conjg(gs)/d
              r = d*u
           end if
        else
           f1 = max(abs(real(f,KIND=${rk}$)),abs(aimag(f)))
           g1 = max(abs(real(g,KIND=${rk}$)),abs(aimag(g)))
     if (f1 > rtmin .and. f1 < rtmax .and. g1 > rtmin .and. g1 < rtmax) then
              ! use unscaled algorithm
              f2 = abssq(f)
              g2 = abssq(g)
              h2 = f2 + g2
              if (f2 > rtmin .and. h2 < rtmax) then
                 d = sqrt(f2*h2)
              else
                 d = sqrt(f2)*sqrt(h2)
              end if
              p = 1/d
              c = f2*p
              s = conjg(g)*(f*p)
              r = f*(h2*p)
           else
              ! use scaled algorithm
              u = min(safmax,max(safmin,f1,g1))
              uu = one/u
              gs = g*uu
              g2 = abssq(gs)
              if (f1*uu < rtmin) then
                 ! f is not well-scaled when scaled by g1.
                 ! use a different scaling for f.
                 v = min(safmax,max(safmin,f1))
                 vv = one/v
                 w = v*uu
                 fs = f*vv
                 f2 = abssq(fs)
                 h2 = f2*w**2 + g2
              else
                 ! otherwise use the same scaling for f and g.
                 w = one
                 fs = f*uu
                 f2 = abssq(fs)
                 h2 = f2 + g2
              end if
              if (f2 > rtmin .and. h2 < rtmax) then
                 d = sqrt(f2*h2)
              else
                 d = sqrt(f2)*sqrt(h2)
              end if
              p = 1/d
              c = (f2*p)*w
              s = conjg(gs)*(fs*p)
              r = (fs*(h2*p))*u
           end if
        end if
        return
     end subroutine la_${ri}$lartg
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARTV: applies a vector of complex plane rotations with real cosines
     !> to elements of the complex vectors x and y. For i = 1,2,...,n
     !> ( x(i) ) := (        c(i)   s(i) ) ( x(i) )
     !> ( y(i) )    ( -conjg(s(i))  c(i) ) ( y(i) )

     pure subroutine la_${ri}$lartv(n,x,incx,y,incy,c,s,incc)
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,incy,n
           ! Array Arguments
           real(${rk}$),intent(in) :: c(*)
           complex(${rk}$),intent(in) :: s(*)
           complex(${rk}$),intent(inout) :: x(*),y(*)
        ! =====================================================================
           ! Local Scalars
           integer(ilp) :: i,ic,ix,iy
           complex(${rk}$) :: xi,yi
           ! Intrinsic Functions
           intrinsic :: conjg
           ! Executable Statements
           ix = 1
           iy = 1
           ic = 1
           do i = 1,n
              xi = x(ix)
              yi = y(iy)
              x(ix) = c(ic)*xi + s(ic)*yi
              y(iy) = c(ic)*yi - conjg(s(ic))*xi
              ix = ix + incx
              iy = iy + incy
              ic = ic + incc
           end do
           return
     end subroutine la_${ri}$lartv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LASR: applies a sequence of real plane rotations to a complex matrix
     !> A, from either the left or the right.
     !> When SIDE = 'L', the transformation takes the form
     !> A := P*A
     !> and when SIDE = 'R', the transformation takes the form
     !> A := A*P**T
     !> where P is an orthogonal matrix consisting of a sequence of z plane
     !> rotations, with z = M when SIDE = 'L' and z = N when SIDE = 'R',
     !> and P**T is the transpose of P.
     !> When DIRECT = 'F' (Forward sequence), then
     !> P = P(z-1) * ... * P(2) * P(1)
     !> and when DIRECT = 'B' (Backward sequence), then
     !> P = P(1) * P(2) * ... * P(z-1)
     !> where P(k) is a plane rotation matrix defined by the 2-by-2 rotation
     !> R(k) = (  c(k)  s(k) )
     !> = ( -s(k)  c(k) ).
     !> When PIVOT = 'V' (Variable pivot), the rotation is performed
     !> for the plane (k,k+1), i.e., P(k) has the form
     !> P(k) = (  1                                            )
     !> (       ...                                     )
     !> (              1                                )
     !> (                   c(k)  s(k)                  )
     !> (                  -s(k)  c(k)                  )
     !> (                                1              )
     !> (                                     ...       )
     !> (                                            1  )
     !> where R(k) appears as a rank-2 modification to the identity matrix in
     !> rows and columns k and k+1.
     !> When PIVOT = 'T' (Top pivot), the rotation is performed for the
     !> plane (1,k+1), so P(k) has the form
     !> P(k) = (  c(k)                    s(k)                 )
     !> (         1                                     )
     !> (              ...                              )
     !> (                     1                         )
     !> ( -s(k)                    c(k)                 )
     !> (                                 1             )
     !> (                                      ...      )
     !> (                                             1 )
     !> where R(k) appears in rows and columns 1 and k+1.
     !> Similarly, when PIVOT = 'B' (Bottom pivot), the rotation is
     !> performed for the plane (k,z), giving P(k) the form
     !> P(k) = ( 1                                             )
     !> (      ...                                      )
     !> (             1                                 )
     !> (                  c(k)                    s(k) )
     !> (                         1                     )
     !> (                              ...              )
     !> (                                     1         )
     !> (                 -s(k)                    c(k) )
     !> where R(k) appears in rows and columns k and z.  The rotations are
     !> performed without ever forming P(k) explicitly.

     pure subroutine la_${ri}$lasr(side,pivot,direct,m,n,c,s,a,lda)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: direct,pivot,side
           integer(ilp),intent(in) :: lda,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: c(*),s(*)
           complex(${rk}$),intent(inout) :: a(lda,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,info,j
           real(${rk}$) :: ctemp,stemp
           complex(${rk}$) :: temp
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters
           info = 0
           if (.not. (la_lsame(side,'L') .or. la_lsame(side,'R'))) then
              info = 1
           else if (.not. (la_lsame(pivot,'V') .or. la_lsame(pivot,'T') .or. &
                     la_lsame(pivot,'B'))) then
              info = 2
           else if (.not. (la_lsame(direct,'F') .or. la_lsame(direct,'B'))) &
                     then
              info = 3
           else if (m < 0) then
              info = 4
           else if (n < 0) then
              info = 5
           else if (lda < max(1,m)) then
              info = 9
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$LASR ',info)
              return
           end if
           ! quick return if possible
           if ((m == 0) .or. (n == 0)) return
           if (la_lsame(side,'L')) then
              ! form  p * a
              if (la_lsame(pivot,'V')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,m - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j + 1,i)
                             a(j + 1,i) = ctemp*temp - stemp*a(j,i)
                             a(j,i) = stemp*temp + ctemp*a(j,i)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j + 1,i)
                             a(j + 1,i) = ctemp*temp - stemp*a(j,i)
                             a(j,i) = stemp*temp + ctemp*a(j,i)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'T')) then
                 if (la_lsame(direct,'F')) then
                    do j = 2,m
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = ctemp*temp - stemp*a(1,i)
                             a(1,i) = stemp*temp + ctemp*a(1,i)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m,2,-1
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = ctemp*temp - stemp*a(1,i)
                             a(1,i) = stemp*temp + ctemp*a(1,i)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'B')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,m - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = stemp*a(m,i) + ctemp*temp
                             a(m,i) = ctemp*a(m,i) - stemp*temp
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = m - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,n
                             temp = a(j,i)
                             a(j,i) = stemp*a(m,i) + ctemp*temp
                             a(m,i) = ctemp*a(m,i) - stemp*temp
                          end do
                       end if
                    end do
                 end if
              end if
           else if (la_lsame(side,'R')) then
              ! form a * p**t
              if (la_lsame(pivot,'V')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,n - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j + 1)
                             a(i,j + 1) = ctemp*temp - stemp*a(i,j)
                             a(i,j) = stemp*temp + ctemp*a(i,j)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j + 1)
                             a(i,j + 1) = ctemp*temp - stemp*a(i,j)
                             a(i,j) = stemp*temp + ctemp*a(i,j)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'T')) then
                 if (la_lsame(direct,'F')) then
                    do j = 2,n
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = ctemp*temp - stemp*a(i,1)
                             a(i,1) = stemp*temp + ctemp*a(i,1)
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n,2,-1
                       ctemp = c(j - 1)
                       stemp = s(j - 1)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = ctemp*temp - stemp*a(i,1)
                             a(i,1) = stemp*temp + ctemp*a(i,1)
                          end do
                       end if
                    end do
                 end if
              else if (la_lsame(pivot,'B')) then
                 if (la_lsame(direct,'F')) then
                    do j = 1,n - 1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = stemp*a(i,n) + ctemp*temp
                             a(i,n) = ctemp*a(i,n) - stemp*temp
                          end do
                       end if
                    end do
                 else if (la_lsame(direct,'B')) then
                    do j = n - 1,1,-1
                       ctemp = c(j)
                       stemp = s(j)
                       if ((ctemp /= one) .or. (stemp /= zero)) then
                          do i = 1,m
                             temp = a(i,j)
                             a(i,j) = stemp*a(i,n) + ctemp*temp
                             a(i,n) = ctemp*a(i,n) - stemp*temp
                          end do
                       end if
                    end do
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$lasr
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARGV: generates a vector of complex plane rotations with real
     !> cosines, determined by elements of the complex vectors x and y.
     !> For i = 1,2,...,n
     !> (        c(i)   s(i) ) ( x(i) ) = ( r(i) )
     !> ( -conjg(s(i))  c(i) ) ( y(i) ) = (   0  )
     !> where c(i)**2 + ABS(s(i))**2 = 1
     !> The following conventions are used (these are the same as in ${ri.upper()}$LARTG,
     !> but differ from the BLAS1 routine ${ri.upper()}$ROTG):
     !> If y(i)=0, then c(i)=1 and s(i)=0.
     !> If x(i)=0, then c(i)=0 and s(i) is chosen so that r(i) is real.

     pure subroutine la_${ri}$largv(n,x,incx,y,incy,c,incc)
        use la_constants_${rk}$,only:zero,one,two,czero
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: incc,incx,incy,n
           ! Array Arguments
           real(${rk}$),intent(out) :: c(*)
           complex(${rk}$),intent(inout) :: x(*),y(*)
        ! =====================================================================

           ! Local Scalars
           ! logical            first
           integer(ilp) :: count,i,ic,ix,iy,j
           real(${rk}$) :: cs,d,di,dr,eps,f2,f2s,g2,g2s,safmin,safmn2,safmx2,scale
           complex(${rk}$) :: f,ff,fs,g,gs,r,sn
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: abs,aimag,cmplx,conjg,int,log,max,real,sqrt
#:else
           intrinsic :: abs,real,cmplx,conjg,aimag,int,log,max,sqrt
#:endif
           ! Statement Functions
           real(${rk}$) :: abs1,abssq
           ! Save Statement
           ! save               first, safmx2, safmin, safmn2
           ! Data Statements
           ! data               first / .true. /
           ! Statement Function Definitions
           abs1(ff) = max(abs(real(ff,KIND=${rk}$)),abs(aimag(ff)))
           abssq(ff) = real(ff,KIND=${rk}$)**2 + aimag(ff)**2
           ! Executable Statements
           ! if( first ) then
              ! first = .false.
              safmin = la_${ci}$lamch('S')
              eps = la_${ci}$lamch('E')
              safmn2 = la_${ci}$lamch('B')**int(log(safmin/eps)/log(la_${ci}$lamch('B')) &
                         /two,KIND=ilp)
              safmx2 = one/safmn2
           ! end if
           ix = 1
           iy = 1
           ic = 1
           loop_60: do i = 1,n
              f = x(ix)
              g = y(iy)
              ! use identical algorithm as in la_${ri}$lartg
              scale = max(abs1(f),abs1(g))
              fs = f
              gs = g
              count = 0
              if (scale >= safmx2) then
              10 continue
                 count = count + 1
                 fs = fs*safmn2
                 gs = gs*safmn2
                 scale = scale*safmn2
                 if (scale >= safmx2 .and. count < 20) go to 10
              else if (scale <= safmn2) then
                 if (g == czero) then
                    cs = one
                    sn = czero
                    r = f
                    go to 50
                 end if
                 20 continue
                 count = count - 1
                 fs = fs*safmx2
                 gs = gs*safmx2
                 scale = scale*safmx2
                 if (scale <= safmn2) go to 20
              end if
              f2 = abssq(fs)
              g2 = abssq(gs)
              if (f2 <= max(g2,one)*safmin) then
                 ! this is a rare case: f is very small.
                 if (f == czero) then
                    cs = zero
                    r = la_${ci}$lapy2(real(g,KIND=${rk}$),aimag(g))
                    ! do complex/real division explicitly with two real
                    ! divisions
                    d = la_${ci}$lapy2(real(gs,KIND=${rk}$),aimag(gs))
                    sn = cmplx(real(gs,KIND=${rk}$)/d,-aimag(gs)/d,KIND=${rk}$)
                    go to 50
                 end if
                 f2s = la_${ci}$lapy2(real(fs,KIND=${rk}$),aimag(fs))
                 ! g2 and g2s are accurate
                 ! g2 is at least safmin, and g2s is at least safmn2
                 g2s = sqrt(g2)
                 ! error in cs from underflow in f2s is at most
                 ! unfl / safmn2 .lt. sqrt(unfl*eps) .lt. eps
                 ! if max(g2,one)=g2, then f2 .lt. g2*safmin,
                 ! and so cs .lt. sqrt(safmin)
                 ! if max(g2,one)=one, then f2 .lt. safmin
                 ! and so cs .lt. sqrt(safmin)/safmn2 = sqrt(eps)
                 ! therefore, cs = f2s/g2s / sqrt( 1 + (f2s/g2s)**2 ) = f2s/g2s
                 cs = f2s/g2s
                 ! make sure abs(ff) = 1
                 ! do complex/real division explicitly with 2 real divisions
                 if (abs1(f) > one) then
                    d = la_${ci}$lapy2(real(f,KIND=${rk}$),aimag(f))
                    ff = cmplx(real(f,KIND=${rk}$)/d,aimag(f)/d,KIND=${rk}$)
                 else
                    dr = safmx2*real(f,KIND=${rk}$)
                    di = safmx2*aimag(f)
                    d = la_${ci}$lapy2(dr,di)
                    ff = cmplx(dr/d,di/d,KIND=${rk}$)
                 end if
                 sn = ff*cmplx(real(gs,KIND=${rk}$)/g2s,-aimag(gs)/g2s,KIND=${rk}$)
                 r = cs*f + sn*g
              else
                 ! this is the most common case.
                 ! neither f2 nor f2/g2 are less than safmin
                 ! f2s cannot overflow, and it is accurate
                 f2s = sqrt(one + g2/f2)
                 ! do the f2s(real)*fs(complex) multiply with two real
                 ! multiplies
                 r = cmplx(f2s*real(fs,KIND=${rk}$),f2s*aimag(fs),KIND=${rk}$)
                 cs = one/f2s
                 d = f2 + g2
                 ! do complex/real division explicitly with two real divisions
                 sn = cmplx(real(r,KIND=${rk}$)/d,aimag(r)/d,KIND=${rk}$)
                 sn = sn*conjg(gs)
                 if (count /= 0) then
                    if (count > 0) then
                       do j = 1,count
                          r = r*safmx2
                       end do
                    else
                       do j = 1,-count
                          r = r*safmn2
                       end do
                    end if
                 end if
              end if
              50 continue
              c(ic) = cs
              y(iy) = sn
              x(ix) = r
              ic = ic + incc
              iy = iy + incy
              ix = ix + incx
           end do loop_60
           return
     end subroutine la_${ri}$largv
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

end module la_lapack_givens_jacobi_rot
