#:include "common.fypp"
!> BLAS-like level 3: rank-k updates and solves in RFP storage
module la_lapack_blas_like_l3
     use la_constants
     use la_blas_aux
     use la_blas_level3_gen
     use la_blas_level3_sym
     use la_blas_level3_tri
     implicit none(type,external)
     private

     public :: sp,dp,qp,lk,ilp
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$lagtm
     public :: la_${ri}$sfrk
     public :: la_${ri}$tfsm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor
#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     public :: la_${ri}$hfrk
     public :: la_${ri}$lacrm
     public :: la_${ri}$lagtm
     public :: la_${ri}$larcm
     public :: la_${ri}$tfsm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

     contains

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LAGTM: performs a matrix-vector product of the form
     !> B := alpha * A * X + beta * B
     !> where A is a tridiagonal matrix of order N, B and X are N by NRHS
     !> matrices, and alpha and beta are real scalars, each of which may be
     !> 0., 1., or -1.

     pure subroutine la_${ri}$lagtm(trans,n,nrhs,alpha,dl,d,du,x,ldx,beta,b,ldb)
        use la_constants_${rk}$

        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: trans
           integer(ilp),intent(in) :: ldb,ldx,n,nrhs
           real(${rk}$),intent(in) :: alpha,beta
           ! Array Arguments
           real(${rk}$),intent(inout) :: b(ldb,*)
           real(${rk}$),intent(in) :: d(*),dl(*),du(*),x(ldx,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           ! Executable Statements
           if (n == 0) return
           ! multiply b by beta if beta/=1.
           if (beta == zero) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = zero
                 end do
              end do
           else if (beta == -one) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = -b(i,j)
                 end do
              end do
           end if
           if (alpha == one) then
              if (la_lsame(trans,'N')) then
                 ! compute b := b + a*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) + d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) + d(1)*x(1,j) + du(1)*x(2,j)
                       b(n,j) = b(n,j) + dl(n - 1)*x(n - 1,j) + d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) + dl(i - 1)*x(i - 1,j) + d(i)*x(i,j) + du(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else
                 ! compute b := b + a**t*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) + d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) + d(1)*x(1,j) + dl(1)*x(2,j)
                       b(n,j) = b(n,j) + du(n - 1)*x(n - 1,j) + d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) + du(i - 1)*x(i - 1,j) + d(i)*x(i,j) + dl(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              end if
           else if (alpha == -one) then
              if (la_lsame(trans,'N')) then
                 ! compute b := b - a*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) - d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) - d(1)*x(1,j) - du(1)*x(2,j)
                       b(n,j) = b(n,j) - dl(n - 1)*x(n - 1,j) - d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) - dl(i - 1)*x(i - 1,j) - d(i)*x(i,j) - du(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else
                 ! compute b := b - a**t*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) - d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) - d(1)*x(1,j) - dl(1)*x(2,j)
                       b(n,j) = b(n,j) - du(n - 1)*x(n - 1,j) - d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) - du(i - 1)*x(i - 1,j) - d(i)*x(i,j) - dl(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              end if
           end if
           return
     end subroutine la_${ri}$lagtm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> Level 3 BLAS like routine for C in RFP Format.
     !> ${ri.upper()}$SFRK: performs one of the symmetric rank--k operations
     !> C := alpha*A*A**T + beta*C,
     !> or
     !> C := alpha*A**T*A + beta*C,
     !> where alpha and beta are real scalars, C is an n--by--n symmetric
     !> matrix and A is an n--by--k matrix in the first case and a k--by--n
     !> matrix in the second case.

     pure subroutine la_${ri}$sfrk(transr,uplo,trans,n,k,alpha,a,lda,beta,c)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           real(${rk}$),intent(in) :: alpha,beta
           integer(ilp),intent(in) :: k,lda,n
           character,intent(in) :: trans,transr,uplo
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(inout) :: c(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lower,normaltransr,nisodd,notrans
           integer(ilp) :: info,nrowa,j,nk,n1,n2
           ! Intrinsic Functions
           intrinsic :: max
           ! Executable Statements
           ! test the input parameters.
           info = 0
           normaltransr = la_lsame(transr,'N')
           lower = la_lsame(uplo,'L')
           notrans = la_lsame(trans,'N')
           if (notrans) then
              nrowa = n
           else
              nrowa = k
           end if
           if (.not. normaltransr .and. .not. la_lsame(transr,'T')) then
              info = -1
           else if (.not. lower .and. .not. la_lsame(uplo,'U')) then
              info = -2
           else if (.not. notrans .and. .not. la_lsame(trans,'T')) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0) then
              info = -5
           else if (lda < max(1,nrowa)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$SFRK ',-info)
              return
           end if
           ! quick return if possible.
           ! the quick return case: ((alpha==0).and.(beta/=zero)) is not
           ! done (it is in la_${ri}$syrk for example) and left in the general case.
           if ((n == 0) .or. (((alpha == zero) .or. (k == 0)) .and. (beta == one))) &
                     return
           if ((alpha == zero) .and. (beta == zero)) then
              do j = 1, ((n*(n + 1))/2)
                 c(j) = zero
              end do
              return
           end if
           ! c is n-by-n.
           ! if n is odd, set nisodd = .true., and n1 and n2.
           ! if n is even, nisodd = .false., and nk.
           if (mod(n,2) == 0) then
              nisodd = .false.
              nk = n/2
           else
              nisodd = .true.
              if (lower) then
                 n2 = n/2
                 n1 = n - n2
              else
                 n1 = n/2
                 n2 = n - n1
              end if
           end if
           if (nisodd) then
              ! n is odd
              if (normaltransr) then
                 ! n is odd and transr = 'n'
                 if (lower) then
                    ! n is odd, transr = 'n', and uplo = 'l'
                    if (notrans) then
                       ! n is odd, transr = 'n', uplo = 'l', and trans = 'n'
                       call la_${ri}$syrk('L','N',n1,k,alpha,a(1,1),lda,beta,c(1),n)

                       call la_${ri}$syrk('U','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c(n + 1) &
                                 ,n)
                       call la_${ri}$gemm('N','T',n2,n1,k,alpha,a(n1 + 1,1),lda,a(1,1), &
                                  lda,beta,c(n1 + 1),n)
                    else
                       ! n is odd, transr = 'n', uplo = 'l', and trans = 't'
                       call la_${ri}$syrk('L','T',n1,k,alpha,a(1,1),lda,beta,c(1),n)

                       call la_${ri}$syrk('U','T',n2,k,alpha,a(1,n1 + 1),lda,beta,c(n + 1) &
                                 ,n)
                       call la_${ri}$gemm('T','N',n2,n1,k,alpha,a(1,n1 + 1),lda,a(1,1), &
                                  lda,beta,c(n1 + 1),n)
                    end if
                 else
                    ! n is odd, transr = 'n', and uplo = 'u'
                    if (notrans) then
                       ! n is odd, transr = 'n', uplo = 'u', and trans = 'n'
                       call la_${ri}$syrk('L','N',n1,k,alpha,a(1,1),lda,beta,c(n2 + 1), &
                                 n)
                       call la_${ri}$syrk('U','N',n2,k,alpha,a(n2,1),lda,beta,c(n1 + 1), &
                                  n)
                       call la_${ri}$gemm('N','T',n1,n2,k,alpha,a(1,1),lda,a(n2,1), &
                                 lda,beta,c(1),n)
                    else
                       ! n is odd, transr = 'n', uplo = 'u', and trans = 't'
                       call la_${ri}$syrk('L','T',n1,k,alpha,a(1,1),lda,beta,c(n2 + 1), &
                                 n)
                       call la_${ri}$syrk('U','T',n2,k,alpha,a(1,n2),lda,beta,c(n1 + 1), &
                                  n)
                       call la_${ri}$gemm('T','N',n1,n2,k,alpha,a(1,1),lda,a(1,n2), &
                                 lda,beta,c(1),n)
                    end if
                 end if
              else
                 ! n is odd, and transr = 't'
                 if (lower) then
                    ! n is odd, transr = 't', and uplo = 'l'
                    if (notrans) then
                       ! n is odd, transr = 't', uplo = 'l', and trans = 'n'
                       call la_${ri}$syrk('U','N',n1,k,alpha,a(1,1),lda,beta,c(1),n1 &
                                 )
                       call la_${ri}$syrk('L','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c(2), &
                                 n1)
                       call la_${ri}$gemm('N','T',n1,n2,k,alpha,a(1,1),lda,a(n1 + 1,1), &
                                  lda,beta,c(n1*n1 + 1),n1)
                    else
                       ! n is odd, transr = 't', uplo = 'l', and trans = 't'
                       call la_${ri}$syrk('U','T',n1,k,alpha,a(1,1),lda,beta,c(1),n1 &
                                 )
                       call la_${ri}$syrk('L','T',n2,k,alpha,a(1,n1 + 1),lda,beta,c(2), &
                                 n1)
                       call la_${ri}$gemm('T','N',n1,n2,k,alpha,a(1,1),lda,a(1,n1 + 1), &
                                  lda,beta,c(n1*n1 + 1),n1)
                    end if
                 else
                    ! n is odd, transr = 't', and uplo = 'u'
                    if (notrans) then
                       ! n is odd, transr = 't', uplo = 'u', and trans = 'n'
                       call la_${ri}$syrk('U','N',n1,k,alpha,a(1,1),lda,beta,c(n2*n2 + 1 &
                                 ),n2)
                       call la_${ri}$syrk('L','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c( &
                                 n1*n2 + 1),n2)
                       call la_${ri}$gemm('N','T',n2,n1,k,alpha,a(n1 + 1,1),lda,a(1,1), &
                                  lda,beta,c(1),n2)
                    else
                       ! n is odd, transr = 't', uplo = 'u', and trans = 't'
                       call la_${ri}$syrk('U','T',n1,k,alpha,a(1,1),lda,beta,c(n2*n2 + 1 &
                                 ),n2)
                       call la_${ri}$syrk('L','T',n2,k,alpha,a(1,n1 + 1),lda,beta,c( &
                                 n1*n2 + 1),n2)
                       call la_${ri}$gemm('T','N',n2,n1,k,alpha,a(1,n1 + 1),lda,a(1,1), &
                                  lda,beta,c(1),n2)
                    end if
                 end if
              end if
           else
              ! n is even
              if (normaltransr) then
                 ! n is even and transr = 'n'
                 if (lower) then
                    ! n is even, transr = 'n', and uplo = 'l'
                    if (notrans) then
                       ! n is even, transr = 'n', uplo = 'l', and trans = 'n'
                       call la_${ri}$syrk('L','N',nk,k,alpha,a(1,1),lda,beta,c(2),n + &
                                 1)
                       call la_${ri}$syrk('U','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(1), &
                                 n + 1)
                       call la_${ri}$gemm('N','T',nk,nk,k,alpha,a(nk + 1,1),lda,a(1,1), &
                                  lda,beta,c(nk + 2),n + 1)
                    else
                       ! n is even, transr = 'n', uplo = 'l', and trans = 't'
                       call la_${ri}$syrk('L','T',nk,k,alpha,a(1,1),lda,beta,c(2),n + &
                                 1)
                       call la_${ri}$syrk('U','T',nk,k,alpha,a(1,nk + 1),lda,beta,c(1), &
                                 n + 1)
                       call la_${ri}$gemm('T','N',nk,nk,k,alpha,a(1,nk + 1),lda,a(1,1), &
                                  lda,beta,c(nk + 2),n + 1)
                    end if
                 else
                    ! n is even, transr = 'n', and uplo = 'u'
                    if (notrans) then
                       ! n is even, transr = 'n', uplo = 'u', and trans = 'n'
                       call la_${ri}$syrk('L','N',nk,k,alpha,a(1,1),lda,beta,c(nk + 2), &
                                 n + 1)
                       call la_${ri}$syrk('U','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(nk + 1 &
                                 ),n + 1)
                       call la_${ri}$gemm('N','T',nk,nk,k,alpha,a(1,1),lda,a(nk + 1,1), &
                                  lda,beta,c(1),n + 1)
                    else
                       ! n is even, transr = 'n', uplo = 'u', and trans = 't'
                       call la_${ri}$syrk('L','T',nk,k,alpha,a(1,1),lda,beta,c(nk + 2), &
                                 n + 1)
                       call la_${ri}$syrk('U','T',nk,k,alpha,a(1,nk + 1),lda,beta,c(nk + 1 &
                                 ),n + 1)
                       call la_${ri}$gemm('T','N',nk,nk,k,alpha,a(1,1),lda,a(1,nk + 1), &
                                  lda,beta,c(1),n + 1)
                    end if
                 end if
              else
                 ! n is even, and transr = 't'
                 if (lower) then
                    ! n is even, transr = 't', and uplo = 'l'
                    if (notrans) then
                       ! n is even, transr = 't', uplo = 'l', and trans = 'n'
                       call la_${ri}$syrk('U','N',nk,k,alpha,a(1,1),lda,beta,c(nk + 1), &
                                 nk)
                       call la_${ri}$syrk('L','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(1), &
                                 nk)
                       call la_${ri}$gemm('N','T',nk,nk,k,alpha,a(1,1),lda,a(nk + 1,1), &
                                  lda,beta,c(((nk + 1)*nk) + 1),nk)
                    else
                       ! n is even, transr = 't', uplo = 'l', and trans = 't'
                       call la_${ri}$syrk('U','T',nk,k,alpha,a(1,1),lda,beta,c(nk + 1), &
                                 nk)
                       call la_${ri}$syrk('L','T',nk,k,alpha,a(1,nk + 1),lda,beta,c(1), &
                                 nk)
                       call la_${ri}$gemm('T','N',nk,nk,k,alpha,a(1,1),lda,a(1,nk + 1), &
                                  lda,beta,c(((nk + 1)*nk) + 1),nk)
                    end if
                 else
                    ! n is even, transr = 't', and uplo = 'u'
                    if (notrans) then
                       ! n is even, transr = 't', uplo = 'u', and trans = 'n'
                       call la_${ri}$syrk('U','N',nk,k,alpha,a(1,1),lda,beta,c(nk*(nk + &
                                 1) + 1),nk)
                       call la_${ri}$syrk('L','N',nk,k,alpha,a(nk + 1,1),lda,beta,c( &
                                 nk*nk + 1),nk)
                       call la_${ri}$gemm('N','T',nk,nk,k,alpha,a(nk + 1,1),lda,a(1,1), &
                                  lda,beta,c(1),nk)
                    else
                       ! n is even, transr = 't', uplo = 'u', and trans = 't'
                       call la_${ri}$syrk('U','T',nk,k,alpha,a(1,1),lda,beta,c(nk*(nk + &
                                 1) + 1),nk)
                       call la_${ri}$syrk('L','T',nk,k,alpha,a(1,nk + 1),lda,beta,c( &
                                 nk*nk + 1),nk)
                       call la_${ri}$gemm('T','N',nk,nk,k,alpha,a(1,nk + 1),lda,a(1,1), &
                                  lda,beta,c(1),nk)
                    end if
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$sfrk
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_REAL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> Level 3 BLAS like routine for A in RFP Format.
     !> ${ri.upper()}$TFSM:  solves the matrix equation
     !> op( A )*X = alpha*B  or  X*op( A ) = alpha*B
     !> where alpha is a scalar, X and B are m by n matrices, A is a unit, or
     !> non-unit,  upper or lower triangular matrix  and  op( A )  is one  of
     !> op( A ) = A   or   op( A ) = A**T.
     !> A is in Rectangular Full Packed (RFP) Format.
     !> The matrix X is overwritten on B.

     pure subroutine la_${ri}$tfsm(transr,side,uplo,trans,diag,m,n,alpha,a,b,ldb)
        use la_constants_${rk}$

        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: transr,diag,side,trans,uplo
           integer(ilp),intent(in) :: ldb,m,n
           real(${rk}$),intent(in) :: alpha
           ! Array Arguments
           real(${rk}$),intent(in) :: a(0:*)
           real(${rk}$),intent(inout) :: b(0:ldb - 1,0:*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lower,lside,misodd,nisodd,normaltransr,notrans
           integer(ilp) :: m1,m2,n1,n2,k,info,i,j
           ! Intrinsic Functions
           intrinsic :: max,mod
           ! Executable Statements
           ! test the input parameters.
           info = 0
           normaltransr = la_lsame(transr,'N')
           lside = la_lsame(side,'L')
           lower = la_lsame(uplo,'L')
           notrans = la_lsame(trans,'N')
           if (.not. normaltransr .and. .not. la_lsame(transr,'T')) then
              info = -1
           else if (.not. lside .and. .not. la_lsame(side,'R')) then
              info = -2
           else if (.not. lower .and. .not. la_lsame(uplo,'U')) then
              info = -3
           else if (.not. notrans .and. .not. la_lsame(trans,'T')) then
              info = -4
           else if (.not. la_lsame(diag,'N') .and. .not. la_lsame(diag,'U')) &
                     then
              info = -5
           else if (m < 0) then
              info = -6
           else if (n < 0) then
              info = -7
           else if (ldb < max(1,m)) then
              info = -11
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$TFSM ',-info)
              return
           end if
           ! quick return when ( (n==0).or.(m==0) )
           if ((m == 0) .or. (n == 0)) return
           ! quick return when alpha==(0e+0_${rk}$)
           if (alpha == zero) then
              do j = 0,n - 1
                 do i = 0,m - 1
                    b(i,j) = zero
                 end do
              end do
              return
           end if
           if (lside) then
              ! side = 'l'
              ! a is m-by-m.
              ! if m is odd, set nisodd = .true., and m1 and m2.
              ! if m is even, nisodd = .false., and m.
              if (mod(m,2) == 0) then
                 misodd = .false.
                 k = m/2
              else
                 misodd = .true.
                 if (lower) then
                    m2 = m/2
                    m1 = m - m2
                 else
                    m1 = m/2
                    m2 = m - m1
                 end if
              end if
              if (misodd) then
                 ! side = 'l' and n is odd
                 if (normaltransr) then
                    ! side = 'l', n is odd, and transr = 'n'
                    if (lower) then
                       ! side  ='l', n is odd, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'n'
                          if (m == 1) then
                             call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a,m,b,ldb)

                          else
                             call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a(0),m,b, &
                                       ldb)
                             call la_${ri}$gemm('N','N',m2,n,m1,-one,a(m1),m,b,ldb, &
                                       alpha,b(m1,0),ldb)
                             call la_${ri}$trsm('L','U','T',diag,m2,n,one,a(m),m,b(m1, &
                                       0),ldb)
                          end if
                       else
                          ! side  ='l', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 't'
                          if (m == 1) then
                             call la_${ri}$trsm('L','L','T',diag,m1,n,alpha,a(0),m,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','U','N',diag,m2,n,alpha,a(m),m,b( &
                                       m1,0),ldb)
                             call la_${ri}$gemm('T','N',m1,n,m2,-one,a(m1),m,b(m1,0), &
                                       ldb,alpha,b,ldb)
                             call la_${ri}$trsm('L','L','T',diag,m1,n,one,a(0),m,b,ldb &
                                       )
                          end if
                       end if
                    else
                       ! side  ='l', n is odd, transr = 'n', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a(m2),m,b,ldb &
                                    )
                          call la_${ri}$gemm('T','N',m2,n,m1,-one,a(0),m,b,ldb,alpha, &
                                    b(m1,0),ldb)
                          call la_${ri}$trsm('L','U','T',diag,m2,n,one,a(m1),m,b(m1,0 &
                                    ),ldb)
                       else
                          ! side  ='l', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 't'
                          call la_${ri}$trsm('L','U','N',diag,m2,n,alpha,a(m1),m,b(m1, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m1,n,m2,-one,a(0),m,b(m1,0),ldb, &
                                     alpha,b,ldb)
                          call la_${ri}$trsm('L','L','T',diag,m1,n,one,a(m2),m,b,ldb)

                       end if
                    end if
                 else
                    ! side = 'l', n is odd, and transr = 't'
                    if (lower) then
                       ! side  ='l', n is odd, transr = 't', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is odd, transr = 't', uplo = 'l', and
                          ! trans = 'n'
                          if (m == 1) then
                             call la_${ri}$trsm('L','U','T',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','U','T',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                             call la_${ri}$gemm('T','N',m2,n,m1,-one,a(m1*m1),m1,b,ldb, &
                                       alpha,b(m1,0),ldb)
                             call la_${ri}$trsm('L','L','N',diag,m2,n,one,a(1),m1,b(m1, &
                                        0),ldb)
                          end if
                       else
                          ! side  ='l', n is odd, transr = 't', uplo = 'l', and
                          ! trans = 't'
                          if (m == 1) then
                             call la_${ri}$trsm('L','U','N',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','L','T',diag,m2,n,alpha,a(1),m1,b( &
                                       m1,0),ldb)
                             call la_${ri}$gemm('N','N',m1,n,m2,-one,a(m1*m1),m1,b(m1, &
                                       0),ldb,alpha,b,ldb)
                             call la_${ri}$trsm('L','U','N',diag,m1,n,one,a(0),m1,b, &
                                       ldb)
                          end if
                       end if
                    else
                       ! side  ='l', n is odd, transr = 't', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is odd, transr = 't', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('L','U','T',diag,m1,n,alpha,a(m2*m2),m2,b, &
                                    ldb)
                          call la_${ri}$gemm('N','N',m2,n,m1,-one,a(0),m2,b,ldb,alpha, &
                                    b(m1,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,m2,n,one,a(m1*m2),m2,b( &
                                    m1,0),ldb)
                       else
                          ! side  ='l', n is odd, transr = 't', uplo = 'u', and
                          ! trans = 't'
                          call la_${ri}$trsm('L','L','T',diag,m2,n,alpha,a(m1*m2),m2,b( &
                                    m1,0),ldb)
                          call la_${ri}$gemm('T','N',m1,n,m2,-one,a(0),m2,b(m1,0), &
                                    ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,m1,n,one,a(m2*m2),m2,b, &
                                    ldb)
                       end if
                    end if
                 end if
              else
                 ! side = 'l' and n is even
                 if (normaltransr) then
                    ! side = 'l', n is even, and transr = 'n'
                    if (lower) then
                       ! side  ='l', n is even, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,k,n,alpha,a(1),m + 1,b,ldb &
                                    )
                          call la_${ri}$gemm('N','N',k,n,k,-one,a(k + 1),m + 1,b,ldb,alpha, &
                                     b(k,0),ldb)
                          call la_${ri}$trsm('L','U','T',diag,k,n,one,a(0),m + 1,b(k,0) &
                                    ,ldb)
                       else
                          ! side  ='l', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 't'
                          call la_${ri}$trsm('L','U','N',diag,k,n,alpha,a(0),m + 1,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('T','N',k,n,k,-one,a(k + 1),m + 1,b(k,0), &
                                    ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','L','T',diag,k,n,one,a(1),m + 1,b,ldb)

                       end if
                    else
                       ! side  ='l', n is even, transr = 'n', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,k,n,alpha,a(k + 1),m + 1,b, &
                                    ldb)
                          call la_${ri}$gemm('T','N',k,n,k,-one,a(0),m + 1,b,ldb,alpha, &
                                    b(k,0),ldb)
                          call la_${ri}$trsm('L','U','T',diag,k,n,one,a(k),m + 1,b(k,0) &
                                    ,ldb)
                       else
                          ! side  ='l', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 't'
                          call la_${ri}$trsm('L','U','N',diag,k,n,alpha,a(k),m + 1,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-one,a(0),m + 1,b(k,0),ldb, &
                                    alpha,b,ldb)
                          call la_${ri}$trsm('L','L','T',diag,k,n,one,a(k + 1),m + 1,b,ldb &
                                    )
                       end if
                    end if
                 else
                    ! side = 'l', n is even, and transr = 't'
                    if (lower) then
                       ! side  ='l', n is even, transr = 't', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is even, transr = 't', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','U','T',diag,k,n,alpha,a(k),k,b,ldb)

                          call la_${ri}$gemm('T','N',k,n,k,-one,a(k*(k + 1)),k,b,ldb, &
                                    alpha,b(k,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,k,n,one,a(0),k,b(k,0), &
                                    ldb)
                       else
                          ! side  ='l', n is even, transr = 't', uplo = 'l',
                          ! and trans = 't'
                          call la_${ri}$trsm('L','L','T',diag,k,n,alpha,a(0),k,b(k,0) &
                                    ,ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-one,a(k*(k + 1)),k,b(k,0), &
                                     ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,k,n,one,a(k),k,b,ldb)

                       end if
                    else
                       ! side  ='l', n is even, transr = 't', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is even, transr = 't', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','U','T',diag,k,n,alpha,a(k*(k + 1)),k, &
                                    b,ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-one,a(0),k,b,ldb,alpha,b( &
                                    k,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,k,n,one,a(k*k),k,b(k,0) &
                                    ,ldb)
                       else
                          ! side  ='l', n is even, transr = 't', uplo = 'u',
                          ! and trans = 't'
                          call la_${ri}$trsm('L','L','T',diag,k,n,alpha,a(k*k),k,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('T','N',k,n,k,-one,a(0),k,b(k,0),ldb, &
                                    alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,k,n,one,a(k*(k + 1)),k,b, &
                                    ldb)
                       end if
                    end if
                 end if
              end if
           else
              ! side = 'r'
              ! a is n-by-n.
              ! if n is odd, set nisodd = .true., and n1 and n2.
              ! if n is even, nisodd = .false., and k.
              if (mod(n,2) == 0) then
                 nisodd = .false.
                 k = n/2
              else
                 nisodd = .true.
                 if (lower) then
                    n2 = n/2
                    n1 = n - n2
                 else
                    n1 = n/2
                    n2 = n - n1
                 end if
              end if
              if (nisodd) then
                 ! side = 'r' and n is odd
                 if (normaltransr) then
                    ! side = 'r', n is odd, and transr = 'n'
                    if (lower) then
                       ! side  ='r', n is odd, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','U','T',diag,m,n2,alpha,a(n),n,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','N',m,n1,n2,-one,b(0,n1),ldb,a(n1), &
                                    n,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,n1,one,a(0),n,b(0,0), &
                                     ldb)
                       else
                          ! side  ='r', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 't'
                          call la_${ri}$trsm('R','L','T',diag,m,n1,alpha,a(0),n,b(0,0 &
                                    ),ldb)
                          call la_${ri}$gemm('N','T',m,n2,n1,-one,b(0,0),ldb,a(n1),n, &
                                     alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,n2,one,a(n),n,b(0,n1) &
                                    ,ldb)
                       end if
                    else
                       ! side  ='r', n is odd, transr = 'n', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','L','T',diag,m,n1,alpha,a(n2),n,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m,n2,n1,-one,b(0,0),ldb,a(0),n, &
                                    alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,n2,one,a(n1),n,b(0,n1 &
                                    ),ldb)
                       else
                          ! side  ='r', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 't'
                          call la_${ri}$trsm('R','U','T',diag,m,n2,alpha,a(n1),n,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','T',m,n1,n2,-one,b(0,n1),ldb,a(0),n, &
                                     alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,n1,one,a(n2),n,b(0,0) &
                                    ,ldb)
                       end if
                    end if
                 else
                    ! side = 'r', n is odd, and transr = 't'
                    if (lower) then
                       ! side  ='r', n is odd, transr = 't', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 't', uplo = 'l', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','L','N',diag,m,n2,alpha,a(1),n1,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','T',m,n1,n2,-one,b(0,n1),ldb,a(n1*n1) &
                                    ,n1,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','T',diag,m,n1,one,a(0),n1,b(0,0) &
                                    ,ldb)
                       else
                          ! side  ='r', n is odd, transr = 't', uplo = 'l', and
                          ! trans = 't'
                          call la_${ri}$trsm('R','U','N',diag,m,n1,alpha,a(0),n1,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m,n2,n1,-one,b(0,0),ldb,a(n1*n1), &
                                     n1,alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','L','T',diag,m,n2,one,a(1),n1,b(0,n1 &
                                    ),ldb)
                       end if
                    else
                       ! side  ='r', n is odd, transr = 't', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 't', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','U','N',diag,m,n1,alpha,a(n2*n2),n2,b( &
                                    0,0),ldb)
                          call la_${ri}$gemm('N','T',m,n2,n1,-one,b(0,0),ldb,a(0),n2, &
                                     alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','L','T',diag,m,n2,one,a(n1*n2),n2,b(0, &
                                     n1),ldb)
                       else
                          ! side  ='r', n is odd, transr = 't', uplo = 'u', and
                          ! trans = 't'
                          call la_${ri}$trsm('R','L','N',diag,m,n2,alpha,a(n1*n2),n2,b( &
                                    0,n1),ldb)
                          call la_${ri}$gemm('N','N',m,n1,n2,-one,b(0,n1),ldb,a(0), &
                                    n2,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','T',diag,m,n1,one,a(n2*n2),n2,b(0, &
                                     0),ldb)
                       end if
                    end if
                 end if
              else
                 ! side = 'r' and n is even
                 if (normaltransr) then
                    ! side = 'r', n is even, and transr = 'n'
                    if (lower) then
                       ! side  ='r', n is even, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','U','T',diag,m,k,alpha,a(0),n + 1,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-one,b(0,k),ldb,a(k + 1),n + &
                                    1,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,k,one,a(1),n + 1,b(0,0) &
                                    ,ldb)
                       else
                          ! side  ='r', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 't'
                          call la_${ri}$trsm('R','L','T',diag,m,k,alpha,a(1),n + 1,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','T',m,k,k,-one,b(0,0),ldb,a(k + 1),n + &
                                    1,alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,k,one,a(0),n + 1,b(0,k) &
                                    ,ldb)
                       end if
                    else
                       ! side  ='r', n is even, transr = 'n', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','L','T',diag,m,k,alpha,a(k + 1),n + 1,b(0, &
                                     0),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-one,b(0,0),ldb,a(0),n + 1, &
                                    alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,k,one,a(k),n + 1,b(0,k) &
                                    ,ldb)
                       else
                          ! side  ='r', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 't'
                          call la_${ri}$trsm('R','U','T',diag,m,k,alpha,a(k),n + 1,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','T',m,k,k,-one,b(0,k),ldb,a(0),n + 1, &
                                    alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,k,one,a(k + 1),n + 1,b(0, &
                                    0),ldb)
                       end if
                    end if
                 else
                    ! side = 'r', n is even, and transr = 't'
                    if (lower) then
                       ! side  ='r', n is even, transr = 't', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 't', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','L','N',diag,m,k,alpha,a(0),k,b(0,k) &
                                    ,ldb)
                          call la_${ri}$gemm('N','T',m,k,k,-one,b(0,k),ldb,a((k + 1)*k &
                                    ),k,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','T',diag,m,k,one,a(k),k,b(0,0), &
                                    ldb)
                       else
                          ! side  ='r', n is even, transr = 't', uplo = 'l',
                          ! and trans = 't'
                          call la_${ri}$trsm('R','U','N',diag,m,k,alpha,a(k),k,b(0,0) &
                                    ,ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-one,b(0,0),ldb,a((k + 1)*k &
                                    ),k,alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','L','T',diag,m,k,one,a(0),k,b(0,k), &
                                    ldb)
                       end if
                    else
                       ! side  ='r', n is even, transr = 't', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 't', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','U','N',diag,m,k,alpha,a((k + 1)*k),k, &
                                    b(0,0),ldb)
                          call la_${ri}$gemm('N','T',m,k,k,-one,b(0,0),ldb,a(0),k, &
                                    alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','L','T',diag,m,k,one,a(k*k),k,b(0,k) &
                                    ,ldb)
                       else
                          ! side  ='r', n is even, transr = 't', uplo = 'u',
                          ! and trans = 't'
                          call la_${ri}$trsm('R','L','N',diag,m,k,alpha,a(k*k),k,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-one,b(0,k),ldb,a(0),k, &
                                    alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','T',diag,m,k,one,a((k + 1)*k),k,b( &
                                    0,0),ldb)
                       end if
                    end if
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$tfsm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> Level 3 BLAS like routine for C in RFP Format.
     !> ${ri.upper()}$HFRK: performs one of the Hermitian rank--k operations
     !> C := alpha*A*A**H + beta*C,
     !> or
     !> C := alpha*A**H*A + beta*C,
     !> where alpha and beta are real scalars, C is an n--by--n Hermitian
     !> matrix and A is an n--by--k matrix in the first case and a k--by--n
     !> matrix in the second case.

     pure subroutine la_${ri}$hfrk(transr,uplo,trans,n,k,alpha,a,lda,beta,c)
        use la_constants_${rk}$
        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           real(${rk}$),intent(in) :: alpha,beta
           integer(ilp),intent(in) :: k,lda,n
           character,intent(in) :: trans,transr,uplo
           ! Array Arguments
           complex(${rk}$),intent(in) :: a(lda,*)
           complex(${rk}$),intent(inout) :: c(*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lower,normaltransr,nisodd,notrans
           integer(ilp) :: info,nrowa,j,nk,n1,n2
           complex(${rk}$) :: calpha,cbeta
           ! Intrinsic Functions
           intrinsic :: max,cmplx
           ! Executable Statements
           ! test the input parameters.
           info = 0
           normaltransr = la_lsame(transr,'N')
           lower = la_lsame(uplo,'L')
           notrans = la_lsame(trans,'N')
           if (notrans) then
              nrowa = n
           else
              nrowa = k
           end if
           if (.not. normaltransr .and. .not. la_lsame(transr,'C')) then
              info = -1
           else if (.not. lower .and. .not. la_lsame(uplo,'U')) then
              info = -2
           else if (.not. notrans .and. .not. la_lsame(trans,'C')) then
              info = -3
           else if (n < 0) then
              info = -4
           else if (k < 0) then
              info = -5
           else if (lda < max(1,nrowa)) then
              info = -8
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$HFRK ',-info)
              return
           end if
           ! quick return if possible.
           ! the quick return case: ((alpha==0).and.(beta/=zero)) is not
           ! done (it is in la_${ri}$herk for example) and left in the general case.
           if ((n == 0) .or. (((alpha == zero) .or. (k == 0)) .and. (beta == one))) &
                     return
           if ((alpha == zero) .and. (beta == zero)) then
              do j = 1, ((n*(n + 1))/2)
                 c(j) = czero
              end do
              return
           end if
           calpha = cmplx(alpha,zero,KIND=${rk}$)
           cbeta = cmplx(beta,zero,KIND=${rk}$)
           ! c is n-by-n.
           ! if n is odd, set nisodd = .true., and n1 and n2.
           ! if n is even, nisodd = .false., and nk.
           if (mod(n,2) == 0) then
              nisodd = .false.
              nk = n/2
           else
              nisodd = .true.
              if (lower) then
                 n2 = n/2
                 n1 = n - n2
              else
                 n1 = n/2
                 n2 = n - n1
              end if
           end if
           if (nisodd) then
              ! n is odd
              if (normaltransr) then
                 ! n is odd and transr = 'n'
                 if (lower) then
                    ! n is odd, transr = 'n', and uplo = 'l'
                    if (notrans) then
                       ! n is odd, transr = 'n', uplo = 'l', and trans = 'n'
                       call la_${ri}$herk('L','N',n1,k,alpha,a(1,1),lda,beta,c(1),n)

                       call la_${ri}$herk('U','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c(n + 1) &
                                 ,n)
                       call la_${ri}$gemm('N','C',n2,n1,k,calpha,a(n1 + 1,1),lda,a(1,1) &
                                 ,lda,cbeta,c(n1 + 1),n)
                    else
                       ! n is odd, transr = 'n', uplo = 'l', and trans = 'c'
                       call la_${ri}$herk('L','C',n1,k,alpha,a(1,1),lda,beta,c(1),n)

                       call la_${ri}$herk('U','C',n2,k,alpha,a(1,n1 + 1),lda,beta,c(n + 1) &
                                 ,n)
                       call la_${ri}$gemm('C','N',n2,n1,k,calpha,a(1,n1 + 1),lda,a(1,1) &
                                 ,lda,cbeta,c(n1 + 1),n)
                    end if
                 else
                    ! n is odd, transr = 'n', and uplo = 'u'
                    if (notrans) then
                       ! n is odd, transr = 'n', uplo = 'u', and trans = 'n'
                       call la_${ri}$herk('L','N',n1,k,alpha,a(1,1),lda,beta,c(n2 + 1), &
                                 n)
                       call la_${ri}$herk('U','N',n2,k,alpha,a(n2,1),lda,beta,c(n1 + 1), &
                                  n)
                       call la_${ri}$gemm('N','C',n1,n2,k,calpha,a(1,1),lda,a(n2,1), &
                                 lda,cbeta,c(1),n)
                    else
                       ! n is odd, transr = 'n', uplo = 'u', and trans = 'c'
                       call la_${ri}$herk('L','C',n1,k,alpha,a(1,1),lda,beta,c(n2 + 1), &
                                 n)
                       call la_${ri}$herk('U','C',n2,k,alpha,a(1,n2),lda,beta,c(n1 + 1), &
                                  n)
                       call la_${ri}$gemm('C','N',n1,n2,k,calpha,a(1,1),lda,a(1,n2), &
                                 lda,cbeta,c(1),n)
                    end if
                 end if
              else
                 ! n is odd, and transr = 'c'
                 if (lower) then
                    ! n is odd, transr = 'c', and uplo = 'l'
                    if (notrans) then
                       ! n is odd, transr = 'c', uplo = 'l', and trans = 'n'
                       call la_${ri}$herk('U','N',n1,k,alpha,a(1,1),lda,beta,c(1),n1 &
                                 )
                       call la_${ri}$herk('L','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c(2), &
                                 n1)
                       call la_${ri}$gemm('N','C',n1,n2,k,calpha,a(1,1),lda,a(n1 + 1,1) &
                                 ,lda,cbeta,c(n1*n1 + 1),n1)
                    else
                       ! n is odd, transr = 'c', uplo = 'l', and trans = 'c'
                       call la_${ri}$herk('U','C',n1,k,alpha,a(1,1),lda,beta,c(1),n1 &
                                 )
                       call la_${ri}$herk('L','C',n2,k,alpha,a(1,n1 + 1),lda,beta,c(2), &
                                 n1)
                       call la_${ri}$gemm('C','N',n1,n2,k,calpha,a(1,1),lda,a(1,n1 + 1) &
                                 ,lda,cbeta,c(n1*n1 + 1),n1)
                    end if
                 else
                    ! n is odd, transr = 'c', and uplo = 'u'
                    if (notrans) then
                       ! n is odd, transr = 'c', uplo = 'u', and trans = 'n'
                       call la_${ri}$herk('U','N',n1,k,alpha,a(1,1),lda,beta,c(n2*n2 + 1 &
                                 ),n2)
                       call la_${ri}$herk('L','N',n2,k,alpha,a(n1 + 1,1),lda,beta,c( &
                                 n1*n2 + 1),n2)
                       call la_${ri}$gemm('N','C',n2,n1,k,calpha,a(n1 + 1,1),lda,a(1,1) &
                                 ,lda,cbeta,c(1),n2)
                    else
                       ! n is odd, transr = 'c', uplo = 'u', and trans = 'c'
                       call la_${ri}$herk('U','C',n1,k,alpha,a(1,1),lda,beta,c(n2*n2 + 1 &
                                 ),n2)
                       call la_${ri}$herk('L','C',n2,k,alpha,a(1,n1 + 1),lda,beta,c( &
                                 n1*n2 + 1),n2)
                       call la_${ri}$gemm('C','N',n2,n1,k,calpha,a(1,n1 + 1),lda,a(1,1) &
                                 ,lda,cbeta,c(1),n2)
                    end if
                 end if
              end if
           else
              ! n is even
              if (normaltransr) then
                 ! n is even and transr = 'n'
                 if (lower) then
                    ! n is even, transr = 'n', and uplo = 'l'
                    if (notrans) then
                       ! n is even, transr = 'n', uplo = 'l', and trans = 'n'
                       call la_${ri}$herk('L','N',nk,k,alpha,a(1,1),lda,beta,c(2),n + &
                                 1)
                       call la_${ri}$herk('U','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(1), &
                                 n + 1)
                       call la_${ri}$gemm('N','C',nk,nk,k,calpha,a(nk + 1,1),lda,a(1,1) &
                                 ,lda,cbeta,c(nk + 2),n + 1)
                    else
                       ! n is even, transr = 'n', uplo = 'l', and trans = 'c'
                       call la_${ri}$herk('L','C',nk,k,alpha,a(1,1),lda,beta,c(2),n + &
                                 1)
                       call la_${ri}$herk('U','C',nk,k,alpha,a(1,nk + 1),lda,beta,c(1), &
                                 n + 1)
                       call la_${ri}$gemm('C','N',nk,nk,k,calpha,a(1,nk + 1),lda,a(1,1) &
                                 ,lda,cbeta,c(nk + 2),n + 1)
                    end if
                 else
                    ! n is even, transr = 'n', and uplo = 'u'
                    if (notrans) then
                       ! n is even, transr = 'n', uplo = 'u', and trans = 'n'
                       call la_${ri}$herk('L','N',nk,k,alpha,a(1,1),lda,beta,c(nk + 2), &
                                 n + 1)
                       call la_${ri}$herk('U','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(nk + 1 &
                                 ),n + 1)
                       call la_${ri}$gemm('N','C',nk,nk,k,calpha,a(1,1),lda,a(nk + 1,1) &
                                 ,lda,cbeta,c(1),n + 1)
                    else
                       ! n is even, transr = 'n', uplo = 'u', and trans = 'c'
                       call la_${ri}$herk('L','C',nk,k,alpha,a(1,1),lda,beta,c(nk + 2), &
                                 n + 1)
                       call la_${ri}$herk('U','C',nk,k,alpha,a(1,nk + 1),lda,beta,c(nk + 1 &
                                 ),n + 1)
                       call la_${ri}$gemm('C','N',nk,nk,k,calpha,a(1,1),lda,a(1,nk + 1) &
                                 ,lda,cbeta,c(1),n + 1)
                    end if
                 end if
              else
                 ! n is even, and transr = 'c'
                 if (lower) then
                    ! n is even, transr = 'c', and uplo = 'l'
                    if (notrans) then
                       ! n is even, transr = 'c', uplo = 'l', and trans = 'n'
                       call la_${ri}$herk('U','N',nk,k,alpha,a(1,1),lda,beta,c(nk + 1), &
                                 nk)
                       call la_${ri}$herk('L','N',nk,k,alpha,a(nk + 1,1),lda,beta,c(1), &
                                 nk)
                       call la_${ri}$gemm('N','C',nk,nk,k,calpha,a(1,1),lda,a(nk + 1,1) &
                                 ,lda,cbeta,c(((nk + 1)*nk) + 1),nk)
                    else
                       ! n is even, transr = 'c', uplo = 'l', and trans = 'c'
                       call la_${ri}$herk('U','C',nk,k,alpha,a(1,1),lda,beta,c(nk + 1), &
                                 nk)
                       call la_${ri}$herk('L','C',nk,k,alpha,a(1,nk + 1),lda,beta,c(1), &
                                 nk)
                       call la_${ri}$gemm('C','N',nk,nk,k,calpha,a(1,1),lda,a(1,nk + 1) &
                                 ,lda,cbeta,c(((nk + 1)*nk) + 1),nk)
                    end if
                 else
                    ! n is even, transr = 'c', and uplo = 'u'
                    if (notrans) then
                       ! n is even, transr = 'c', uplo = 'u', and trans = 'n'
                       call la_${ri}$herk('U','N',nk,k,alpha,a(1,1),lda,beta,c(nk*(nk + &
                                 1) + 1),nk)
                       call la_${ri}$herk('L','N',nk,k,alpha,a(nk + 1,1),lda,beta,c( &
                                 nk*nk + 1),nk)
                       call la_${ri}$gemm('N','C',nk,nk,k,calpha,a(nk + 1,1),lda,a(1,1) &
                                 ,lda,cbeta,c(1),nk)
                    else
                       ! n is even, transr = 'c', uplo = 'u', and trans = 'c'
                       call la_${ri}$herk('U','C',nk,k,alpha,a(1,1),lda,beta,c(nk*(nk + &
                                 1) + 1),nk)
                       call la_${ri}$herk('L','C',nk,k,alpha,a(1,nk + 1),lda,beta,c( &
                                 nk*nk + 1),nk)
                       call la_${ri}$gemm('C','N',nk,nk,k,calpha,a(1,nk + 1),lda,a(1,1) &
                                 ,lda,cbeta,c(1),nk)
                    end if
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$hfrk
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LACRM: performs a very simple matrix-matrix multiplication:
     !> C := A * B,
     !> where A is M by N and complex; B is N by N and real;
     !> C is M by N and complex.

     pure subroutine la_${ri}$lacrm(m,n,a,lda,b,ldb,c,ldc,rwork)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: lda,ldb,ldc,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: b(ldb,*)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rk}$),intent(in) :: a(lda,*)
           complex(${rk}$),intent(out) :: c(ldc,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,l
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: aimag,cmplx,real
#:else
           intrinsic :: real,cmplx,aimag
#:endif
           ! Executable Statements
           ! quick return if possible.
           if ((m == 0) .or. (n == 0)) return
           do j = 1,n
              do i = 1,m
                 rwork((j - 1)*m + i) = real(a(i,j),KIND=${rk}$)
              end do
           end do
           l = m*n + 1
           call la_${ci}$gemm('N','N',m,n,n,one,rwork,m,b,ldb,zero,rwork(l),m)

           do j = 1,n
              do i = 1,m
                 c(i,j) = rwork(l + (j - 1)*m + i - 1)
              end do
           end do
           do j = 1,n
              do i = 1,m
                 rwork((j - 1)*m + i) = aimag(a(i,j))
              end do
           end do
           call la_${ci}$gemm('N','N',m,n,n,one,rwork,m,b,ldb,zero,rwork(l),m)

           do j = 1,n
              do i = 1,m
                 c(i,j) = cmplx(real(c(i,j),KIND=${rk}$),rwork(l + (j - 1)*m + i - 1),KIND=${rk}$)

              end do
           end do
           return
     end subroutine la_${ri}$lacrm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LAGTM: performs a matrix-vector product of the form
     !> B := alpha * A * X + beta * B
     !> where A is a tridiagonal matrix of order N, B and X are N by NRHS
     !> matrices, and alpha and beta are real scalars, each of which may be
     !> 0., 1., or -1.

     pure subroutine la_${ri}$lagtm(trans,n,nrhs,alpha,dl,d,du,x,ldx,beta,b,ldb)
        use la_constants_${rk}$

        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: trans
           integer(ilp),intent(in) :: ldb,ldx,n,nrhs
           real(${rk}$),intent(in) :: alpha,beta
           ! Array Arguments
           complex(${rk}$),intent(inout) :: b(ldb,*)
           complex(${rk}$),intent(in) :: d(*),dl(*),du(*),x(ldx,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j
           ! Intrinsic Functions
           intrinsic :: conjg
           ! Executable Statements
           if (n == 0) return
           ! multiply b by beta if beta/=1.
           if (beta == zero) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = zero
                 end do
              end do
           else if (beta == -one) then
              do j = 1,nrhs
                 do i = 1,n
                    b(i,j) = -b(i,j)
                 end do
              end do
           end if
           if (alpha == one) then
              if (la_lsame(trans,'N')) then
                 ! compute b := b + a*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) + d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) + d(1)*x(1,j) + du(1)*x(2,j)
                       b(n,j) = b(n,j) + dl(n - 1)*x(n - 1,j) + d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) + dl(i - 1)*x(i - 1,j) + d(i)*x(i,j) + du(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else if (la_lsame(trans,'T')) then
                 ! compute b := b + a**t * x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) + d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) + d(1)*x(1,j) + dl(1)*x(2,j)
                       b(n,j) = b(n,j) + du(n - 1)*x(n - 1,j) + d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) + du(i - 1)*x(i - 1,j) + d(i)*x(i,j) + dl(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else if (la_lsame(trans,'C')) then
                 ! compute b := b + a**h * x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) + conjg(d(1))*x(1,j)
                    else
                       b(1,j) = b(1,j) + conjg(d(1))*x(1,j) + conjg(dl(1))*x(2, &
                                 j)
                       b(n,j) = b(n,j) + conjg(du(n - 1))*x(n - 1,j) + conjg(d(n))*x( &
                                  n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) + conjg(du(i - 1))*x(i - 1,j) + conjg(d(i)) &
                                    *x(i,j) + conjg(dl(i))*x(i + 1,j)
                       end do
                    end if
                 end do
              end if
           else if (alpha == -one) then
              if (la_lsame(trans,'N')) then
                 ! compute b := b - a*x
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) - d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) - d(1)*x(1,j) - du(1)*x(2,j)
                       b(n,j) = b(n,j) - dl(n - 1)*x(n - 1,j) - d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) - dl(i - 1)*x(i - 1,j) - d(i)*x(i,j) - du(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else if (la_lsame(trans,'T')) then
#:if rk == "sp"
                 ! compute b := b - a**t*x
#:else
                 ! compute b := b - a**t *x
#:endif
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) - d(1)*x(1,j)
                    else
                       b(1,j) = b(1,j) - d(1)*x(1,j) - dl(1)*x(2,j)
                       b(n,j) = b(n,j) - du(n - 1)*x(n - 1,j) - d(n)*x(n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) - du(i - 1)*x(i - 1,j) - d(i)*x(i,j) - dl(i &
                                    )*x(i + 1,j)
                       end do
                    end if
                 end do
              else if (la_lsame(trans,'C')) then
#:if rk == "sp"
                 ! compute b := b - a**h*x
#:else
                 ! compute b := b - a**h *x
#:endif
                 do j = 1,nrhs
                    if (n == 1) then
                       b(1,j) = b(1,j) - conjg(d(1))*x(1,j)
                    else
                       b(1,j) = b(1,j) - conjg(d(1))*x(1,j) - conjg(dl(1))*x(2, &
                                 j)
                       b(n,j) = b(n,j) - conjg(du(n - 1))*x(n - 1,j) - conjg(d(n))*x( &
                                  n,j)
                       do i = 2,n - 1
                          b(i,j) = b(i,j) - conjg(du(i - 1))*x(i - 1,j) - conjg(d(i)) &
                                    *x(i,j) - conjg(dl(i))*x(i + 1,j)
                       end do
                    end if
                 end do
              end if
           end if
           return
     end subroutine la_${ri}$lagtm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> ${ri.upper()}$LARCM: performs a very simple matrix-matrix multiplication:
     !> C := A * B,
     !> where A is M by M and real; B is M by N and complex;
     !> C is M by N and complex.

     pure subroutine la_${ri}$larcm(m,n,a,lda,b,ldb,c,ldc,rwork)
        use la_constants_${rk}$
        ! -- lapack auxiliary routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           integer(ilp),intent(in) :: lda,ldb,ldc,m,n
           ! Array Arguments
           real(${rk}$),intent(in) :: a(lda,*)
           real(${rk}$),intent(out) :: rwork(*)
           complex(${rk}$),intent(in) :: b(ldb,*)
           complex(${rk}$),intent(out) :: c(ldc,*)
        ! =====================================================================

           ! Local Scalars
           integer(ilp) :: i,j,l
           ! Intrinsic Functions
#:if rk == "sp"
           intrinsic :: aimag,cmplx,real
#:else
           intrinsic :: real,cmplx,aimag
#:endif
           ! Executable Statements
           ! quick return if possible.
           if ((m == 0) .or. (n == 0)) return
           do j = 1,n
              do i = 1,m
                 rwork((j - 1)*m + i) = real(b(i,j),KIND=${rk}$)
              end do
           end do
           l = m*n + 1
           call la_${ci}$gemm('N','N',m,n,m,one,a,lda,rwork,m,zero,rwork(l),m)

           do j = 1,n
              do i = 1,m
                 c(i,j) = rwork(l + (j - 1)*m + i - 1)
              end do
           end do
           do j = 1,n
              do i = 1,m
                 rwork((j - 1)*m + i) = aimag(b(i,j))
              end do
           end do
           call la_${ci}$gemm('N','N',m,n,m,one,a,lda,rwork,m,zero,rwork(l),m)

           do j = 1,n
              do i = 1,m
                 c(i,j) = cmplx(real(c(i,j),KIND=${rk}$),rwork(l + (j - 1)*m + i - 1),KIND=${rk}$)

              end do
           end do
           return
     end subroutine la_${ri}$larcm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

#:for rk, rt, ri, ci, rkl, ril, cil, rku, riu, ciu in LA_CMPL_KINDS
#:if LA_GUARD[rk]
#ifdef ${LA_GUARD[rk]}$
#:endif
     !> Level 3 BLAS like routine for A in RFP Format.
     !> ${ri.upper()}$TFSM:  solves the matrix equation
     !> op( A )*X = alpha*B  or  X*op( A ) = alpha*B
     !> where alpha is a scalar, X and B are m by n matrices, A is a unit, or
     !> non-unit,  upper or lower triangular matrix  and  op( A )  is one  of
     !> op( A ) = A   or   op( A ) = A**H.
     !> A is in Rectangular Full Packed (RFP) Format.
     !> The matrix X is overwritten on B.

     pure subroutine la_${ri}$tfsm(transr,side,uplo,trans,diag,m,n,alpha,a,b,ldb)
        use la_constants_${rk}$

        ! -- lapack computational routine --
        ! -- lapack is a software package provided by univ. of tennessee,    --
        ! -- univ. of california berkeley, univ. of colorado denver and nag ltd..--
           ! Scalar Arguments
           character,intent(in) :: transr,diag,side,trans,uplo
           integer(ilp),intent(in) :: ldb,m,n
           complex(${rk}$),intent(in) :: alpha
           ! Array Arguments
           complex(${rk}$),intent(in) :: a(0:*)
           complex(${rk}$),intent(inout) :: b(0:ldb - 1,0:*)
        ! =====================================================================

           ! Local Scalars
           logical(lk) :: lower,lside,misodd,nisodd,normaltransr,notrans
           integer(ilp) :: m1,m2,n1,n2,k,info,i,j
           ! Intrinsic Functions
           intrinsic :: max,mod
           ! Executable Statements
           ! test the input parameters.
           info = 0
           normaltransr = la_lsame(transr,'N')
           lside = la_lsame(side,'L')
           lower = la_lsame(uplo,'L')
           notrans = la_lsame(trans,'N')
           if (.not. normaltransr .and. .not. la_lsame(transr,'C')) then
              info = -1
           else if (.not. lside .and. .not. la_lsame(side,'R')) then
              info = -2
           else if (.not. lower .and. .not. la_lsame(uplo,'U')) then
              info = -3
           else if (.not. notrans .and. .not. la_lsame(trans,'C')) then
              info = -4
           else if (.not. la_lsame(diag,'N') .and. .not. la_lsame(diag,'U')) &
                     then
              info = -5
           else if (m < 0) then
              info = -6
           else if (n < 0) then
              info = -7
           else if (ldb < max(1,m)) then
              info = -11
           end if
           if (info /= 0) then
              call la_xerbla('${ri.upper()}$TFSM ',-info)
              return
           end if
           ! quick return when ( (n==0).or.(m==0) )
           if ((m == 0) .or. (n == 0)) return
           ! quick return when alpha==(0e+0_${rk}$,0e+0_${rk}$)
           if (alpha == czero) then
              do j = 0,n - 1
                 do i = 0,m - 1
                    b(i,j) = czero
                 end do
              end do
              return
           end if
           if (lside) then
              ! side = 'l'
              ! a is m-by-m.
              ! if m is odd, set nisodd = .true., and m1 and m2.
              ! if m is even, nisodd = .false., and m.
              if (mod(m,2) == 0) then
                 misodd = .false.
                 k = m/2
              else
                 misodd = .true.
                 if (lower) then
                    m2 = m/2
                    m1 = m - m2
                 else
                    m1 = m/2
                    m2 = m - m1
                 end if
              end if
              if (misodd) then
                 ! side = 'l' and n is odd
                 if (normaltransr) then
                    ! side = 'l', n is odd, and transr = 'n'
                    if (lower) then
                       ! side  ='l', n is odd, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'n'
                          if (m == 1) then
                             call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a,m,b,ldb)

                          else
                             call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a(0),m,b, &
                                       ldb)
                             call la_${ri}$gemm('N','N',m2,n,m1,-cone,a(m1),m,b,ldb, &
                                       alpha,b(m1,0),ldb)
                             call la_${ri}$trsm('L','U','C',diag,m2,n,cone,a(m),m,b(m1, &
                                        0),ldb)
                          end if
                       else
                          ! side  ='l', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'c'
                          if (m == 1) then
                             call la_${ri}$trsm('L','L','C',diag,m1,n,alpha,a(0),m,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','U','N',diag,m2,n,alpha,a(m),m,b( &
                                       m1,0),ldb)
                             call la_${ri}$gemm('C','N',m1,n,m2,-cone,a(m1),m,b(m1,0), &
                                        ldb,alpha,b,ldb)
                             call la_${ri}$trsm('L','L','C',diag,m1,n,cone,a(0),m,b, &
                                       ldb)
                          end if
                       end if
                    else
                       ! side  ='l', n is odd, transr = 'n', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,m1,n,alpha,a(m2),m,b,ldb &
                                    )
                          call la_${ri}$gemm('C','N',m2,n,m1,-cone,a(0),m,b,ldb,alpha, &
                                    b(m1,0),ldb)
                          call la_${ri}$trsm('L','U','C',diag,m2,n,cone,a(m1),m,b(m1, &
                                    0),ldb)
                       else
                          ! side  ='l', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'c'
                          call la_${ri}$trsm('L','U','N',diag,m2,n,alpha,a(m1),m,b(m1, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m1,n,m2,-cone,a(0),m,b(m1,0), &
                                    ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','L','C',diag,m1,n,cone,a(m2),m,b,ldb)

                       end if
                    end if
                 else
                    ! side = 'l', n is odd, and transr = 'c'
                    if (lower) then
                       ! side  ='l', n is odd, transr = 'c', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is odd, transr = 'c', uplo = 'l', and
                          ! trans = 'n'
                          if (m == 1) then
                             call la_${ri}$trsm('L','U','C',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','U','C',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                             call la_${ri}$gemm('C','N',m2,n,m1,-cone,a(m1*m1),m1,b,ldb, &
                                        alpha,b(m1,0),ldb)
                             call la_${ri}$trsm('L','L','N',diag,m2,n,cone,a(1),m1,b( &
                                       m1,0),ldb)
                          end if
                       else
                          ! side  ='l', n is odd, transr = 'c', uplo = 'l', and
                          ! trans = 'c'
                          if (m == 1) then
                             call la_${ri}$trsm('L','U','N',diag,m1,n,alpha,a(0),m1,b, &
                                       ldb)
                          else
                             call la_${ri}$trsm('L','L','C',diag,m2,n,alpha,a(1),m1,b( &
                                       m1,0),ldb)
                             call la_${ri}$gemm('N','N',m1,n,m2,-cone,a(m1*m1),m1,b(m1, &
                                       0),ldb,alpha,b,ldb)
                             call la_${ri}$trsm('L','U','N',diag,m1,n,cone,a(0),m1,b, &
                                       ldb)
                          end if
                       end if
                    else
                       ! side  ='l', n is odd, transr = 'c', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is odd, transr = 'c', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('L','U','C',diag,m1,n,alpha,a(m2*m2),m2,b, &
                                    ldb)
                          call la_${ri}$gemm('N','N',m2,n,m1,-cone,a(0),m2,b,ldb,alpha, &
                                     b(m1,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,m2,n,cone,a(m1*m2),m2,b( &
                                    m1,0),ldb)
                       else
                          ! side  ='l', n is odd, transr = 'c', uplo = 'u', and
                          ! trans = 'c'
                          call la_${ri}$trsm('L','L','C',diag,m2,n,alpha,a(m1*m2),m2,b( &
                                    m1,0),ldb)
                          call la_${ri}$gemm('C','N',m1,n,m2,-cone,a(0),m2,b(m1,0), &
                                    ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,m1,n,cone,a(m2*m2),m2,b, &
                                    ldb)
                       end if
                    end if
                 end if
              else
                 ! side = 'l' and n is even
                 if (normaltransr) then
                    ! side = 'l', n is even, and transr = 'n'
                    if (lower) then
                       ! side  ='l', n is even, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,k,n,alpha,a(1),m + 1,b,ldb &
                                    )
                          call la_${ri}$gemm('N','N',k,n,k,-cone,a(k + 1),m + 1,b,ldb, &
                                    alpha,b(k,0),ldb)
                          call la_${ri}$trsm('L','U','C',diag,k,n,cone,a(0),m + 1,b(k,0 &
                                    ),ldb)
                       else
                          ! side  ='l', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'c'
                          call la_${ri}$trsm('L','U','N',diag,k,n,alpha,a(0),m + 1,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('C','N',k,n,k,-cone,a(k + 1),m + 1,b(k,0), &
                                    ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','L','C',diag,k,n,cone,a(1),m + 1,b,ldb)

                       end if
                    else
                       ! side  ='l', n is even, transr = 'n', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','L','N',diag,k,n,alpha,a(k + 1),m + 1,b, &
                                    ldb)
                          call la_${ri}$gemm('C','N',k,n,k,-cone,a(0),m + 1,b,ldb,alpha, &
                                    b(k,0),ldb)
                          call la_${ri}$trsm('L','U','C',diag,k,n,cone,a(k),m + 1,b(k,0 &
                                    ),ldb)
                       else
                          ! side  ='l', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'c'
                          call la_${ri}$trsm('L','U','N',diag,k,n,alpha,a(k),m + 1,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-cone,a(0),m + 1,b(k,0),ldb, &
                                     alpha,b,ldb)
                          call la_${ri}$trsm('L','L','C',diag,k,n,cone,a(k + 1),m + 1,b, &
                                    ldb)
                       end if
                    end if
                 else
                    ! side = 'l', n is even, and transr = 'c'
                    if (lower) then
                       ! side  ='l', n is even, transr = 'c', and uplo = 'l'
                       if (notrans) then
                          ! side  ='l', n is even, transr = 'c', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','U','C',diag,k,n,alpha,a(k),k,b,ldb)

                          call la_${ri}$gemm('C','N',k,n,k,-cone,a(k*(k + 1)),k,b,ldb, &
                                    alpha,b(k,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,k,n,cone,a(0),k,b(k,0), &
                                     ldb)
                       else
                          ! side  ='l', n is even, transr = 'c', uplo = 'l',
                          ! and trans = 'c'
                          call la_${ri}$trsm('L','L','C',diag,k,n,alpha,a(0),k,b(k,0) &
                                    ,ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-cone,a(k*(k + 1)),k,b(k,0) &
                                    ,ldb,alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,k,n,cone,a(k),k,b,ldb)

                       end if
                    else
                       ! side  ='l', n is even, transr = 'c', and uplo = 'u'
                       if (.not. notrans) then
                          ! side  ='l', n is even, transr = 'c', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('L','U','C',diag,k,n,alpha,a(k*(k + 1)),k, &
                                    b,ldb)
                          call la_${ri}$gemm('N','N',k,n,k,-cone,a(0),k,b,ldb,alpha,b( &
                                     k,0),ldb)
                          call la_${ri}$trsm('L','L','N',diag,k,n,cone,a(k*k),k,b(k,0 &
                                    ),ldb)
                       else
                          ! side  ='l', n is even, transr = 'c', uplo = 'u',
                          ! and trans = 'c'
                          call la_${ri}$trsm('L','L','C',diag,k,n,alpha,a(k*k),k,b(k, &
                                    0),ldb)
                          call la_${ri}$gemm('C','N',k,n,k,-cone,a(0),k,b(k,0),ldb, &
                                    alpha,b,ldb)
                          call la_${ri}$trsm('L','U','N',diag,k,n,cone,a(k*(k + 1)),k,b, &
                                     ldb)
                       end if
                    end if
                 end if
              end if
           else
              ! side = 'r'
              ! a is n-by-n.
              ! if n is odd, set nisodd = .true., and n1 and n2.
              ! if n is even, nisodd = .false., and k.
              if (mod(n,2) == 0) then
                 nisodd = .false.
                 k = n/2
              else
                 nisodd = .true.
                 if (lower) then
                    n2 = n/2
                    n1 = n - n2
                 else
                    n1 = n/2
                    n2 = n - n1
                 end if
              end if
              if (nisodd) then
                 ! side = 'r' and n is odd
                 if (normaltransr) then
                    ! side = 'r', n is odd, and transr = 'n'
                    if (lower) then
                       ! side  ='r', n is odd, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','U','C',diag,m,n2,alpha,a(n),n,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','N',m,n1,n2,-cone,b(0,n1),ldb,a(n1), &
                                    n,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,n1,cone,a(0),n,b(0,0) &
                                    ,ldb)
                       else
                          ! side  ='r', n is odd, transr = 'n', uplo = 'l', and
                          ! trans = 'c'
                          call la_${ri}$trsm('R','L','C',diag,m,n1,alpha,a(0),n,b(0,0 &
                                    ),ldb)
                          call la_${ri}$gemm('N','C',m,n2,n1,-cone,b(0,0),ldb,a(n1), &
                                    n,alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,n2,cone,a(n),n,b(0,n1 &
                                    ),ldb)
                       end if
                    else
                       ! side  ='r', n is odd, transr = 'n', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','L','C',diag,m,n1,alpha,a(n2),n,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m,n2,n1,-cone,b(0,0),ldb,a(0),n, &
                                     alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,n2,cone,a(n1),n,b(0, &
                                    n1),ldb)
                       else
                          ! side  ='r', n is odd, transr = 'n', uplo = 'u', and
                          ! trans = 'c'
                          call la_${ri}$trsm('R','U','C',diag,m,n2,alpha,a(n1),n,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','C',m,n1,n2,-cone,b(0,n1),ldb,a(0), &
                                    n,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,n1,cone,a(n2),n,b(0,0 &
                                    ),ldb)
                       end if
                    end if
                 else
                    ! side = 'r', n is odd, and transr = 'c'
                    if (lower) then
                       ! side  ='r', n is odd, transr = 'c', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'c', uplo = 'l', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','L','N',diag,m,n2,alpha,a(1),n1,b(0, &
                                    n1),ldb)
                          call la_${ri}$gemm('N','C',m,n1,n2,-cone,b(0,n1),ldb,a(n1*n1 &
                                    ),n1,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','C',diag,m,n1,cone,a(0),n1,b(0,0 &
                                    ),ldb)
                       else
                          ! side  ='r', n is odd, transr = 'c', uplo = 'l', and
                          ! trans = 'c'
                          call la_${ri}$trsm('R','U','N',diag,m,n1,alpha,a(0),n1,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','N',m,n2,n1,-cone,b(0,0),ldb,a(n1*n1) &
                                    ,n1,alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','L','C',diag,m,n2,cone,a(1),n1,b(0, &
                                    n1),ldb)
                       end if
                    else
                       ! side  ='r', n is odd, transr = 'c', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is odd, transr = 'c', uplo = 'u', and
                          ! trans = 'n'
                          call la_${ri}$trsm('R','U','N',diag,m,n1,alpha,a(n2*n2),n2,b( &
                                    0,0),ldb)
                          call la_${ri}$gemm('N','C',m,n2,n1,-cone,b(0,0),ldb,a(0), &
                                    n2,alpha,b(0,n1),ldb)
                          call la_${ri}$trsm('R','L','C',diag,m,n2,cone,a(n1*n2),n2,b( &
                                    0,n1),ldb)
                       else
                          ! side  ='r', n is odd, transr = 'c', uplo = 'u', and
                          ! trans = 'c'
                          call la_${ri}$trsm('R','L','N',diag,m,n2,alpha,a(n1*n2),n2,b( &
                                    0,n1),ldb)
                          call la_${ri}$gemm('N','N',m,n1,n2,-cone,b(0,n1),ldb,a(0), &
                                    n2,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','C',diag,m,n1,cone,a(n2*n2),n2,b( &
                                    0,0),ldb)
                       end if
                    end if
                 end if
              else
                 ! side = 'r' and n is even
                 if (normaltransr) then
                    ! side = 'r', n is even, and transr = 'n'
                    if (lower) then
                       ! side  ='r', n is even, transr = 'n', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','U','C',diag,m,k,alpha,a(0),n + 1,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-cone,b(0,k),ldb,a(k + 1),n + &
                                    1,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,k,cone,a(1),n + 1,b(0,0 &
                                    ),ldb)
                       else
                          ! side  ='r', n is even, transr = 'n', uplo = 'l',
                          ! and trans = 'c'
                          call la_${ri}$trsm('R','L','C',diag,m,k,alpha,a(1),n + 1,b(0, &
                                    0),ldb)
                          call la_${ri}$gemm('N','C',m,k,k,-cone,b(0,0),ldb,a(k + 1),n + &
                                    1,alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,k,cone,a(0),n + 1,b(0,k &
                                    ),ldb)
                       end if
                    else
                       ! side  ='r', n is even, transr = 'n', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','L','C',diag,m,k,alpha,a(k + 1),n + 1,b(0, &
                                     0),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-cone,b(0,0),ldb,a(0),n + 1, &
                                     alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','U','N',diag,m,k,cone,a(k),n + 1,b(0,k &
                                    ),ldb)
                       else
                          ! side  ='r', n is even, transr = 'n', uplo = 'u',
                          ! and trans = 'c'
                          call la_${ri}$trsm('R','U','C',diag,m,k,alpha,a(k),n + 1,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','C',m,k,k,-cone,b(0,k),ldb,a(0),n + 1, &
                                     alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','L','N',diag,m,k,cone,a(k + 1),n + 1,b(0, &
                                    0),ldb)
                       end if
                    end if
                 else
                    ! side = 'r', n is even, and transr = 'c'
                    if (lower) then
                       ! side  ='r', n is even, transr = 'c', and uplo = 'l'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'c', uplo = 'l',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','L','N',diag,m,k,alpha,a(0),k,b(0,k) &
                                    ,ldb)
                          call la_${ri}$gemm('N','C',m,k,k,-cone,b(0,k),ldb,a((k + 1) &
                                    *k),k,alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','C',diag,m,k,cone,a(k),k,b(0,0), &
                                     ldb)
                       else
                          ! side  ='r', n is even, transr = 'c', uplo = 'l',
                          ! and trans = 'c'
                          call la_${ri}$trsm('R','U','N',diag,m,k,alpha,a(k),k,b(0,0) &
                                    ,ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-cone,b(0,0),ldb,a((k + 1) &
                                    *k),k,alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','L','C',diag,m,k,cone,a(0),k,b(0,k), &
                                     ldb)
                       end if
                    else
                       ! side  ='r', n is even, transr = 'c', and uplo = 'u'
                       if (notrans) then
                          ! side  ='r', n is even, transr = 'c', uplo = 'u',
                          ! and trans = 'n'
                          call la_${ri}$trsm('R','U','N',diag,m,k,alpha,a((k + 1)*k),k, &
                                    b(0,0),ldb)
                          call la_${ri}$gemm('N','C',m,k,k,-cone,b(0,0),ldb,a(0),k, &
                                    alpha,b(0,k),ldb)
                          call la_${ri}$trsm('R','L','C',diag,m,k,cone,a(k*k),k,b(0,k &
                                    ),ldb)
                       else
                          ! side  ='r', n is even, transr = 'c', uplo = 'u',
                          ! and trans = 'c'
                          call la_${ri}$trsm('R','L','N',diag,m,k,alpha,a(k*k),k,b(0, &
                                    k),ldb)
                          call la_${ri}$gemm('N','N',m,k,k,-cone,b(0,k),ldb,a(0),k, &
                                    alpha,b(0,0),ldb)
                          call la_${ri}$trsm('R','U','C',diag,m,k,cone,a((k + 1)*k),k,b( &
                                     0,0),ldb)
                       end if
                    end if
                 end if
              end if
           end if
           return
     end subroutine la_${ri}$tfsm
#:if LA_GUARD[rk]
#endif
#:endif
#:endfor

end module la_lapack_blas_like_l3
