# Deploy documentation to gh-pages
name: Deploy Doxygen Documentation
   
on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the `main` branch

inputs:
  doxygen_version:
    description: 'Doxygen version to install'
    required: true
    default: '1.13.2'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Doxygen
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz -y

      # Step 3: Install Doxygen
      - name: Install Doxygen v${{ inputs.doxygen_version }}
        run: |
          transformed_version=$(echo "${{ inputs.doxygen_version }}" | tr '.' '_')
          wget https://github.com/doxygen/doxygen/releases/download/Release_${transformed_version}/doxygen-${{ inputs.doxygen_version }}.linux.bin.tar.gz
          tar -xzf doxygen-${{ inputs.doxygen_version }}.linux.bin.tar.gz
          sudo mv doxygen-${{ inputs.doxygen_version }}/bin/doxygen /usr/local/bin/doxygen

      # Step 4: Generate Doxygen documentation
      - name: Generate Doxygen Documentation
        run: cd project/doxygen && doxygen 

      # Step 5: Ensure no Jekyll is present  
      - name: Create .nojekyll file
        run: echo "" > ./project/doxygen/html/.nojekyll

      # Step 6: Deploy to `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./project/doxygen/html

