# Deploy documentation to gh-pages
name: Deploy Doxygen Documentation
   
on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOXYGEN_VERSION: '1.13.2' 

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Doxygen
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full ghostscript graphviz -y

      # Step 3: Install Doxygen
      - name: Install Doxygen v${{ env.DOXYGEN_VERSION }}  
        run: |
          transformed_version=$(echo "${{ env.DOXYGEN_VERSION }}" | tr '.' '_')
          wget https://github.com/doxygen/doxygen/releases/download/Release_${transformed_version}/doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          tar -xzf doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          sudo mv doxygen-${{ env.DOXYGEN_VERSION }}/bin/doxygen /usr/local/bin/doxygen

      # Step 4: Generate Doxygen documentation
      - name: Generate Doxygen Documentation
        run: cd project/doxygen && doxygen 

      # Step 5: Ensure no Jekyll is present  
      - name: Create .nojekyll file
        run: echo "" > ./project/doxygen/html/.nojekyll

      # Step 6: Deploy to `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./project/doxygen/html

