# Deploy documentation to gh-pages
name: Deploy Doxygen Documentation
   
on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Doxygen
      - name: Install Doxygen and Graphviz
        run: sudo apt-get install doxygen graphviz -y

      # Step 3: Generate Doxygen documentation
      - name: Generate Doxygen Documentation
        run: doxygen ./project/doxygen/Doxyfile

      # Step 4: Deploy to `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./html

